application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java, ui-ngx/src/app/core/auth/auth.service.ts
Rolled back to the old oauth2 clients api path  for backward compatibility.
=> Rollback to the old oauth2 clients api 

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeConfiguration.java
Related REST API Call node front-end changes:
https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/182
Some requests in version 3.7.0 fail with the following error, caused by exceeding the web client's default max buffer size (256KB):
The error message is misleading. This PR provides a correct error message in case of failure and the option to update the max in-memory size.
The new error message correctly identifies the root cause.
=> REST API call node: max response size parameter added

common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Refactoring, new tbUtils methods equal docs
=> tbel: refactoring, tbUtils to docs

pom.xml
=> Tbel fix bug map key value

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
https://thingsboard-portal.atlassian.net/browse/PROD-4304
=> Fixed credentials check if simple client factory is used and fixed checks for system proxy properties in TbHttpClient

application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/rpc/MqttClientSideRpcIntegrationTest.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportContext.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/limits/GatewaySessionLimits.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/limits/SessionLimits.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/DeviceSessionCtx.java, common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/session/DeviceAwareSessionContext.java
Client RPC with method: **_getSessionLimits_**
limits for gateway:
```
{
"maxPayloadSize": 65536,
"maxInflightMessages": 100,
"payloadType": "JSON",
"rateLimits": {
"messages": "20:600",
"telemetryMessages": "10:600",
"telemetryDataPoints": "40:600"
},
"gatewayRateLimits": {
"messages": "100:600",
"telemetryMessages": "50:600",
"telemetryDataPoints": "200:600"
}
}
```
limits for device:
```
{
"maxPayloadSize": 65536,
"maxInflightMessages": 100,
"payloadType": "JSON",
"rateLimits": {
"messages": "20:600",
"telemetryMessages": "10:600",
"telemetryDataPoints": "40:600"
}
}
```
Doc: https://github.com/thingsboard/thingsboard.github.io/pull/1630
=> added support of getServiceConfiguration RPC

common/transport/coap/src/main/proto/efento/proto_config.proto
=> chore: update proto_config.proto

ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata-tag-function-panel.component.html, ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata-tag-function-panel.component.ts, ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata.component.html, ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata.component.ts, ui-ngx/src/app/modules/home/pages/scada-symbol/scada-symbol-editor.models.ts, ui-ngx/src/app/shared/components/js-func.component.ts, ui-ngx/src/app/shared/models/ace/ace.models.ts
=> Refactor SCADA editor highlighting to support Safari on iOS versions 16.3 and below

ui-ngx/src/app/core/http/user.service.ts, ui-ngx/src/app/modules/home/pages/user/activation-link-dialog.component.html, ui-ngx/src/app/modules/home/pages/user/activation-link-dialog.component.ts, ui-ngx/src/app/modules/home/pages/user/add-user-dialog.component.ts, ui-ngx/src/app/modules/home/pages/user/users-table-config.resolver.ts, ui-ngx/src/app/modules/login/login-routing.module.ts, ui-ngx/src/app/modules/login/login.module.ts, ui-ngx/src/app/modules/login/pages/login/link-expired.component.html, ui-ngx/src/app/modules/login/pages/login/link-expired.component.scss, ui-ngx/src/app/modules/login/pages/login/link-expired.component.ts, ui-ngx/src/app/shared/models/user.model.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Added message about link expiration for user activation dialog.
before: 
after:
Expired activation and password reset links redirect to informational panel
=> TTL for password reset and user activation links UI

ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Timewindow configuration changes are not saved when saving the dashboard
=> Fix saving dashboard timewindow configuration

ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
=> Improved show error in layout settings

ui-ngx/src/app/core/api/alias-controller.ts, ui-ngx/src/app/core/api/widget-api.models.ts, ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Same dashboard filter applied for widgets with same data sources on states opened in dialog or popover behaves separately.
Config:
**Alias:**
**Filter:**
**Both entity tables on both states:**
**Before fix:**
https://github.com/user-attachments/assets/da5423df-5a40-4671-9251-600ba1da841b
**After fix:**
https://github.com/user-attachments/assets/2e26b834-2fec-44e6-bc64-01bb061ccd19
=> Filters are not applying to state if it is opened in dialog window or popover

ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts, ui-ngx/src/app/modules/home/pages/admin/admin-routing.module.ts, ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-property-panel.component.html, ui-ngx/src/app/modules/home/pages/widget/widget-library.module.ts, ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-dialog.component.html, ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-dialog.component.scss, ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-dialog.component.ts, ui-ngx/src/app/modules/home/pages/widget/widgets-bundle.component.html, ui-ngx/src/app/modules/home/pages/widget/widgets-bundle.component.ts, ui-ngx/src/app/shared/components/image/image-gallery.component.ts, ui-ngx/src/app/shared/components/widgets-bundle-select.component.html, ui-ngx/src/app/shared/components/widgets-bundle-select.component.ts, ui-ngx/src/app/shared/models/widgets-bundle.model.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Improvements:
1. Automatically calculate row and column on uploading new SCADA symbol.
2. Changing on row click event from selecting to redirect on the edit SCADA symbol page. (only for SCADA symbol page)
3. Add an empty option for disable on property field.
4. Add create new widget bundle option from create widget dialog.
=> Improvements for SCADA system

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
=> Revert close connection header hotfix

application/src/main/java/org/thingsboard/server/service/mail/DefaultTbMailConfigTemplateService.java, common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
fixed the error that the file could not be found after packing
```shell
Caused by: java.io.FileNotFoundException: class path resource [templates/mail_config_templates.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/D:/idea_work/thingsboard/application/target/thingsoard-3.6.2-boot.jar!/BOOT-INF/classes!/templates/mail_config_templates.json
at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.3.26.jar!/:5.3.26]
at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:164) ~[spring-core-5.3.26.jar!/:5.3.26]
at org.thingsboard.server.service.mail.DefaultTbMailConfigTemplateService.postConstruct(DefaultTbMailConfigTemplateService.java:20) …
```
=> fix: fixed the error that the file could not be found after packing

application/src/main/data/json/system/scada_symbols/sand-filter.svg, application/src/main/data/json/system/widget_bundles/scada_fluid_system.json
=> Rename stand filter to sand filter SCADA

application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java, application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
https://thingsboard-portal.atlassian.net/browse/PROD-4385
```
Unexpected error occurred in scheduled task
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1784)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at …
```
=> fixed concurrent modification during printStats

application/src/main/java/org/thingsboard/server/controller/SystemInfoController.java
Added platform type to system info
PE: https://github.com/thingsboard/thingsboard-pe/pull/2825
=> Added platform type to system info

common/cache/src/main/java/org/thingsboard/server/cache/CacheKey.java, common/cache/src/main/java/org/thingsboard/server/cache/CaffeineTbTransactionalCache.java, common/cache/src/main/java/org/thingsboard/server/cache/RedisTbCacheTransaction.java, common/cache/src/main/java/org/thingsboard/server/cache/RedisTbTransactionalCache.java, common/cache/src/main/java/org/thingsboard/server/cache/TbTransactionalCache.java, common/cache/src/main/java/org/thingsboard/server/cache/VersionedCacheKey.java, common/cache/src/main/java/org/thingsboard/server/cache/VersionedCaffeineTbCache.java, common/cache/src/main/java/org/thingsboard/server/cache/VersionedRedisTbCache.java, common/cache/src/main/java/org/thingsboard/server/cache/VersionedTbCache.java, common/cache/src/main/java/org/thingsboard/server/cache/device/DeviceCacheKey.java, dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileCacheKey.java, dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeCacheKey.java, dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileCacheKey.java, dao/src/main/java/org/thingsboard/server/dao/entity/CachedVersionedEntityService.java, dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewCacheKey.java, dao/src/main/java/org/thingsboard/server/dao/timeseries/TsLatestCacheKey.java
=> Refactor versioned caching

application/src/main/data/json/system/scada_symbols/vertical-ball-valve.svg
=> Fixed behavior for vertical ball value SCADA

ui-ngx/src/app/core/http/ota-package.service.ts
Fixed otaPackage api call in accordance with documentation
=> Fixed otaPackage api call in accordance with documentation

ui-ngx/src/app/shared/models/constants.ts
=> Change link for entity view documentation

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
https://thingsboard-portal.atlassian.net/browse/PROD-4384
Added new env `TB_RE_HTTP_CLIENT_POOL_MAX_CONNECTIONS` for configuration maxConnections in TbHttpClient.
=> Added ability to configure max connections for TbHttpClient

packaging/js/scripts/init/template
Fixed a typo in function name in the template script
https://github.com/thingsboard/thingsboard/issues/10538
=> incorrect function name in template script #10538

ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/modbus-version-processor.abstract.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.abstract.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-legacy-basic-config.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.scss, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-values/modbus-values.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/modbus-version-mapping.util.ts
Gateway Connector Modbus fixes and adjustments
- version mapping adjustments
- recursive call fix
- values UI adjustments 
- mapping tables edit tooltips
- added Word Order field for Serial
- on setting client data tabs jump fix
=> Gateway Connector Modbus fixes and adjustments

application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java, application/src/main/resources/thingsboard.yml
=> Disable WS subscriptions rate limits by default

application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeActorMessageProcessor.java, common/actor/src/main/java/org/thingsboard/server/actors/TbActorMailbox.java
```
[RULE_NODE|0473e400-71c3-11ef-a435-f70964ded0d7] Failed to destroy actor: {} java.lang.NullPointerException: Cannot invoke "org.thingsboard.server.common.data.rule.RuleNode.getName()" because "this.ruleNode" is null
at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.getComponentName(RuleNodeActorMessageProcessor.java:185)
at org.thingsboard.server.actors.service.ComponentActor.logAndPersist(ComponentActor.java:177)
at org.thingsboard.server.actors.service.ComponentActor.destroy(ComponentActor.java:110)
at org.thingsboard.server.actors.ruleChain.RuleEngineComponentActor.destroy(RuleEngineComponentActor.java:61)
at org.thingsboard.server.actors.TbActorMailbox.lambda$destroy$8(TbActorMailbox.java:254)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteActi …
```
=> fixed NPE in RuleNodeActorMessageProcessor

application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
added upgrade script for device profile node.
=> Added upgrade script for device profile node

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
=> EdgeGrpcSession: fix typo in comment

common/queue/src/main/java/org/thingsboard/server/queue/discovery/TopicService.java
https://thingsboard-portal.atlassian.net/browse/PROD-4448
=> fixed concurrent modification in TopicService

application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java, application/src/main/java/org/thingsboard/server/service/entitiy/alarm/TbAlarmService.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/AlarmsUnassignTaskProcessor.java, application/src/test/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmServiceTest.java, application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java, common/data/src/main/java/org/thingsboard/server/common/data/housekeeper/AlarmsUnassignHousekeeperTask.java, dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java, dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java, dao/src/main/java/org/thingsboard/server/dao/sql/alarm/AlarmRepository.java, dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
Now we split user's alarms that we need to unassign into multiple tasks.
The implementation with id and created time offsets is the same as for alarms deletion.
=> Housekeeper: performance improvements for alarms unassigning

application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainManagerActor.java, application/src/main/java/org/thingsboard/server/actors/shared/RuleChainErrorActor.java, application/src/test/java/org/thingsboard/server/actors/tenant/TenantActorTest.java
=> [Rule Engine] fixed RuleEngine OOM

ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.html, ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts, ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
=> Fixed incorrect show widgets in layout

ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts, ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
=> Fixed incorrect show widgets in layout when active edit mode

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNode.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
PR covering missing upgrade step for merged PR:
https://github.com/thingsboard/thingsboard/pull/11500
=> TbRestApiCallNode - added upgrade step to add maxInMemoryBufferSizeInKb config

ui-ngx/src/form.scss
=> Adjust styles for outlined input with floating label for iOS

ui-ngx/src/app/shared/components/contact.component.html, ui-ngx/src/app/shared/components/country-autocomplete.component.ts
before: 
[Screenity video - Sep 13, 2024.webm](https://github.com/user-attachments/assets/e1da5b45-2d31-406c-a7d1-8270b93aa66a)
after:
[Screenity video - Sep 13, 2024 (1).webm](https://github.com/user-attachments/assets/58fca9b7-859a-4dc7-b28c-5fe4737251cc)
Fixed ZIP error not displaying properly
before:
after:
=> Fixed country autocomplete blocking tenant creation

ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/mqtt-version-processor.abstract.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/advanced/gateway-advanced-configuration.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/basic/gateway-basic-configuration.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/gateway-configuration.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/models/gateway-configuration.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc/opc-server-config/opc-server-config.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/opc-version-mapping.util.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Gateway UI improvements and minor bug fixes
- changed Gateway Configuration command delete button
- fixed default value of created Gateway 
- changed input to security policy for OPC
- connector sync fix
=> Gateway UI improvements and minor bug fixes

ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-dialog.component.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/clients-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain.component.html, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain.component.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app.component.html, ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed:
-  the copy Application secret button highlight is not positioned correctly
before:
after:
- domain and mobile-application tables have to be refreshed to see value in clients column changed
Added white spaces validation for app package name field of mobile-application.
Code cleanup.
=> OAuth 2 UI improvements, code cleanup

ui-ngx/src/app/core/auth/auth.service.ts
Some time not show a login error dialog
=> Fixed race conditional when show login error dialog

ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html, ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.html, ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts, ui-ngx/src/app/shared/import-export/import-export.service.ts
Version Conflict Fixes:
- prevent multiple dashboard saves for users with slow internet 
- broken dialog on device credentials conflict 
- correct file name for on Version Conflict export Customer
=> Version Conflict Fixes

ui-ngx/src/app/core/services/utils.service.ts, ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.ts, ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-select-panel.component.ts, ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.html, ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.ts, ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html, ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.scss, ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.ts, ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts, ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts, ui-ngx/src/app/shared/models/alarm.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json, ui-ngx/src/styles.scss
In case if user that was assigned to any alarm and has left comments in details is deleted - alarm tables and details panel are breaking.
This PR adds handling of those errors and visualizes that alarm is assigned to deleted user or comments are written by deleted one.
=> Fixed alarm assignee and comments for deleted user

ui-ngx/src/app/shared/import-export/import-export.service.ts
Refactored logic: Customer - Version Conflict - Export
=> Refactored logic: Customer - Version Conflict - Export

ui-ngx/src/styles.scss
=> Removed unused style class

ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
before:
https://github.com/user-attachments/assets/af4f7ac6-924d-4fb8-9597-d1bfdc47a39c
after: 
https://github.com/user-attachments/assets/fa2d4d11-587f-4c04-9bfd-ae3b0cb6802a
=> Fixed coping of instances when deleting LWM2M objects

ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
=> Fixed select widget in touch screen

application/src/main/data/json/system/scada_symbols/sand-filter.svg
=> Fixed disabling click area for sand filter symbol

ui-ngx/src/assets/help/en_US/scada/symbol_state_render_fn.md, ui-ngx/src/assets/help/en_US/scada/tag_click_action_fn.md, ui-ngx/src/assets/help/en_US/scada/tag_state_render_fn.md
=> Help for Scada system

ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
=> Fixed text color of table widgets not applying to action cell buttons

ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Fixed layout settings translate

ui-ngx/src/app/modules/home/pages/device/device-credentials-dialog.component.ts
Fixed device credentials on discard/cancel conflict
[Screencast from 26.09.24 13:12:36.webm](https://github.com/user-attachments/assets/8341b6f4-907d-40c3-8246-9db279c914ea)
=> Fixed device credentials on discard/cancel conflict

ui-ngx/src/assets/help/en_US/scada/symbol_state_render_fn.md, ui-ngx/src/assets/help/en_US/scada/tag_click_action_fn.md, ui-ngx/src/assets/help/en_US/scada/tag_state_render_fn.md
=> Complete scada help examples

application/src/main/data/json/system/scada_symbols/left-analog-water-level-meter.svg, application/src/main/data/json/system/scada_symbols/right-analog-water-level-meter.svg
=> Fixed position for icon SCADA analog meters

ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
=> Fixed quick update of value in gauge widget during animation

common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java, common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java, common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepositoryService.java
=> Add option to fetch repo if already cloned (for converters library)

application/src/main/java/org/thingsboard/server/controller/AuthController.java, application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/main/java/org/thingsboard/server/controller/CustomerController.java, application/src/main/java/org/thingsboard/server/controller/TenantController.java, application/src/main/java/org/thingsboard/server/controller/UserController.java, common/dao-api/src/main/java/org/thingsboard/server/dao/dashboard/DashboardService.java, dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
Added check for default and home dashboard existence whendo  GET /auth/user.
PE: https://github.com/thingsboard/thingsboard-pe/pull/2835
=> Check default and home dashboard exists when GET /auth/user

ui-ngx/src/app/shared/models/widget-settings.models.ts
=> Fixed incorrect parsing of the CSS units 'rem' and 'vmin'

ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-notification-dialog.component.html, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Renamed 'Webhook URL' to 'Workflow URL' for the new connector API in Microsoft Teams notification recipient

common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java, common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/utils/CoapEfentoUtils.java, common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/utils/PulseCounterType.java, common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResourceTest.java
Fixed pulse counter telemetry calculation
PE: https://github.com/thingsboard/thingsboard-pe/pull/2900
=> Fixed pulse counter telemetry calculation

common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java
Added logging for CoapEfentoTransportResource
=> Added logging for CoapEfentoTransportResource

ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
=> Fixed pattern animation for chrome 127

ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/gateway-connector-version-processor.abstract.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/security-config/security-config.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html, ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/pipes/gateway-help-link.pipe.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/pipes/latest-version-config.pipe.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/gateway-connector-version-mapping.util.ts, ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/opc-version-mapping.util.ts, ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts, ui-ngx/src/assets/help/en_US/widget/lib/gateway/attributes_timeseries_expressions_fn.md, ui-ngx/src/assets/locale/locale.constant-en_US.json, ui-ngx/src/assets/metadata/connector-default-configs/modbus.json
Gateway fixes:
- deleted redundant fileds in security config on changing security type in advanced
- added config version for empty config
- added Add Connector Dialog to zone
- added attributes/timeseries expressions show help
- added Modbus Report strategy default config
- json config watcher on creation fix
- OPC device node source mapping fix
- connectors config watchers unsub fix
- showing GW version after GW connected for Legacy
- added support for newer Gateway versions
=> Gateway fixes and added support for newer Gateway versions

ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.html, ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
=> Fixed edit and disabled oauth client settings scope

application/src/main/resources/thingsboard.yml
=> Drop max Hikari pool size to 4 for dedicated datasource

ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
=> Fixed the inability to edit resource type in resource library when created resource

ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html, ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.ts, ui-ngx/src/app/shared/components/time/timewindow-panel.component.html
=> Fixed not updated group interval in history time windows

common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java, common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResourceTest.java
Fixed accumulative pulse counter total value calculation
=> Fixed accumulative pulse counter total value calculation

pom.xml
- https://github.com/thingsboard/tbel/pull/38
=> tbel: version 1.2.4

dao/src/main/java/org/thingsboard/server/dao/AbstractVersionedInsertRepository.java, dao/src/test/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDaoTest.java
```
2024-10-07 11:28:51,654 [sql-queue-0-ts latest-10-thread-1] ERROR o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Failed to save 3 entities
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at org.thingsboard.server.dao.AbstractVersionedInsertRepository.lambda$saveOrUpdate$0(AbstractVersionedInsertRepository.java:72)
```
=> fixed IndexOutOfBoundsException during saving old latestTs

common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java, common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
=> Improve Git repository init

ui-ngx/src/app/core/services/dashboard-utils.service.ts
Fix overlapping widgets when changing layout columns count
=> Fix overlapping widgets when changing layout columns count

ui-ngx/src/app/modules/home/components/widget/lib/settings/map/circle-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/common-map-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/datasources-key-autocomplete.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/google-map-provider-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/here-map-provider-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/image-map-provider-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-editor-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-provider-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/marker-clustering-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/markers-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/openstreet-map-provider-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/polygon-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/route-map-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/tencent-map-provider-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-common-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-marker-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-path-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-point-settings.component.html
=> Remove flex layout in map widgets settings

application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mTemperatureSensor.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadCollectedValueTest.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
- lwm2m_fix_bug_test_CollectedValue
=> Lwm2m fix bug

application/src/test/java/org/thingsboard/server/transport/coap/rpc/AbstractCoapServerSideRpcIntegrationTest.java
=> Fix bug coap tests

ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
=> Fixed scada editor row and column calculation

application/src/main/java/org/thingsboard/server/controller/AdminController.java, application/src/main/java/org/thingsboard/server/controller/AuthController.java, application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/main/java/org/thingsboard/server/controller/UserController.java, application/src/main/java/org/thingsboard/server/service/entitiy/user/DefaultUserService.java, application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java, application/src/main/java/org/thingsboard/server/service/security/auth/mfa/provider/impl/EmailTwoFaProvider.java
=> Hide mail sender error details

application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java, application/src/main/java/org/thingsboard/server/service/install/EntityDatabaseSchemaService.java, application/src/main/java/org/thingsboard/server/service/install/SqlEntityDatabaseSchemaService.java, application/src/main/java/org/thingsboard/server/service/install/SqlTsDatabaseSchemaService.java, dao/src/main/resources/sql/schema-entities.sql
=> automaticaly set schema version based on app version

application/src/main/data/json/edge/instructions/install/centos/instructions.md, application/src/main/data/json/edge/instructions/install/docker/instructions.md, application/src/main/data/json/edge/instructions/install/ubuntu/instructions.md, application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_db.md, docker/docker-compose.hybrid.yml, docker/docker-compose.postgres.yml, msa/tb/docker-cassandra/Dockerfile
Updated postgres from 15 to 16
=> Updated postgres from 15 to 16

application/src/test/java/org/thingsboard/server/transport/coap/rpc/AbstractCoapServerSideRpcIntegrationTest.java
```
org.awaitility.core.ConditionTimeoutException: Condition with alias 'await Two Way Rpc (client.getObserveRelation)' didn't complete within 30 seconds because condition with Lambda expression in org.thingsboard.server.transport.coap.rpc.AbstractCoapServerSideRpcIntegrationTest was not fulfilled.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
at org.thingsboard.server.transport.coap.rpc.AbstractCoapServerSideRpcIntegrationTest.processTwoWayRpcTest(AbstractCoapServerSideRpc …
```
=> fix_bug_test_coap_processTwoWayRpcTest

application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DashboardSyncService.java, application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java, application/src/main/java/org/thingsboard/server/service/sync/DefaultGitSyncService.java, common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ResourceService.java, common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java, dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
=> Sync with Git: ignore if no changes

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNode.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNodeTest.java
Previously created nodes fails on start after upgrade from 0 to 1 if config does not have limit and aggregation when fetchMode is set to ALL. 
=> Fixed originator telemetry node

common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-4858
- TbUtils.parseInt("+0")
before:
```
java.lang.NumberFormatException: Value: "+0" is not numeric or hexDecimal format!
at org.thingsboard.script.api.tbel.TbUtils.getRadix10_16(TbUtils.java:533)
at org.thingsboard.script.api.tbel.TbUtils.isValidStringAndRadix(TbUtils.java:1208)
at org.thingsboard.script.api.tbel.TbUtils.parseInt(TbUtils.java:449)
at org.thingsboard.script.api.tbel.TbUtils.parseInt(TbUtils.java:443)
at org.thingsboard.script.api.tbel.TbUtils.parseInt(TbUtils.java:439)
at org.thingsboard.script.api.tbel.TbUtilsTest.parseInt(TbUtilsTest.java:216)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at …
```
=> tbel_fix_bug_validate_decimal

application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java, application/src/main/java/org/thingsboard/server/service/update/DeprecationService.java, application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java, common/data/src/main/java/org/thingsboard/server/common/data/notification/info/GeneralNotificationInfo.java, common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusAdmin.java, common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubAdmin.java, common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqAdmin.java, common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsAdmin.java, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java, rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
=> Deprecate all queue types except Kafka and in-memory

ui-ngx/src/app/shared/components/html.component.ts
Usage of "&" symbol blocks saving.
Before:
After:
=> Disabled "Named entity expected" for html editor

ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html, ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss, ui-ngx/src/app/shared/models/notification.models.ts
With given config:
Preview before:
After:
=> Microsoft Teams notification preview improvements

ui-ngx/src/assets/help/en_US/widget/lib/gateway/address-filter_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/gateway/attribute-name-expression_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/gateway/byte_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/gateway/request-expression_fn.md
Added md help files for socket basic config implementation
=> Added md help files for socket basic config implementation

application/src/main/data/json/system/scada_symbols/conical-tank.svg, application/src/main/data/json/system/scada_symbols/large-conical-tank.svg, application/src/main/data/json/system/scada_symbols/small-cylindrical-tank.svg, application/src/main/data/json/system/widget_bundles/scada_fluid_system.json
=> SCADA conicals and small cylindrical tank

ui-ngx/src/app/shared/components/entity/entity-select.component.ts
Step to reproduce:
- Create or edit entity view with target entity Device and select any devices;
- Click to edit and change entity type to Asset;
- Click Decline changes;
=> Fixed entity select 

ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html, ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.ts
Added trim spaces for alarm comments
before:
after:
=> Added trim spaces for alarm comments

ui-ngx/src/assets/locale/locale.constant-en_US.json
Added launch command translation for Gateway
before:
after:
=> Added launch command translation for Gateway

application/src/main/java/org/thingsboard/server/service/update/DeprecationService.java, application/src/main/resources/thingsboard.yml, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java, msa/vc-executor/src/main/resources/tb-vc-executor.yml, transport/coap/src/main/resources/tb-coap-transport.yml, transport/http/src/main/resources/tb-http-transport.yml, transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml, transport/mqtt/src/main/resources/tb-mqtt-transport.yml, transport/snmp/src/main/resources/tb-snmp-transport.yml
=> Queue providers deprecation

application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java, application/src/test/java/org/thingsboard/server/rules/flow/AbstractRuleEngineFlowIntegrationTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-4919
Detected latency issue if we do the infinite loop using input node.
=> used enqueue for input node to avoid latency issue

application/src/main/java/org/thingsboard/server/controller/CalculatedFieldController.java, application/src/main/java/org/thingsboard/server/service/entitiy/AbstractTbEntityService.java, application/src/main/java/org/thingsboard/server/service/entitiy/cf/DefaultTbCalculatedFieldService.java, application/src/main/java/org/thingsboard/server/service/entitiy/cf/TbCalculatedFieldService.java, common/dao-api/src/main/java/org/thingsboard/server/dao/cf/CalculatedFieldService.java, dao/src/main/java/org/thingsboard/server/dao/cf/BaseCalculatedFieldService.java, dao/src/main/java/org/thingsboard/server/dao/cf/CalculatedFieldLinkDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/cf/JpaCalculatedFieldDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/cf/JpaCalculatedFieldLinkDao.java, dao/src/test/java/org/thingsboard/server/dao/service/CalculatedFieldServiceTest.java
=> added tbCalculatedField Service

ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
Added rulechains description column
=> Added rulechains description column

ui-ngx/src/app/core/interceptors/entity-conflict.interceptor.ts, ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts, ui-ngx/src/app/shared/import-export/import-export.service.ts, ui-ngx/src/app/shared/models/entity.models.ts
Added fallback for non-entity conflicts
=> Added fallback for non-entity conflicts

ui-ngx/src/styles.scss
=> Updated link styles after updated Angular

ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
=> Fix update of OAuth details when switching between clients in the OAuth 2.0 clients table

ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.html, ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html, ui-ngx/src/app/modules/home/pages/customer/customer.component.html
Flex Layout migration fixes
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> Flex Layout migration fixes

ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
Y-Axis for hidden datakey is still visible if max value specified
=> Fixed сhart widget not apply hidden datakey by default

application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/main/java/org/thingsboard/server/controller/NotificationController.java, application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java, application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java, application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java, application/src/test/java/org/thingsboard/server/edge/NotificationEdgeTest.java, application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationSettingsService.java, common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationTemplateService.java, common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationType.java, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTargetService.java, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTemplateService.java, dao/src/main/java/org/thingsboard/server/dao/notification/NotificationTemplateDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationTemplateDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationTemplateRepository.java, rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
This PR is mainly **for compatibility with PE** (refactoring of self-registration API to use notification center)
=> System notification type; improvements for notification center

ui-ngx/src/app/shared/components/image/image-gallery.component.html
Fixed Scroll and pagination buttons are absent on the SCADA symbol and Image gallery tables when there are 20+ elements
=> Fixed Scroll and pagination buttons are absent, SCADA/Image table

ui-ngx/src/app/core/settings/settings.effects.ts, ui-ngx/src/app/core/settings/settings.utils.ts
=> Update document 'lang' attribute based on user language preference

ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
=> Fixed close mobile bundle dialog without add/edit

dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
Entity Data Query optimisation - entityFilter.isFetchLastLevelOnly() to hit index and avoid sequential scan
(and nr.relation_type_group = 'COMMON')
Ticket https://thingsboard-portal.atlassian.net/browse/PROD-5010
before
after
=> Entity Data Query optimisation - entityFilter.isFetchLastLevelOnly() to hit index and avoid sequential scan

ui-ngx/src/assets/help/en_US/widget/lib/gateway/address-filter_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/gateway/report-strategy_fn.md
Added md file for Gateway Report strategy and updated socket md file
=> Added md file for Gateway Report strategy

ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/signal-strength-widget-settings.component.ts
=> Fixed show color in signal strength widget when low signal

ui-ngx/src/app/modules/home/components/audit-log/audit-log-details-dialog.component.ts, ui-ngx/src/app/modules/home/components/event/event-content-dialog.component.ts
Fixed audit log and event content dialogs sizing
before:
after:
=> Fixed audit log and event content dialogs sizing

ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
=> Fixed add small widget in mobile layout dashboard

application/src/main/java/org/thingsboard/server/config/CustomOAuth2AuthorizationRequestResolver.java, common/dao-api/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientService.java, dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientDao.java, dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/JpaOAuth2ClientDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/OAuth2ClientRepository.java
Fixed oauth2 authorization for apps of version 1.3.0 and less
=> Fixed oauth2 authorization for apps of version 1.3.0 and less

application/src/main/data/upgrade/3.8.1/schema_update.sql, application/src/main/java/org/thingsboard/server/controller/MobileAppController.java, common/data/src/main/java/org/thingsboard/server/common/data/mobile/LoginMobileInfo.java, common/data/src/main/java/org/thingsboard/server/common/data/mobile/UserMobileInfo.java, dao/src/main/java/org/thingsboard/server/dao/mobile/MobileAppServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/JpaOAuth2ClientDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/OAuth2ClientRepository.java, dao/src/main/resources/sql/schema-entities.sql
Allow mobile app deletion if used in mobile app.
PE: https://github.com/thingsboard/thingsboard-pe/pull/3034
=> Updated mobile app deletion logic

application/src/main/java/org/thingsboard/server/service/install/update/ResourcesUpdater.java, application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java, common/util/src/main/java/org/thingsboard/common/util/ThingsBoardExecutors.java
=> Improvements for resources upgrade

application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
=> Update cache cleanup service

common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
Increased timeout execution for TBEL script compiler
=> Increased TBEL script compilation timeout

ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html, ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss, ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
=> Fixed incorrect show mail notification preview

ui-ngx/src/assets/help/en_US/rulenode/tbel/generator_node_script_fn.md
=> Fixed wrong example in TBEL round number

ui-ngx/src/app/modules/home/pages/asset-profile/asset-profiles-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/device-profile/device-profiles-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/tenant-profile/tenant-profiles-table-config.resolver.ts
=> Add support custom translate for entity description columns

ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-widget-select.component.html
Show SCADA symbols in preview mode without metadata.
=> Show SCADA symbols svg in preview mode

ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.html, ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts, ui-ngx/src/app/modules/home/pages/mobile/applications/remove-app-dialog.component.html, ui-ngx/src/app/modules/home/pages/mobile/applications/remove-app-dialog.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.html, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.scss, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts, ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.html, ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Fixed and imporvements mobile center

ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.component.ts
=> Fixed "no signal" logical in signal strength widgets

ui-ngx/src/app/modules/home/components/alias/entity-alias-select.component.html, ui-ngx/src/app/modules/home/components/alias/entity-alias-select.component.models.ts, ui-ngx/src/app/modules/home/components/alias/entity-alias-select.component.ts, ui-ngx/src/app/modules/home/components/widget/config/data-keys.component.html, ui-ngx/src/app/modules/home/components/widget/config/data-keys.component.ts, ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
=> Add edit alias from dasource widgets

application/src/main/java/org/thingsboard/server/controller/MobileAppController.java, dao/src/main/java/org/thingsboard/server/dao/mobile/MobileAppBundleServiceImpl.java
Fixed mobile layout configuration response for default  layout configuration.
=> Fixed mobile layout configuration response

msa/js-executor/api/jsInvokeMessageProcessor.ts
fixed the absence of the request bodies on debug level for js-executor
the source log was
the resulted log is
=> js-executor: added request body on debug level

application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantEdgeProcessor.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java, application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java, common/data/src/main/java/org/thingsboard/server/common/data/DeviceIdInfo.java, common/data/src/main/java/org/thingsboard/server/common/data/DeviceProfileInfo.java, common/data/src/main/java/org/thingsboard/server/common/data/asset/AssetProfileInfo.java, common/data/src/main/java/org/thingsboard/server/common/data/id/EntityIdFactory.java, common/data/src/main/java/org/thingsboard/server/common/data/id/TenantId.java, common/data/src/main/java/org/thingsboard/server/common/data/id/UUIDBased.java, common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java, common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/VersionControlRequestCtx.java, dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2ClientEntity.java, dao/src/main/java/org/thingsboard/server/dao/model/sql/QueueEntity.java, dao/src/main/java/org/thingsboard/server/dao/model/sql/QueueStatsEntity.java, dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/TenantIdLoader.java
=> hashcode caching for immutable objects

rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
Added active filter for RestClient method
=> Active tenant devices filter for RestClient

application/src/main/java/org/thingsboard/server/service/housekeeper/HousekeeperService.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/HousekeeperTaskProcessor.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/LatestTsDeletionTaskProcessor.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/TsHistoryDeletionTaskProcessor.java, application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/SemaphoreWithTbMsgQueue.java
Interrupt task processing on timeout to avoid blocking processor thread
=> Improvements for Housekeeping service

application/src/main/java/org/thingsboard/server/service/housekeeper/HousekeeperService.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/HousekeeperTaskProcessor.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/LatestTsDeletionTaskProcessor.java, application/src/main/java/org/thingsboard/server/service/housekeeper/processor/TsHistoryDeletionTaskProcessor.java, application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java, common/util/src/main/java/org/thingsboard/common/util/ThingsBoardScheduledThreadPoolExecutor.java, msa/js-executor/api/jsInvokeMessageProcessor.ts, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/SemaphoreWithTbMsgQueue.java
=> rc + license:format

ui-ngx/src/assets/help/en_US/widget/lib/gateway/bacnet-device-name-field-expression_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/gateway/bacnet-device-profile-name-expression_fn.md
Added show helps for bacnet connector basic config
=> Added show helps for bacnet connector basic config

pom.xml
CE
https://avd.aquasec.com/nvd/cve-2024-38821 - critical
https://avd.aquasec.com/nvd/cve-2024-7254 - high
https://avd.aquasec.com/nvd/cve-2024-47535 - high
https://avd.aquasec.com/nvd/cve-2024-34750 - high
https://avd.aquasec.com/nvd/cve-2024-38816 - high
https://avd.aquasec.com/nvd/cve-2024-38816 - high
https://avd.aquasec.com/nvd/cve-2024-29025 - medium
https://avd.aquasec.com/nvd/cve-2024-31141 - medium
https://avd.aquasec.com/nvd/cve-2024-38820 - medium
https://avd.aquasec.com/nvd/cve-2024-38809 - medium
PE
https://avd.aquasec.com/nvd/cve-2024-47561 - critical
https://avd.aquasec.com/nvd/cve-2024-47554 - high
=> Fix multiple vulnerabilities

ui-ngx/src/app/modules/home/components/widget/lib/button/two-segment-button-widget.component.html
=> Fixed Two segment button widget disable event on edit mode

ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html, ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.ts, ui-ngx/src/app/modules/home/pages/admin/admin.module.ts, ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/resource/resource-tabs.component.html, ui-ngx/src/app/modules/home/pages/admin/resource/resource-tabs.component.ts, ui-ngx/src/app/shared/models/vc.models.ts
=>  Added JavaScript library details audit logs and version control

application/src/main/java/org/thingsboard/server/service/install/update/ResourcesUpdater.java, application/src/main/java/org/thingsboard/server/service/resource/DefaultTbResourceService.java, application/src/test/java/org/thingsboard/server/controller/DashboardControllerTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ResourceService.java, common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetType.java, dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java, dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
=> Dashboard/widget resources export - process whole config

pom.xml
[Put your PR description here instead of this sentence.   ](https://thingsboard-portal.atlassian.net/browse/PROD-5132)
=> tbel_add_bitwise_boolean

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
=> Fix edge events migration

ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
=> Fixed double open dialog when edit mobile bundle

ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
=> Fixed hide menu export dashboard after select option

ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-layout.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.ts, ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Fixed mobile center translate, validation and editor

ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
=> Fixed load background in image map

ui-ngx/src/app/modules/home/components/public-api.ts
Shared `echart-widget.models` to allow use it in thingsboard-extensions.
=> Share echarts-widget.models

ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
=> Fixed relative urls in send email notification

ui-ngx/src/app/modules/home/components/audit-log/audit-log-details-dialog.component.ts
UI: adjusted audit logs dialog codeblock height
=> Adjusted audit logs dialog codeblock height

application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
=> Fixes for system notification type

ui-ngx/src/app/shared/components/ota-package/ota-package-autocomplete.component.ts
=> Fixed error toast when editing device details

ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
UI: Rollback (Original PR - [#12033](https://github.com/thingsboard/thingsboard/pull/12033)) hide datakey (not axis) to original behaviour
ECharts' behavior of displaying axes when `min` and `max` values are defined is intentional and aligns with its design logic. This is because specifying these constraints implies that the axis should be visible to represent the defined range. Which is actually quite logical, because if value constrains is defined there is no need to hide axis (which is generated automatically only if there is some value to calculate constrains from).
Given this, it's advisable to adhere to ECharts' intended functionality rather than attempting to override it, which could require significant development effort and potentially lead to unexpected issues.
=> Rollback hide axis to original behaviour

ui-ngx/src/app/modules/home/components/widget/lib/home-page/usage-info-widget.component.scss
=> Fixed scroll on progress bar for usage info widget

ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Reproduce:
1. Open the dashboard and enable edit mode
2. Copy any widget and paste it to the right part of the dashboard
3. Grid adaptation is applied by width
4. Move this widget to the left 
5. Grid adaptation does not apply by width
Before:
After:
=> Fixed adaptive dashboard grid when moving widget

ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.ts, ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.scss, ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
Fixed error when updating the mobile layout.
Fixed edit-panel overlay and overflow editor.
Before:
After:
=> Fixed updated mobile layout and show mobile edit panel

ui-ngx/src/app/core/services/dashboard-utils.service.ts, ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts, ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
In some cases, when copying a widget on a dashboard and saving the changes, the position of the widgets changed after saving the dashboard.
Before:
After:
=> Fixed incorrect copy widget in dashboard

docker/docker-upgrade-tb.sh, msa/tb-node/docker/start-tb-node.sh, msa/tb/docker/upgrade-tb.sh, packaging/java/scripts/install/upgrade.sh, packaging/java/scripts/install/upgrade_dev_db.sh, packaging/java/scripts/windows/upgrade.bat
https://github.com/thingsboard/thingsboard-pe/pull/3069
https://github.com/thingsboard/thingsboard-pe-docker-compose/pull/57
https://github.com/thingsboard/thingsboard-ce-k8s/pull/138
https://github.com/thingsboard/thingsboard-pe-k8s/pull/94
https://github.com/thingsboard/tb-qa-cluster/pull/66
=> removed FROM_VERSION check from upgrade scripts

application/src/main/java/org/thingsboard/server/controller/QrCodeSettingsController.java
Fixed mobile redirect if ios is disabled in properties
=> Fixed mobile redirect if ios is disabled in properties

dao/src/main/java/org/thingsboard/server/dao/domain/DomainServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java, dao/src/main/java/org/thingsboard/server/dao/service/validator/DomainDataValidator.java, dao/src/test/java/org/thingsboard/server/dao/service/DomainServiceTest.java
=> Added domain validation

ui-ngx/src/app/shared/directives/truncate-with-tooltip.directive.ts
Before:
Several tooltips could be left visible at the same time on scrolling (mouse wheel)
After:
=> Fixed truncateWithTooltip directive behavior on different mouse events

ui-ngx/src/app/modules/home/components/widget/widget-container.component.html, ui-ngx/src/app/modules/home/components/widget/widget.component.ts
Step to reproduce:
1. Enter edit mode dashboard
2. Cancel edit mode dashboard
3. Updated time windows in widget
4. Ented edit mode dashboard
5. Enter the edit widget mode and show previous time windows
Before:
After:
=> Fixed incorrect apply timewindows after cancel edit dashboard

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
=> EdgeGrpcSession: change max downlink attempts value

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
=> Fix widget type sync up

application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java, ui-ngx/src/app/modules/home/pages/user/user.component.html, ui-ngx/src/app/modules/home/pages/user/user.component.ts, ui-ngx/src/app/shared/models/user.model.ts
=> Fix user info

application/pom.xml, pom.xml
added [git-commit-id-maven-plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin?tab=readme-ov-file) for the application to expose the git information under `actuator/info`
will looks like
to enable, expose the info endpoint
```
export METRICS_ENDPOINTS_EXPOSE=prometheus,health,info
export METRICS_ENABLED=true
```
internally it added the `git.properties` to the target classes folder
=> added git-commit-id-maven-plugin for the application to expose the git information under actuator/info

common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Before, if repository rules were not met, no error was shown but the branch and commit were not created.
Now, the error from the remote ref update is shown:
=> VC: show error when push is rejected

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/background-settings-panel.component.scss, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/background-settings.component.ts
- Open any dashboard and try to add widget: Cards - Value card
- Click on the Background button
- Try to scroll the parent page
Before fix:
After fix:
=> Fixed background settings popover collapses

ui-ngx/src/app/shared/components/nav-tree.component.ts
Hierarcy widget fires select node action too many times fix
Before:
Opens as much new windows as much nodes you have (because of 'ready' events).
After:
https://github.com/user-attachments/assets/f2615ee4-0ad0-4d29-b62d-45297d631bc5
`changed.jstree` event also triggers `ready` events of all nodes, Thats why we using `select_node.jstree` event now.
Clicking on expand/collapse doenst trigger `select_node`, after and before fix.
It is impossible to reproduce in `tb-customers-hierarchy` (even with trottling) because there we have `All` main node that needs to be expanded first. But this change will also affect `tb-customers-hierarchy` just in case.
=> Hierarcy widget fires select node action too many times fix

application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java, application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java, application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java, application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/AssetProfileExportService.java, application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DefaultEntityExportService.java, application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DeviceProfileExportService.java, application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/WidgetsBundleExportService.java, application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ImageService.java, dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
Before, after exporting device profile, asset profile or widgets bundle with an image, when Caffeine cache is used, the entity's image would become invalid for some time:
=> Fix image getting broken after exporting entity

application/src/main/data/upgrade/basic/schema_update.sql, dao/src/main/java/org/thingsboard/server/dao/domain/DomainServiceImpl.java
Updated constraint name to valid one
=> Updated constraint name to valid one

application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java, application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/AlarmTriggerProcessor.java, application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationRequestService.java, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationRequestService.java, dao/src/main/java/org/thingsboard/server/dao/notification/NotificationRequestDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationRequestDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRequestRepository.java
This fixes duplicated alarm notification when clear rule ("stop escalation when X") of the alarm notification rule is met, or the alarm is deleted:
=> Fix duplicate alarm notification when clear rule is met

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
=> EdgeGrpcSession - fixed abort of sync process in case high priority message notification

ui-ngx/src/assets/help/en_US/resource/js-resource-module_fn.md
JS Resource Module minor symbol correction
=> JS Resource Module example minor symbol correction

ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-table-header.component.html, ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-table-header.component.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/clients-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-header.component.html, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-header.component.ts, ui-ngx/src/app/shared/models/constants.ts, ui-ngx/src/app/shared/models/entity-type.models.ts
1.  Added a help link to the Domain entity.
2.  Updated help links for mobileApplication and mobileQrCode.
3.  Improved the display of help buttons in the table header on mobile screens.
Before:
After:
=> Enhance help links and improve help button display

ui-ngx/src/app/core/http/mobile-app.service.ts
=> Fixed send empty OAuth2 mobile clients data

ui-ngx/src/app/shared/components/js-func-module-row.component.html, ui-ngx/src/app/shared/components/js-func-module-row.component.ts, ui-ngx/src/app/shared/components/js-func-modules.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
1. Fixed the issue where the "Apply" button did not become active after deleting a JS module.
2. Added validation for the alias name of the JS module to ensure it complies with JS valid variable name standards.
After:
=> Fixed deletion of JS module in function and added validation for alias name in JS module

ui-ngx/src/app/shared/models/js-function.models.ts
Usage of special HTML chars in makrdawn fix
=> Usage of special HTML chars in mardown fix

ui-ngx/.browserslistrc
=> Improved browser compatibility coverage for better platform functionality across various browsers

ui-ngx/eslint.config.mjs
=> Improvement configuration eslint.config.mjs

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeGrpcSession.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/GeneralEdgeEventFetcher.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java, dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
=> Fixed case when seqId started new cycle. Improved edge trace/debug logging

application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
lwM2mUplinkMsgHandler.updateAttrTelemetry(
<any org.eclipse.leshan.server.registration.Registration>,
"/3_1.2/0/9",
null
);
Wanted 3 times:
-> at org.thingsboard.server.transport.lwm2m.server.uplink.DefaultLwM2mUplinkMsgHandler.updateAttrTelemetry(DefaultLwM2mUplinkMsgHandler.java:642)
But was 14 times:
```
```
change .times to .atLeast
```
=> fix_ bug_lwm2m_flaky_test

ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts, ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
Fixed an issue in the TinyMCE editor where links containing substitution patterns were automatically appended with the base URL. This behavior led to incorrect link formatting.
Before:
After:
=> Fixed incorrect auto-conversion of inserted links in TinyMCE editor

application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
=> Ignore unconfigured delivery method for system notification type

application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
=> Fix test: testRuleChains

application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java, application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java
=> Ignore version from tb_schema_settings when from_version property is specified

application/src/main/resources/thingsboard.yml
=> Temporary disabled relatedEdges due to issue with scan method

application/src/test/java/org/thingsboard/server/cache/CaffeineCacheDefaultConfigurationTest.java
=> Fix CaffeineCacheDefaultConfigurationTest

application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java
=> tbel_tests_doc_bitwise_operations

msa/js-executor/api/jsExecutor.models.ts, msa/js-executor/api/jsInvokeMessageProcessor.ts, msa/js-executor/api/utils.ts, msa/js-executor/package.json, msa/js-executor/queue/kafkaTemplate.ts, msa/js-executor/yarn.lock
Clear after remove all queue types except Kafka
=> Clear JS executor dependencies and code

application/src/main/java/org/thingsboard/server/service/ttl/AlarmsCleanUpService.java, application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java, application/src/test/java/org/thingsboard/server/service/script/AbstractTbelInvokeTest.java, application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java, application/src/test/java/org/thingsboard/server/service/script/TbelInvokeServiceTest.java, application/src/test/java/org/thingsboard/server/service/ttl/AlarmsCleanUpServiceTest.java
=> tbel test refactoring

ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/notification/template/template-table-config.resolver.ts
=> Fixed notification template/rules table not updating after copy creation

application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java, common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-5362
- hexToBytesArray
```
var validInputList = "0x01752B0367FA000500010488FFFFFFFFFFFFFFFF33";
var validInputArray = "AABBCCDDEE";
msg.hexToBytes = hexToBytes(validInputList);
msg.hexToBytesArray = hexToBytesArray(validInputArray);
```
_return_ 
```
"hexToBytes": [1, 117, 43, 3, 103, -6, 0, 5, 0, 1, 4, -120, -1, -1, -1, -1, -1, -1, -1, -1, 51],
"hexToBytesArray": [-86, -69, -52, -35, -18]
```
- base64ToBytesList
```
msg.base64ToBytes =  base64ToBytes("Kkk=");
msg.base64ToBytesList =  base64ToBytesList("AQIDBAU=");
```
return 
```
"base64ToBytes": [42, 73],
"base64ToBytesList": [1, 2, 3, 4, 5]
```
=> tbel: add hexToBytesArray, base64ToBytesList

ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-dialog.component.ts
=> Fixed not allow edit release note in mobile application

ui-ngx/angular.json, ui-ngx/esbuild/tb-html-fallback-middleware.ts
=> Fixed blank screen on SCADA editor page refresh in development mode

ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html, ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.ts
Fixed empty notifications on slow WS connection
https://github.com/user-attachments/assets/933258b6-2d76-4d6f-a271-5c23de55282e
https://github.com/user-attachments/assets/025bc546-8954-485c-873e-4e2e8f31ac98
Now we showing empty state only when empty array is returned explicitly. Otherwise loading state is showing.
=> Fixed empty notifications on slow WS connection

dao/src/main/java/org/thingsboard/server/dao/service/validator/MobileAppDataValidator.java
Fixed mobile app store info validation
=> Fixed mobile app store info validation

common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
=> VC: fix invalid error when checking access to repository

dao/src/main/java/org/thingsboard/server/dao/mobile/QrCodeSettingServiceImpl.java
Fixed mobile app bundle id null pointer exception after migration
=> Fixed mobile app bundle id null pointer exception after migration

common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java, common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
NPE occurred after transport restart if lwm2m device was connected.
```
2025-01-06 14:09:23,779 [main] WARN o.t.s.t.l.s.s.TbRedisLwM2MClientStore - Failed to serialize client: LwM2mClient(endpoint=BXuNaZCooRRChbCSOOCe)
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.toString()" because the return value of "org.eclipse.leshan.server.registration.Registration.getAddress()" is null
at org.thingsboard.server.transport.lwm2m.server.store.util.LwM2MClientSerDes.serialize(LwM2MClientSerDes.java:129)
at org.thingsboard.server.transport.lwm2m.server.store.TbRedisLwM2MClientStore.put(TbRedisLwM2MClientStore.java:113)
at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.updateFetchedClient(LwM2mClientContextImpl.java:145)
at …
```
=> [Transport] lwm2m client serialization fixes

packaging/java/scripts/control/template.service
Fixed Restart option for systemd service template. Systemd parsed everything after '=' as the option, so the comment broke the Restart policy for Thingsboard service. The service didn't restart in case of failure. The command for verifying systemd services is 
```
sudo systemd-analyze verify thingsboard.service
```
=> Fixed systemd template Restart parameter

ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
=> Fix issue where drawing a circle didn't work in map widgets

ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
=> Fix issue where polygon/circle fill and stroke color functions didn't work in map widgets

ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.html, ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts
Updated the logic to ensure the form reflects the latest validation constraints.
=> Synchronize validation rules for the mobile app configuration form with the API

ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-bar.models.ts
=> Fixed incorrect display of negative values in the time series bar chart

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rabbitmq/TbRabbitMqNodeConfiguration.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rabbitmq/TbRabbitMqNodeTest.java
fix: removed default host value for RabbitMQ node
=> Removed default host value for RabbitMQ node

application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
- Changed random failure logic for DownlinkMsg. A DownlinkMsg can fail only twice.
=> Fix telemetry edge test

ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-widget-settings.component.ts
=> Fixed some of the applied settings not being shown in trip animation widget

ui-ngx/src/app/modules/home/components/entity/entity-chips.component.html, ui-ngx/src/app/modules/home/components/relation/relation-table.component.html, ui-ngx/src/app/modules/home/components/widget/lib/home-page/doc-link.component.html, ui-ngx/src/app/modules/home/components/widget/lib/home-page/doc-links-widget.component.html, ui-ngx/src/app/shared/components/dialog/confirm-dialog.component.html
Added custom translation support in :
- entity table chips 
- relation table 
- home doc links and link
=> Added custom translation support

ui-ngx/src/app/shared/import-export/import-dialog.component.ts
Fixed both import types active on import dialog open
=> Fixed both import types active on import dialog open

ui-ngx/src/app/modules/home/components/widget/lib/display-columns-panel.component.scss
Fixed columns to display filter panel scroll when on dashboard bottom edge
When a parent container has `height: fit-content`, it will size itself to match its content's height. This creates a circular dependency with the child's `height: 100%`:
- The child (:host element) tries to be 100% of the parent's height
- But the parent has height: fit-content, so it's trying to size itself based on the child's content
- This circular dependency often results in unexpected behavior, particularly with scrolling
By removing `height: 100%` the component will size naturally based on its content.
=> Fixed columns to display filter panel scroll when on dashboard edge

ui-ngx/src/app/core/http/domain.service.ts, ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts, ui-ngx/src/app/shared/models/oauth2.models.ts
Added domain update request chaining
`Oauth2Clients` should not be updated if domain update fails, that's why `switchMap` requests chaining was introduced.
=> Added domain update request chaining

ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
Fixed oathclient - client id and secret removal with slow internet
https://github.com/user-attachments/assets/b9016b00-9c13-4400-a804-8ae62ead321c
https://github.com/user-attachments/assets/8270afbc-a4aa-441e-a87c-ae7985d9a688
If `getOAuth2Template` request takes too much time `clientId` and `clientSecret` fields are erased by `setProviderDefaultValue` method. `setProviderDefaultValue` on initiating is useless unless it's Oauth2Client creation.
=> Fixed oathclient - client id and secret removal with slow internet

ui-ngx/src/app/shared/components/js-func-modules.component.html
Fixed unnecessary scroll in JS Library alias on error tooltip showing
Adding `flex` to component creates a flex context that helps contain absolutely positioned elements.
=> Fixed unnecessary scroll in JS Library alias on error tooltip showing

application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java, application/src/main/java/org/thingsboard/server/service/telemetry/InternalTelemetryService.java, common/dao-api/src/main/java/org/thingsboard/server/dao/timeseries/TimeseriesService.java, common/data/src/main/java/org/thingsboard/server/common/data/kv/TimeseriesSaveResult.java, dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
=> Return TimeseriesSaveResult when saving timeseries

common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/DefaultTransportMBeanConfiguration.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/HashMapObserver.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/HashMapObserverMBean.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewayDeviceSessionContext.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewayDeviceSessionContext.java, common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/MqttDeviceAwareSessionContext.java
mbean transport sessions
gateway handler session leak fix
https://thingsboard-portal.atlassian.net/browse/PAAS-196
=> mbean transport sessions

ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.ts, ui-ngx/src/app/shared/models/mobile-app.models.ts
=> Fixed validation issues for URLs on the mobile page configuration, including Unicode symbols

ui-ngx/src/app/modules/home/components/widget/lib/maps/polyline.ts
=> Fixed error when using path decorator setting  in trip animation widget

ui-ngx/src/app/core/api/entity-data-subscription.ts
Fix removes key duplicates in subscription cmds when subscribed to the same key multiple times.
Before:
The data values 6-11 are duplicates of the 0-5:  
After:
=> Entity data subscription cmds prepare keys without duplicates.

application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
core device actor: device subscriptions remove on session limit
https://thingsboard-portal.atlassian.net/browse/PAAS-198
P.S. mergable with PE with no conflicts.
=> core device actor: device subscriptions remove on session limit

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/BaseCalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/RocksDBStateService.java, common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java, common/proto/src/main/proto/queue.proto, dao/src/main/java/org/thingsboard/server/dao/service/validator/CalculatedFieldDataValidator.java
=> Calculated fileds

ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts, ui-ngx/src/app/modules/home/pages/asset-profile/asset-profile-tabs.component.html, ui-ngx/src/app/modules/home/pages/asset/asset-tabs.component.html, ui-ngx/src/app/modules/home/pages/device-profile/device-profile-tabs.component.html, ui-ngx/src/app/shared/models/calculated-field.models.ts
Calculated fields adjustments, improvements and fixes
- Added calculated list for Assets, Asset Profiles, Device profiles
- Added hint for Rolling keys in Simple
- Output-type to scope rename
- Fixed calculatedFieldType change shows errors
- Arguments name show on calculatedFieldType change fix
- Key scope not saved fix
=> Calculated fields adjustments, improvements and fixes

ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
=> Fixed lose context when use expandSettingComponentMap in custom widgets

ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html, ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
Fixed unclear cached result in dashboard autocomplete when changing user.
Fixed incorrect aria-label text on a link.
Fixed autocomplete panel remaining visible when the element was disabled.
=> Fixed unclear cached result in dashboard autocomplete when changing user

application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/service/cf/CalculatedFieldExecutionService.java, application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldCache.java, application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldExecutionService.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/CalculatedFieldStateService.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/BaseCalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/RocksDBStateService.java, application/src/main/java/org/thingsboard/server/service/security/permission/TenantAdminPermissions.java, application/src/main/resources/thingsboard.yml, application/src/test/java/org/thingsboard/server/service/cf/ctx/state/ScriptCalculatedFieldStateTest.java, application/src/test/java/org/thingsboard/server/service/cf/ctx/state/SimpleCalculatedFieldStateTest.java, common/data/src/main/java/org/thingsboard/server/common/data/cf/configuration/Argument.java, common/data/src/main/java/org/thingsboard/server/common/data/cf/configuration/Output.java, common/data/src/main/java/org/thingsboard/server/common/data/cf/configuration/ReferencedEntityKey.java, dao/src/main/java/org/thingsboard/server/dao/cf/BaseCalculatedFieldService.java, dao/src/main/java/org/thingsboard/server/dao/sql/event/CalculatedFieldDebugEventRepository.java, dao/src/main/resources/sql/schema-entities.sql
=> Calculated fields

application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/BaseDashboardProcessor.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/DashboardEdgeProcessor.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/DashboardEdgeProcessorV1.java, application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java
PR related to next bug:
https://github.com/thingsboard/thingsboard-edge/issues/140
Despite the fact, that Dashboard entity shown properly assigned customers on dashboards list, relation between customer and dashboard was not created properly. Because of this customer was not able to see dashboards in the list.
=> Edge - fixed assignment/un-assignment of dashboards

common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java, common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Fixed an issue where a user attempted to unsubscribe from a topic without having been subscribed to it.
=> MQTT: fix unsubscribe error without previous subscribe

application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DashboardSyncService.java, application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java, application/src/main/java/org/thingsboard/server/service/install/ProjectInfo.java, application/src/main/resources/thingsboard.yml, common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
=> Resolve gateway dashboard branch automatically

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
Issue https://github.com/thingsboard/thingsboard/issues/12639
=> Encode username/password pair instead of decoding it.

ui-ngx/src/app/shared/import-export/import-export.service.ts
Semicolon is a delimiter in CSV files.
Strings containing this symbol should be wrapped in quotes.
Before:
Exported alarm activity
Author;Created date;Edited date;Text
tenant@thingsboard.org;2025-02-07 18:39:06;;_Active Unacknowledged; 2025-02-07_
After:
Exported alarm activity
Author;Created date;Edited date;Text
tenant@thingsboard.org;2025-02-07 18:39:06;;**"**_Active Unacknowledged; 2025-02-07_**"**
=> Fixed CSV export for strings containing semicolon

ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html, ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
This PR fixes two issues related to the entity autocomplete component:
**Incorrect link generation** – Previously, the link to the entity details page was generated incorrectly.
**Incorrect navigation after editing** – After changing the value in the autocomplete field, the navigation still led to the previous entity instead of the newly selected one.
=> Fixed incorrect entity details page link in entity autocomplete component

ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.ts
=> Fixed incorrect liquid level widget config selector

ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.html
=> Fixed incorrect shape layout settings in liquid level widget

application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_db.md, application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/GeneralEdgeEventFetcher.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/BaseDashboardProcessor.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/EdgeRequestsService.java, application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
1. Fixed docker upgrade Edge instructions
2. Ack NOT timeseries downlink messages to speed up setup in case of some failures
3. Added additional during fetchin edge events from DB in case seq id started from begin
=> Improved Edge handling in case connect/disconnect. Speed up initial setup

application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java, application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java, application/src/test/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessorTest.java
Added test to verify attribute and RPC subscriptions removal on session overflow. 
The test ensures that when a new session is added, the least recent sessions (including their associated attributes and RPC subscriptions) are removed as expected.
=> Added test to verify attribute and RPC subscriptions removal

ui-ngx/src/app/core/http/calculated-fields.service.ts, ui-ngx/src/app/core/http/rule-chain.service.ts, ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/public-api.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts, ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html, ui-ngx/src/app/modules/home/components/event/event-table-config.ts, ui-ngx/src/app/modules/home/components/home-components.module.ts, ui-ngx/src/app/shared/components/value-input.component.html, ui-ngx/src/app/shared/components/value-input.component.ts, ui-ngx/src/app/shared/models/calculated-field.models.ts, ui-ngx/src/app/shared/models/entity.models.ts, ui-ngx/src/app/shared/models/rule-node.models.ts, ui-ngx/src/assets/help/en_US/calculated-field/expression_fn.md, ui-ngx/src/assets/help/en_US/calculated-field/test-expression_fn.md, ui-ngx/src/assets/locale/locale.constant-en_US.json
Implemented Calculated Fields debug test
=> Implemented Calculated Fields debug test

ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts, ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Added calculated field responsive styles
SplitObjects garbage collected without explicit destroy call
=> Added calculated field responsive styles

ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts, ui-ngx/src/app/modules/home/components/event/event-table-config.ts, ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts, ui-ngx/src/app/modules/home/pages/device-profile/device-profile-tabs.component.html
Calculated field adjustments
- Test script from debugging event save calculated field bug fix;
- Added test function icon button 
- Scope output field only on device entity
- Entity link in debugging events and ids tooltips
- Moved calculated fields in device profile tabs
=> Calculated field adjustments

ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
Added debug events action from calculated field table
=> Added debug events action from calculated field table

ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html, ui-ngx/src/app/shared/components/js-func.component.ts, ui-ngx/src/app/shared/models/calculated-field.models.ts
Added Calculated field arguments autocomplete
=> Added Calculated field arguments autocomplete

docker/docker-compose.prometheus-grafana.yml
docker-compose was blocked by outdated prometheus image version.
updated from 2.1.0 to 3.1.0
=> updated prometheus version to 3.1.0

application/src/main/java/org/thingsboard/server/service/cf/AbstractCalculatedFieldStateService.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/KafkaCalculatedFieldStateService.java, common/queue/src/main/java/org/thingsboard/server/queue/common/AbstractTbQueueTemplate.java, common/queue/src/main/java/org/thingsboard/server/queue/common/TbProtoQueueMsg.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java
=> CF Kafka states cleanup

ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.ts
=> Fixed apply changes button enabled by default in Device Profile Transport configuration tab

application/src/main/data/json/system/scada_symbols/control-panel-hp.svg, application/src/main/data/json/system/scada_symbols/horizontal-connector-hp.svg, application/src/main/data/json/system/scada_symbols/leak-sensor.svg, application/src/main/data/json/system/scada_symbols/left-analog-water-level-meter.svg, application/src/main/data/json/system/scada_symbols/left-drain-pipe.svg, application/src/main/data/json/system/scada_symbols/left-elbow-drain-pipe.svg, application/src/main/data/json/system/scada_symbols/long-bottom-filter.svg, application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg, application/src/main/data/json/system/scada_symbols/long-top-filter.svg, application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg, application/src/main/data/json/system/scada_symbols/right-analog-water-level-meter.svg, application/src/main/data/json/system/scada_symbols/right-drain-pipe.svg, application/src/main/data/json/system/scada_symbols/right-elbow-drain-pipe.svg, application/src/main/data/json/system/scada_symbols/short-bottom-filter.svg, application/src/main/data/json/system/scada_symbols/short-left-drain-pipe.svg, application/src/main/data/json/system/scada_symbols/short-right-drain-pipe.svg, application/src/main/data/json/system/scada_symbols/short-top-filter.svg, application/src/main/data/json/system/scada_symbols/vertical-connector-hp.svg
=> Imporove description for scada symbols

application/src/main/data/json/system/scada_symbols/dynamic-vertical-scale-hp.svg, application/src/main/data/json/system/scada_symbols/simple-vertical-scale-hp.svg
=> Fixed scale symbol units

ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.html, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-dialog.component.html, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-dialog.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
PROD-5516: Add validators to check max length and cannot contain only white spaces to:
- Mobile center Bundle dialog: title
- Custom mobile dialog: page name
PROD-5525: Mobile center Bundle do not updateData() after close dialog MobileAppConfiguration.
=> Improve Mobile center Bundle validators, remove redundant request

application/src/main/data/json/system/scada_symbols/bottom-flow-meter.svg, application/src/main/data/json/system/scada_symbols/horizontal-inline-flow-meter.svg, application/src/main/data/json/system/scada_symbols/left-flow-meter.svg, application/src/main/data/json/system/scada_symbols/right-flow-meter.svg, application/src/main/data/json/system/scada_symbols/top-flow-meter.svg, application/src/main/data/json/system/scada_symbols/vertical-inline-flow-meter.svg, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Add property decimals for flow meter symbol

application/src/main/data/json/system/scada_symbols/electrical-engine-hp.svg, application/src/main/data/json/system/scada_symbols/gas-preventer-hp.svg, application/src/main/data/json/system/scada_symbols/gas-wellhead-hp.svg, application/src/main/data/json/system/scada_symbols/heat-exchanger-hp.svg, application/src/main/data/json/system/scada_symbols/large-horizontal-separator-connector-hp.svg, application/src/main/data/json/system/scada_symbols/large-horizontal-separator-hp.svg, application/src/main/data/json/system/scada_symbols/large-vertical-separator-connector-hp.svg, application/src/main/data/json/system/scada_symbols/large-vertical-separator-hp.svg, application/src/main/data/json/system/scada_symbols/oil-pump-hp.svg, application/src/main/data/json/system/scada_symbols/small-horizontal-separator-connector-hp.svg, application/src/main/data/json/system/scada_symbols/small-horizontal-separator-hp.svg, application/src/main/data/json/system/scada_symbols/small-vertical-separator-connector-hp.svg, application/src/main/data/json/system/scada_symbols/small-vertical-separator-hp.svg, application/src/main/data/json/system/scada_symbols/turbine-hp.svg, application/src/main/data/json/system/widget_bundles/general_high_performance_scada_symbols.json, application/src/main/data/json/system/widget_bundles/high_performance_scada_oil_gas.json
=> SCADA Oil and gas extraction

ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.scss
=> Fixed a blur effect issue in the Getting started widget

ui-ngx/src/form.scss
Fixed mdc notch unnecessary border
=> Fixed mdc notch unnecessary border

application/src/main/resources/thingsboard.yml, application/src/test/java/org/thingsboard/server/transport/coap/AbstractCoapIntegrationTest.java, application/src/test/java/org/thingsboard/server/transport/coap/security/AbstractCoapSecurityIntegrationTest.java, application/src/test/resources/application-test.properties, common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapServerComponent.java, common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapTransportComponent.java
property coap.enabled (`COAP_SERVER_ENABLED`) has conflict with env `COAP_ENABLED`
=> Fix CoAP enabled properties

application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java, application/src/test/java/org/thingsboard/server/actors/rule/DefaultTbContextTest.java
Input rule node always uses Main queue for enqueue! 
https://thingsboard-portal.atlassian.net/browse/PROD-5658
=> [Input node] Use correct queue name from msg

application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
Cherry-picked from https://github.com/thingsboard/thingsboard/pull/12751 for hotfix
=> used correct queueName for TPI in input node

application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java, rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
=> Minor refactoring for TbContext

ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/shared/models/calculated-field.models.ts
Calculated fields adjustments
- Arguments table update 
- Changed default debugSettings to enabled
=> Calculated fields adjustments

application/src/main/data/json/system/widget_types/image_map.json, application/src/main/data/json/system/widget_types/map.json, ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions-dialog.component.html, ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions-dialog.component.ts, ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.ts, ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html, ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts, ui-ngx/src/app/modules/home/components/widget/config/basic/common/widget-actions-panel.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet/leaflet-tb.ts, ui-ngx/src/app/modules/home/components/widget/lib/maps/map.scss, ui-ngx/src/app/modules/home/components/widget/lib/maps/map.ts, ui-ngx/src/app/modules/home/components/widget/lib/maps/models/map.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action-settings-panel.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action-settings-panel.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-button-row.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-button-row.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-buttons-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-buttons-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts, ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts, ui-ngx/src/app/modules/home/components/widget/widget-config.component.html, ui-ngx/src/app/modules/home/components/widget/widget.component.ts, ui-ngx/src/app/shared/models/widget.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json, ui-ngx/src/typings/leaflet-extend-tb.d.ts
=> Added new map action type - Map action buttons

common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbelCfTsRollingArgTest.java, ui-ngx/src/app/shared/components/js-func.component.ts
=> JS func update

application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java, application/src/test/java/org/thingsboard/server/actors/rule/DefaultTbContextTest.java, rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
https://thingsboard-portal.atlassian.net/browse/PROD-5669
=> use queueName from TbMsg for enqueue

application/src/test/java/org/thingsboard/server/controller/DeviceProfileControllerTest.java, dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
In some cases, after creating a new device profile (or some other entity), invalid version was assigned, causing the following error when trying to update the entity:
=> Fix invalid entity version after creation

application/src/main/java/org/thingsboard/server/service/security/permission/Resource.java, application/src/main/java/org/thingsboard/server/service/security/permission/TenantAdminPermissions.java
PE: https://github.com/thingsboard/thingsboard-pe/pull/3288
=> Calculated fields: resource

application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/Lwm2mTestHelper.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_0_Test.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_1_Test.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_2_Test.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2MIntegrationObserveCompositeTest.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_0_Test.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_1_Test.java, application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_2_Test.java, application/src/test/resources/lwm2m/3-1_0.xml, application/src/test/resources/lwm2m/3-1_1.xml, common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
(cherry picked from commit fcf74a82407ef54236e35eea97d6d838c531bc9f)
=> LwM2M: fix observe

common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
=> TbDate - added functions to add years, months, days, etc.

msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java, transport/coap/src/main/resources/tb-coap-transport.yml
=> [CoAP transport] removed unnecessary coap configs

ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss, ui-ngx/src/app/shared/models/calculated-field.models.ts, ui-ngx/src/assets/help/en_US/calculated-field/test-expression_fn.md, ui-ngx/src/assets/locale/locale.constant-en_US.json
Added rolling argument functions autocompletes
=> Added rolling argument functions autocompletes

application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java, application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmCountSubCtx.java, application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java, common/data/src/main/java/org/thingsboard/server/common/data/query/AlarmCountQuery.java, common/data/src/main/java/org/thingsboard/server/common/data/query/EntityCountQuery.java, dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java, dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java, dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/query/AlarmQueryRepository.java, dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultAlarmQueryRepository.java, dao/src/test/java/org/thingsboard/server/dao/service/AlarmServiceTest.java, ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarm-count-basic-config.component.html, ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarm-count-basic-config.component.ts, ui-ngx/src/app/modules/home/components/widget/config/datasource.component.html, ui-ngx/src/app/modules/home/components/widget/config/datasource.component.ts, ui-ngx/src/app/modules/home/components/widget/config/datasources.component.ts
Added new optional parameters in the alarm count datasource
=> Entity filters for AlarmCountQuery

application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/SingleValueArgumentEntry.java, application/src/main/resources/thingsboard.yml, application/src/test/java/org/thingsboard/server/service/cf/ctx/state/SingleValueArgumentEntryTest.java
- added logic to persist state even calculation is not performed
- removed check for value change when update state
- moved calculation result timeout to configuration parameter
=> Removed check for value change when update state

ui-ngx/src/app/core/http/calculated-fields.service.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
Added latest debug event call in Calculated Field Dialog on Test function
=> Added latest debug event call in СF Dialog on Test function

application/src/main/data/upgrade/basic/schema_update.sql, common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java, ui-ngx/src/app/shared/models/tenant.model.ts
added upgrade script for tenant profiles to add limits for calculated fields
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/3310
=> Added upgrade script for tenant profile

application/src/test/java/org/thingsboard/server/service/entitiy/EdqsEntityServiceTest.java, application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java
=> Fixed flaky EDQS tests

application/src/main/java/org/thingsboard/server/service/cf/ctx/state/SimpleCalculatedFieldState.java, application/src/test/java/org/thingsboard/server/service/cf/ctx/state/SimpleCalculatedFieldStateTest.java, common/data/src/main/java/org/thingsboard/server/common/data/cf/configuration/Output.java, common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
=> Added option to round result for simple type

.github/workflows/check-configuration-files.yml
=> Update GitHub workflow Ubuntu version to 22.04

application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java, application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
=> Fix TenantControllerTest

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldCache.java, application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldProcessingService.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/BaseCalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldState.java, application/src/test/java/org/thingsboard/server/service/cf/ctx/state/ScriptCalculatedFieldStateTest.java, application/src/test/java/org/thingsboard/server/service/cf/ctx/state/SimpleCalculatedFieldStateTest.java
=> Added check for single value argument size

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java, application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldProcessingService.java, application/src/main/resources/thingsboard.yml, common/data/src/main/java/org/thingsboard/server/common/data/TenantProfile.java, common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java, common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/TenantProfileData.java
- added validation
- fixed timeouts
=> Added validation and fixed timeouts

application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java, application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
[PE PR](https://github.com/thingsboard/thingsboard-pe/pull/3320)
=> Save time series strategies: fix broken tests for device state service

application/src/main/resources/thingsboard.yml, dao/src/main/java/org/thingsboard/server/dao/config/DedicatedEventsJpaDaoConfig.java
PE: https://github.com/thingsboard/thingsboard-pe/pull/3322
=> Added cf debug event entity to dedicated events config

ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts, ui-ngx/src/app/shared/models/calculated-field.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Changed Calculated fields highlights and autocompletes
=> Changed Calculated fields highlights and autocompletes

common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java, dao/src/main/resources/sql/schema-entities-idx-psql-addon.sql
PE: https://github.com/thingsboard/thingsboard-pe/pull/3324
=> Added index for cf debug event

ui-ngx/src/assets/help/en_US/calculated-field/expression_fn.md
=> CF: help page

ui-ngx/src/app/shared/models/widget/maps/marker-shape.models.ts, ui-ngx/src/assets/markers/shape7.svg
=> Fixed fill-opacity in marker shape7.svg

common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/EntityViewFields.java, dao/src/main/java/org/thingsboard/server/dao/sql/entityview/EntityViewRepository.java
=> EDQS: fix entity views sync

common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
=> Fix createEdgeEventMsgConsumer

ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/default-mobile-page-panel.component.html, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/default-mobile-page-panel.component.ts, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.html, ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.ts
Mobile center - Bundles. Field page name added validators 256-length, cannot contain white spaces.
=> Mobile center added page name validators

ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-key-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-key-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-key-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-key-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Setting to disable sorting in Table-widgets

ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
Fixed transport messages maximum number hints
=> Fixed transport messages maximum number hints

ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-instances.component.scss
Remove extra scroll in Device profile LWM2M transport table. 
Before:
After:
=> Fix device profile extra scroll in lwm2m model

application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java
=> Add 3.9.1 to SUPPORTED_VERSIONS_FOR_UPGRADE

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java, common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
=> CF: improvements

application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
=> CF: fixed init cf actor

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/service/cf/CalculatedFieldResult.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java, application/src/main/java/org/thingsboard/server/service/entitiy/queue/DefaultTbQueueService.java, application/src/test/java/org/thingsboard/server/cf/CalculatedFieldIntegrationTest.java, application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java, application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java, dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
=> Calculated fields: improvements and fixes

application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldInitService.java
=> Fixed cf init service

common/edqs/src/main/java/org/thingsboard/server/edqs/repo/TenantRepo.java
=> EDQS: refactoring

application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java, common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/EntityDataInfo.java
=> Fix method getEntityDataInfo in VersionController

application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java, application/src/test/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessorTest.java, common/util/src/main/java/org/thingsboard/common/util/LinkedHashMapRemoveEldest.java, common/util/src/test/java/org/thingsboard/common/util/LinkedHashMapRemoveEldestTest.java
Usage of long refactored to int in LinkedHashMapRemoveEldest class
=> Usage of long refactored to int in LinkedHashMapRemoveEldest class

application/src/main/java/org/thingsboard/server/actors/service/ComponentActor.java, application/src/test/java/org/thingsboard/server/actors/service/ComponentActorTest.java
Tests for scheduleStatsPersistTick and destroy methods in ComponentActor were written.
=> Tests for ComponentActor

application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
Fixed relation created for gateway devices
PE: https://github.com/thingsboard/thingsboard-pe/pull/3347
=> Gateway relation fix

common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/EntityFields.java
Fixed missed "title" entity field subscription
=> Fixed missed "title" entity field subscription

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCalculatedFieldConsumerService.java, application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- added handling component lifecycle events
- added check for partition to avoid cf init on each partition
- fixed tests
=> CF: fixed cluster issues

application/src/test/java/org/thingsboard/server/actors/service/ComponentActorTest.java
=> Fix license header

application/src/main/data/json/system/scada_symbols/cylindrical-tank.svg, application/src/main/data/json/system/scada_symbols/elevated-tank.svg, application/src/main/data/json/system/scada_symbols/horizontal-tank-hp.svg, application/src/main/data/json/system/scada_symbols/horizontal-tank.svg, application/src/main/data/json/system/scada_symbols/large-cylindrical-tank.svg, application/src/main/data/json/system/scada_symbols/large-stand-cylindrical-tank.svg, application/src/main/data/json/system/scada_symbols/large-stand-vertical-tank.svg, application/src/main/data/json/system/scada_symbols/large-vertical-tank.svg, application/src/main/data/json/system/scada_symbols/pool-hp.svg, application/src/main/data/json/system/scada_symbols/short-vertical-tank-hp.svg, application/src/main/data/json/system/scada_symbols/small-cylindrical-tank.svg, application/src/main/data/json/system/scada_symbols/small-spherical-tank.svg, application/src/main/data/json/system/scada_symbols/spherical-tank.svg, application/src/main/data/json/system/scada_symbols/stand-cylindrical-tank.svg, application/src/main/data/json/system/scada_symbols/stand-horizontal-tank.svg, application/src/main/data/json/system/scada_symbols/stand-vertical-short-tank.svg, application/src/main/data/json/system/scada_symbols/stand-vertical-tank.svg, application/src/main/data/json/system/scada_symbols/vertical-short-tank.svg, application/src/main/data/json/system/scada_symbols/vertical-tank-hp.svg, application/src/main/data/json/system/scada_symbols/vertical-tank.svg, ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed https://github.com/thingsboard/thingsboard/issues/12742
=> Scale format for SCADA tank with units

ui-ngx/src/app/core/http/entity.service.ts
=> Fixed get rule chains for entity list component

ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
=> Fixed entity autocomplete

ui-ngx/src/app/shared/components/string-autocomplete.component.html, ui-ngx/src/app/shared/components/unit-input.component.html
=> Fixed icon close button position

ui-ngx/src/app/modules/home/pages/admin/settings-card.scss, ui-ngx/src/app/modules/home/pages/admin/sms-provider.component.scss, ui-ngx/src/styles.scss
=> Fixed help button color and position

ui-ngx/src/app/modules/home/components/rule-node/action/create-relation-config.component.ts
=> Fixed validation for target entity type create relation node

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings-panel.component.ts, ui-ngx/src/assets/help/en_US/widget/config/parse_value_get_dashboard_state_id_fn.md
=> Help for get dashboard state id aciton

ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
=> Fixed default events and add hot keys for Mac

ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html, ui-ngx/src/app/modules/home/components/event/event-table-config.ts, ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.ts, ui-ngx/src/app/shared/components/js-func.component.html, ui-ngx/src/app/shared/components/js-func.component.ts, ui-ngx/src/app/shared/import-export/import-export.service.ts, ui-ngx/src/app/shared/models/calculated-field.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Calculated adjustments
- Implemented import Calculated field with unknown ids
- Disabled test event if no arguments minor fix
- Made limit required minor fix
- Entity version create minor fix
- Highlight minor fix
- Tenant profile calculated field config translations minor fix
- Help popup width minor fix
- Added support for arrays result in events table 
- Updated default script
=> Calculated adjustments

ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
=> Improvement event handling hotkeys for Mac on the rulechain page

ui-ngx/src/app/shared/components/time/datetime-period.component.ts
=> Fixed date time period start/end values check

ui-ngx/src/app/shared/models/ace/tbel-utils.models.ts
=> Refactoring tbel utils autocompletes and highlights

ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html, ui-ngx/src/app/shared/models/constants.ts
=> Added link to help page for timewindow settings

application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java, dao/src/main/java/org/thingsboard/server/dao/relation/BaseRelationService.java
Fixed entity relation cleanup method
=> Fixed entity relation cleanup method

README.md
=> Remove link to Google Groups from README

ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
=> Hotfix for header action

common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
=> [API usage] revert accidentally deleted api-usage clearing

application/src/main/java/org/thingsboard/server/service/cf/ctx/state/KafkaCalculatedFieldStateService.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCalculatedFieldConsumerService.java, common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java, common/queue/src/main/java/org/thingsboard/server/queue/edqs/EdqsQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/edqs/InMemoryEdqsQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/edqs/KafkaEdqsQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerTemplate.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryMonolithQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/TbRuleEngineQueueFactory.java
=> Fix invalid queue admin reference

dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
Do not send update to edqs if rows were not updated
=> Ignore null version

application/src/test/java/org/thingsboard/server/edge/AssetProfileEdgeTest.java, application/src/test/java/org/thingsboard/server/edge/DeviceProfileEdgeTest.java
=> Fix testSendDeviceProfileToCloud & testSendAssetProfileToCloud

ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html, ui-ngx/src/assets/locale/locale.constant-en_US.json
Debug Configuration improvements
If you toggling it of there was always previous value shown (1 min left). But now when you turn it off it shows default value (15 min)
=> Debug Configuration improvements

ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts, ui-ngx/src/app/modules/home/components/widget/widget-container.component.html, ui-ngx/src/app/modules/home/components/widget/widget.component.ts, ui-ngx/src/app/modules/home/models/widget-component.models.ts, ui-ngx/src/app/shared/models/widget.models.ts
=> Refactoring widget header action button

application/src/test/java/org/thingsboard/server/controller/EdqsControllerTest.java, common/edqs/src/main/java/org/thingsboard/server/edqs/util/VersionsStore.java
Fixed edqs sync
PE: https://github.com/thingsboard/thingsboard-pe/pull/3367
=> Fixed edqs sync

common/edqs/src/main/java/org/thingsboard/server/edqs/data/ApiUsageStateData.java, common/edqs/src/main/java/org/thingsboard/server/edqs/data/BaseEntityData.java, common/edqs/src/main/java/org/thingsboard/server/edqs/data/EntityData.java, common/edqs/src/main/java/org/thingsboard/server/edqs/repo/TenantRepo.java, common/edqs/src/main/java/org/thingsboard/server/edqs/util/RepositoryUtils.java
=> Fixed EDQS sorting

application/src/main/resources/thingsboard.yml, application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java, dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Updated coaps connectivity commands with downloading certificates
=> COAP DTLS: updated connectivity commands

common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
MQTT transport handler - log tenant on subscribe issue
=> MQTT transport handler - log tenant on subscribe issue

dao/src/main/java/org/thingsboard/server/dao/sqlts/AbstractChunkedAggregationTimeseriesDao.java, dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java, dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java, dao/src/test/java/org/thingsboard/server/dao/sqlts/AbstractChunkedAggregationTimeseriesDaoTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-5846
=> [WS] fixed OOM

application/src/main/java/org/thingsboard/server/service/edqs/DefaultEdqsApiService.java, application/src/main/java/org/thingsboard/server/service/edqs/DefaultEdqsService.java, application/src/main/java/org/thingsboard/server/service/edqs/EdqsSyncService.java, application/src/main/java/org/thingsboard/server/service/edqs/KafkaEdqsSyncService.java, application/src/main/resources/thingsboard.yml, common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProducer.java, common/edqs/src/main/java/org/thingsboard/server/edqs/state/EdqsPartitionService.java, common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java, common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueRequestTemplate.java, common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java, common/queue/src/main/java/org/thingsboard/server/queue/discovery/PartitionService.java, common/queue/src/main/java/org/thingsboard/server/queue/edqs/KafkaEdqsQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaAdmin.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java, edqs/src/main/resources/edqs.yml, monitoring/src/main/java/org/thingsboard/monitoring/data/Latencies.java, monitoring/src/main/java/org/thingsboard/monitoring/data/MonitoredServiceKey.java, monitoring/src/main/java/org/thingsboard/monitoring/service/BaseMonitoringService.java, monitoring/src/main/resources/tb-monitoring.yml
=> Fixes for EDQS

ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
Fixed Calculated Field cross instance import with current tenant target entity argument shows unnecessary error
=> Fixed Calculated Field cross instance import with current tenant target entity argument shows unnecessary error

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-layers.component.html
=> Limit table content height in map layers with scroll on overflow

msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
=> Fix msa tests after docker service renaming

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/place-map-item-sample-html.raw, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/place-map-item-sample-js.raw, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-data-layer-dialog.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.html, ui-ngx/src/app/shared/components/entity/entity-type-select.component.html, ui-ngx/src/app/shared/components/entity/entity-type-select.component.ts, ui-ngx/src/assets/help/en_US/widget/action/custom_additional_params.md, ui-ngx/src/assets/help/en_US/widget/action/place_map_item/create_dialog_html.md, ui-ngx/src/assets/help/en_US/widget/action/place_map_item/create_dialog_js.md, ui-ngx/src/assets/help/en_US/widget/action/place_map_item/place_map_item_action.md, ui-ngx/src/assets/locale/locale.constant-en_US.json
Added a new example for the action type - place map item
Described the additionalParams argument type for custom actions
Described new action type - Place map item
Added hints for new settings
=> Add new map widgets helps/example

ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-widget-settings.component.ts
=> Fixed not work decline settings in advanced map settings

ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.html, ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.ts
=> Fixed autocomplete not closing in LWM2M list model

ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.scss
=> Clear getting start widget style

application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
Fixed sending empty time series updates on the latest cmp update.
PE: https://github.com/thingsboard/thingsboard-pe/pull/3380
=> Adding threshold to time-series line chart affects data sources post-processing

ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.models.ts, ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.ts
=> Fixed incorrect update date in widgets action table when switching widgets

ui-ngx/src/app/core/api/widget-api.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/maps/map.ts
=> Fixed place map item action on multiple header button clicks

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-color-settings-panel.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-color-settings-panel.component.scss, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-pattern-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/marker-clustering-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/marker-image-settings-panel.component.scss, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/trip-timeline-settings.component.html, ui-ngx/src/assets/locale/locale.constant-en_US.json
Added a default style in help popover:
Before:
After:
Added  scroll content in popover settings:
Before:
After:
=> Minor improvement in map widget

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java
=> Calculated fields: fixes and improvements

pom.xml
tomcat
CVE-2025-24813 - critical
CVE-2024-50379 - high
CVE-2024-56337 - high
netty
CVE-2025-24970 - high
CVE-2025-25193 - medium
=> Fixed vulnerabilities

ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
=> Fix custom translation not working for Y-axis label in chart widget

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-widget-settings.component.ts
=>  Fix map settings not updating when switching between different map type widgets

ui-ngx/src/app/shared/models/js-function.models.ts
=> Fixed scrolling markdown source code module

ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
Fixed an issue where chart settings did not update when switching between different chart type widgets in Advanced Mode
=> Fixed chart settings not updating when switching types in Advanced Mode

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
=> Refactoring widget action

ui-ngx/src/app/shared/components/color-input.component.ts
=> Fixed positioning for color picker popover

ui-ngx/src/app/core/services/utils.service.ts, ui-ngx/src/app/modules/home/components/widget/lib/maps/map.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/map-item-tooltips.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/map-item-tooltips.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts, ui-ngx/src/app/shared/models/widget.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Add to place map item action  - customize tooltip

ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
=> Fixed typo in 'Calculate Field' script section title

ui-ngx/src/app/modules/home/components/rule-node/common/time-unit-input.component.ts
=> Fixed time-unit component not correctly calculating selected time

ui-ngx/src/app/shared/components/string-items-list.component.html, ui-ngx/src/app/shared/components/string-items-list.component.ts
=> Add fetch function for string items list; fix double item addition on blur

ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.html, ui-ngx/src/app/shared/components/toggle-header.component.html, ui-ngx/src/app/shared/components/toggle-header.component.scss, ui-ngx/src/app/shared/components/toggle-header.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Error icon with tooltip for toggle select for Map widget settings

application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldEntityMessageProcessor.java, application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java, application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java, application/src/main/java/org/thingsboard/server/controller/EventController.java, common/data/src/main/java/org/thingsboard/server/common/data/event/CalculatedFieldDebugEventFilter.java, dao/src/main/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDao.java
- fixed clearing cf debug events by filter
- added check if my partitoin for linked telemetry msg
=> Calculated fields: fixes

application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java, common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/BoolDataPoint.java, common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/DoubleDataPoint.java, common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/LongDataPoint.java
Fixed issue with comparing different data point types 
PE: https://github.com/thingsboard/thingsboard-pe/pull/3409
=> Different data type comparison

application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java, common/edqs/src/main/java/org/thingsboard/server/edqs/util/RepositoryUtils.java
Non-exiting data point should return 0 ts
PE: https://github.com/thingsboard/thingsboard-pe/pull/3408
=> EDQS: “N/A” message doesn’t display

application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java, application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java, application/src/main/java/org/thingsboard/server/service/ws/telemetry/sub/TelemetrySubscriptionUpdate.java, application/src/test/java/org/thingsboard/server/controller/TbTestWebSocketClient.java, application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java, common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
Fixed telemetry update handling for timeseries subscription when scope is LATEST_TELEMETRY.
PE: https://github.com/thingsboard/thingsboard-pe/pull/3388
=> [Telemetry] WS Subscription: Older telemetry overwrites newer data on UI

application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java
Added custom functions to cf expression
=> Added custom functions to cf expression

application/src/main/java/org/thingsboard/server/service/edqs/EdqsSyncService.java
EDQS: added error handling while data sync
=> EDQS: added error handling while data sync

dao/src/main/java/org/thingsboard/server/dao/sqlts/CachedRedisSqlTimeseriesLatestDao.java, dao/src/main/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDao.java, dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java, dao/src/test/java/org/thingsboard/server/dao/service/timeseries/sql/TimeseriesServiceSqlTest.java
If there is no telemetry in the database (or if the version is null), we do not put a null value in the cache (we do not overwrite the previous value) and it remains unchanged, so the cache will return the old value that was deleted.
=> Fixed time series redis cache

application/src/main/resources/thingsboard.yml, application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java, dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Added env property to configure gateway image version.
CE: https://github.com/thingsboard/thingsboard-pe/pull/3423
=> Configurable gateway image version

application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java, common/util/pom.xml, common/util/src/main/java/org/thingsboard/common/util/ExpressionFunctionsUtil.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNode.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
Added custom functions to the math node
=> Added custom functions to the math node

ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.html
=> Fixed enter press trigger click handler in dialogs

ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
=> Add link, table and image for text editor panel

ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/event/event-table-config.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Fixed calculated fields translation

ui-ngx/src/app/shared/models/tenant.model.ts
=> Updated default value maxDebugModeDurationMinutes in tenant profile

ui-ngx/src/app/shared/import-export/import-dialog.component.html
=> Fixed import file dialog when long file name

common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
=> Fix repo open catch

ui-ngx/src/app/core/auth/auth.models.ts, ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts, ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts, ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html, ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.ts, ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings.model.ts, ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html, ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Fixed debug settings panel; Improved model data entity debug setting panel

ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts
=> Fixed bug in delete enabled calculation in JS library

common/edqs/src/main/java/org/thingsboard/server/edqs/repo/DefaultEdqsRepository.java, edqs/src/test/java/org/thingsboard/server/edqs/repo/AbstractEDQTest.java
=> Fix EDQS tests init

ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html, ui-ngx/src/app/modules/home/components/rule-node/action/math-function-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/common/arguments-map-config.component.html, ui-ngx/src/assets/help/en_US/math/math-methods_fn.md
Added show help on math funcs in Calculated field simple expression and math node
=> Added show help on math funcs in Calculated field simple expression

application/src/main/resources/thingsboard.yml, common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/CompressedStringDataPoint.java, common/edqs/src/main/java/org/thingsboard/server/edqs/stats/DefaultEdqsStatsService.java, common/edqs/src/main/java/org/thingsboard/server/edqs/util/EdqsConverter.java, edqs/src/main/resources/edqs.yml
=> EDQS: configurable string compression threshold; fix stats service condition

ui-ngx/src/app/shared/components/popover.component.ts
Fixed show help not showing occasionally on first interaction
When `showHelpMarkdownComponent` is called async from `component.tbComponentChange.subscribe` it can not rerender and not change opacity 1 to opacity 0 which causes no show help showing on click.
We make sure that it is updated by calling `detectChanges` on async call of `showHelpMarkdownComponent`
=> Fixed show popover some time not showing occasionally on first interaction

application/src/main/java/org/thingsboard/server/controller/AuthController.java, application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java, ui-ngx/src/app/core/auth/auth.service.ts, ui-ngx/src/app/modules/login/pages/login/reset-password.component.ts
resetPassword in AuthController now returns nothing instead of token pair, just updates password. Button 'reset password' in reset password form now redirects to login page
[Jira](https://thingsboard-portal.atlassian.net/browse/PROD-1571)
=> Now, when you reset password, you redirected to login page

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/customer/CustomerEdgeProcessor.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbEdgeConsumerService.java, application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java, application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java, application/src/test/java/org/thingsboard/server/edge/TenantProfileEdgeTest.java, common/dao-api/src/main/java/org/thingsboard/server/dao/customer/CustomerService.java, dao/src/main/java/org/thingsboard/server/dao/customer/CustomerServiceImpl.java
This update addresses the issue of unnecessary public customer creation during edge connections when synchronizing entities to the edges. 
Especially, in the Professional Edition, a public customer was created for every customer and their subcustomers. 
This PR introduces a mechanism to prevent the creation of these redundant public customers during edge connection.
=> Avoid Creation of Unnecessary Public Customers During Edge Connection

application/src/main/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtils.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java, application/src/main/java/org/thingsboard/server/service/ttl/KafkaEdgeTopicsCleanUpService.java, application/src/main/resources/thingsboard.yml, common/queue/src/main/java/org/thingsboard/server/queue/discovery/TopicService.java, common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java, common/queue/src/main/java/org/thingsboard/server/queue/provider/TbCoreQueueProducerProvider.java
* Rate Limiting with **max.poll.records** Configuration:
Added the max.poll.records configuration to the edge queues. This change aims to efficiently rate limit the processing of edge events, helping to better manage system resources and optimize performance.
* Log Management Enhancement:
Implemented a fix to silence a specific edge error message that was causing log flooding. This adjustment ensures more readable and manageable log files, making it easier for developers to monitor and debug the system.
=> Enhance Edge Queue Processing with Rate Limiting and Logging Improvements

common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
=> Fix getEntityDataInfo

application/src/main/resources/thingsboard.yml, application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java, dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
=> Updated gateway image version to stable

docker/monitoring/grafana/provisioning/dashboards/core_js_tbel_metrics.json
Update Grafana dashboard title to include TBEL metrics
=> update dashboard title to include TBEL metrics

ui-ngx/src/app/modules/home/models/widget-component.models.ts, ui-ngx/src/app/shared/models/widget.models.ts
Added logic to not overwrite widget "externalId" property on save widget.
**Before**
Before edit:
After save:
**After**
Before edit:
After save:
=> Fix overwrite of externalId on save widget

ui-ngx/src/app/modules/common/modules-map.ts
=> Add Echart in modules map

ui-ngx/src/app/modules/home/pages/admin/resource/js-resource.component.html, ui-ngx/src/app/shared/components/js-func.component.scss, ui-ngx/src/assets/help/en_US/resource/js-resource-module_fn.md
Changes in JavaScript library (Module type):
1. Remove redundant space after "Module script" and before symbol *;
2. Change the width of help popover window. 
**Before**
**After**
=> JavaScript library style enhancement

ui-ngx/src/app/modules/home/components/widget/config/timewindow-config-panel.component.html
=> Added timezone selection in widget settings timewindow

ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.scss, ui-ngx/src/app/shared/components/markdown.component.scss
**Before:**
_Chrome_
_Firefox_
**After:**
_Chrome_
_Firefox_
=> Improved CSS styles for copy-code button in markdown

application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
=> Fix DefaultTbCoreConsumerServiceTest

ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.scss
=> Fixed visability actions table header in preview mode for widget settings

ui-ngx/src/app/modules/common/modules-map.ts
=> Remove echart from module map

common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/EntityFields.java, dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
Added validation for entity name filter
=> Added validation for entity name filter

application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java, common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/AbstractQueryProcessor.java
Fixed CustomerData permission checks
=> Fixed Customer permission checks

application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
This PR addresses the bug identified by #13153 in the `DeviceConnectivityControllerTest` class, where the `coapProfile` is mistakenly configured with an MQTT Transport configuration.
=> Coap Profile Test

ui-ngx/src/app/modules/home/models/entity/entity-details-page-component.models.ts, ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts, ui-ngx/src/app/modules/home/pages/admin/resource/js-resource.component.html, ui-ngx/src/app/modules/home/pages/admin/resource/js-resource.component.ts
=> Fixed empty delete dialog in javascript library panel

ui-ngx/src/app/shared/components/popover.component.ts
Some time when user have slow network not show help popover
**Before:**
**After:**
=> Fixed show help popover

ui-ngx/src/assets/help/en_US/widget/lib/map/shape_fill_image_fn.md
=> Add example in shape fill image how to use attribute

ui-ngx/src/assets/help/en_US/widget/lib/map/clustering_color_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/map/color_fn_examples.md, ui-ngx/src/assets/help/en_US/widget/lib/map/label_fn_examples.md, ui-ngx/src/assets/help/en_US/widget/lib/map/marker_image_fn.md, ui-ngx/src/assets/help/en_US/widget/lib/map/tooltip_fn_examples.md
=> Updated map help

application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java, common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeService.java, dao/src/main/java/org/thingsboard/server/dao/edge/EdgeDao.java, dao/src/main/java/org/thingsboard/server/dao/edge/EdgeServiceImpl.java, dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeRepository.java, dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaEdgeDao.java
=> Edge - slow down processing of edge events for SYS_TENANT_ID

application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
=> BaseEdgeProcessor - Fixed incorrect return

application/src/main/resources/thingsboard.yml
=> Updated properties to exclude tags

ui-ngx/src/app/shared/models/dynamic-form.models.ts
=> Fix saving issue for dynamic form array items of type 'fieldset'

ui-ngx/src/app/core/utils.ts
fixed #13193 
Replace `instanceof Date` and `instanceof Array` with `Object.prototype.toString.call(target) === "[object Date]"` and `Array.isArray(target)` respectively to ensure reliable type checking across different global contexts, where `instanceof` fails due to distinct constructors.
=> Fix type checking for Date and Array in iframes

application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
default notification center log debug level
because too much logs
```
tb-1        | 2025-04-17 08:09:53,437 [NotificationExecutorService-0-11] INFO  o.t.s.s.n.DefaultNotificationCenter - [9c9f83d0-1b62-11f0-acfc-fd098044504e][579ffb60-1b63-11f0-a792-3fa8aff642b5] Notification request processing finished in 5 ms (sent: 1)
tb-1        | 2025-04-17 08:09:53,438 [NotificationExecutorService-0-7] INFO  o.t.s.s.n.DefaultNotificationCenter - [9c9f83d0-1b62-11f0-acfc-fd098044504e][579fad41-1b63-11f0-a792-3fa8aff642b5] Notification request processing finished in 6 ms (sent: 1)
tb-1        | 2025-04-17 08:09:53,439 [NotificationExecutorService-0-12] INFO  o.t.s.s.n.DefaultNotificationCenter - [9c9f83d0-1b62-11f0-acfc-fd098044504e][57a02270-1b63-11f0-a792-3fa8aff642b5] Notification request …
```
=> default notification center log debug level

application/src/main/java/org/thingsboard/server/controller/CalculatedFieldController.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/BaseCalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldCtx.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/CalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/ScriptCalculatedFieldState.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/SimpleCalculatedFieldState.java, application/src/test/java/org/thingsboard/server/cf/CalculatedFieldIntegrationTest.java, common/data/src/main/java/org/thingsboard/server/common/data/cf/configuration/SimpleCalculatedFieldConfiguration.java, common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbelCfCtx.java, ui-ngx/src/assets/help/en_US/calculated-field/expression_fn.md
=> Added ability to preserve last update ts for calculated value

ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html, ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts, ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
In Device profile lwm2m transport configuration added Observe strategy select field.
=> Device profile lwm2m transport added Observe strategy selector

common/dao-api/src/main/java/org/thingsboard/server/dao/job/JobService.java, dao/src/main/java/org/thingsboard/server/dao/job/DefaultJobService.java, dao/src/main/java/org/thingsboard/server/dao/job/JobDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/job/JobRepository.java, dao/src/main/java/org/thingsboard/server/dao/sql/job/JpaJobDao.java
=> Added findByKey method to job service

ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/rpc/persistent-table.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Fixed an issue when the user could break the pagination settings validation by switching between the basic/advanced mode tabs in table-widgets
=> Fixed an issue with broken pagination settings validation in table-widgets

ui-ngx/src/app/shared/models/constants.ts
=> Fixed incorrect help links for calculated fields

application/src/main/java/org/thingsboard/server/service/entitiy/ota/DefaultTbOtaPackageService.java, application/src/test/java/org/thingsboard/server/controller/OtaPackageControllerTest.java
* fixed 'value too long' after saving ota
* fixed tests
=> fixed 'value too long' after saving ota (#13277)

application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java, common/data/src/main/java/org/thingsboard/server/common/data/relation/EntityRelation.java, dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java, dao/src/test/java/org/thingsboard/server/dao/service/RuleChainServiceTest.java
=> Automatic relations creation between Rule Chains when adding "Rule Chain" node

application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/main/java/org/thingsboard/server/controller/CalculatedFieldController.java, application/src/main/java/org/thingsboard/server/service/security/permission/Resource.java, application/src/main/java/org/thingsboard/server/service/security/permission/TenantAdminPermissions.java
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/3512
=> Removed resource Calculated Field

common/script/script-api/src/main/java/org/thingsboard/script/api/AbstractScriptInvokeService.java, common/script/script-api/src/main/java/org/thingsboard/script/api/js/AbstractJsInvokeService.java, common/script/script-api/src/main/java/org/thingsboard/script/api/js/JsValidator.java, common/script/script-api/src/test/java/org/thingsboard/script/api/AbstractScriptInvokeServiceTest.java, common/script/script-api/src/test/java/org/thingsboard/script/api/js/AbstractJsInvokeServiceTest.java, common/script/script-api/src/test/java/org/thingsboard/script/api/js/JsValidatorTest.java
invalidate async js scripts
validating in two steps
1. regex (quick check)
2. JavaScript syntax wise (//Recheck if quick check failed. Ignoring comments and strings)
downside:
isExecEnabled and scriptBodySizeExceeded performed twice per eval. But it relatively cheap.
key messages to a user:
```
"Script must not contain 'async' keyword."
"Script must not contain 'await' keyword."
"Script must not use 'Promise'."
"Script must not use 'setTimeout' method."
```
=> invalidate async js scripts

ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
1. Added ignore loading and errors
2. Added error handling when loading the dashboard.
Before:
After:
=> Improved dashboard autocomplete  component

ui-ngx/src/app/modules/home/components/widget/lib/chart/pie-chart.ts
The wrong value is due to 'fake' series data;
Before fix:
After fix:
=> Fixed percent value for doughnut chart

ui-ngx/src/app/modules/home/components/rule-node/action/gps-geo-action-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/action/math-function-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/action/save-to-custom-table-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/common/arguments-map-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/common/device-relations-query-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/common/message-types-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/common/select-attributes.component.html, ui-ngx/src/app/modules/home/components/rule-node/enrichment/entity-details-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/external/lambda-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/filter/check-message-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/filter/originator-type-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/transformation/copy-keys-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/transformation/deduplication-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/transformation/delete-keys-config.component.html, ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.html, ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.scss, ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
Add missing general rule node config style
Before:
After:
=> Fixed rule node config style

application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java, application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponseHandler.java, application/src/main/java/org/thingsboard/server/service/security/auth/AuthExceptionHandler.java, common/data/src/main/java/org/thingsboard/server/common/data/exception/ThingsboardErrorCode.java
=> Handle uncaught auth exceptions

ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
=> Remove sticky option for argument table header row in calculate field dialog

ui-ngx/src/app/modules/home/components/event/event-table-config.ts, ui-ngx/src/app/modules/home/components/event/event-table.component.ts
=> Event table hide clear event button as input

ui-ngx/src/app/modules/home/components/rule-node/action/gps-geo-action-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/action/save-to-custom-table-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/action/timeseries-config.component.html
=> Fixed help icon color in rule node

monitoring/src/main/java/org/thingsboard/monitoring/ThingsboardMonitoringApplication.java, monitoring/src/main/java/org/thingsboard/monitoring/client/TbClient.java, monitoring/src/main/java/org/thingsboard/monitoring/client/WsClient.java, monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportInfo.java, monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportMonitoringTarget.java, monitoring/src/main/java/org/thingsboard/monitoring/data/MonitoredServiceKey.java, monitoring/src/main/java/org/thingsboard/monitoring/data/ServiceFailureException.java, monitoring/src/main/java/org/thingsboard/monitoring/data/cmd/EntityDataUpdate.java, monitoring/src/main/java/org/thingsboard/monitoring/service/BaseHealthChecker.java, monitoring/src/main/java/org/thingsboard/monitoring/service/BaseMonitoringService.java, monitoring/src/main/java/org/thingsboard/monitoring/service/MonitoringEntityService.java, monitoring/src/main/java/org/thingsboard/monitoring/service/MonitoringReporter.java, monitoring/src/main/java/org/thingsboard/monitoring/service/transport/TransportHealthChecker.java, monitoring/src/main/java/org/thingsboard/monitoring/util/ResourceUtils.java, monitoring/src/main/resources/rule_chain.json, monitoring/src/main/resources/tb-monitoring.yml, rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
=> Calculated fields monitoring

application/src/main/data/json/system/widget_bundles/high_performance_scada_energy_system.json
=> Fixed HP curcuit breaker widget type fqn

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbMsgDeduplicationNodeTest.java
Issue:
In the Deduplication rule node, you can configure the Max Retries parameter in the Advanced Settings section.
If you set Max Retries to 0, the rule node will not produce a message with the relation type Success.
Tests:
=> deduplication node: fixed retry mechanism

rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeConfiguration.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNode.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeConfiguration.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/AbstractRuleNodeUpgradeTest.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeTest.java, ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.ts, ui-ngx/src/app/modules/home/components/rule-node/external/mqtt-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/external/mqtt-config.component.ts, ui-ngx/src/app/shared/components/mqtt-version-select.component.html, ui-ngx/src/app/shared/components/mqtt-version-select.component.ts, ui-ngx/src/app/shared/models/device.models.ts, ui-ngx/src/app/shared/models/mqtt.models.ts, ui-ngx/src/app/shared/shared.module.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
MQTT, Azure IoT rule nodes - add ability to set mqtt version "Protocol version":
=> Add MQTT version selection for rule nodes

application/src/main/resources/thingsboard.yml, transport/coap/src/main/resources/tb-coap-transport.yml, transport/http/src/main/resources/tb-http-transport.yml, transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml, transport/mqtt/src/main/resources/tb-mqtt-transport.yml, transport/snmp/src/main/resources/tb-snmp-transport.yml
This PR adds comment reference with Valkey in service configuration YML files, so there is an understanding that it could be deployed instead of Redis
see  https://github.com/thingsboard/thingsboard.github.io/pull/2015
=> Add Valkey reference in .yml  files

common/data/src/main/java/org/thingsboard/server/common/data/trendz/TrendzSettings.java
=> Add Serializable to TrendzSettings

application/src/test/java/org/thingsboard/server/controller/TrendzControllerTest.java, common/data/src/main/java/org/thingsboard/server/common/data/trendz/TrendzSettings.java, ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.html, ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.scss, ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.ts, ui-ngx/src/app/shared/models/trendz-settings.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
Adding a new field "apiKey" to Trendz Settings.
=> Trendz settings api key

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- Refactored init method to use @AfterStartUp with REGULAR_SERVICE order
=> Changed EdgeGrpcService startup

dao/src/test/java/org/thingsboard/server/dao/AbstractNoSqlContainer.java, docker/docker-compose.hybrid.yml
=> Cassandra 5.0 support

application/src/main/java/org/thingsboard/server/service/ws/telemetry/sub/TelemetrySubscriptionUpdate.java, msa/black-box-tests/src/test/java/org/thingsboard/server/msa/WsClient.java
=> Add JsonIgnore to TelemetrySubscriptionUpdate.getValues

common/edqs/src/main/java/org/thingsboard/server/edqs/repo/TenantRepo.java
Fixed customer creation for NULL customer id
PE: https://github.com/thingsboard/thingsboard-pe/pull/3552
=> [EDQS] Fixed customer creation for NULL customer id

common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/AbstractEntityFields.java
=> Fix EntityFields customerId

application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/AbstractOAuth2ClientMapper.java, common/dao-api/src/main/java/org/thingsboard/server/dao/tenant/TenantService.java, dao/src/main/java/org/thingsboard/server/dao/sql/tenant/JpaTenantDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/tenant/TenantRepository.java, dao/src/main/java/org/thingsboard/server/dao/tenant/TenantDao.java, dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
=> Fix tenant id resolving in OAuth2 mapper

dao/src/main/java/org/thingsboard/server/dao/sql/tenant/JpaTenantDao.java, dao/src/main/java/org/thingsboard/server/dao/sql/tenant/TenantRepository.java
=> Fix findTenantByName as tenant tile is not unique

application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
=> Fix compile error

dao/src/main/resources/sql/schema-entities-idx-psql-addon.sql
remove FILLFACTOR 95. As default 90 is fine for most applications
=> remove FILLFACTOR 95. As default 90 is fine for most applications

application/src/main/java/org/thingsboard/server/controller/BaseController.java, application/src/main/java/org/thingsboard/server/controller/JobController.java, application/src/main/java/org/thingsboard/server/service/cf/ctx/state/KafkaCalculatedFieldStateService.java, application/src/main/java/org/thingsboard/server/service/job/DummyJobProcessor.java, application/src/main/java/org/thingsboard/server/service/job/task/DummyTaskProcessor.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCalculatedFieldConsumerService.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java, application/src/main/java/org/thingsboard/server/service/queue/DefaultTbEdgeConsumerService.java, application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManager.java, application/src/main/java/org/thingsboard/server/service/security/permission/Resource.java, application/src/main/java/org/thingsboard/server/service/security/permission/TenantAdminPermissions.java, application/src/test/java/org/thingsboard/server/service/job/JobManagerTest.java, application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineStrategyTest.java, common/data/src/main/java/org/thingsboard/server/common/data/job/DummyJobConfiguration.java, common/data/src/main/java/org/thingsboard/server/common/data/job/task/DummyTask.java, common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java, common/queue/src/main/java/org/thingsboard/server/queue/common/PartitionedQueueResponseTemplate.java, common/queue/src/main/java/org/thingsboard/server/queue/common/consumer/MainQueueConsumerManager.java, common/queue/src/main/java/org/thingsboard/server/queue/task/TaskProcessor.java
=> Task manager improvements

common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/AbstractEntityFields.java
=> EDQS: fix null uuid customer id after sync

ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.html, ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-tooltip.models.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Hide zero tooltip for time series charts

application/src/main/data/json/system/widget_types/knob_control.json, ui-ngx/src/app/modules/home/components/widget/lib/rpc/knob.component.html, ui-ngx/src/app/modules/home/components/widget/lib/rpc/knob.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/settings/control/knob-control-widget-settings.component.html, ui-ngx/src/app/modules/home/components/widget/lib/settings/control/knob-control-widget-settings.component.ts, ui-ngx/src/app/shared/models/widget/rpc/knob.component.models.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Improved knob control widgets

ui-ngx/src/app/modules/home/components/relation/relation-dialog.component.html, ui-ngx/src/app/modules/home/components/relation/relation-dialog.component.ts, ui-ngx/src/app/shared/components/entity/entity-list-select.component.html, ui-ngx/src/app/shared/components/entity/entity-list-select.component.ts
=> Add allow created/view relation to rule chain

application/src/main/data/json/system/scada_symbols/horizontal-connector-hp.svg, application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg, application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg, application/src/main/data/json/system/scada_symbols/vertical-connector-hp.svg
=> Fixed SCADA connectors arrow color

ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts, ui-ngx/src/styles.scss
=> Fixed full screen mode in editors

application/src/main/java/org/thingsboard/server/service/cf/ctx/state/SingleValueArgumentEntry.java
Fixed error when json passed as argument 
=> Calculated fields: fixed JSON argument handling

common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java, dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
=> Add backward compatibility for RateLimitsNotificationInfo

common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java, common/edqs/src/main/java/org/thingsboard/server/edqs/util/VersionsStore.java
EDQS - VersionStore - Use local map instead of caffeine to reduce memory heap size.
=> Edqs - VersionStore - Use local cache instead of caffeine to reduce memory heap size

common/data/src/main/java/org/thingsboard/server/common/data/edqs/EdqsState.java
=> Fix EdqsState.isApiReady

ui-ngx/src/scss/animations.scss
=> Fixed details panel button freeze midway in firefox

ui-ngx/src/app/modules/home/components/dashboard-page/edit-widget.component.scss
=> Fixed visible elements behind widget preview

ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-instances.component.scss, ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-resources.component.html
=> Fixed lwm2m device profile object configuration checkbox alignment

ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Fixed edit Advanced button style due to Edit Action.
=> Fixed advanced button style on edit action

ui-ngx/src/app/core/http/ota-package.service.ts, ui-ngx/src/assets/locale/locale.constant-en_US.json
=> Added "Confirm OTA Update" title to the OTA update confirmation dialog

ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-tooltip.models.ts
=> Fixed tooltip with string false and empty tooltip

application/src/main/java/org/thingsboard/server/controller/BaseController.java
=> Handle ExecutionException in controllers

ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
Before fix:
After fix:
Manually enter any numeric value into the input field associated with the slider.
=> Fixed dynamicly update slider on input value change for Rule notification dialog

ui-ngx/src/app/core/services/dashboard-utils.service.ts, ui-ngx/src/app/core/services/item-buffer.service.ts, ui-ngx/src/app/modules/home/components/alias/entity-aliases-dialog.component.ts, ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.ts, ui-ngx/src/app/shared/models/widget/maps/map-model.definition.ts, ui-ngx/src/app/shared/models/widget/widget-model.definition.ts
=>  Prevent deleting an (entity alias/filter) that’s still used in map widgets

application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/ResourceImportService.java
Fixed NPE when load resource version
=> Fixed NPE when load resource version

ui-ngx/src/assets/help/en_US/rulenode/switch_node_script_fn.md, ui-ngx/src/assets/help/en_US/rulenode/tbel/switch_node_script_fn.md
Documentation has been updated and now it does not show the use of this node.
=> Removed links to the doc in switch node

ui-ngx/src/app/shared/models/time/time.models.ts
Before:
Changing interval and applying changes in edit mode leads to error
After:
No error occurs
=> Fixed updating timewindow configuration

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
=> EdgeGrpcService - destroy if previous session exists

common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/AbstractEntityProfileNameQueryProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/AbstractEntityProfileQueryProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/EntityNameQueryProcessor.java, common/edqs/src/main/java/org/thingsboard/server/edqs/util/RepositoryUtils.java, edqs/src/test/java/org/thingsboard/server/edqs/repo/RepositoryUtilsTest.java
This PR introduces SQL-like filtering capabilities to EDQS by adding support for the following filter operations:
* contains
* not contains
* startsWith
* endsWith
=> EDQS - added SQL like style for filter contains/starts with/ends with

ui-ngx/src/app/modules/home/components/rule-node/common/credentials-config.component.html
=> Credentials expansion paned expanded by default

application/src/test/java/org/thingsboard/server/service/job/JobManagerTest.java
=> Fix testCancelJob_whileRunning

common/actor/src/main/java/org/thingsboard/server/actors/TbActorMailbox.java, common/data/src/main/java/org/thingsboard/server/common/data/AdminSettings.java, common/data/src/main/java/org/thingsboard/server/common/data/BaseData.java, common/data/src/main/java/org/thingsboard/server/common/data/Dashboard.java, common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleNode.java, common/data/src/main/java/org/thingsboard/server/common/data/settings/UserSettings.java, common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetType.java, common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/KeystoreSslCredentials.java, common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/PemSslCredentials.java
1. Actor mailbox not properly cleaned up after destroy (on init failed or stop):
In one of the dumps, there are 155MB of dangling mailbox messages:
2. Rule node `configurationBytes` duplicates the JsonNode `configuration` field, resulting in doubling the needed memory size: 
Got rid of configurationBytes, as JsonNode already supports Serializable.
This should clean up ~750MB:
=> Memory usage improvements

application/src/test/java/org/thingsboard/server/service/job/JobManagerTest.java, application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
=> Fix some flaky tests

ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.ts, ui-ngx/src/app/shared/components/mqtt-version-select.component.ts
=> Exclude mqtt version select in azure rule node

application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java, common/cache/src/main/java/org/thingsboard/server/cache/resourceInfo/ResourceInfoCacheKey.java, dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
=> Fix showing outdated system resource info on tenant level

common/cluster-api/src/main/java/org/thingsboard/server/queue/TbQueueHandler.java, common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java, common/queue/src/main/java/org/thingsboard/server/queue/common/PartitionedQueueResponseTemplate.java
=> EDQS: handle Kafka response sending error

ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
=> Fixed detect changes for entities and alarm tables

ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.html, ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.ts
Fix for widgetTitlePanel templateOutlet: From 4.0, widgetTitlePanel didn't support adding templates from the widget library, as it did until 3.9.
Before: 
After:
=> Fix for widgetTitlePanel templateOutlet

application/src/main/java/org/thingsboard/server/controller/TelemetryController.java, application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java, application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java, common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java, common/proto/src/test/java/org/thingsboard/server/common/adaptor/JsonConverterTest.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/DeviceState.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbCalculatedFieldsNode.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
=> Fixed no type-cast for attributes when adding from UI

common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/DefaultTransportRateLimitService.java
=> Fixed consuming wrong rate limit for devices connected via gateway

application/src/main/data/upgrade/basic/schema_update.sql
=> Fix upgrade

netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
manual test with trace enabled is ok
```
<logger name="org.thingsboard.mqtt.MqttClientImpl" level="TRACE" />
```
=> Reduced log severity to debug for Scheduling reconnect message to avoid log flood under high-load. Logs are made more informative.

common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java, netty-mqtt/src/main/java/org/thingsboard/mqtt/ChannelClosedException.java, netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientCallback.java, netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientConfig.java, netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java, netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttConnectResult.java, netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttSubscription.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
=> MQTT: validate client id length based on protocol version

application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java, common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java, common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java, pom.xml
https://thingsboard-portal.atlassian.net/browse/PROD-6532
Introduced `ExecutionLinkedHashSet`, a specialized list implementation for TBEL runtime execution context.
- `add`
- `addAll`
- `remove`
- `clear`
- `sort`
- `toSorted`
- `toList`
This utility simplifies list operations within TBEL expressions by providing a consistent and fluent API.
=> tbel_add_ExecutionLinkedHashSet

application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDataReceivedFromClientTest.java
=> Add missing license header

ui-ngx/src/assets/locale/locale.constant-en_US.json
- Rename 'App ID' into 'App Site Association ID'.
=> Enhancement Mobile center Applications form label

ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.ts
- Fix for cases when user can not duplicate a dashboard state after the name of state duplicate was changed.
=> Fix rewrite of dashboard duplicate state with same id

application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_preparing.md, docker/docker-compose.cassandra.volumes.yml, docker/docker-compose.confluent.yml, docker/docker-compose.edqs.volumes.yml, docker/docker-compose.edqs.yml, docker/docker-compose.hybrid.yml, docker/docker-compose.kafka.yml, docker/docker-compose.postgres.volumes.yml, docker/docker-compose.postgres.yml, docker/docker-compose.prometheus-grafana.yml, docker/docker-compose.valkey-cluster.volumes.yml, docker/docker-compose.valkey-cluster.yml, docker/docker-compose.valkey-sentinel.volumes.yml, docker/docker-compose.valkey-sentinel.yml, docker/docker-compose.valkey.volumes.yml, docker/docker-compose.valkey.yml, docker/docker-compose.volumes.yml, docker/docker-compose.yml, msa/black-box-tests/src/test/resources/docker-compose.hybrid-test-extras.yml, msa/black-box-tests/src/test/resources/docker-compose.mosquitto.yml, msa/black-box-tests/src/test/resources/docker-compose.postgres-test-extras.yml, msa/black-box-tests/src/test/resources/docker-compose.rabbitmq-server.yml, msa/black-box-tests/src/test/resources/docker-compose.valkey-ssl.volumes.yml, msa/black-box-tests/src/test/resources/docker-compose.valkey-ssl.yml
Removed `version` property from all docker-compose to remove the following warning
```
the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
=> removed version property from docker-compose

ui-ngx/src/app/modules/home/models/datasource/entity-datasource.ts
In the EntitiesDataSource class, multiple calls to loadEntities do not cancel previous ongoing requests. This can lead to race conditions where a stalled earlier request completes after a newer one, overwriting the results and causing incorrect data in the result observable.
Before:
After:
=> Fix race condition in EntitiesDataSource loadEntities by cancelling previous requests

netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
=> Fixed MQTT client disconnect

application/src/main/java/org/thingsboard/server/service/telemetry/DefaultAlarmSubscriptionService.java, common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java, dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java, dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java, dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java, rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineAlarmService.java, rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java, rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCreateAlarmNodeTest.java
=> Create alarm node: process message asynchronously to avoid blocking dispatcher thread

application/pom.xml, application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java, common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/SslCredentialsWebServerCustomizer.java, dao/src/main/java/org/thingsboard/server/dao/model/BaseSqlEntity.java, dao/src/main/java/org/thingsboard/server/dao/sql/IdGenerator.java, dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java, pom.xml, rule-engine/rule-engine-components/pom.xml
- Fixed all critical and high vulnerabilities (fixable), reduced the amount of medium 
- Refactored and improved dependency management
=> Fixed vulnerabilites and updated libraries

ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
=> Fix error message in Alarm widget preview when opening Assign field dropdown

ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
The Calculated fields argument settings window jumps when switching argument types (e.g., from "Attribute" to "Latest telemetry") under various screen resolutions, such as 1680x1050 and 1920x1080, as reported in the ticket.
=> Stabilize calculated field argument settings popover position on argument type change

common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/StringDataPoint.java, edqs/src/test/java/org/thingsboard/server/edqs/repo/EntityTypeFilterTest.java
Fixed EDQS entity field filter for numeric values saved in str_v
PE: https://github.com/thingsboard/thingsboard-pe/pull/3707/files
=> Fixed EDQS entity field filter for numeric values saved as string

application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultSlackService.java, common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/slack/SlackFile.java, rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/notification/SlackService.java
=> Fix Slack files upload support

ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.ts
=> Fix overwrite of dashboard state duplicates when changing name

ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts, ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.html, ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.scss, ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.ts
=> Refactoring dashboard managment

application/src/main/java/org/thingsboard/server/service/query/DefaultEntityQueryService.java
Fixed default sort property for alarm entity query
=> Fixed default sort property for alarm entity query

application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultFirebaseService.java
=> Fix NPE on Firebase app cleanup

ui-ngx/src/app/modules/home/components/ai-model/ai-model-dialog.component.ts, ui-ngx/src/app/modules/home/components/rule-node/external/ai-config.component.html, ui-ngx/src/app/modules/home/components/rule-node/external/ai-config.component.ts, ui-ngx/src/app/modules/home/pages/ai-model/ai-model-table-header.component.ts
Add deep trim on create AI model.
Fixed disabling response format type and json editor in AI request rule node.
Fixed trancate table tatle AI models.
=> Minor fixes for Ai models

msa/black-box-tests/src/test/java/org/thingsboard/server/msa/cf/CalculatedFieldTest.java, msa/black-box-tests/src/test/resources/connectivity.xml
=> Fix some MSA tests not running

ui-ngx/src/assets/locale/locale.constant-da_DK.json
=> Fixed tranlate format in da_DK

ui-ngx/src/assets/help/en_US/rulenode/ai_node_prompt_settings.md
=> AI request node: add predictive maintenance example

ui-ngx/src/app/modules/home/components/widget/lib/maps/data-layer/data-layer-utils.ts
Fixed an issue where the tooltip in the map widget was closing when the mouse moved from the map overlay to the tooltip. Now the tooltip remains open while hovering over it.
=> Map widget tooltip no longer closes when hovering from overlay to tooltip

application/src/main/java/org/thingsboard/server/controller/ImageController.java
Added Content-Security-Policy header to /public image api to prevent malicious code injection
=> Malicious code injection into the SVG image vulnerability

common/data/src/main/java/org/thingsboard/server/common/data/mobile/bundle/MobileAppBundle.java, common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRule.java, common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRuleConfig.java, common/data/src/main/java/org/thingsboard/server/common/data/notification/template/DeliveryMethodNotificationTemplate.java, ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.ts
Added NoXss validations to notification dtos.
=> NoXss validation enhancements

application/src/main/java/org/thingsboard/server/service/query/DefaultEntityQueryService.java, application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
Fixed /api/alarmsQuery/find api to retrieve entity latest values
=> Fixed missing values in exported alarm data widget

ui-ngx/src/app/shared/models/widget/maps/map-model.definition.ts, ui-ngx/src/app/shared/models/widget/maps/map.models.ts
=> Fixed lat/long keys duplication in additional keys list in map widget settings

ui-ngx/src/app/modules/home/components/vc/complex-version-create.component.html, ui-ngx/src/app/modules/home/components/vc/complex-version-load.component.html, ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html, ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.ts, ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html, ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html, ui-ngx/src/app/modules/home/components/vc/entity-version-restore.component.html, ui-ngx/src/app/modules/home/components/vc/remove-other-entities-confirm.component.html, ui-ngx/src/app/shared/components/vc/branch-autocomplete.component.html, ui-ngx/src/app/shared/components/vc/branch-autocomplete.component.ts
Update Version control components: use Angular 19 template syntax, set outline appearance.
=> Version control: fixed multiple identical requests, update template style

ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
Fixed decimals displaying in Liquid level widget
=> Fixed decimals support in Liquid level widget

ui-ngx/src/app/core/interceptors/global-http-interceptor.ts, ui-ngx/src/app/core/utils.ts, ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts, ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
Fixed XSS vulnerabilities in the Rule node name and description
After save changes in node:
After trying to save changes in Rule Chain:
=> Fixed XSS vulnerabilities in the Rule node

ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
Send notification dialog: fix issue for Microsoft Teams  when users cannot navigate back if an error occurs.
=> Send notification dialog: fix navigation error for Teams 

application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java, application/src/test/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateServiceTest.java, common/message/src/main/java/org/thingsboard/server/common/msg/tools/SchedulerUtils.java
Fixed nextCycleTs calculation for api usages
=> Fixed API usage cycle reset

application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
Pick up bug fixes from master PR:
https://github.com/thingsboard/thingsboard/pull/13843
=> Improved Edge session cleanup to prevent resource leaks and message backlog due to unstable network conditions and Kafka busy timeout

ui-ngx/src/app/shared/import-export/import-export.service.ts
=> Add support UTF-8 symbols in export file name
