- docker/tb/run-application.sh
When running thingsboard with docker swarm port is reported as ```filtered``` rather than ```open```
> Added filtered state to cassandra service check.

- application/src/main/resources/thingsboard.yml
Fix times to match what is documented.  Both off by a factor of 10,000.  I'm guessing this was not intended.
> Fix intervals

- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/handlers/TelemetryRestMsgHandler.java
This prevents an endless loop that can hang up the server, and is probably what the user intuitively wanted.
> If user specifies an interval of 0, convert aggregation to NONE

- application/pom.xml
- application/src/main/java/org/thingsboard/server/service/security/model/token/JwtTokenFactory.java
- pom.xml
From Java SE 8 onwards Joda-Time can be replaced by _java.time_ (JSR-310).
> Removal of Joda-Time library.

- ui/src/app/extension/extensions-forms/extension-form-modbus.directive.js
- ui/src/app/extension/extensions-forms/extension-form-modbus.tpl.html
The transport configuration may include extra fields after switching from one type to another.
Fixed by resetting transport model on each switch.
> Modbus GUI configuration fix

- transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionCtx.java
The server do not send a PUBLIC ACK when receiving a PUBLIC message on v1/gateway/rpc.
> BUGFIX: fixed the server do not send a PUBLIC ACK on v1/gateway/rpc

- transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionCtx.java
The device connect to the gateway will be auto created by the thingsboard. If a gateway is assigned to a customer, the auto created device should be auto assigned to the customer too.
> A device created by gateway should be auto assigned to the customer that the gateway is assigned to

- ui/src/app/widget/lib/CanvasDigitalGauge.js
- ui/src/app/widget/lib/canvas-digital-gauge.js
The bug was reproducing in a case when value updated faster than animation-duration time.
> fixed issues in updating digital-value with progress-bar-animation

- application/src/main/scripts/install/install_dev_db.sh
When following instructions on https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#create-database-schema-and-populate-demo-data, the install script doesn't work when the thingsboard user doens't have a password because su is used instead of sudo.
By using sudo instead of su you can execute the install script without a specified password for the thingsboard user.
> Fix install_dev_db.sh by using sudo instead of su

- application/src/main/java/org/thingsboard/server/actors/rpc/RpcManagerActor.java
When firing an RpcBroadcastMsg message or a ToAllNodesMsg from one node, the other nodes never get notified because the messages doesn't have a serverAddress.
As a result firing such a method is not forwarded to the other cluster nodes.
This PR adds the serverAddress for each node that the message is sent to so the other nodes get the message and can react to component lifecycle changes.
> RpcBroadcastMsg never arrives at other cluster nodes

- application/src/main/java/org/thingsboard/server/actors/ruleChain/RemoteToRuleChainTellNextMsg.java
The recently add RemoteToRuleChainTellNextMsg isn't Serializable. As a consequence sending this message over the wire fails. This PR fixes that.
```
java.lang.IllegalArgumentException: Failed to serialize object of type: class org.thingsboard.server.actors.ruleChain.RemoteToRuleChainTellNextMsg
at org.springframework.util.SerializationUtils.serialize(SerializationUtils.java:49) ~[spring-core-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
at org.thingsboard.server.service.encoding.ProtoWithJavaSerializationDecodingEncodingService.encode(ProtoWithJavaSerializationDecodingEncodingService.java:50) ~[classes!/:2.1.0-SNAPSHOT]
at org.thingsboard.server.service.encoding.ProtoWithJavaSerializationDecodingEncodingService.convertToProtoDataMessage(ProtoWithJavaSerializationDecodingEncodingService.java:64) …
```
> Make RemoteToRuleChainTellNextMsg Serializable

- application/src/main/java/org/thingsboard/server/actors/ruleChain/RemoteToRuleChainTellNextMsg.java
- application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeToRuleChainTellNextMsg.java
Sending RemoteToRuleChainTellNextMsg over the wire still fails because it's parent's class also must be Serializable.
This is a fixes what https://github.com/thingsboard/thingsboard/pull/949 should have fixed but dodn't entirely.
I noticed that value objects are by default not serializable. I don't know if this is by design, so I just let this one class implement Serializable and leave the others.
> RuleNodeToRuleChainTellNextMsg is not Serializable

- application/src/main/resources/thingsboard.yml
- common/data/src/main/java/org/thingsboard/server/common/data/CacheConstants.java
- dao/src/main/java/org/thingsboard/server/dao/asset/AssetService.java
- dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
- dao/src/test/resources/application-test.properties
Cache assets when finding them by tenant and name just like it's done when caching of devices.
For this the method signature of findAssetByTenantIdAndName was changed. It now returns an `Asset` or `null` instead of an `Option<Asset>`.
> Cache assets

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientConfig.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
The MqttClient cannot handle messages larger than 8KB because the MqttClientImpl uses the default constructor for MqttDecoder, which has a DEFAULT_MAX_BYTES_IN_MESSAGE of 8092.
Als by default the reconnect timer is set to 1 second, this should be configurable.
> ReconnectDelay and MaxBytesInMessage configurable

- application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
A break was missing in one of the cases of AppActor's switch statement. As a result the logfiles got an false warning message (Unknown message).
> Add missing break in switch statement of AppActor.

- application/src/main/java/org/thingsboard/server/service/cluster/discovery/ZkDiscoveryService.java
Hello @ashvayka,
In Release-2.0, tb application can't understand whether its' zNode is removed somehow while the tb server is still up and running. I found out some bugs while playing with cluster setup on kubernetes. I list down here some drawbacks of current implementation;
- Sometimes zookeeper can be unreachable for some very small time. (Mostly after zookeeper cluster restarts.) In these situations, tb application creates multiple ephemeral sequential zNodes for the current server without knowing there is already a record for itself.
- If you delete a zNode manually from zk for the tb server, it simply ignores it. Newly added tb applications wouldn't be aware of the deleted tb server. With this commit it is now able to understand its' zNode is removed and insert a new one. 
- If tb …
> Zookeeper reconnect error

- ui/package-lock.json
- ui/package.json
- ui/pom.xml
Updating npm version (in ui/pom.xml) to current version: [6.4.1](https://github.com/npm/cli/releases/tag/v6.4.1)
Since v5, npm generates [package-lock.json](https://docs.npmjs.com/files/package-lock.json). This file describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
The main benefit of including this file is that **provides a single representation of a dependency tree** such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
:warning: It includes https://github.com/thingsboard/thingsboard/pull/1271
> Updating npm version to create package-lock.json 

- ui/package.json
Correct mispelled **flot.curvedlines** (was flow-curvedlines) dependency on ui/package.json
Package name is [flot.curvedlines](https://github.com/MichaelZinsmaier/CurvedLines/blob/master/package.json#L2)  (with a dot)
Resolves https://github.com/thingsboard/thingsboard/issues/1248
Literally a single character MR :smile: 
Before this, when executing `npm run build`, it throws this error:
```
ERROR in ./src/app/widget/lib/flot-widget.js
/home/gmatheu/Documentos/ascentio/ascentio-tech/thingsboard/ui/src/app/widget/lib/flot-widget.js
26:8  error  Unable to resolve path to module 'flot.curvedlines/curvedLines'  import/no-unresolved
✖ 1 problem (1 error, 0 warnings)
ERROR in ./src/app/widget/lib/flot-widget.js
Module not found: Error: Cannot resolve module 'flot.curvedlines/curvedLines' in …
```
> issue-1248: Correct mispelled package.json dependecy (flot.curvedlines)

- dao/src/main/resources/sql/schema-entities.sql
- dao/src/main/resources/sql/schema-ts.sql
This pull request changes the unique indexes of the four tables without primary keys into primary keys.
Reason: Many database tools like Entity Framework Core require a primary key to be present for each table in order to generate a database context and all entities.
I have tested that the database is fully working by applying this script to an existing schema:
```
ALTER TABLE relation DROP CONSTRAINT relation_unq_key;
ALTER TABLE relation ADD CONSTRAINT relation_pkey PRIMARY KEY (from_id, from_type, relation_type_group, relation_type, to_id, to_type);
ALTER TABLE attribute_kv DROP CONSTRAINT attribute_kv_unq_key;
ALTER TABLE attribute_kv ADD CONSTRAINT attribute_kv_pkey PRIMARY KEY (entity_type, entity_id, attribute_type, attribute_key);
ALTER TABLE ts_kv DROP CONSTRAINT ts_kv_unq_key; …
```
> Fix sql missing primary keys

- ui/src/app/api/subscription.js
- ui/src/app/widget/lib/map-widget2.js
Added _dataReceived_ attribute to data source to indicate that data was received at least once.
Added _initBounds_ attribute to map widget which indicates ability remove auto focus and zoom on current map.
Added check/change condition for _initBounds_ attribute that depends on _dataReceived_ attribute value.
> Add ability to disable map updates after zoom-in PROD-60 task

- ui/src/app/components/contact.directive.js
Please review. Note the upper case change, if necessary lower case can be added back but generally upper case is used in Canadian postal codes.
> Add full Canadian postal code validation.

- k8s/postgres.yml
When creating postgres deployment on GKE Postgres complains about data folder being mounted directly on root of the PV claim.
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
initdb: directory "/var/lib/postgresql/data" exists but is not empty
It contains a lost+found directory, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```
A simple solution is to force Postgres to use a sub …
> Fix postgres deployment on GKE

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/JsonMqttAdaptor.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/MqttTransportAdaptor.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewayDeviceSessionCtx.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/adaptor/JsonConverter.java
On Gateway-mqtt-api the current Attributes Request response payload is missing `device` attribute. [Documentation](https://thingsboard.io/docs/reference/gateway-mqtt-api/#request-attribute-values-from-the-server) shows that it should be included.
Before this PR:
```
{"id":` $request_id, "value": "value1"}
```
After this PR:
```
{"id":` $request_id, "device": "Device A", "value": "value1"}
```
> Gateway-mqtt-api: deviceName added to attribute Attributes Request response message

- ui/src/app/widget/lib/flot-widget.js
Delete param "Axis title's angle" because it does not work on ThingsBoard and even not supported in the current version of float charts.
Fix displaying yAxis in charts, when option "Axis position" is set to "right" and the value of  "Axis step size between ticks" option is set up.  In that case, yAxis ignored option "Axis step size between ticks" but the autoscaling.
> Improvement float directory: fix autoScale and delete not support param

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/AbstractTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/SessionMetaData.java
Responding Issue #1686 
Adding scheduledFuture to Session Map to be able to cancel scheduler in case of successful response.
Adding registerSyncSession to the RPC_REQUEST case for CoAP to respond correctly on Server RPC Requests.
> #1686 no response to client side rpc via coap

- ui/src/app/components/datasource-entity.directive.js
- ui/src/app/components/datasource-entity.scss
- ui/src/app/components/datasource-entity.tpl.html
- ui/src/app/components/datasource-func.directive.js
- ui/src/app/components/datasource-func.tpl.html
- ui/src/app/components/md-chip-draggable.directive.js
- ui/src/app/widget/index.js
Widget entity dataKeys may be created for timeseries and attibutes keys selecting keys in arbitrary way (no more restriction due to timeseries keys before attributes keys).
Data key type (timeseries or attributes) is now showed with icon and tooltip on detaKeys selector and dataKey chips.
Moreover it's possible to change the datKeys order by drag-and-drop dataKey chips on UI for both entity dataKeys and function dataKeys
> widget entity datakeys flexible creation order with reordering option

- ui/src/app/components/widget/widget.controller.js
- ui/src/app/dashboard/states/entity-state-controller.js
Using ${entityName} in dashboard state name allows entity name resolution using resolveEntity() function. 
This is done using the following object:
```
{
entityId: {
id: "767b5ca0-878f-11e9-bc60-e900a1e32051", 
entityType: "ASSET"}
entityName: "Current name"
}
```
However, if a state entity parameter name (i.e. "parameterName") is defined when opening a new dashboard state, the previous object is modified as:
```
{
parameterName: {
entityId: {
id: "767b5ca0-878f-11e9-bc60-e900a1e32051", 
entityType: "ASSET"}
entityName: "Current name"
}
}
```
In this way, resolveEntity() cannot access entityName key anymore, and ${entityName} results undefined.
This fix add a further key (**targetEntityParamName**) to point out a state entity parameter name is used, so entityName can be still resolved. …
> Fix ${entityName} resolution when using a state entity parameter name

- ui/src/app/api/subscription.js
Widgets HTML template has a 'md-circular-progress' element that remains active until its subscription returns a list of resolved entities. However, it this list is empty, no one disables the progress indicator, which runs to infinity. This fix invokes the 'notifyDataLoaded' callback even if there are no resolved entities, without however reconfiguring widget data.
> Fix 'md-circular-progress' with no resolved entities

- ui/src/app/api/time.service.js
- ui/src/app/components/dashboard.tpl.html
- ui/src/app/components/timeinterval.directive.js
- ui/src/app/components/timeinterval.tpl.html
- ui/src/app/components/timewindow-panel.controller.js
- ui/src/app/components/timewindow-panel.tpl.html
- ui/src/app/components/timewindow.directive.js
- ui/src/app/components/widget/widget-config.tpl.html
- ui/src/app/dashboard/dashboard.tpl.html
- ui/src/app/locale/locale.constant-en_US.json
- ui/src/app/locale/locale.constant-es_ES.json
- ui/src/app/locale/locale.constant-fr_FR.json
- ui/src/app/locale/locale.constant-it_IT.json
In edit mode, dashboard or widget timewindow fields can be hidden. In this way, users could be prevented from changing some timewindow parameters, i.e. aggregation type, while changing interval period.
> Add the possibility to hide single timewindow fields

- ui/src/app/locale/locale.constant-de_DE.json
> Fixed spelling of german word Standard

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbClearAlarmNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbAlarmNodeTest.java
There is a bug now when cleatTs and endTs in debug event data in Clear Alarm node is 0. This PR fixes it
> Fix Clear Alarm Node clearTs and endTs in log message

- ui/src/app/components/dashboard.directive.js
Widgets order breaks down after dashboard state updated in mobile view.
> UI:fix. Dashboard (widgets order mobile view)

- application/src/main/java/org/thingsboard/server/config/ThingsboardMessageConfiguration.java
SpringResourceLoader needs to be public for **java -jar thingsboard-<VERSION>-boot.jar** to work.
> Set SpringResourceLoader to public

- ui/src/app/api/alarm.service.js
Issue: https://github.com/thingsboard/thingsboard/issues/1261
The delete alarm api wasn't added to the alarm.service.js.
Can be used in alarm widget like this:
```
var $injector = widgetContext.$scope.$injector;
var alarmService = $injector.get('alarmService');
alarmService.deleteAlarm(additionalParams.alarm.id.id);
```
> added delete alarm api to alarm ui service

- ui/src/app/api/time.service.js
This resolves the issue described in https://github.com/thingsboard/thingsboard/issues/2268
> Fix timewindow parameters when zooming flot widget chart

- ui/src/app/widget/lib/flot-widget.js
Actually, bars in 'flot-widget' have timestamp left aligned with respect to the column, causing a wrong display of the column (in some cases it overlaps with the next time point). By centering the column on the timestamp the problem would disappear: to do this, it is necessary to select 'center' as bar alignment. 
This feature adds, in addition to the default value 'left', also 'center' and 'right'.
> Add option to set bar alignment in 'flot-bar-widget'

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportServerInitializer.java
When **certificate authentication** is turned on, **under high concurrency**, if a large number of real devices are frequently reconnected, they may be connected to other devices on the platform, which will eventually lead to confusion in device data upload.
> fix bug:Device reconnect abnormal when certificate authentication is turned on

- ui/src/app/components/react/json-form-ace-editor.jsx
- ui/src/app/components/react/json-form-schema-form.jsx
- ui/src/app/components/react/json-form.scss
On this case: bug occurred when using widget that using grouped react schema forms, when clicking 'fullscreen' button on the input field for JavaScript code, all the groups were given a ' SchemaFormFullscreen' instead of targeted one;
> fixed: focus on fullscreen for react schema grouped forms

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
The compareAndSet method and getAndIncrement method of the AtomicInteger class are atomic, but when these two methods are used at the same time, they are no longer atomic.
> fix bug: Under high concurrency, Mqtt client nextMessageId exceeds the 0xffff limit

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
#2500 
MQTT clients don't send PINGREQ messages if they've recently sent [UN]SUBSCRIBE/PUBLISH messages.  The MQTT server last activity timestamp is currently only updated in response to PINGREQ messages.  This causes the server to disconnect any clients that regularly send PUBLISH messages since they don't send PINGREQ. 
This change adds reportActivity calls in response to PUBLISH, SUBSCRIBE and UNSUBSCRIBE in addition to PINGREQ.
> Fix MQTT inactivity disconnects

- netty-mqtt/src/main/java/org/thingsboard/mqtt/RetransmissionHandler.java
In the mqtt 3.1 protocol or mqtt 3.1.1 protocol, except for messages of type pubish, the isDup of other messages must be zero，Sending a subscription message multiple times causes the client to reconnect，therefore, resending the subscription message with isDup true will cause the server to think that the message is abnormal, thus interrupting the connection with the client
> fix bug: Resending the message causes the client to interrupt

- k8s/.env
- k8s/common/cassandra.yml
In 3.0.0 Cassandra datacenter is hardcoded in AbstractCassandraCluster.initSession() method.
This is just a quick fix to make scripts work.
Also changed default DEPLOYMENT_TYPE to 'basic'.
> Set correct cassandra datacenter

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTransportQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryTbTransportQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbTransportQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTransportQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTransportQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTransportQueueFactory.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportContext.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportService.java
- common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
- common/transport/http/src/main/java/org/thingsboard/server/transport/http/HttpTransportContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportContext.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
For example in cluster mode, when there are 'transport' services and there's no need to have that functionality on 'tb-node's
> Added property to disable 'transport' features for 'monolith' service type

- dao/src/main/java/org/thingsboard/server/dao/timeseries/AbstractCassandraBaseTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesLatestDao.java
This changes are required to fix NullPointerException in PE _CassandraBaseTimeseriesDao_ class and line (when _rs.one()_ returns _null_) :
_return getFuture(executeAsyncRead(tenantId, stmt), rs -> convertResultToTsKvEntry(rs.one()));_
> Moved convertResultToTsKvEntry to base class and updated it

- application/src/main/resources/thingsboard.yml
- common/dao-api/src/main/java/org/thingsboard/server/dao/cassandra/CassandraDriverOptions.java
- dao/src/test/resources/cassandra-test.properties
Inspired by the recommendations in [this issue](https://github.com/thingsboard/thingsboard/issues/3420#issue-692135699), added mechanisms to provide all DataStax DefautlSslEngineFactory properties through thingsboard.yml.
Tests passed with Cassandra SSL disabled, enabled with server-only authentication and enabled with two-way authentication. I also confirmed it works in my usual ThingsBoard dev setup, with two-way Cassandra SSL to a remote server.
> Add full DataStax Java Driver SSL configs

- application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/rule/RuleChainService.java
- common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChainData.java
- common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChainImportResult.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
Created 2 REST endpoints for bulk rule chain import & export. 
All real Rule Chain ID's are substituted by the fake ones upon export. The new UUIDs are there to ensure consistency between rule chains in the export
The Import endpoint can either a) import rule chains as new rule chains or b) overwrite the existing rule chains by name.
this is triggered by ?overwrite=true request parameter.
if overwrite is set to false (by default) or no Rule Chain with such name already exist, then the Rule chain will be given a new ID and saved to the system.
if overwrite is set to true and there is a matching rule chain found, the existing Rule Chain will be updated and ID will be preserved.
If any of the imported Rule Nodes contain Tenant ID in Rule Node configuration, it will be replaced with the …
> Rule chain bulk import export

- ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts
some gauge widgets didn't update their value, setting "animatedValue" to "true" resolves the problem
> set lib attribute "animatedValue" to "true" in analogue-gauge.models.ts

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
```console
$ mosquitto_sub -d -h "10.136.32.204" -p 8883 -t "v1/devices/me/attributes" --cafile ca.crt --cert client_expired.crt --key client_expired.key --insecure
Client mosq-pCzcQrhlQN6Rh9xsCr sending CONNECT
Client mosq-pCzcQrhlQN6Rh9xsCr received CONNACK (5)
Connection error: Connection Refused: not authorised.
Client mosq-pCzcQrhlQN6Rh9xsCr sending DISCONNECT
```
```console
$ mosquitto_sub -d -h "10.136.32.204" -p 8883 -t "v1/devices/me/attributes" --cafile ca.crt --cert client.crt --key client.key --insecure
Client mosq-XEDB16vr32xYB681l5 sending CONNECT
Client mosq-XEDB16vr32xYB681l5 received CONNACK (0)
Client mosq-XEDB16vr32xYB681l5 sending SUBSCRIBE (Mid: 1, Topic: v1/devices/me/attributes, QoS: 0, Options: 0x00)
Client mosq-XEDB16vr32xYB681l5 received SUBACK
Subscribed (mid: …
```
> add validity on device X.509 certificate over MQTT transport connection

- application/src/main/java/org/thingsboard/server/service/device/DeviceProvisionServiceImpl.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceProvisionService.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
Added validation for device name in provision request, if it is present. Added session closing when provision client tries to use topics not allowed for provisioning feature
> Added validation for provision request

- ui-ngx/src/app/modules/home/components/import-export/import-export.models.ts
Prevents converting '0080000004027000' to 80000004027000 when importing
> [3.2.1]Prevent unnecessarily converting strings to numbers when importing

- ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget.component.ts
- ui-ngx/src/app/shared/models/widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added a new setting "Open in a new browser tab" in the widget action "Navigate to other dashboard"
> [3.2.1] UI: Added a new settings "Open in a new browser tab" in the widget action

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/ProfileState.java
entityKeys are not cleared currently on device profile update. So imagine the scenario:
1. you and an attribute to the device profie, say 'my_attr'
2. the device does not have that attribute
3. you realize that and remove 'my_attr' from the device profile config
4. 'my_attr' is still present in entityKeys map, however, it is not visible to user, and the device_profile node will fail with NPE because of not finding the 'my_attr' attribute
5. 'my_attr' will only be removed from entity_keys upon server restart.
The fix is to clear and re-initialize entityKeys on profile update
> Fix update device profile

- ui-ngx/src/app/shared/components/file-input.component.ts
Currently, when there are multiple file inputs on the page attempt of file selection in the second triggers file selection in the first one.
> Make file input work properly when there are multiple on page

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
If you select a time interval that does not have any data, the system returns all the telemetry saved in the database of the selected entity and the page load is extremely slow
> Do not load all data if it is not in the current time interval

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
**The case:**
When profile of a device is changed, the event is pushed to specific partition that is responsible for this device and thus the device profile cache on this core service instance will be updated, unlike other core instances' caches. If we create new alarm it will go correctly to the new rule chain, but when we then clear this alarm from UI the request may go to the core instance with outdated device profile cache, and therefore the clear alarm event will be pushed to the wrong rule chain that is assigned to the old device profile, and сonsequently when a new alarm comes it will be processed by the new rule chain where there is no clear alarm event and so the alarm will no be created but updated.
> [3.2.2] [PROD-851] Fix invalid alarm clearing behaviour in the cluster mode

- application/src/main/java/org/thingsboard/server/controller/RpcController.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/adaptor/JsonConverter.java
fix needed for Protobuf, cause in the protobuf adaptors we sending directly TransportProtos.ToDeviceRpcRequestMsg bytes.
> added a fix for string value RPC params: removed redundant escaped characters

- dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
'buildStringPredicateQuery' method used to return null if the search value was empty (because of one fix for version 3.3). For this reason a NullPointerException could occur when building predicate query (line 490).
> Refactor predicate queries building

- ui-ngx/src/app/modules/home/pages/asset/assets-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/dashboard/dashboards-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/device/devices-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/edge/edge.component.html
- ui-ngx/src/app/modules/home/pages/edge/edges-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/entity-view/entity-views-table-config.resolver.ts
Changes:
1) Assets, Devices, EntityViews, Dashboards table-config resolver: 'edge_customer_user' - enable detailsReadonly; disable addEnabled.
2) edge.component: Manage assigned entities buttons: hide for 'customer' scope; minor refactoring.
3) edges-table-config: fixed translation reference.
> UI: Fixed: entity tables config for edge_customer_user; edge component; translation

- application/src/main/resources/thingsboard.yml
- dao/src/main/java/org/thingsboard/server/dao/sqlts/insert/latest/psql/PsqlLatestInsertTsRepository.java
There is a bug when the historic data arrives and overrides the value
with morerecent timestamp in ts_kv_latest table. This PR adds
possibility to update the ts_kv_latest table only if the value that
arrives has the newer timestamp than the one that is already in
ts_kv_latest
> Update Latest TS by timestamp

- common/queue/src/main/java/org/thingsboard/server/queue/common/AbstractTbQueueConsumerTemplate.java
Not going to sleep after pull if time left less than 1 millisecond. topic added to logs
The problem identified in the logs.
The motivation of this fix is to prevent consumers from asleep for a duration of less than 1ms.
> queue consumer 1ms sleep fix

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/secure/TbLwM2MDtlsCertificateVerifier.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/adaptor/JsonConverter.java
- common/transport/transport-api/src/test/java/JsonConverterTest.java
If the value can't fit into Long or Double, we should send String
> JsonConverter improvements (correct value conversion)

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Empty string received, when threshold attribute isn't set, was treated as zero, and the threshold was displayed.
> UI: Flot widget, fix thresholds appearing when threshold attribute is not set

- ui-ngx/src/app/core/api/entity-data-subscription.ts
This affects timeseries widgets with paginated data (particularly route map and trip animation).
On the very first _processEntityData_ function call for timeseries widget with paginated data _dataAggregators_ already exist, which causes duplicate _onData_ function call: first time taking into account data aggregator, and second time without it. The second call, in this case, is redundant, also it returns data in reverse order relative to the first function call.
Currently, this may cause a blinking effect on route map initialization: at the very first moment marker could be placed at the start point of the route, after a second it will be at its correct position at the route end.
> UI: Entity data subscription: remove duplicate call of onData function

- ui-ngx/src/app/modules/home/components/widget/lib/canvas-digital-gauge.ts
Unit titles of digital gauges are automatically changed to uppercase.
That is an issue when the unit is a greek letter. e.g. for the measure of a conductivity, the unit is µS/cm.
Capitalizing it makes it MS/CM, which does not have the same meaning. Additionally, I don't understand the benefit of capitalizing this by default.
This PR proposal removes the ".toUpperCase()" on the unit title labels.
> fix: do not "uppercase" unit title of digital gauges

- common/actor/src/test/java/org/thingsboard/server/actors/ActorSystemTest.java
- common/actor/src/test/java/org/thingsboard/server/actors/SlowCreateActor.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerTemplate.java
This fixes the situation when many short requests polled rapidly and **async commit** the consumed offset is **racing** on Kafka single thread client with the poll.
In the previous version, this issue did not appear because after each pool thread falls asleep to gain the pooling interval (unwanted latency). This version with no latency on the consumer, so we have to commit the offset before getting new messages. While we committing new messages to accumulate in the topic and will be pulled as a batch at the next moment after commit offset.
Low latency is very important for js-executors, for example within the long-chain js-script-based rule chain.
This reduces Kafka's load.
Below you can find an example logs from the real issue:
```
{"log":"2021-05-26 10:05:37,899 …
```
> kafka commit sync

- application/src/main/resources/thingsboard.yml
- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/cache/CacheExecutorService.java
- dao/src/test/java/org/thingsboard/server/dao/attributes/CachedAttributesServiceTest.java
This fix will unlock the sql-attributes thread (that writes with batches).
After the batch written successfully callback fired the cache evict (I/O) in the same thread. And Each rule node that awaits a callback will wait while remote cache will be evicted in a single thread one by one.
For the local cache (caffeine only), directExecutor still in place, because no I/O appeared on the local cache
Threads before (the solid green line is bad):
Fixed behavior (much wider timeline), thread mostly idle - good.
P.S. I found that cache service was refactored significantly. I'm not sure where is the correct package for the new CacheExecutorService. Please, fill free to change the class location.
> Cache attribute service performance improvement

- ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
According to the ECMAScript standard, the function name can't start with a number.
> UI: Fixed generate invalid name function in widgetTypeFunctionBody

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/TbTopicWithConsumerPerPartition.java
- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/TbQueueConsumer.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/AbstractTbQueueConsumerTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryTbQueueConsumer.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/settings/TbRuleEngineQueueConfiguration.java
This is major feature that enable to process each partition in separate thread with a separate queue consumer. Actual implementation process all partitions as a single batch.
This feature required to scale up horizontally (increase) for the highly loaded rule chains that experiences a latency (like I/O calls, multiple chained JS calls). In that scenario, the greatest latency for a single message will cause the entire batch to await. 
Another application is a pulling big messages from queue that exceeds maximum batch size. 
The example is 6 nodes and a high-load topic with 30 partitions. Each node will spin up 5 (30/6) threads and 5 independent consumers.
In case of scale up or down the nodes will spin up a new threads or stop unused threads. So, do not scale down your nodes too much …
> rule engine thread per topic partition

- pom.xml
Kafka java client  2.8.0    Released April 19, 2021 
Working fine on production with the previous version of Kafka broker 2.7
No breaking changes.
Run and drive.
Author @volodymyr-babak
> Upgrade kafka client version to 2.8.0

- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/DeviceProfileMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/WidgetsBundleMsgConstructor.java
- common/edge-api/src/main/proto/edge.proto
1. Added image field to edge device profile proto to send it to edge
2. Added description filed to edge widget bundle proto to send it to edge
> [3.3.0] Edge - add missing fields to device profile and widget bundle protos

- common/dao-api/src/main/java/org/thingsboard/server/dao/device/claim/ClaimData.java
when use redis as the cache, this interface
http(s)://host:port/api/v1/$ACCESS_TOKEN/claim  throw 
a
SerializationFailedException but ignored by AbstractTransformFuture
,and when do  Device Claiming API
Request(http(s)://host:port/api/customer/device/$DEVICE_NAME/claim),the
system show :Failed to claim the device
show like this
> [3.3.0] Fixed Failed to claim the device when use redis as cache

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/TbMsgPushToCloudNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNode.java
tbActionNodePushToCloudConfig and tbActionNodePushToEdgeConfig directives already merged and are available in the rulenode-core-config.js file
> [3.3.0] minor update for push to edge/cloud nodes: use attribute scope from node configuration instead metadata

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
At the moment if you use timeseries as storage for the device state, updating in the real time of inactivityTimeout will not trigger any updates to device state service.
Added listener to timeseries update and push event to device state service.
> [3.3.0] Update inactivity timeout for device state in case timeseries used for device states

- ui-ngx/src/app/modules/home/components/dashboard-page/states/state-controller.component.ts
When calling encodeURIComponent for value null return string.
Function navigate add query params state in value null, but not clear this parameter.
> [3.3.0] UI: Fixed update state: not clear state params

- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
> Include the limit value in the getTimeseries REST call.

- dao/src/main/java/org/thingsboard/server/dao/sqlts/AbstractChunkedAggregationTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/timescale/TimescaleTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/TimeseriesDao.java
- dao/src/test/java/org/thingsboard/server/dao/nosql/CassandraPartitionsCacheTest.java
DO NOT apply custom to partition, otherwise, short TTL will remove partition too early
partitions must remain in the DB forever or be removed only by systemTtl
removal of empty partition is too expensive (we need to scan all data keys for these partitions with ALLOW FILTERING)
> [3.3.0] Partitions should not be removed by custom TTL

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/main/java/org/thingsboard/server/service/state/DeviceStateService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
Added additional check that device belongs to the current node before adding to states map. 
Added clean up in case device doesn't belong to this node anymore
> [3.3.0] Fixes for device state service in cluster mode to avoid 'dead' device monitoring on incorrect nodes

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
mqtt transport close channel on processing exception for handleGatewayPublishMsg method
> [3.3.0] mqtt transport close channel on processing exception for handleGatewayPublishMsg method

- application/pom.xml
- common/transport/mqtt/pom.xml
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
- common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandlerTest.java
- pom.xml
Gateway session handler improvements:
weakmap for device lock, refactored getDeviceCreationFuture with putIfAbsent, refactored SettableFuture usage, test with awaitility.
**close channel** if processPostTelemetryMsg exception (Failed to convert telemetry)
> [3.3.0] Gateway session handler improvements

- application/pom.xml
- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/NoSecLwM2MIntegrationTest.java
- pom.xml
Lwm2m test fix with Awaitility (detailed example with logs and javadoc to demonstrate the flow and benefits of async testing)
* This is the example how to use the AWAITILITY instead Thread.sleep()
* Test will finish as fast as possible, but will await until TIMEOUT if a build machine is busy or slow
* Check the detailed log output to learn how Awaitility polling the API and when exactly expected result appears
Screenshot and logs you can find below:
```
2021-07-30 21:28:59,877 [main] WARN  o.t.s.t.l.NoSecLwM2MIntegrationTest - Saving by API Device [tenantId=015b0ce0-f164-11eb-b53b-09ae3f425f9a, customerId=13814000-1dd2-11b2-8080-808080808080, name=Device A, type=LwM2M, label=null, deviceProfileId=01fb1d70-f164-11eb-b53b-09ae3f425f9a, deviceData=null, …
```
> [3.3.0] Lwm2m test fix with Awaitility (detailed example with logs and javadoc to demonstrate the flow and benefits of async testing)

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rpc/TbSendRPCRequestNode.java
enqueueForTellFailure needed to prevent the case when someone catches a Failure message and continue processing the logic (e.g. send failed message to remote service using rest api). If the rest api fails, the message will not be reprocessed without enqueueForTellFailure.
> [3.3.1] enqueue newly created messages

- pom.xml
Spring security has issue in 5.4.1: Changing SecurityContext More Than Once in Single Request Can Fail to Save.
Look here: https://tanzu.vmware.com/security/cve-2021-22112.
> Fix spring security issue

- application/src/main/resources/thingsboard.yml
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/DeviceSessionCtx.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewayDeviceSessionCtx.java
- common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/MqttTransportHandlerTest.java
- common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/SnmpTransportContext.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/session/DeviceAwareSessionContext.java
- pom.xml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
Its a continue of https://github.com/thingsboard/thingsboard/pull/5001
During the testing, I found that netty dependency has many versions and unit tests get Implementation from version 66. but Interface from 45. This cause 
```
SLF4J: Failed toString() invocation on an object of type [io.netty.handler.codec.mqtt.MqttPublishMessage]
java.lang.NoSuchMethodError: 'io.netty.buffer.ByteBuf io.netty.buffer.ByteBufUtil.ensureAccessible(io.netty.buffer.ByteBuf)'
```
To test perfectly, we need to add a blackbox test for:
* grpc integration
* azure-servicebus https://github.com/azure/azurite
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=docker-hub
> [3.3.1] Mqtt transport handler test with cleanup old netty versions

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Added parameters for Kafka producer
The motivation is to provide a flexible Kafka producer config in Kubernetes with env vars.
Here an example of the Kafka producer latency issue under the high load (JMX, Kafka MBean, VisualVM tool):
So increasing/decreasing max.inflight.requests are really useful to play with limits in such kind of issue.
But use it carefully as well!
The most convenient way to reduce the actual max.inflight.requests is to increase linger.ms (up to 5 ms). This will help the producer to accumulate much bigger matches and reduce tiny requests to the Kafka broker.
`TB_KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: "10"`
`TB_KAFKA_LINGER_MS: "5"`
Kafka other properties example added:
```
queue:
kafka:
other: # In this section you can specify custom parameters for Kafka …
```
> [WIP][3.3.0] Kafka max in flight requests per connection,  max.request.size

- common/cache/pom.xml
- common/cache/src/main/java/org/thingsboard/server/cache/CaffeineCacheConfiguration.java
- common/cache/src/main/java/org/thingsboard/server/cache/TBRedisCacheConfiguration.java
- common/cache/src/test/java/org/thingsboard/server/cache/CaffeineCacheConfigurationTest.java
- common/cache/src/test/resources/logback.xml
This fixes the rule chain read/write functions. During the save rule chain in Transaction code hits some Cachable methods in relationService. And sometimes read data from the cache instead of the database. Also, the cache was outdated during the transaction and can point to non persisted data yet. This helps to reduce transaction duration and overall performance as well.
This issue was discovered during fixing the test that was failed about 5 of 100 test runs (new PR upcoming soon)
'application/src/test/java/org/thingsboard/server/rules/flow/AbstractRuleEngineFlowIntegrationTest.java'
> [3.3.0] cache: Transaction aware cache to synchronize cache put/evict operations with ongoing Spring-managed transactions.

- ui-ngx/src/app/shared/components/time/timewindow-panel.component.scss
Made timewindow panel max values slider thumbnail bigger, so numbers value fits in now
> [3.3.1] UI: changed slider thumbnail size

- ui-ngx/src/app/core/services/menu.service.ts
In SysAdmin HomePage, "resources-library" page can't be redirected
> Fix: resources-library page can't be redirected

- application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainActorMessageProcessor.java
The issue was the Main queue was blocked (infinite repeat strategy) due to message tried to tellNext by relations [Success] ,
but rule node already deleted and get relations was already instead some collection. this fires NullPointerException.
The only workaround is to delete and import the rulechain (rule chain id performs mush earlier than this issue appears)
The message that cause error:
`2021-09-01 14:58:01,312 [rule-dispatcher-1-1] DEBUG o.t.server.actors.TbActorMailbox - [RULE_CHAIN|81c3ebc0-2362-11eb-9d7b-05919825a1a8] Going to process message: QueueToRuleEngineMsg(tenantId=4360dc00-849b-11ea-b908-fb276498eb8c, relationTypes=[Success], failureMessage=)`
`2021-09-01 14:58:01,312 [rule-dispatcher-1-1] TRACE o.t.s.a.r.RuleChainActorMessageProcessor - …
> Rule chain actor message processor on tell next NullPointerException fix

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.ts
1) Saving required input field by Enter keypress if 'Show action buttons' disabled.
Fix: change ngIf on button block  to fxShow(for correct work Enter event)
2) Sending double requests by Enter keypress if 'Show action buttons' disabled.
Fix: add variable isSavingInProgress and write logic for correct submitting form if 'Show action buttons' disabled.
> [3.2.2] Fixed multiple input widget sending double requests and saving required input by Enter keypress

- ui-ngx/src/app/modules/home/components/profile/alarm/alarm-duration-predicate-value.component.ts
Edit alarm rule condition (icon - pencil) or view alarm rule condition, press button "(X)" Switch to dynamic value - not displayed the checkbox "Inherit from owner"
Fix:
> [3.3.2] Fix checkbox Inherit from owner Device Profile Alarm Rules

- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
- ui-ngx/src/app/shared/models/edge.models.ts
- show entity.body for POST_ATTRIBUTES, ATTRIBUTES_UPDATED, ATTRIBUTES_DELETED, TIMESERIES_UPDATED;
- update status pending/deployed color without refresh page;
- for RELATION type show empty 'entityId';
> [3.3.2] UI: Edge Downlinks table minor fixes

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/RpcDownlinkRequestCallbackProxy.java
When an actor received RPC status DELIVERED or FAILED we will send the next RPC but when we received the status FAILED after DELIVERED it will second sending the same RPC which was sent after status DELIVERED.
> [3.3.2]fixed double sending rpc and timeout for lwm2m

- common/data/src/main/java/org/thingsboard/server/common/data/DeviceProfile.java
serialVersionUID is set as it was before the f47de8cfa60220c12f1eef357f132b0e1a8173af commit (latest change to DeviceProfile class)
> Set serialVersionUID for DeviceProfile class

- ui-ngx/src/app/modules/home/components/profile/device/coap-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/shared/components/protobuf-content.component.html
- ui-ngx/src/app/shared/components/protobuf-content.component.scss
- ui-ngx/src/app/shared/components/protobuf-content.component.ts
- ui-ngx/src/app/shared/models/ace/ace.models.ts
- ui-ngx/src/app/shared/shared.module.ts
UI changes in Device profiles -> Transport configuration -> Transport type: MQTT/CoAP.
- Added component ProtobufComponent in Shared module;
- Load 4 new modules in loadAceDependencies():
1. 'ace-builds/src-noconflict/mode-c_cpp'
2. 'ace-builds/src-noconflict/mode-protobuf'
3. 'ace-builds/src-noconflict/snippets/c_cpp'
4. 'ace-builds/src-noconflict/snippets/protobuf'
> [3.3.2] UI: Added ace editor for protobuf content

- application/src/main/java/org/thingsboard/server/service/queue/processing/TbRuleEngineProcessingStrategyFactory.java
Fixing the issue for the unnecessary consumer waiting for messages reprocessing when no messages are needed to be reprocessed.
Example of the current logic:
processing-strategy.type = RETRY_TIMED_OUT
10 messages are sent for processing in a pack. Result: 9 successful, 1 is failed.
if (retryFailed) { // false
result.getFailedMap().forEach(toReprocess::put);
}
if (retryTimeout) { // true
result.getPendingMap().forEach(toReprocess::put);  -> will not add anthing to the map since there are 0 timedOut messages
}
then
return new TbRuleEngineProcessingDecision(false, toReprocess); // empty map
So, no messages will be sent for the processing, but the consumer will wait approximately:
X retries * pack-processing-timeout + X retries * pause-between-retries (plus max-pause-between-retries could be …
> [3.3.2] Fixed analyze reprocessing decision in TbRuleEngineProcessingStrategyFactory

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateRelationNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCreateRelationNodeTest.java
Improved create relation rule node logic related to the "Remove current relations" (hint on the UI - Removes current relations from the originator of the incoming message based on direction and type.) checkbox.
Currently, if it is selected, it is removing the relations only if the new one that should be created from the originator to the target configured entity is not present yet. That could cause many discrepancies in the hierarchy of the relationships and this logic does not reflect what should be and how the hint is described. This causes confusion.
Improved to delete the current relations if selected in any case and refactored the code. Added tests.
> [3.3.2] Create relation rule node fix and tests

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttPendingPublish.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttPendingSubscription.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttPendingUnsubscription.java
If sending future was failed - we didn't remove a message from pending map and processed it again.
> Fix for mqtt duplication sending on sent failed

- application/src/main/java/org/thingsboard/server/actors/stats/StatsActor.java
- application/src/main/java/org/thingsboard/server/actors/stats/StatsPersistMsg.java
- application/src/test/java/org/thingsboard/server/actors/stats/StatsActorTest.java
- application/src/test/java/org/thingsboard/server/actors/stats/StatsPersistMsgTest.java
We found that about 9 million from total 11 million events are about empty stats;
```
delete from event 
where body like '%,"messagesProcessed":0,"errorsOccurred":0}%'
```
At this moment there are no parameters available to write or not zero values.
I found no motivation to add an optional parameter to bloat the event table, but if it is necessary for some users, just let me know.
> Stats: do not persist empty stats (reducing event table size and disk IOPS)

- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.ts
1. Fixed bug with missing the required credential-config when new device-profile(with LwM2m transport) was created via "Device wizard dialog"
2. Fixed bug with UI updating of bootstrap-config for LwM2M device-profiles when the user is switching between two profile table-rows with opened "Details" side-panel.
> [3.3.3] UI: Bugs fixing for LwM2M transport

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/firmware/FirmwareUpdateState.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/software/SoftwareUpdateResult.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/software/SoftwareUpdateState.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
fix bug:
- if in profile: objectId=5 and ojbjectId =3 with resourceId="State", info to device - always 
> Failed to process firmware update: LwM2MClientFwOtaInfo(super=LwM2MClientOtaInfo(endpoint=867723030209919, baseUrl=null, targetName=null, targetVersion=null, targetTag=null, targetUrl=null, strategy=OBJ_5_BINARY, updateState=IDLE, result=null, status=null, failedPackageId=null, retryAttempts=0, currentName=null, currentVersion3=null, currentVersion=null), deliveryMethod=null). Previous update failed.
> [3.3.3] lwm2m - info about previous update Ota

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
Added ordering for initializing Leshan server, and LwM2M clients. 
Leshan server should initialize after fetching LwM2M clients.
If Leshan server will start first and device (which was connected before restart transport and client was saved to the Redis) send data before fetching LwM2M clients will be created a new session. When will fetch LwM2M clients, sessions will be updated again.
> [3.3.3] fixed sessions updating on lwm2m transport start

- pom.xml
This is the improvement to bump log4j-api to 2.15 regarding https://github.com/advisories/GHSA-jfh8-c2jp-5v3q
Note that we don't use log4j-core. We use logback and slf4j instead.
That is why we are **NOT** affected by [CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228). See additional comments from [Spring](https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot) and [Slf4j](http://slf4j.org/log4shell.html).
> Explicitly upgrade log4j-api, log4j-core, log4j-to-slf4j  to 2.15 on dependency management. NOTE: log4j-core is not used!

- ui-ngx/src/app/modules/home/components/device/device-credentials.component.html
- ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
- ui-ngx/src/assets/locale/locale.constant-de_DE.json
- ui-ngx/src/assets/locale/locale.constant-el_GR.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-es_ES.json
- ui-ngx/src/assets/locale/locale.constant-fa_IR.json
- ui-ngx/src/assets/locale/locale.constant-fr_FR.json
- ui-ngx/src/assets/locale/locale.constant-it_IT.json
- ui-ngx/src/assets/locale/locale.constant-ja_JA.json
- ui-ngx/src/assets/locale/locale.constant-ka_GE.json
- ui-ngx/src/assets/locale/locale.constant-ko_KR.json
- ui-ngx/src/assets/locale/locale.constant-lv_LV.json
- ui-ngx/src/assets/locale/locale.constant-pt_BR.json
- ui-ngx/src/assets/locale/locale.constant-ro_RO.json
- ui-ngx/src/assets/locale/locale.constant-ru_RU.json
- ui-ngx/src/assets/locale/locale.constant-sl_SI.json
- ui-ngx/src/assets/locale/locale.constant-tr_TR.json
- ui-ngx/src/assets/locale/locale.constant-uk_UA.json
- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
- ui-ngx/src/assets/locale/locale.constant-zh_TW.json
From:
"rsa-key": "RSA public key",
"rsa-key-required": "RSA public key is required."
To:
"certificate-pem-format": "Certificate in PEM format",
"certificate-pem-format-required": "Certificate is required."
> [3.3.3] UI: Change translation rsa-key to certificate-pem-format and delete in other languages

- dao/src/main/java/org/thingsboard/server/dao/sql/relation/JpaRelationDao.java
Improving the fix for concurrent relation deletion to fix the bug shown below.
On the following screenshot, two messages has the same originator.
> [3.3.3] no class entity with id exists for relation fix

- pom.xml
Just to be sure (even if it is not used, better safe than sorry). 2.15 is flawed because of [CVE-2021-45046](https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45046).
> Upgrade log4j artifacts to 2.16

- application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- application/src/test/java/org/thingsboard/server/actors/ActorSystemContextTest.java
device actor -  do not dump/restore device session for local cache. 
CPU overhead reduces for the local cache.
Test added for Actor system context init, default values supplied to simplify testing.
> device actor -  do not dump/restore device session for local cache

- dao/src/main/java/org/thingsboard/server/dao/timeseries/NoSqlTsPartitionDate.java
Fixed NPE in case of incorrect partitioning name parameter 
(now you will see the normal log message with error)
> Fixed NPE in case of incorrect partitioning name parameter 

- dao/pom.xml
- dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityDataAdapter.java
- dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityDataAdapterTest.java
fixed EntityDataAdapter.convertValue that convert "500D" ("valid Java number") into "500.0" as double. 
For the String attribute "gatewayType", the text value "500D" was converted as 500.0 that confuses a user.
EntityDataAdapterTest added.
> [3.3.3] fixed EntityDataAdapter.convertValue that convert "500D" (valid Java number) into "500.0" as double

- common/data/src/main/java/org/thingsboard/server/common/data/kv/BaseReadTsKvQuery.java
When we compare two BaseReadTsKvQuery objects, which have all field equals, except key, startTs, and endTs. Without @EqualsAndHashCode(callSuper = true), these objects are equals, but it is incorrect because key, startTs, and endTs are different. But with this annotation result is correct
> [3.3.3] improve equals for BaseReadTsKvQuery

- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/timeseries/TimeseriesService.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineTelemetryService.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNodeConfiguration.java
This feature could be helpful for high-performance use cases when there is no need to frequently update the latest ts values.
It helps psql DB not to be overloaded. Verified on the real prod system.
> [3.3.3] Save timeseries without latest persistence

- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
device delete transactional and cache evict refactor
device deletion may potentially fire race conditions between cache evict and DAO call.
To maintain consistency, perform deleting the device in a transaction.
> [3.3.3] device delete transactional and cache evict refactor

- dao/src/main/java/org/thingsboard/server/dao/DaoUtil.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseOtaPackageServiceTest.java
Unsorted page link replaced with sort by id ASC.
This complies with SQL specs like [PostgreSQL](https://www.postgresql.org/docs/14/queries-order.html)
> If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on. A particular output ordering can only be guaranteed if the sort step is explicitly chosen.
> Unsorted page link replaced with sort by id ASC.

- application/src/main/java/org/thingsboard/server/service/ota/DefaultOtaPackageStateService.java
If fw/sw is not set and we are updating the device, we should not send deleting the fw/sw attributes
> [3.3.3] fixed removing fw/sw attributes if fw/sw is not set

- application/src/main/java/org/thingsboard/server/service/install/CassandraAbstractDatabaseSchemaService.java
We can't set up the CASSANDRA_KEYSPACE_NAME name during install. But we say we can do this in the documentation about installing TB.
More about this issue: https://github.com/thingsboard/thingsboard/issues/5603
> [3.3.3] CASSANDRA_KEYSPACE_NAME ignored during install

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/JsonMqttAdaptor.java
`Gson` class uses `JsonWriter` with HTML escaping enabled by default, that is causing the issue. When calling `JsonElement.toString` the default JsonWriter with disabled htmlSafe option is used
> [3.3.3] Fix invalid serialization of '=' to \u003d in JsonMqttAdaptor

- application/src/main/resources/logback.xml
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
MQTT: log.info replaced with log.debug for connect/disconnect events. It reduces log, CPU, disk overhead when a few thousand devices are in place. As an alternative to debugging MQTT - logback.xml has been adjusted.
Here is an example of log output before this fix:
> [3.3.3] reduce MQTT info logs for connect/disconnect events

- pom.xml
logback 1.2.10 released https://logback.qos.ch/news.html
In response to https://cve.report/CVE-2021-42550
Logback note:
> We note that the vulnerability mentioned in CVE-2021-42550 requires write access to logback's configuration file as a prerequisite. Please understand that log4Shell and CVE-2021-42550 are of different severity levels.
So no worry.
> [3.3.3] upgrade logback version

- application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
Do not update ws lastActivity in case of general response - only on pong response. 
Clean up properly subscription map in case canceling subsription
> [3.3.3] Do not update ws lastActivity in case of general response

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeConfiguration.java
Added a boolean param to be able to append suffix for "clientId" param in the MQTT rule node.
This is helpful for the cluster mode when the client wants to specify "clientId" (not to have a random id) and does not face the issue with the broker that does not allow client connections with the same clientId.
> [3.3.3] Mqtt rule node update

- ui-ngx/src/app/shared/components/dialog/color-picker-dialog.component.ts
- ui-ngx/src/app/shared/components/json-form/json-form.component.ts
Any widget (with color picker in advanced tab) - advanced tab - select color picker - if press the "Cancel" button so sets black color instead of the previous params.
> [3.3.3] UI: Fixed cancel event on color picker

- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogLevelFilter.java
The "i / I" characters lead problem in Turkish, toUpperCase method used with Locale.English in order to fix this problem. (Previous code generates "ENTİTY_VİEW" which is incorrect, it is possible to face similar problems in some languages too.)
> fix problematic letters for different lang

- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Disable column sort for that column where the post-processing function is enabled. Only for entities widget table and timeseries widget table.
> [3.3.3] UI: Disable column sort if enable post-processing function

- application/src/test/java/org/thingsboard/server/service/ServiceSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/service/sql/SequentialTimeseriesPersistenceTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNodeConfiguration.java
Add ignoreMetadataTs to ignore the timestamp that arrives from message metadata.
Useful for all sorts of sequential processing if you merge messages from multiple sources (devices, assets, etc).
For example, we generate ts for devices and save this to devices and common asset:
And we can see, we don't save to asset last ts: 
So ignoreMetadataTs fix this issue.
**Need add UI for rule node**
> [3.3.3] Add ignoreMetadataTs to TbMsgTimeseriesNode

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/WidgetTypeMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RuleChainEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/WidgetTypeEdgeProcessor.java
- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- application/src/test/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructorTest.java
- common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
- common/edge-api/src/main/proto/edge.proto
- dao/src/main/java/org/thingsboard/server/dao/sql/relation/JpaRelationDao.java
This functionality will support 3.3.0 edges to connect to the 3.3.3 server and receive correct rule chains updates.
Widget type image and descriptions propagated to edge as well.
> [3.3.3] [Edge] support 3.3.0 edge version rule chains

- application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
- common/actor/src/main/java/org/thingsboard/server/actors/TbActorCtx.java
- common/actor/src/main/java/org/thingsboard/server/actors/TbActorId.java
- common/actor/src/main/java/org/thingsboard/server/actors/TbActorMailbox.java
- common/actor/src/main/java/org/thingsboard/server/actors/TbEntityActorId.java
- common/actor/src/main/java/org/thingsboard/server/actors/TbStringActorId.java
Now we have one scheduled message per tenant and not one per device.
> [3.3.3] Reduce number of scheduled messages for session timeout

- application/src/main/resources/thingsboard.yml
spring.jpa.properties.hibernate.order_by.default_null_ordering: "${SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_BY_DEFAULT_NULL_ORDERING:none}"
The motivation is well described by @limejeroen on https://github.com/thingsboard/thingsboard/issues/4519
> [3.4] Null ordering default is none (previous was last [DESC NULLS LAST])

- dao/src/main/java/org/thingsboard/server/dao/event/BaseEventService.java
We must not change page number of a deletion page link. If amount of events to delete is larger then 1000 (batch size) in a couple of times, only some part of events would be deleted (because after we delete a page, we increase the page number, and then events that are now on the previous page are left untouched, and so on). 
P.s. It was like that before, didn't notice when developed the events clearing api
> [3.3.3] Fix events deletion

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
- ui-ngx/src/app/modules/home/models/datasource/attribute-datasource.ts
The value when getting timeseries or attributes which is absent and deleting the timeseries or attributes by WS should be the same.
get: coordinates: {ts: 0, value: ""}
delete: coordinates: {ts: 0, value: null}
> [3.3.3]improved removing timeseries/attributes

- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
Added compatibility for widgets that defined with enable show title icon and disabled show widget title.
> [3.3.3] UI: Added additional condition to define showTitleIcon

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- defaulte  bootstrap dtlsConfig DtlsConfig.DTLS_ROLE==BOTH
-- error "IllegalStateException("certificate has no proper key usage as clients!");"
- bootstrap dtlsConfig DtlsConfig.DTLS_ROLE==SERVER_ONLY -> Ok
> [3.3.3] lwm2m: fix_bug_DTLSconfig_bootstrap

- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
If we send attributes/rpc subscription by `public void process(TransportToDeviceActorMsg msg, TransportServiceCallback<Void> callback)` then `SubscriptionInfo :{attributeSubscription: false, rpcSubscription: false}`
> [3.3.3] added updating session metadata if attributes/rpc subscription was sent by this way

- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/EdgeId.java
At the moment to be able to send RPC requests from cloud to edge, TB service must be restarted, once device is provisioned to edge.
> [3.3.3] Fix RPC call from cloud to edge

- ui-ngx/src/app/core/services/resources.service.ts
Fixed JS resources order loaded in widget. Not change UI. Fixed #5975.
> [3.4] UI: Fixed that widget JS resources will be loaded in the order in which they in list resources

- common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/SnmpTransportContext.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/6025 
The problem was occurring because of an improper SNMP transport context startup order: it had the order value equal to 2, the same as transport API template (that is needed for the transport context to get the list of SNMP devices and process initialization), and due to Spring performing an arbitrary ordering when order values are same, the SNMP transport context sometimes was being started before the necessary transport API template. 
This problem only affects a monolith TB setup.
Tested locally with docker-compose.
> [3.3.4] Fix SNMP transport initialization error

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/event/event-content-dialog.component.ts
This PR added the ability to decode base64 income information of  Events to normal view and fixed the issue [#5697](https://github.com/thingsboard/thingsboard/issues/5697).
Before fix:
After:
> [3.3.4] UI: Decode base64 and return normal value

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
Issue: https://github.com/thingsboard/thingsboard/issues/6022
I fix bug with clear alarm. When we disable "Allow alarms clear" but enable "Enable alarms selection", the users can't clear an alarm. They can select an alarm, and in the top right corner, they haven't a "clear" button.
> [3.3.4] UI: Alarms table widget allows alarms to be cleared when "Allow alarms clear" is disabled

- ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
When the image card widget is set to load images from the entity attribute and when loading the default entity does not have this attribute, the data will no longer be loaded, even when there is a switch on the entity that has this attribute. Fixed #6092
> [3.3.4] UI: Fixed image map widget not updated image after firt load empty data

- common/message/src/main/java/org/thingsboard/server/common/msg/TbMsgMetaData.java
- common/message/src/test/java/org/thingsboard/server/common/msg/TbMsgMetaDataTest.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/6122
- if value of property in metadata == NULL
```
public TbMsgMetaData(Map<String, String> data) {
this.data = new ConcurrentHashMap<>();
data.forEach(this::putValue);
}
```
> [3.3.4] testScript_fix_bug_value_null

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbAlarmNodeTest.java
Issue: [#6132](https://github.com/thingsboard/thingsboard/issues/6132)
When building new alarm via `Create Alarm` node the propagation to tenant/owner configuration is being missed
Fixed by adding propagation to tenant/owner configuration when building new alarm
> [3.3.4] Fix building alarms in `TbCreateAlarmNode`

- application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/OtherConfiguration.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/TelemetryMappingConfiguration.java
Issue: https://github.com/thingsboard/thingsboard/issues/5996
The cause is that front-end does not accept null fields in LwM2M device profile transport configuration, so the config values are now being set to some defaults during automatic profile creation when processing bulk import.
> [3.3.4] Fix LwM2M devices import

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2mDefaultBootstrapSessionManager.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapClientInstanceIds.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapConfigStoreTaskProvider.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapTaskProvider.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/6118
**In LwM2MBootstrapConfigStoreTaskProvider**
- "securityInstances" and "serverInstances" variables deleted 
- create Map<String, LwM2MBootstrapClientInstanceIds> lwM2MBootstrapSessionClients= new ConcurrentHashMap<>()
- add new methods:
- - put by endpoint
- - remove by endpoint
- add "ReentrantReadWriteLock().writeLock.lock()" to metthods "put" and "remove"
**Entity "LwM2MBootstrapClientInstanceIds" created**
- - with variables "securityInstances" and "serverInstances"
**From LwM2mDefaultBootstrapSessionManager call:**
- - method "put by endpoint"
- - method "remove by endpoint"
> [3.3.4] fix_bug_lwm2m_getTasks_thread-safe

- application/src/main/java/org/thingsboard/server/service/query/DefaultEntityQueryService.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityQueryControllerTest.java
- common/util/pom.xml
- common/util/src/main/java/org/thingsboard/common/util/KvUtil.java
Issue: [#6212](https://github.com/thingsboard/thingsboard/issues/6212)
Bug in dashboard widget exporting - when we create an export file of the filtered widget data it only takes the default value of a threshold ignoring the set dynamic threshold. The cause is that dynamic values is not being resolved on regular (not web socket) connection.
Was added `resolveDynamicValue` method, which invokes before `findEntityDataByQuery` method.
Also added corresponding tests.
> [3.3.4] Fix unresolved dynamic values on API request

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
Resolve #6200
Make thingsboard server able to receive send request from LWM2M client
A new SendService has been added to LwM2mServerListener.
A new method has been added to LwM2mUplinkMsgHandler to update value on send requests
> [3.4] Handle LWM2M send request

- dao/src/main/resources/sql/schema-entities.sql
- dao/src/test/java/org/thingsboard/server/dao/SqlDaoServiceTestSuite.java
- dao/src/test/java/org/thingsboard/server/dao/service/install/sql/EntitiesSchemaSqlTest.java
Fixed `fk_device_profile_ota_package` constraint creation in the install script, so that it works during repeated install. 
The upgrade script associated with this constraint is fine.
> [3.4] Fix SQL error on reinstall

- ui-ngx/.yarnrc
- ui-ngx/generate-types.js
> [3.4] UI: Fixed generate types and build in Windows OS

- ui-ngx/src/app/core/guards/confirm-on-exit.guard.ts
Issue: [#6349](https://github.com/thingsboard/thingsboard/issues/6349)
Before fix:
canDeactivate dialog shows double times with redirect.
After fix:
Dialog shows one time.
> [3.4] UI: Fixed show double dialog with redirect

- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseTenantProfileControllerTest.java
- common/cache/src/main/java/org/thingsboard/server/cache/TBRedisCacheConfiguration.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/util/TbAutoConfiguration.java
- dao/pom.xml
- dao/src/main/java/org/thingsboard/server/dao/HsqlTsDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/HsqlTsLatestDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/JpaDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/PsqlTsDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/PsqlTsLatestDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/SqlTimeseriesDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/TimescaleDaoConfig.java
- dao/src/main/java/org/thingsboard/server/dao/TimescaleTsLatestDaoConfig.java
- pom.xml
This PR fixed the [issue](https://github.com/thingsboard/thingsboard/issues/6278) and https://github.com/thingsboard/thingsboard/issues/5546
We've updated the libraries to resolving this issue:
- Netty to version 4.1.75.Final
- Spring boot to version 2.5.12 (tomcat:9.0.60)
- Spring to version 5.3.18
> [3.4] updated spring, netty and jackson versions

- application/src/test/java/org/thingsboard/server/controller/BaseAssetControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
Issue: https://github.com/thingsboard/thingsboard/issues/6323
For fixing this issue we evict cache for old entity view.
If we evict cache for new entity view caches by name and entityId won't evict.
> [3.4] fixed entity view caching

- application/src/main/resources/thingsboard.yml
- common/cache/pom.xml
- common/cache/src/main/java/org/thingsboard/server/cache/CaffeineCacheConfiguration.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraTsPartitionsCache.java
Caffeine cache stats for general and Cassandra ts partition cache
This feature is intended to able tune-up caches based on the hit ratio.
for the Cassandra
more about Caffeine stats - https://github.com/ben-manes/caffeine/wiki/Statistics
> [3.x] Caffeine cache stats 

- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/service/entitiy/DefaultTbNotificationEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/TbNotificationEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/TbAlarmService.java
> [3.4] Refactoring Alarm controller

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/DeviceState.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/DeviceStateTest.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/6393.
Before the fix, all alarm rules were reevaluated when any attribute was deleted, and so cleared alarms got active; also, there was an NPE when handling alarm delete notification for a cleared alarm.
> [3.4] Fixes for handling alarm deletion and attributes deletion in DeviceState

- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/TransportPayloadTypeConfiguration.java
Related ticket on edge repository:
https://github.com/thingsboard/thingsboard-edge/issues/6
The issue happened because the interface doesn't extend `Serializable` interface.
Adding `Serializable` interface fixes the problem.
Test is modified as well to cover this scenario.
> [3.4] [Bug] Device profile with non default transport is not propagated to edge

- ui-ngx/src/app/modules/home/components/widget/lib/canvas-digital-gauge.ts
- ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
Issue: https://github.com/thingsboard/thingsboard/issues/6461   
Before:
After:
> [3.4] UI: Fix displaying 'Unit title' and 'value timestamp' for Digital gauges widgets

- ui-ngx/src/app/modules/home/components/widget/lib/rpc/knob.component.html
Fixed #6141
Knob Control widget incorrect resize by negative vertical.
Before:
After:
> [3.4] UI: Fixed not correct work vertical resize in knob widget

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Fixed #6020 
We could not switch from the widget add panel to the widget edit panel in dashboard page.
> [3.4] UI: Fixed incorrect switch edit widget panel when active add widget panel in dashboard page

- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
Fixed incorrect display of 'Deployed' status on edge tab:
BEFORE FIX:
AFTER FIX:
> [UI][3.4] Fixed bug with incorrect display of delayed status

- ui-ngx/src/app/modules/home/components/dashboard-page/add-widget-dialog.component.html
Issue: #6706
Fix: remove padding from add widget dialog component.
Before fix:
After fix:
> [3.4] Fix remove padding from add widget dialog

- msa/tb/docker-cassandra/Dockerfile
- msa/tb/docker-postgres/Dockerfile
- msa/tb/pom.xml
Postgresql repo from os-release $VERSION_CODENAME for dockerfile. Disable docker cache temporarily to avoid cached releases collission.
This fixes docker build when FROM debian 11 (bulleye), but repo from debian 10 (buster)
> [3.4] Postgresql repo from os-release $VERSION_CODENAME for dockerfile.

- msa/tb/docker-cassandra/start-db.sh
- msa/tb/docker-postgres/start-db.sh
- msa/tb/docker/install-tb.sh
- msa/tb/docker/start-tb.sh
Await Postgres startup.
Before this, Postgres was started in the background and Thingsboard starts in parallel.
In some cases when the database size is big and the shutdown was unclean, the Postgres might start for a couple of minutes. This led to ThingsBoard failing to start and the whole container restarted by the loop.
It is highly recommended to spin up a Postgres in a separate container to isolate applications and increase fault tolerance
Another improvement is the first lunch reliability. If the installation fails (port already bound, etc), the process will start from the beginning. 
PE: https://github.com/thingsboard/thingsboard-pe/pull/914
Let's test the result:
Builld ThingsBoard docker images with Postgresql
`mvn --projects msa/tb --also-make -T 1C license:format clean install …
> [3.4] Postgres await startup in docker containers with Postgres bundled

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
Improvement image-map when image attribute empty set default image
> [3.4] UI: Improvement image-map when image attr empty set default image

- ui-ngx/src/app/core/services/script/node-script-test.service.ts
- ui-ngx/src/app/modules/home/pages/rulechain/add-rule-node-dialog.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/add-rule-node-dialog.component.scss
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
- ui-ngx/src/styles.scss
> [3.4] UI: Fixed incorrect show rulechain dialog in sm display (600-959px)

- application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityRelationControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/sql/EntityRelationControllerSqlTest.java
Issue: [#6029](https://github.com/thingsboard/thingsboard/issues/6029)
Relations check refactoring - moved relations checkers into `relationCheck` method and made them not perform checks if relations is from current tenant to themself
> [3.4] Fix "403 forbidden" error when a tenant creates a relations with themselves

- docker/docker-compose.redis-cluster.yml
Sometimes cluster does not create properly when nodes start in parallel. 
This led to exceptions on the ThingsBoard on the Jedis driver and the cause is not obvious to a user. 
```
Caused by: org.springframework.dao.DataAccessResourceFailureException: Cannot obtain connection to node 7ce8a34df194ab76b44cc109a404d94cb6b3ff2as as it is not associated with a hostname!
at org.springframework.data.redis.connection.jedis.JedisClusterConnection$JedisClusterNodeResourceProvider.getConnectionForSpecificNode(JedisClusterConnection.java:968)
at org.springframework.data.redis.connection.jedis.JedisClusterConnection$JedisClusterNodeResourceProvider.getResourceForSpecificNode(JedisClusterConnection.java:943)
at org.springframework.data.redis.connection.jedis.JedisClusterConnection$JedisClusterNodeResour …
```
> [3.4] Redis cluster startup slow down avoiding an issue with cluster create

- application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
- application/src/main/resources/thingsboard.yml
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
These bugs were found because edge black-box tests are unstable without these fixes. 
PR contains fixes:
1. Saving of edge event in batches should be single-threaded.
2. Persistent attributes should not be propagated to edge
No specific tests were added for this - it's covered in edge project with a black box tests functionality.
> [3.4][Bug] Saving of edge event in batches should be single threaded 

- docker/compose-utils.sh
- docker/docker-check-log-folders.sh
- docker/docker-create-log-folders.sh
- docker/docker-install-tb.sh
- docker/docker-start-services.sh
- docker/docker-upgrade-tb.sh
This PR will check and set the owner for data folders on install, start, and upgrade scripts
Here is the sample output:
A new script `./docker-check-log-folders.sh` was added. It only checks folders and returns "OK" or errors. Here is the sample output:
PE: https://github.com/thingsboard/thingsboard-pe-docker-compose/pull/35
> [3.4] docker-compose checkFolders: create and set owner

- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/AbstractRuleChainMetadataConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructorFactory.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructorV330.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructorV333.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructorV340.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RuleChainEdgeProcessor.java
- application/src/test/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructorTest.java
- common/edge-api/src/main/proto/edge.proto
PR related to this ticket:
https://github.com/thingsboard/thingsboard-edge/issues/16
In the 3.4+ release checkpoint, rule node configuration was updated - the edge layer must handle this properly and send correct metadata according to the edge version.
- Multiple (v330, v333, and v340) metadata constructors were introduced from the monolith rulechain metadata constructor.
- Factory for different rule chain metadata constructors was introduced.
- Checkpoint rule node configuration update was added.
> [3.4] Edge push to rule chain node

- docker/.env
- docker/docker-compose.yml
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
This limits Java memory usage under black-box tests. Without limits, Java claims too much memory and it worms up the Build machine.
It is also possible to set JAVA_OPTS for docker-compose
```
JAVA_OPTS = "-Xmx384m -Xss256k"
```
> [3.4] Black box tests memory limit

- ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
Fixed #6908 
The timeseries widget with the 'Use dashboard timewindow' option enabled won't react to dashboard timewindow update in a case when the dashboard state containing this widget is used within the State widget. Widget data won't be updated accordingly when selecting a new time period.
The binding for dashboard timewindow is fixed.
> [3.4] UI: Fix binding to dashboard timewindow for timeseries widgets used within state widget

- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
**The client closes faster than it passes registration to the server**
```
NoSecLwM2MIntegrationTest.testWithNoSecConnectLwm2mSuccessBootstrapRequestTriggerConnectBsSuccess_UpdateTwoSectionAndLm2m_ConnectLwm2mSuccess
NoSecLwM2MIntegrationTest.testWithNoSecConnectLwm2mSuccessBootstrapRequestTriggerConnectBsSuccess_UpdateLwm2mSectionAndLm2m_ConnectLwm2mSuccess
RpkLwM2MIntegrationTest.testWithRpkConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess
X509_TrustLwM2MIntegrationTest.testWithX509TrustConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess
X509_NoTrustLwM2MIntegrationTest.testWithX509NoTrustConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess
PskLwm2mIntegrationTest.testWithPskConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_Conne …
```
> [3.4] fix_bug_tests lwm2m

- ui-ngx/src/app/core/services/dashboard-utils.service.ts
- ui-ngx/src/app/core/services/item-buffer.service.ts
After copying or exporting the alarm widget to another dashboard, it would not quit loading
before:
> [3.4] UI: Fixed incorrect import/export/copy alarm type widgets

- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraTsPartitionsCache.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java
Pull request is related to the issue https://github.com/thingsboard/thingsboard/issues/6951
Partitions cache in case of Cassandra DB is not properly cleaned up during the removal of partitions and new time-series data cannot be written for recently removed partition.
> [WIP][3.4] Clean up cassandra partitions cache on remove

- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
**The client closes faster than it passes registration to the server**
```
NoSecLwM2MIntegrationTest.testWithNoSecConnectLwm2mSuccessBootstrapRequestTriggerConnectBsSuccess_UpdateTwoSectionAndLm2m_ConnectLwm2mSuccess
NoSecLwM2MIntegrationTest.testWithNoSecConnectLwm2mSuccessBootstrapRequestTriggerConnectBsSuccess_UpdateLwm2mSectionAndLm2m_ConnectLwm2mSuccess
RpkLwM2MIntegrationTest.testWithRpkConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess
X509_TrustLwM2MIntegrationTest.testWithX509TrustConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess
X509_NoTrustLwM2MIntegrationTest.testWithX509NoTrustConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess
PskLwm2mIntegrationTest.testWithPskConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_Conne …
```
> [3.4] fix_bug_tests lwm2m Security

- dao/src/main/java/org/thingsboard/server/dao/service/validator/AssetDataValidator.java
Without this changes my locally built Docker instance cannot event start. Issue with log [#6982](https://github.com/thingsboard/thingsboard/issues/6982).
Strange why already existing `spring.main.allow-circular-references: "true"` in `thinsboard.yml` doesn't resolve the case.
> [3.4.1] Fix start up failure due to Spring circular dependencies

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
We should set the default value after update with incorrect value or remove the inactivityTimeout.
> [3.4.1] fixed update or remove inactivityTimeout kv

- ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
This pull request will show a warning message of missing rule chains during the unassign action (at the moment only on assigned actions this check happens).
Related issue:
https://github.com/thingsboard/thingsboard/issues/7042
Added check during unassing action.
> [3.4.1][UI] Check for missing edge rule chain during unassign of rule chain(s) from edge

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/OtaLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
- ERROR
```
- at org.thingsboard.server.transport.lwm2m.security.sql.X509_TrustLwM2MIntegrationTest.testWithX509TrustConnectBsSuccess_UpdateTwoSectionsBootstrapAndLm2m_ConnectLwm2mSuccess(X509_TrustLwM2MIntegrationTest.java:80)
at jdk.internal.reflect.GeneratedMethodAccessor1618.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(Inv …
```
> [fix_bug]  lwm2m tests

- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/DeviceMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/DeviceProfileMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/OtaPackageMsgConstructor.java
- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- common/edge-api/src/main/proto/edge.proto
Firmware ID is not propagated from cloud to edge in device and device profile entities.
Related issue:
https://github.com/thingsboard/thingsboard-edge/issues/18
Changes implemented - firmware ID added to the proto file and propagated to edge from the cloud in contructors.
> [3.4.1] Firmware ID not synced from cloud  to edge in device / device profiles

- ui-ngx/src/app/modules/home/pages/user/user-tabs.component.html
Asset and device details page lets a user to review theirs relation either to user or some other entity, so it would make sense to have such tab for users as well.
> [3.4.1] UI: Add relation tab to user details.

- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
Issue: [#7008](https://github.com/thingsboard/thingsboard/issues/7008)
Bug: For custom marker not apply custom size (size by default was 30px)
Before fix:
Marker size doesn't change.
After fix:
> [3.4.1] UI: Fixed custom marker size for map widgets

- ui-ngx/src/app/modules/home/components/entity/entities-table.component.scss
Issue: [#7107](https://github.com/thingsboard/thingsboard/issues/7107)
When you triple-click on the entity view, the image shifts to the left. when you triple-click again, it goes back.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to the Entity View;
2. Go to any Entity View group;
3. Triple-click on any entity view. The image shifts to the left;
4. Repeated triple-click shifts the image to the right.
Before fix: 
After fix: 
Everything works fine (Screenshot after triple click).
> [3.4.1] UI: Fixed table shift after triple click

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAssetControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseCustomerControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDashboardControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseRuleChainControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
- dao/src/main/java/org/thingsboard/server/dao/customer/CustomerServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/edge/EdgeServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantProfileServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
Entity delete with delete relations:
- if entity deletion is invalid, it is restored, but relations are deleted 
**Suggested solution:**
-  the operation "delete/remove entity" should be performed with annotate @Transactional
- By entity Tenant (exception): 
```
@Transactional - doesn't make sense
Tenant cannot delete himself (Forbidden 403)
Tenant could be removed only by SysAdmin
```
> [fix_bug] Entity_delete_relations_with_transactional

- pom.xml
Updated bouncycastle dependency to 1.69 to be in sync with Apache Pulsar dependency in PE version.
This will remove duplicate jar files and reduce the general size of PE jar version.
- update version of bouncycastle dependency.
No tests added - integration tests to check apache pulsar integration is going to be added in PE in the scope of covering all integrations by tests.
**Apache Pulsar integration was validated manually in the local environment.**
Size before changes:
**467** jars
Size after changes:
**465** jars
Diff:
> [3.4.2] Update bouncycastle from 1.67 to 1.69 to avoid duplicate of dependencies

- ui-ngx/src/app/shared/adapter/custom-datatime-adapter.ts
- ui-ngx/src/app/shared/shared.module.ts
Issue: [#7091](https://github.com/thingsboard/thingsboard/issues/7091)
Bug: After manual editing day and month change position.
Fix: Added custom datetimeAdaptor which get locale and parse the date in the right format.
> [3.4.2] UI: Fixed DatetimeAdapter for 'en-GB' locale

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Issue: https://github.com/thingsboard/thingsboard/issues/7128
Before:
Pie-flot widget has selection: {mode:x} as a result widget has bug with time:
After:
Removed 'selection: {mode:x}' +  reset Timevindow after boudle clicking for pie widgets:
> [3.4.2] UI: Remove selection (mode:x) for Pie-flot widget

- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/markdown-widget-settings.component.ts
Fixed #7158 
Before:
Markdown/HTML value function content in markdown widget settings is not displayed, while the function value isn't empty.
> [3.4.2] UI: fixed displaying of Markdown/HTML value function content in markdown widget settings

- application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
EntityActionService ->  pushEntityActionToRuleEngine(
**... TenantId tenantId == null..**.)
```
[05:29:35] :	 [Step 3/6] 2022-09-13 05:29:35,955 [main] WARN  o.t.s.s.action.EntityActionService - [0df83410-3325-11ed-a833-9ba4da4d847c] Failed to push entity action to rule engine: ADDED
[05:29:35] :	 [Step 3/6] java.lang.NullPointerException: null
[05:29:35] :	 [Step 3/6] 	at org.thingsboard.server.service.action.EntityActionService.pushEntityActionToRuleEngine(EntityActionService.java:201)
[05:29:35] :	 [Step 3/6] 	at org.thingsboard.server.service.entitiy.DefaultTbNotificationEntityService.logEntityAction(DefaultTbNotificationEntityService.java:95)
[05:29:35] :	 [Step 3/6] 	at org.thingsboard.server.service.entitiy.DefaultTbNotificationEntityService.logEntityAction(DefaultTbNotificationEnti …
```
> [fix bug] pushEntityActionToRuleEngine endpoint if tenantId == null

- application/src/main/java/org/thingsboard/server/service/script/AbstractJsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/script/JsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/script/NashornJsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/script/RemoteJsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/script/RuleNodeJsScriptEngine.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/service/script/JsInvokeServiceTest.java
- application/src/test/java/org/thingsboard/server/service/script/MockJsInvokeService.java
- msa/js-executor/api/jsInvokeMessageProcessor.ts
- msa/js-executor/config/custom-environment-variables.yml
- msa/js-executor/config/default.yml
Default limits values:
for **total args size** - 100k symbols;
for **invocation result size** - 300k;
for **script body size** - 50k.
If a property value is set to 0 - limit is disabled.
> [3.4.2] Limits for JS script body, input args and invocation result size

- application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
- application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeRpcService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- common/cluster-api/src/main/java/org/thingsboard/server/cluster/TbClusterService.java
- common/cluster-api/src/main/proto/queue.proto
- common/message/src/main/java/org/thingsboard/server/common/msg/MsgType.java
- common/message/src/main/java/org/thingsboard/server/common/msg/edge/EdgeSessionMsg.java
- common/message/src/main/java/org/thingsboard/server/common/msg/edge/FromEdgeSyncResponse.java
- common/message/src/main/java/org/thingsboard/server/common/msg/edge/ToEdgeSyncRequest.java
This RP fixes incorrect sync edge requests in cluster mode. 
In case an edge session is started on one core and an edge sync request is invoked from another - the sync process will not be started.
PR is related to the issue:
https://github.com/thingsboard/thingsboard/issues/7099
- added cluster support for sync request/response messages over cluster service
- added a separate executor service to avoid blocking actor threads by edge processing logic 
Test for sync functionality already available for a monolith and they passed successfully.
> [3.4.2][Bug] Edge sync functionality - added cluster support

- application/src/main/java/org/thingsboard/server/service/script/AbstractJsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/script/AbstractNashornJsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/script/RemoteJsInvokeService.java
- application/src/test/java/org/thingsboard/server/service/script/LocalJsInvokeServiceTest.java
- application/src/test/java/org/thingsboard/server/service/script/RemoteJsInvokeServiceTest.java
- common/cluster-api/src/main/proto/jsinvoke.proto
- msa/js-executor/api/jsExecutor.models.ts
- msa/js-executor/api/jsInvokeMessageProcessor.ts
- msa/js-executor/api/utils.ts
- msa/js-executor/queue/awsSqsTemplate.ts
- msa/js-executor/queue/kafkaTemplate.ts
- msa/js-executor/queue/pubSubTemplate.ts
- msa/js-executor/queue/queue.models.ts
- msa/js-executor/queue/rabbitmqTemplate.ts
- msa/js-executor/queue/serviceBusTemplate.ts
Now, when submitting a script invoke request to remote JS executor, script body will not be sent, expecting the executor to have it in its `scriptMap`. In case the script was not in the map , `NOT_FOUND_ERROR` code will be returned, and `RemoteJsInvokeService` in turn will send the same invoke request again (to the same partition) but with the needed script body in it.
Also, migrated from using UUID script id for remote executor to a hash of tenant id and script body. This will reduce the amount of compiled scripts with same body, and also the amount of scripts will not depend on the rule engine instance count.
> [3.4.2] Improvements for remote JS executor

- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/Oauth2AuthenticationSuccessHandler.java
- ui-ngx/src/app/modules/login/pages/login/login.component.html
- ui-ngx/src/app/modules/login/pages/login/login.component.ts
When the admin shares the link to a dashboard with the user by clicking the URL the user is forced to log in to TB first. This is normal behavior. One can authenticate via credentials or from configured IDP / SSO provider. But after a successful sign-in, one is forwarded to a Home page instead of the targeted dashboard.
The user indeed is authorized to see the dashboard. To view it, they need to click the URL again which is not convenient. 
With this feature user will be redirected to the targeted url.
PR is related to the issue:
[#7277
](https://github.com/thingsboard/thingsboard/issues/7277)
No tests were added due to impossibility of mocking required redirects that are required from third party services.
> [3.4.2] Feature: Redirect to the targeted url after successful login via oauth2

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-key-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
This PR lets to configure data keys of entities widget not only to hide or show but to show only in desktop mode and hide in mobile mode.
> [3.4.2] UI: Let data keys of entities widget to hide in mobile mode.

- application/src/main/java/org/thingsboard/server/config/RateLimitProcessingFilter.java
- application/src/test/java/org/thingsboard/server/system/BaseRestApiLimitsTest.java
- application/src/test/java/org/thingsboard/server/system/sql/RestApiLimitsSqlTest.java
Replaced basic class filter for rate limits filter. 
GenericFilterBean was used as a base class for filter, but it apply filter function twice for every received request. So to avoid extra rate limit charge we should use OncePerRequestFilter as a base class for rate limit filter.
Jira ticket - PROD-1547
> [3.4.2] Fix for rate limits filter

- ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
Not work for data aggregation in the widget without pageData
Before:
After:
> [3.4.2] UI: Fixed check isEmpty validation in EntityDataCmd models

- pom.xml
upgrade protobuf version from 3.17.2 -> 3.21.7, support Mac M1(ARM Core) protobuf files compile,
fixed issue #5734
**(3.17.2)older protobuf version don't have protoc-osx-aarch file**  
as of version 3.21.7 version, protoc-osx-aarch has been added, and it compiled on my Mac M1 computer。✅
> [3.4.2] Feature -upgrade protobuf version from 3.17.2 -> 3.21.7, support Mac M1(ARM Core) protobuf files compile

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/RepositorySettings.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/RepositorySettingsInfo.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
- ui-ngx/src/app/core/http/admin.service.ts
- ui-ngx/src/app/modules/home/components/vc/auto-commit-settings.component.html
- ui-ngx/src/app/modules/home/components/vc/auto-commit-settings.component.ts
- ui-ngx/src/app/modules/home/components/vc/complex-version-create.component.ts
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.ts
- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.html
- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.scss
- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.ts
- ui-ngx/src/app/shared/models/settings.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
In the Version control Repository settings added back-end (AdminController) and front-end support to control Read-only status. 
If the checkbox is checked:
- the user will not be able to 'Create entities version' or 'Create version' and vice versa.
- the user won't be able to edit, delete or save Auto-commit settings
UI changes:
1. Checkbox Read-only is checked:
2. Checkbox Read-only is unchecked:
> [3.4.2] Feature: Version control Repository settings with 'Read-only' flag

- ui-ngx/src/app/modules/home/components/event/event-filter-panel.component.ts
- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Issue: [#7470](https://github.com/thingsboard/thingsboard/issues/7470)
Fixed height event filter panel.
> [3.4.2] UI: Fixed height and console error for Event filter panel

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/value-source.component.html
Without this PR it is `column` for all screen sizes.
> [3.4.2] UI: Use row layout on screen bigger than xs size.

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-key-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-key-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-key-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-key-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Here is single table column of *Entity table* widget. With this PR user would specify custom column header title (see *Power / Capacity* on the screenshot) meanwhile cell content function will operate with data key's label as it was before. For example,
```
return `${entity['Power]} / ${entity['Capacity]}` ;
```
> [3.4.2] UI: Added support of custom table header title in addition to data key label.

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/DefaultEdgeNotificationService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/DeviceEdgeProcessor.java
> [3.4.2] Refactoring - replace String.format with log.XXX formatter

- ui-ngx/src/app/modules/home/components/widget/data-key-config.component.html
- ui-ngx/src/app/modules/home/components/widget/data-key-config.component.scss
Changes in "Data key configuration":
- Settings tab. Aggregation section (timeseries keys): fixed mat-expansion-panel height for hints for mobile mode.
Before:
After:
> [3.4.2] UI: Minor style fixes in data key config 

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
With the help of this PR, chart would be able to draw not only single threshold lines but a set of lines based on an array of values provided in the entity attribute.
> [3.4.2] UI: Chart thresholds support array of values

- ui-ngx/src/app/core/services/utils.service.ts
- ui-ngx/src/app/modules/home/components/widget/dynamic-widget.component.ts
- ui-ngx/src/app/modules/home/models/services.map.ts
- ui-ngx/src/app/modules/home/models/widget-component.models.ts
- ui-ngx/src/app/shared/components/phone-input.component.ts
Description of problem is in #7258
With this PR I would receive continuous updates  in my custom widgets from all timeseries data keys without explicitly specifying them in widget configuration:
```
self.onInit = function() {
let utils = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('utils'));
utils.subscribeToEntityTelemetry(self.ctx).subscribe(
data => console.log('Data: ', data),
error => console.log('Error: ', error));
}
```
> [3.4.2] UI: Add API to create telemetry websocket updater in custom widgets

- ui-ngx/src/app/core/services/utils.service.ts
- ui-ngx/src/app/modules/home/components/widget/dynamic-widget.component.ts
- ui-ngx/src/app/modules/home/models/services.map.ts
- ui-ngx/src/app/modules/home/models/widget-component.models.ts
Description of problem is in #7258
With this PR I would receive continuous updates  in my custom widgets from all timeseries data keys without explicitly specifying them in widget configuration:
```
self.onInit = function() {
let utils = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('utils'));
utils.subscribeToEntityTelemetry(self.ctx).subscribe(
data => console.log('Data: ', data),
error => console.log('Error: ', error));
}
self.onDestroy = function() {
if (self.ctx.telemetrySubscriber) {
self.ctx.telemetrySubscriber.unsubscribe();
}
}
```
> [3.4.2] UI: Add API to create telemetry websocket updater in custom widgets.

- common/message/src/main/java/org/thingsboard/server/common/msg/TbMsgProcessingStackItem.java
- common/message/src/test/java/org/thingsboard/server/common/msg/TbMsgProcessingStackItemTest.java
PE: https://github.com/thingsboard/thingsboard-pe/pull/1242
This fixes the issue with FST serialization. It was reported on RedisSerializator for DownlinkMsg
Test added to prove and fix the issue.
```
java.lang.RuntimeException: Class org.thingsboard.server.common.msg.TbMsgProcessingStackItem does not implement Serializable or externalizable
at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)
```
Test passed
> [3.4.2] TbMsgProcessingStackItem implements Serializable

- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
Issue: https://github.com/thingsboard/thingsboard/issues/7551 
PE: https://github.com/thingsboard/thingsboard-pe/pull/1244
Simply build (assign) prepared statements array atomically
Tests OK:
> [3.4.2] Fix Cassandra prepared statement produces NullPointerException in some case

- msa/js-executor/queue/kafkaTemplate.ts
- msa/js-executor/server.ts
This is a quick fix for the situationthe  when js-executor node stops KafkaClient, but does not exit the main process.
The symptom may looks like a very uneven distribution of CPU load through the js-executors pods. And eventually the rule engine will end up with a lot of timeouts.
The fix is brutal but works fine for about 10 days with js-executors restarts when needed.
This PR needs to be improved by the very expert on node.js
The Grafana dashboard on JS-executors may looks like
You also may see no new logs for some time. Or see some weird errors like
```
2022-09-22 16:32:54,771 [kafkaTemplate] ERROR: Failed batch send to kafka, length: [3396], pending to reprocess msgs
2022-09-22 16:32:54,771 [kafkaTemplate] ERROR: TypeError: Cannot read properties of undefined (reading 'sendBatch')
at …
```
> [3.4.2] js-executor - improved lifecycle events and added kill for crash event

- dao/src/main/java/org/thingsboard/server/dao/aspect/SqlDaoCallsAspect.java
Now, for `INFO` logging level, top **by timing** is printed, instead of top by failures.
Stats example for `INFO` logging level:
```
Total timing statistics below:
[ea076010-3d85-11ed-9200-77fc04fa14fa]: calls: 81, failures: 0, exec time: 284 
[ea076010-3d85-11ed-9200-77fc04fa14fa] Top 3 methods by timing:
[ea076010-3d85-11ed-9200-77fc04fa14fa]: method: JpaAbstractDao.findById(..), calls: 61, failures: 0, exec time: 180
[ea076010-3d85-11ed-9200-77fc04fa14fa]: method: JpaRelationDao.findAllByFrom(..), calls: 2, failures: 0, exec time: 24
[ea076010-3d85-11ed-9200-77fc04fa14fa]: method: JpaDeviceDao.findDeviceInfosByTenantId(..), calls: 1, failures: 0, exec time: 20
[b7d45a20-3e26-11ed-9a91-2129c969dba6]: calls: 39, failures: 0, exec time: 149 
[b7d45a20-3e26-11ed-9a91-2129c969dba6] Top 3 …
```
> [3.4.2] Improve db calls stats printing

- application/src/main/resources/thingsboard.yml
- dao/src/main/java/org/thingsboard/server/dao/sqlts/AbstractChunkedAggregationTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/timescale/TimescaleTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/timescale/TsKvTimescaleRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/ts/TsKvRepository.java
This fixes issue https://github.com/thingsboard/thingsboard/issues/7528
Using native query for finding kvs to ignore `hibernate.order_by.default_null_ordering` property.
Now the query will end with `ORDER BY ts DESC LIMIT 10` regardless of the yml settings, and index scan will be used.
> [3.4.2] Use default SQL null ordering for ts_kv

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
Fix logic for inactivity timeout fetching to be in sync when **fetchDeviceStateDataUsingEntityDataQuery** is used on method **onAddedPartitions** execution.
Issue: https://github.com/thingsboard/thingsboard/issues/7545
> [3.4.2] inactivity timeout fix

- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultAlarmQueryRepository.java
Issue: #7588 
query before:
```
select count(*)
from (select *
from (select a.id                       as id,
a.created_time             as created_time,
a.ack_ts                   as ack_ts,
a.clear_ts                 as clear_ts,
a.additional_info          as additional_info,
a.end_ts                   as end_ts,
a.originator_id            as originator_id,
a.originator_type          as originator_type,
a.propagate                as propagate,
a.propagate_to_owner       as propagate_to_owner,
a.propagate_to_tenant      as propagate_to_tenant,
a.severity                 as severity,
a.start_ts                 as start_ts,
a.status                   as status,
a.tenant_id                as tenant_id,
a.customer_id              as customer_id,
a.propagate_relation_types as …
```
> [3.4.2] Bugfix of alarm count query with null sortOrder and textSearch specified.

- application/src/test/resources/logback-test.xml
> [3.4.2] mute TelemetryEdgeSqlTest that causes a lot of randomly generated errors

- application/src/main/data/json/tenant/edge_management/rule_chains/edge_root_rule_chain.json
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- common/data/src/main/java/org/thingsboard/server/common/data/EdgeUtils.java
- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
Added method to fetch rule chains by type - to be able to fetch edge rule chains.
Remove a connection from 'RPC from device' to 'Push to cloud' node - it's already removed in PE in the last release, but forgotten in CE.
> [3.4.2] RestClient updates. Remove default connection from RPC from device to push to cloud

- common/data/src/main/java/org/thingsboard/server/common/data/SearchTextBasedWithAdditionalInfo.java
- dao/src/main/java/org/thingsboard/server/dao/service/NoXssValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/NoXssValidatorTest.java
Added validation on xss for entity's additionalInfo.
> [3.4.2] Validation for entity's additionalInfo

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Fixed incorrect work custom dashboard CSS. Fixed https://github.com/thingsboard/thingsboard/issues/7642
Dashboard not full-screen mode
before:
after:
> [3.4.2] UI: Fixed custom dashboard CSS was not applied when a dashboard is full-screen

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
Fixed sending notifications to transports if we use monolith.
> [3.4.2] fixed queue notifications in monolith

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAuditLogControllerTest.java
- application/src/test/java/org/thingsboard/server/service/script/TbelInvokeServiceTest.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/insert/sql/SqlPartitioningRepository.java
Fixed transaction abortion when couldn't save the partition:
set propagation type to NOT_SUPPORTED for createPartitionIfNotExists so that it is executed non-transactionally.
Catch all errors on partition saving.
Handling of concurrent partition creation errors was tested manually.
> [3.4.2] Fix issues with partition creation

- application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
Because of no broadcasted event, `assetProfileCache` was not updated, and therefore after changing profile of an asset, messages are still processed by the previous profile's rule chain.
> [3.4.3] Fix asset's profile changing

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/BaseReadTsKvQuery.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/BaseTsKvQuery.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java
This fixes the issues https://github.com/thingsboard/thingsboard/issues/7739 and https://github.com/thingsboard/thingsboard/issues/7742.
The root cause for no timeseries data for entity view was that in `BaseTimeseriesService`.`updateQueriesForEntityView` we were replacing initial `BaseReadTsKvQuery` with updated one with new id generated, and therefore returned `ReadTsKvQueryResult` had `queryId` not matching the initial query.
The cause for invalid State Chart behavior: when `fetchLatestPreviousPoint` in `GetTsCmd` is enabled, we are adding extra `BaseReadTsKvQuery` for same ts key, and then when processing the results, the result for the first query was rewritten by the result of the second one.
> [3.4.3] Fix no timeseries data in widget for entity view; fix State Chart invalid behavior

- application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractDataSubCtx.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmDataSubCtx.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbEntityDataSubCtx.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
PR fixes issue with redundant updates over the websockets:
https://github.com/thingsboard/thingsboard/issues/7774
Let's have next timeseries data at 7th of November for next ts: **04:34**, **11:28**, **14:55** and at **20:37**.
We request aggregate by **SUM** of timeseries data for the 7th of November.
Grouping interval is set to 1 hour. 
Cassandra will provide 4 results at ts of these results are: **04:30**, **11:30**, **14:30** and at **20:30**.
**20:30** is used as the latest TS for key states of subscription context, and we are going to request all missed updates starting from **20:30**. But because of this, the timeseries data at **20:37** is going to be considered as missed updates. But this value was already used in **SUM** calculation for **20:00-21:00** period. …
> [3.4.3][Bug] Getting a lot of updates over WS in case of aggregation query, even if no real updates happened

- application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
We shouldn't update device credentials (generate new random access token) if it absent in csv file.
> [3.4.3] fixed device bulk import with empty credentials

- application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetryWebSocketService.java
- application/src/test/java/org/thingsboard/server/controller/BaseWebsocketApiTest.java
- application/src/test/java/org/thingsboard/server/controller/TbTestWebSocketClient.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/7789.
Added null check when retrieving tenant profile by tenant id in WS services.
> [3.4.3] Fix NPE on WS subscription for sysadmin

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbSplitArrayMsgNode.java
issue: https://github.com/thingsboard/thingsboard/issues/7790
> [3.5] Bugfix: Node 'split array msg'. Empty array

- ui-ngx/src/app/modules/home/components/import-export/import-export.models.ts
- ui-ngx/src/app/modules/home/components/import-export/table-columns-assignment.component.html
- ui-ngx/src/app/modules/home/components/import-export/table-columns-assignment.component.ts
Fixed #7663.
This PR fixed the incorrect validation CSV mapping column when used without a header line.
Improvement validation and allow fields for Edge.
Before:
After:
> [3.4.3] UI: Fixed validation in bulk import and improvement bulk import for Edge

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.scss
Resolve #7781
Improvement of multiple input widget: always visible action button
Before:
After:
> [3.4.3] UI: Always visible action button in multiple input widgets

- application/src/main/java/org/thingsboard/server/service/edge/DefaultEdgeNotificationService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RuleChainEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/TelemetryEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
- application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/BaseRuleChainEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/BaseTelemetryEdgeTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNodeTest.java
During solution template development for edge next bugs/features were created:
https://github.com/thingsboard/thingsboard-edge/issues/32
https://github.com/thingsboard/thingsboard-edge/issues/33
https://github.com/thingsboard/thingsboard-edge/issues/34
This PR contain minor fixes for the above issues.
1. Added support of USER entity for edge processors.
2. Added correct propagation of isRoot flag to edge rule chain processor.
3. Exclude INACTIVITY_TIMEOUT from filter
- [] Description contains brief notes about what needs to be added to the documentation.
> [3.4.3][Bug] Edge root rule chain update fix. USER entity support added. INACTIVITY_TIMEOUT pushed to edge.

- application/src/main/data/upgrade/3.4.1/schema_update.sql
> [3.5] Fixed incorrect index creation for edge event migration

- application/src/main/java/org/thingsboard/server/service/session/DefaultDeviceSessionCacheService.java
If we use redis cache then all device sessions will be saved in redis. 
In device session cache used `putIfAbsent` so sessions will be saved and never updated.   
If we will restart the `core` this sessions will be restored but this sessions always without attributes and rpc subscriptions.
After each process function we try to do sessions dump.
For solving this issue we should use `put` instead of `putIfAbsent`.
> [3.5] fixed device sessions dump

- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/components/home-components.module.ts
- ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
- ui-ngx/src/app/modules/home/components/widget/widget.component.ts
1. **Issue**: After hiding in the dashboard-header, the **"tb-dashboard-select"** component stayed in DOM-structure and send an unnecessary request for getting dashboard-objects. 
**Solution**: The directive "fxShow" was changed to "ngIf" in order to remove a current component from the DOM-structure. 
2. **Issue**: Issue: For "single-entity" alias-filter types we are sending a request for getting entity-info data in order to display the name of a current entity in dashboard header. It is unnecessary to do this for "Entity from dashboard state" alias-filter, since we can get needed info from stateParams in this case without extra request.
**Solution**: For the case of "Entity from dashboard state" alias-filter, we are getting the needed data from stateParams instead of doing an extra …
> Optimizations for dashboard-pages that open in popover or dialog.

- application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
After migration to spring 2.7 caching static resources doesn't work. 
For fixing we replace `SecurityFilterChain resources` due to migration [doc!](https://www.baeldung.com/spring-deprecated-websecurityconfigureradapter#3-configure-web-security)
> [3.4.4] fixed js cache

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbFetchDeviceCredentialsNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbSplitArrayMsgNode.java
issue: https://github.com/thingsboard/thingsboard/issues/7971
> [3.4.4] Bugfix: node fetch device cred and split array

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbAbstractTypeSwitchNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbAssetTypeSwitchNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbDeviceTypeSwitchNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbOriginatorTypeSwitchNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbAssetTypeSwitchNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbDeviceTypeSwitchNodeTest.java
issue: https://github.com/thingsboard/thingsboard/issues/7975
> [3.5] Feature: new nodes 'asset type switch' & 'device type switch'

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbAbstractTypeSwitchNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbAssetTypeSwitchNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbDeviceTypeSwitchNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbOriginatorTypeSwitchNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbAssetTypeSwitchNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbDeviceTypeSwitchNodeTest.java
issue: https://github.com/thingsboard/thingsboard/issues/7975
> [3.4.4] Feature: new nodes 'asset type switch' & 'device type switch'

- ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
If push backspace in empty search fields showing null value
After:
Before:
> Fixed when deleting a value in the search field time shows null value

- ui-ngx/src/app/modules/home/components/widget/data-keys.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
Fixed: [#7902](https://github.com/thingsboard/thingsboard/issues/7902)
Minor fixes:
- Added gap for widget setting mobile mod slide toggle;
- Fixed translation in data-key-component.
> Hotfix added gap for widget setting mobile mod and fix translation

- dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityDataAdapter.java
- dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityDataAdapterTest.java
> [3.4.4] Fix data convertion for BigInteger values that stored in DB as String

- ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.html
- ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.scss
- ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.ts
Added Input for hint in the queue-autocomplete component. 
This  change was added for this task: https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/108
UI example:
> Queue autocomplete add input hint

- ui-ngx/src/app/core/api/widget-subscription.ts
{i18n:variable-name} displayed instead of human-readable text.  
Fixed #8011 
Timeseries table data keys configuration
Before:
After:
> Fixed applying custom translation to labels of latest data keys in timeseries widgets

- ui-ngx/src/app/modules/dashboard/dashboard-pages.routing.module.ts
- ui-ngx/src/app/modules/home/components/home-components.module.ts
- ui-ngx/src/app/modules/home/pages/home-pages.module.ts
This PR fixes the error that could occur on loading custom widgets that are using tb-extensions.
1. Create a dashboard with two states.
2. Add custom widget that uses the tb-extension module on the second state
3. On the first state add the state widget with the link to the second state.
Before:
An error will occur while loading the widget.
After:
No error is present. The widget will be loaded correctly.
> Fixed error on loading custom widgets module withing dashboard state component

- ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
In case '_**is module**_' is checked for one of the widget resources, basic modules (SharedModule, WidgetComponentsModule, HomeComponentsModule) won't be included.
This could lead to errors like on the screenshot below.
After the change missed components will be included to widget resources. The widget will be loaded without errors.
> Fix loading widget resources, when one of the resources is marked as module

- ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Chips UI element for  adding sparkplug metrics names that will be stored as device attributes.
> [3.4.5] Sparkplug UI: Add SparkPlug attributes metric names

- application/src/main/resources/thingsboard.yml
Issue: https://github.com/thingsboard/thingsboard/issues/8093
PE: https://github.com/thingsboard/thingsboard-pe/pull/1469
`SPRING_DATASOURCE_HIKARI_REGISTER_MBEANS` parameter added
This enables spring.jpa.datasource.hikari.registerMbeans parameter via an environment variable.
Default is `false` - no changes, same as before
When `true` - the MBean will appear via JMX
This will help to diagnose pool utilization and congestion, as shown in the picture:
More details on [Hiraki pool](https://github.com/brettwooldridge/HikariCP)
> [3.5] Enable MBean to diagnose the Hikari connection pool state via JMX

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestProperties.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractBasePage.java
- msa/black-box-tests/src/test/resources/docker-selenium.yml
PE: https://github.com/thingsboard/thingsboard-pe/pull/1484
- fixed hardcoded IP '172.17.0.1' in docker-compose selenium - `host.docker.internal:host-gateway` (outdated)
- wait timeout increased up to 30 sec for slow or busy environments
- host-gateway replaced with the simple call **https://haproxy** as the selenium runs within the same network with load balancer and can reach it by service name
The problem was the hardcoded IP address in tests for the docker host machine.
For the TeamCity build agent in docker, the address is different `'172.18.0.1'`, so the fix required
The result during the build with `host-gateway` is on the screenshot below:
```
docker exec -it teamcity-agent bash
user@581c32d7ebdd:/# docker run alpine:3.16 sh -c "ip route|awk '/default/ { print $3 }'"
Unable to …
```
> [3.5] UI tests stability improvements

- ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-comment-dialog.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-comment-dialog.component.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.html
Moved alarm table widget comments action on first position, moved alarm comments dialog actions on top, added ignoring of loading alarm details dialog on commenting and reassigning.
> [3.5] UI: alarm comments/assign amendments

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusQueueConfigs.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbCoreQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbRuleEngineQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbCoreQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbRuleEngineQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbCoreQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbRuleEngineQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbCoreQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbRuleEngineQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubSubscriptionSettings.java
- common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqQueueArguments.java
- common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsQueueAttributes.java
Implemented queues:
- AWS SQS
- Google PubSub
- RabbitMQ
- Azure Service Bus
> alarm rule queues implementations

- application/src/test/java/org/thingsboard/server/service/resource/sql/BaseTbResourceServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseDeviceServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseOtaPackageServiceTest.java
Rule ExpectedException refactored with AssertJ Exception Assertions
> [3.5] Rule ExpectedException refactored with AssertJ Exception Assertions

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
…Time(true);
add 
`sessionMetaData.setOverwriteActivityTime(true);`
> [fix bug][3.4.5] failed_close_session_of_device

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/attributes/AbstractMqttAttributesIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/rpc/AbstractMqttServerSideRpcIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv5/attributes/AbstractAttributesMqttV5Test.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv5/client/connection/AbstractMqttV5ClientConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv5/client/subscribe/AbstractMqttV5ClientSubscriptionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv5/client/unsubscribe/AbstractMqttV5ClientUnsubscribeTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv5/rpc/AbstractMqttV5RpcTest.java
Fix tests - await for device actor to receive subscription
> [3.5] Fix tests - await for device actor to receive subscription

- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultAlarmQueryRepository.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseAlarmServiceTest.java
Added sorting by `assignee_email` instead of sorting by `assignee` (There is no column with such name in alarm view).
Added lost `AND` for where clause for `assignee_id` filter in `AlarmDataQuery` processing.
> [3.5] Fix/alarm assignment sorting

- application/src/main/data/upgrade/3.4.4/schema_update.sql
- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
Fixed `ERROR: VACUUM cannot be executed within a pipeline` during upgrade from 3.4.4.
Reproduced in postgresql version 14.7
> [3.5]fixed upgrade schema update

- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
before, we could save alarm with assigne Id that references user from another tenant. fixed this
> [3.5] added assignee check for alarm

- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
- ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.html
- ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.ts
In our projects we are trying to reuse TB code widgets as much as possible. The `tb-entity-autocomplete` widget provides useful filtering feature by setting property called `excludeEntityIds`.
This PR adds the same functionality but for the `tb-entity-subtype-autocomplete` widget by setting properties called `excludeSubTypes`. Angular's `appearance` property was added as well.
> Exclude specified subtypes from autocomplete widget.

- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
There are some cases in dashboard development when you need to have little mobile row height (e.g., 25px), but at the same time some widgets on the same dashboard state should higher than 250 px (10 * 25px), where 10 - is upper value of multiplier for widget height in mobile mode.
This PR is to get rid of upper bound (upper value of multiplier).
> Leave only lower bould for widget's height in mobile mode.

- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.html
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added hint to the "Password / access token" input:
> Added hint to the "Password / access token" input (Repository settings)

- ui-ngx/src/app/modules/home/components/dashboard-page/states/default-state-controller.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/states/entity-state-controller.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/states/state-controller.component.ts
This PR a bit simplifies dashboard state management in case of "dynamic navigation". 
Our approach in dashboard development is to have single dashboard what covers all type of devices. But user/customer should see only that types what he/she wants or buys. We called it "dynamic navigation". So to have smooth navigation experience, we need to pass additional information in dashboard state.
> Optionally update dashboard state when using navigate back API.

- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
- application/src/test/java/org/thingsboard/server/edge/BaseTelemetryEdgeTest.java
In case attribute was deleted for non device type - incorrect future completion, and as a result error messages in the logs.
* properly return future and finish it for non device types
* added test to validate it
> [3.5] Edge processor - delete attribute msg is not properly handled for non device type

- ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.ts
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
> Change notification template/rule type disabled in edit mode

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
> [3.5] Fixed logging of EdgeGrpcSession

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
- common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
- common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeRpcClient.java
- common/edge-api/src/main/proto/edge.proto
This PR addresses cases where gRPC messages sent to or received from the edge exceed the default maximum message size. The changes introduced in this PR allow for better handling of such cases and provide the ability to customize the maximum message size.
* Add the ability to override the max message size for the client
* Communicate max message size information between the client and server
* Validate message size before sending and receiving messages to and from the client
Related issue: https://github.com/thingsboard/thingsboard-edge/issues/41
Documentation updates required:
* Update the Edge installation page to include an explanation of the **CLOUD_RPC_MAX_INBOUND_MESSAGE_SIZE** environment variable and how to set it for customizing the maximum message size.
> [3.5] Handle gRPC messages exceeding default max message size

- common/script/remote-js-client/src/main/java/org/thingsboard/server/service/script/RemoteJsInvokeService.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
Deleted redundant jetbrain @NotNull annotations
> Deleted redundant @NotNull annotations

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbOriginatorTypeSwitchNode.java
> Originator node

- ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.html
Before fix: after selecting option - no users matching, autocomplete tries to select the null user and gets an error.
After fix: Added stop Propagation for click action and fixed CSS layout for it.
> Fix for no users matching assignment user

- ui-ngx/src/app/shared/models/constants.ts
- ui-ngx/src/app/shared/models/rule-node.models.ts
Steps to reproduce: 
1. Open rule chain
2. add rule node Calculate delta (occur pop-up window)
3. click the Help button ( ? )
4. redirect to https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/overview/ 
but should be redirected to https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/enrichment-nodes/#calculate-delta
Fix: Added correct help link for calculate delta rule node.
> Add help link for calculate delta rule node

- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Fixed default icon size for table cell action.
Before fix:
After fix:
> Fixed default icon size for table cell action

- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Add fixed width for event table cell with copy button (Entity Id, Message Id) that gives the ability to align copy button in one line.
Before fix:
After fix:
> Event table fixed width for cell with copy button

- application/src/main/resources/thingsboard.yml
_Issue:_ On Windows, ${file.separator} for JavaCacerts path is replaced with "backslash", which cannot be parsed by yml file, so the application cannot be built and run fails.
_Error message:_ 
org.thingsboard.server.ThingsboardServerApplication
2023-05-04 15:37:58,122 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.yaml.snakeyaml.scanner.ScannerException: while scanning a double-quoted scalar
in 'reader', line 150, column 11:
path: "${SECURITY_JAVA_CACERTS_PATH:${ ... 
^
found unknown escape character l(108)
in 'reader', line 150, column 54:
... _JAVA_CACERTS_PATH:${java.home}\lib\security\cacerts}"
_Fix:_ Replace fetching ${file.separator} from System.properties with hardcoded "forward slash".  
Windows could process request with a forward slash:
> Bug/Yml cannot scan a double-quoted scalar on Windows

- application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeActorMessageProcessor.java
> fixed singleton mode update

- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/template-configuration.ts
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
- ui-ngx/src/app/shared/components/notification/notification.component.scss
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed notification button size.
Added notification action button text validator for a max length.
Before:
After:
> Minor noification improvement

- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
When we change the widget dataSource type from required data keys (Screen 1) to optional data keys (Screen 2), there are no updated validators in dataSource data keys.
_Screen 1_
Before:
_Screen 2_
After:
_Screen 2_
> Fixed incorrect updated dataSource validator when changing dataSource type

- application/src/main/resources/thingsboard.yml
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/AlarmRepository.java
This fixed the error message `This statement does not declare an OUT parameter`
The functions in Postgres have a return statement that effectively works as OUT parameters.
We had a hikari pool size is 16. After 32 error messages the system was not able to acquire a new connection from the pool.
This connection leak was really unexpected because the standard `@Procedure` was used (not our issue).
After refactoring `@Procedure` with `@Query` the issue is gone. tests passed and worked as expected.
To make the Hikari pool leak detection feature much easier to enable - the respective key `SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD` was exposed in `yaml`.
The screenshot that diagnoses the hikari pool leak
After the fix:
Tip: To determine the Hikari poo leak, just set the …
> [hotfix][3.5.0] alarm repository fix this statement does not declare an out parameter

- dao/src/main/java/org/thingsboard/server/dao/sqlts/insert/sql/SqlPartitioningRepository.java
SqlPartitioningRepository hotfix: partition already pending detach in a partitioned table
This is a quick workaround for disabling the Postgres 15 feature. 
This is related to the issue https://github.com/thingsboard/thingsboard/issues/8271
This is **not a solution** but a workaround. The only reason is to release **disk space** for **Postgresql 15** instances.
> [hotfix][3.5.0] SqlPartitioningRepository hotfix: partition already pending detach in partitioned table

- ui-ngx/src/app/modules/home/components/widget/lib/settings/control/round-switch-widget-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/control/slide-toggle-widget-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/control/switch-control-widget-settings.component.ts
Issue: [#8538](https://github.com/thingsboard/thingsboard/issues/8538)
Fixed: Switch control widget, Slide Toggle Control, Round switch - widget title changes
> Fixed control widgets setting change

- ui-ngx/src/app/modules/home/pages/api-usage/api_usage_json.raw
Fixed: [#8545](https://github.com/thingsboard/thingsboard/issues/8545)
Fixed fill color for Api usage widget.
> Fixed Api usage widget fill color

- ui-ngx/src/app/shared/components/file-input.component.scss
- ui-ngx/src/app/shared/components/image-input.component.scss
- ui-ngx/src/app/shared/components/multiple-image-input.component.scss
Fixed incorrectly called select files window. Clicking the button did not always show the file selection window.
> Fix handle action "browser file" in file input components

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttChannelHandler.java
Before changes: 
In case the Mqtt Integration config "max bytes in the message" are lower than the message payload size, the message cannot be processed and the user receives a class cast exception: _class io.netty.handler.codec.mqtt.MqttMessage cannot be cast to class io.netty.handler.codec.mqtt.MqttPublishMessage._ 
After changes: 
In cases where the config payload size would be lower than the message size, receive a log error: 
_2023-05-25 16:28:57,644 [nioEventLoopGroup-2-4] ERROR o.t.mqtt.MqttChannelHandler - [netty-mqtt/LzE1Ce3E] Message decoding failed: too large message: 3120 bytes_
**More probable cases:**
For instance, there are 4 usages for this check type (look at the screen below): MqttTransportHandler doesn't need to have this check directly before the switch, because …
> [3.5.2] Fix/mqttChannelHandler prevent class cast exception

- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Issue: [#8570](https://github.com/thingsboard/thingsboard/issues/8570)
Added columns visibility for Timeseries table with support of multiple datasources with timeseries and latest data columns.
Timeseries data key 
Latest data key
> Added columns visibility for Timeseries table

- ui-ngx/src/app/modules/common/modules-map.ts
Added ToggleHeaderComponent to the module-map. This change allows using ToggleHeaderComponent inside rule-config-ui-ngx, widget extensions, etc.
> Add ToggleHeaderComponent to the module-map

- ui-ngx/src/app/modules/home/pages/admin/mail-server.component.html
- ui-ngx/src/app/modules/home/pages/admin/mail-server.component.ts
Fix:
- Delete password from json if not change it (sent password: null at save);
- Added possible to send test mail without saving settings in basic settings and if oauth2 settings you can send test mail only after saving.
> Fixed oauth2 mail server settings

- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
Fixed: [#8783](https://github.com/thingsboard/thingsboard/issues/8783)
Before fix: 'Notify again' dialog with template when you click 'Next' stays in the “Compose” tab, and the “Review” tab doesn’t appear.
After fix: everything works fine and tab 'Review' opens.
> Fixed 'Notify again' dialog in notification center

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-toolbar.component.scss
Fixed #8813 
Before:
It is not possible to navigate to a previous dashboard state on mobile view by selecting the target state in the dashboard toolbar.
The list of previous states does not appear on clicking the current state name.
After:
The list of previous states does appear, and navigation is possible in this way.
> Fixed dashboard state selection in toolbar on mobile view

- application/src/main/data/upgrade/3.5.1/schema_update.sql
- application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/AlarmMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/GeneralEdgeEventFetcher.java
- application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
- application/src/test/resources/application-test.properties
- common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeEventService.java
- common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEvent.java
- dao/src/main/java/org/thingsboard/server/dao/edge/BaseEdgeEventService.java
- dao/src/main/java/org/thingsboard/server/dao/edge/EdgeEventDao.java
- dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/EdgeEventEntity.java
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeEventRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
- dao/src/main/resources/sql/schema-entities.sql
- dao/src/test/java/org/thingsboard/server/dao/service/EdgeEventServiceTest.java
- dao/src/test/resources/sql/system-test-psql.sql
**Motivation**: This pull request addresses two potential issues that could arise from improper message delivery to the edge, particularly under heavy load or in cluster mode.
The 'edge_event' table is currently processed by sorting via the 'createdTime' column. Under heavy load, it's possible for multiple events to have identical 'createdTime' values. In such cases, some events might be missed and not sent to the edge under certain conditions, or conversely, some events might be sent twice.
In cluster mode, 'createdTime' is generated on a specific cluster node. If there is a time difference between nodes, or if there are issues in the steps to save events, resulting in delayed delivery, certain events can be missed and not delivered to the edge.
To resolve these issues, a new sequential …
> Edge event table - added sequential ID column to handle properly heavy load and cluster cases

- ui-ngx/src/app/shared/decorators/coercion.ts
Cource decorators worked incorrectly with the following entry:
this entry was parsed as 'required = false'
This PR fixing this problem.
> Update cource Decorators

- ui-ngx/src/app/modules/home/pages/device/data/device-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/pages/device/data/snmp-device-transport-configuration.component.ts
Fixed: [#8883](https://github.com/thingsboard/thingsboard/issues/8883)
Before fix:
After fix:
> Fixed device transport configuration with SNMP protocol enabled/disabled state

- ui-ngx/src/app/shared/components/unit-input.component.html
- ui-ngx/src/form.scss
Before:
_standard mode_
_hover_
After:
_standard mode_
_hover_
> Added on unit input to show the clear button when hovering the element

- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/TbAlarmService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/user/DefaultUserService.java
- application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
Added unassigning for all alarms, assigned to user when user has been deleted.
https://thingsboard-portal.atlassian.net/browse/PROD-2144
PE PR - https://github.com/thingsboard/thingsboard-pe/pull/1797
> [3.5.2] Added unassignment on user deleting

- application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
- application/src/test/java/org/thingsboard/server/controller/plugin/TbWebSocketHandlerTest.java
We face a deadlock situation in version `3.5.1`. It looks like the dashboards open, but the content is never loaded.
Thread dump analyses prove the problem.
The web socket `handlePongMessage` is from the client, and at the same time, another thread is trying to close the connection by timeout.
Code analysis with @volodymyr-babak shows that the current implementation of `TbWebSocketHandler` is thread-safe, and `synchronized` is obsolete.
What is the fix:
* TbWebSocketHandler.SessionMetaData removed synchronization to avoid deadlock with WsSession that already have its own lock.
* TbWebSocketHandler.checkLimits refactored to extract IO session.close() call from the synchronized scope 
* ws msg queue fixed the last msg pickup, and as a result - the msg order (see pictures and comments at the …
> [Hotfix] web socket synchronized fix

- ui-ngx/src/app/modules/home/pages/notification/inbox/inbox-table-config.resolver.ts
Added support of custom translations in Subject and Message columns of inbox notifications talbe.
Before:
After:
> Fix for custom translation in inbox notifications table

- ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
- ui-ngx/src/app/shared/models/notification.models.ts
Fix notification rule saved without additionalConfig breaks notification rules page.
> Fix for notification rules page

- ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.html
- ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.html
Fixed: [#8978](https://github.com/thingsboard/thingsboard/issues/8978)
Fix: Hide edit button if profile is not selected Asset/Device profile autocomplete.
Before fix:
After fix:
> Fixed hide edit button if entity is not selected Asset/Device Profile

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfigServiceImpl.java
- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfigServiceImplTest.java
Merge function added. Tests Added.
PE: https://github.com/thingsboard/thingsboard-pe/pull/1883
This fixes the startup issue.
```
ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Duplicate key urn:imei:151358811362971 (attempted merging values LwM2MModelConfig(endpoint=urn:imei:151358811362971, attributesToAdd={}, attributesToRemove=[], toObserve=[], toCancelObserve=[], toRead=[/5_1.1/0/3]) and LwM2MModelConfig(endpoint=urn:imei:151358811362971, attributesToAdd={}, attributesToRemove=[], toObserve=[], toCancelObserve=[], toRead=[/5_1.1/0/3]))
at org.thingsboard.server.transport.lwm2m.server.model.LwM2MModelConfigServiceImpl.init(LwM2MModelConfigServiceImpl.java:92)
```
Before this fix, tests failed.
After is fine.
> [hotfix] Lwm2m transport - merge non-unique endpoints for models fetched from the cache

- application/src/main/java/org/thingsboard/server/service/entitiy/user/DefaultUserService.java
- application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
Fix for user removing, when we remove a tenant user from sysadmin level we have an empty tenantId and we cannot find related alarms, so we should use tenantId from user that we are removing. It won't cause security issue, because we check permissions in controller, before calling changed method.
> Fix for removing user from sysadmin level alarm unassignment

- application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/TbMsgPackCallback.java
- application/src/test/java/org/thingsboard/server/service/queue/TbMsgPackCallbackTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/exception/AbstractRateLimitException.java
- common/data/src/main/java/org/thingsboard/server/common/data/exception/ApiUsageLimitsExceededException.java
- common/message/src/main/java/org/thingsboard/server/common/msg/queue/RuleEngineException.java
- common/message/src/main/java/org/thingsboard/server/common/msg/queue/TbMsgCallback.java
- common/message/src/main/java/org/thingsboard/server/common/msg/tools/TbRateLimitsException.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/MultipleTbQueueCallbackWrapper.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/MultipleTbQueueTbMsgCallbackWrapper.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/TbQueueTbMsgCallbackWrapper.java
- common/util/src/main/java/org/thingsboard/common/util/ExceptionUtil.java
- common/util/src/test/java/org/thingsboard/common/util/ExceptionUtilTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/MultipleTbMsgsCallbackWrapper.java
This is about skipping all failed rule engine messages caused by rate limits.
The implementation is a quick win. 
`onRateLimit` method was added to the `TbMsgCallback` interface. 
ExceptionUtil.lookupExceptionInCause refactored from recursion to a loop. Tests added
before StackOverflow:
after OK
> Rule engine: ack all rate limited failures

- application/src/main/data/upgrade/3.5.1/schema_update.sql
- dao/src/main/resources/sql/schema-entities.sql
Error occures on trying to send notification using rule node:
```
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:280)
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.comm …
```
> fix_bug_default_VARCHAR_length_notification_request.info_1M

- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Please take a look at the picture for details.
Thank you @ChantsovaEkaterina for your help
> UI event table speedup config (15min default time window), ms in time for events 

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
- common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/CoapTransportResourceTest.java
From PROD ticket:
Device responds to the server when using X509 based authentication.
Step to reproduce:
Observe coaps://THINGSBOARD_URL/api/v1/rpc
Send server-side RPC to device
Device receives RPC and responds to coaps://THINGSBOARD_URL/api/v1/rpc/{$id}. DOES NOT WORK.
> fix CoAP over DTLS feature type handling for server-side rpc response

- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
- dao/src/main/resources/sql/schema-entities-idx.sql
SQL partial index idx_notification_recipient_id_unread added for cheap and fast unread notification count on UI
According to the PostgreSQL stats from real production, the notification bell on UI consumes many resources for tenants with 100k+ notifications in history.
The new partial index solves the problem, and the UI notification bell appears immediately after the page refresh without noticeable delay.
> [3.5.2] Notification unread counter query speedup

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
When device activity becomes false, we update InactivityTimeout to a greater value, then device activity becomes true, and after the timeout remains true.
> fixed update inactivity timeout attribute

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
Changes affect alarms, entities and timeseries table widgets.
Before:
After:
> Increased reserved space for hidden action cell buttons

- ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
- ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.html
- ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.ts
Updated label logic for tb-relation-type-autocomplete to ensure backward compatibility. 
According to the new design, the label should be hidden only in the table.
Additional PR: https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/130
Hiding: 
Not hiding:
> Update label logic for relation-type-autocomplete

- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.ts
Bug: on restoring of entities version if choose 'remove other entities' checkbox and cancel displayed popover, other entities are removed anyway.
**BEFORE**:
**AFTER**
> Fix for 'remove other entities' popover in version control

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
- ui-ngx/src/styles.scss
Fixed: [#8766](https://github.com/thingsboard/thingsboard/issues/8766)
Fixed styles for the widgets table to make it possible to apply styles from the row function. After the fix also bg color apply to the actions table cell.
Before fix:
After fix:
> Fixed widgets table styles for correct applying row style function

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
1. Login as a tenant user
2. Open any dashboard 
3. Enable edit mode
4. Click Add widget
5. Choose any widget but do not confirm adding
6. Click close (“X“) of pop-up window (of widget)
7. Try to follow to another menu item 
Occur twice  'Unsaved changes' window
After fix: 'Unsaved changes' window shows one time.
> Fixed showing exit dialog twice on dashboard page

- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.ts
- ui-ngx/src/app/modules/home/pages/device/devices-table-config.resolver.ts
Rename button from 'skip' to 'close':
After closing the device connectivity dialog after creating device and the device status active refresh table
> Improve device connectivity dialog

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
Before this PR, the math node throws an exception instead of tellFailure.
In the case of two parallel math nodes with different parameters, but with the same input, the exception might leave message unprocessed in the msg queue
On the user level it will look like timeout to process with last rule node 'math node'
Test added to reproduce the issue
The fixed version looks fine. All failed messages got the tellFailure response with no timeout
Two tests that expected exceptions are also refactored
after the fix
The new test failed because processing had to run in the right rule node instance. 
Adding the Supplier function in the queue object will resolve the issue.
The node fixed: call processMsgAsync via BiFunction this::processMsgAsync
> MathNode: tellFailure and process the next message in the queue in case we are the last consumer

- ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Fixed widget shaking on changing the dashboard size, for example when you click "edit widget button" and widgets have some size when there is scroll bar appears on the right. 
[Screencast from 31.08.23 16:54:10.webm](https://github.com/thingsboard/thingsboard/assets/143483163/39328140-0567-4cc5-af02-43af1526ae94)
> Fixed widget shacking

- ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-pie-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-pie-widget-settings.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Radius, inner radius and tilt should be in range from 0 to 1. Added corresponding error message. Step of these number input field is now 0.1.
**BEFORE**
**AFTER**
> Validation for pie flot common settings

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
The issue with full description: https://github.com/thingsboard/thingsboard/issues/8872
Upd: [TbDate isoDateFormat is ThreadLocal instead synchronization](https://github.com/thingsboard/thingsboard/pull/8873/commits/2a683f9977b4acb5bd9551406e7f0f4e688c46a3)
> [3.5.2] TbDate toISOString sync as SimpleDateFormat required 

- application/src/main/data/json/edge/rule_chains/edge_root_rule_chain.json
- application/src/main/data/json/tenant/device_profile/rule_chain_template.json
- application/src/main/data/json/tenant/rule_chains/root_rule_chain.json
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeConfigurationTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeTest.java
Will check the cache before node attribute save.
There is **no thread-safe** or transactivity (same as before). If you need **sequential** (happen-before) guarantees  - the SequentialByOriginator is the right choice.
The only difference user will experience: are **no update of the timestamp** of the attribute (extremely rare usage by users) and **no attr changes notification** as well if no update happens.
**Backward compatibility** for existing tenants, but **rule chain templates** will have the true value for **new tenants**
**UI** by @volodymyr-babak : https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/128
My concern is that UI have default value "false" when I create a new node. And I can not make default config true
> [3.5.2] 'Update on value change' for save attributes rule node feature

- dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsServiceImpl.java
Remove useless setPassword. The code in question serves no purpose.
> remove useless setPassword

- ui-ngx/src/app/core/translate/missing-translate-handler.ts
Fixed: [#9183](https://github.com/thingsboard/thingsboard/issues/9183)
Before fix: we see double or even more console warn of missing translate.
After fix: missign translate show warn in console one time and setting missing key to translate store.
> Fixed doubled error message for missing translate

- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/WidgetTypeMsgConstructor.java
- application/src/test/java/org/thingsboard/server/edge/WidgetEdgeTest.java
- common/edge-api/src/main/proto/edge.proto
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Older versions of Edge experience issues with widget display when connected to version 3.6 servers. This is due to the removal of alias and bundle alias fields in the latest release. This fix populates the deprecated fields, allowing older Edge versions to connect successfully to new servers.
> Fix Widget Display Issues in Older Edge Versions Connected to 3.6 Servers

- common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmModificationRequest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbAlarmResult.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNodeTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-2411
When Device Profile increases the severity (i.e. Warning to Minor), the rule chain does NOT generate ‘Alarm Severity Updated’ type. It only does ‘Alarm Updated’, which can be the case for any changes, not severity.
> fixed alarm severity change

- ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-widgets.component.ts
Disabled add widget mode after saving widget bundle.
Before fix:
After fix:
> Fixed add widget mode for widget bundles

- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
Set the stepper label position to the bottom for Sent and Template notifications dialog.
Before fix:
After fix:
> Fixed notifications dialog

- ui-ngx/src/app/shared/components/image-input.component.scss
Added padding bottom for image input component.
Before fix:
After fix:
> Fixed padding for image input

- ui-ngx/src/styles.scss
Fixed: [#9297](https://github.com/thingsboard/thingsboard/issues/9297)
Added class 'mat-mdc-table' for more weight specificity.
Before fix:
After fix:
> Fixed entity table fields overlaying

- application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
> Fixed upgrade script

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed issue when spaces inside command was defined as error
And removed posibility to send string containing only spaces as command
> Command whitespaces hotfix

- ui-ngx/src/app/modules/home/pages/dashboard/dashboard-form.component.html
> Fixed dashboard detail button

- ui-ngx/src/app/core/guards/confirm-on-exit.guard.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/pages/widget/widget-editor.component.ts
- ui-ngx/src/app/shared/models/window-message.model.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added display of a confirm dialog about not saving changes in the widget editor. It also considers whether the widget editing mode is activated to show the dialog.
After:
> Improved show confirm on exit dialog in widget editor

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings.component.ts
> Improvement for font settings panel added settings to disabled and hide line height

- common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandlerTest.java
This test was fluky because it relies on a single GC run. GC implementation is not guaranteed that memory become crystal clear after GC call. It is rather to do the best effort to clean as much as possible with less CPU time.
For the business logic it matter that that map is kind of Weak map that is absolutely fine. It is not a point to verify the Spring ConcurrentReferenceMap implementation
> GatewaySessionHandlerTest createWeakMap() test simplified

- msa/vc-executor-docker/docker/Dockerfile
> [3.6.1] vc-executor: Dockerfile ncdu installed

- ui-ngx/src/app/modules/home/components/widget/config/basic/chart/flot-basic-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/config/datasources.component.ts
Bug: on adding timeseries chart widget to dashboard after adding datasource and removing data keys and switching modes validation of basic mode is blocking widget creation if we add datakey.
**BEFORE**
[Screencast from 27.10.23 11:18:13.webm](https://github.com/thingsboard/thingsboard/assets/87172504/dc240cb8-af7f-42bc-96ca-e3da86984d89)
**AFTER**
[Screencast from 27.10.23 11:18:55.webm](https://github.com/thingsboard/thingsboard/assets/87172504/9fa4951e-9aa1-4682-8282-a1eac6f2b9fe)
> Fix for timeseries charts validation blocks widget adding

- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
- ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
- ui-ngx/src/app/shared/models/alarm.models.ts
Before this improve: if there are selected acknowledged and unacknowledged alarms - occurs error on acknowledge selected, same with clear.
**BEFORE**
[Screencast from 06.11.23 16:36:27.webm](https://github.com/thingsboard/thingsboard/assets/87172504/c1c57df0-d11f-4b61-9678-e869da645d9e)
**AFTER**
[Screencast from 06.11.23 16:39:30.webm](https://github.com/thingsboard/thingsboard/assets/87172504/c47360f4-be4e-4ed1-b9eb-ca7cb6e48246)
> Improved usability of bulk operations in alarm widget table

- ui-ngx/src/app/modules/home/components/public-api.ts
- ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
In the current version of Thingsboard users can't create custom basic settings components, as `BasicWidgetConfigComponent` isn't shared and registration of basic settings forms doesn't work properly (**basic** components put into **advanced components map** as a result system doesn't see **basic** forms).
This PR share `BasicWidgetConfigComponent` and update `registerWidgetSettingsForms` to allow the creation  of custom basic settings forms.
> Added support basic settings form of custom widgets

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-2554
If parameter is Object as int:
If parameter is Object as String:
> [fix][bug]String asObjectToBytes

- packaging/java/scripts/control/deb/preinst
- packaging/js/scripts/control/deb/preinst
adduser command (from Debian "preinst" file) contains the duplicated option "--quiet"
> packaging: remove dupplicated "adduser --quiet" option in deb preinst

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
- ui-ngx/src/app/shared/models/widget-settings.models.ts
This pull request is created to fix the crash on empty colorProcessor type , as a fix solution added default value to colorSettings type and default case for colorProcessor  to ensure the layered approach that application is resilient against errors.
**BEFORE** 
https://github.com/thingsboard/thingsboard/assets/54553744/5a23300a-8d03-4658-9797-4bcee61b5c0f
**AFTER**
https://github.com/thingsboard/thingsboard/assets/54553744/c4784a93-215d-44f2-b4e2-2ea15cfc53a9
> Fixed value and chart card crash on empty colorProcessor type

- application/src/main/java/org/thingsboard/server/controller/DeviceConnectivityController.java
- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
This PR contains the following things:
1. Added --network=host for docker command in gateway launch command in ThingsBoard IoT gateways dashboard.
2. Added support for IPv6 baseUrl and device connectivity host. Earlier, any IPv6 address was processed incorrectly, because it should be differently represented for different protocols ( e.g. ::1 for MQTT, but [::1] for others)
3. Added default REST connector port forwarding to docker launch command.
PE PR - https://github.com/thingsboard/thingsboard-pe/pull/2159
> Added fix for docker command for gateway launch command and support for ipv6 adresses in device connectivity

- application/src/main/java/org/thingsboard/server/service/queue/ProtoUtils.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
Works like a normal RPC. The persistent parameter has no effect and does not return a rpcId. (in microservice deployment)
```
{
"method": "test",
"params": {
"pin": 7,
"value": 1
},
"persistent": true,
"timeout": 5000
}
```
https://thingsboard-portal.atlassian.net/browse/PROD-2699
> fixed persistent RPC

- ui-ngx/src/app/modules/home/components/alias/entity-alias-dialog.component.ts
Fixed: [#9628](https://github.com/thingsboard/thingsboard/issues/9628)
Before fix:
After fix:
After save
> Dashboard alias stacking relation filters

- application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
**The case**
Periodically our system needs to select devices based on several attributes and telemetry keys, then send to each of them RPC command. For these purpose we need custom rule node that will be able to get devices with predefined filter.
**Drawback of implementation**
Dynamic filters are not supported, because this functionality is in `application` module.
**Partial workaround**
1. Implement log in procedure.
2. Call Entities Query REST API
3. Convert response to separate messages per each device.
4. !!! **Change originator to device entity based on its ID located in message** !!! (doesn't support by TB yet)
> Add entity service to actor context.

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbAbstractTransformNodeWithTbMsgSource.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbCopyKeysNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbRenameKeysNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbCopyKeysNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbRenameKeysNodeTest.java
Logic added below wasn't updated in the UI:
1. copy key-values (tbTransformationNodeCopyKeysConfig):
change the config boolean fromMetadata -> TbMsgSource copyFrom 
// default value: DATA.
2. delete key-value pairs (tbTransformationNodeDeleteKeysConfig):
change the config boolean fromMetadata -> TbMsgSource deleteFrom // default value: DATA.
3. rename keys (tbTransformationNodeRenameKeysConfig)
change the config boolean fromMetadata -> TbMsgSource renameIn 
// default value: DATA.
As a result, this affects the creation of new rule nodes:
```org.thingsboard.rule.engine.api.TbNodeException: java.lang.IllegalArgumentException: Can't convert value: {"fromMetadata":"DATA","keys":["temperature"]}
at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:46)
at …
```
> Added hotfix upgrade for transformation rule nodes with TbMsgSource

- ui-ngx/src/app/shared/import-export/import-export.service.ts
- ui-ngx/src/app/shared/models/base-data.ts
- ui-ngx/src/app/shared/models/tenant.model.ts
- ui-ngx/src/app/shared/models/widget.models.ts
Fixed cannot import from JSON file entity when include not null external fields:
> Fixed externalId when import/export entity

- ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html
> Widget action dialog fixed name field error overlay

- application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationSchedulerService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/NotificationTargetExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationTargetImportService.java
> Fix VC support for notification recipients

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
As for now, the AbstractTbMsgPushNode checks for a supported entity type, after saving it into the database, where events are fetching and checking on the supported type during processing. So there are 2 places, we need to support for processing, which is redundant. 
> Edge - optimization: eliminate duplicate type checks in TbMsgPushNode

- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/AbstractActivityManager.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityManager.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/TransportActivityManager.java
- common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/service/TransportActivityManagerTest.java
Scenario for this bug:
- First activity for a session is reported
- Session is removed
- Activity manager tries to create new activity state for this session
- New state is not created due to a check if session is still present (state will be null in case session is not present)
- Bug: Activity manager sees that created state is null and does not record activity
Now transport activity manager does not check if session is still present when creating new state.
No documentation changes needed.
[PE PR](https://github.com/thingsboard/thingsboard-pe/pull/2309)
> Fix new activity state not being created correctly

- ui-ngx/src/app/core/http/asset-profile.service.ts
- ui-ngx/src/app/core/http/device-profile.service.ts
- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.ts
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
- ui-ngx/src/app/shared/components/entity/entity-subtype-select.component.ts
Issue - https://github.com/thingsboard/thingsboard/issues/9321
Related BE - https://github.com/thingsboard/thingsboard/pull/9776
Before:
[scrnli_1_3_2024_3-07-41 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/251c5921-a42e-4a5a-b03e-26e3b4f05e9e)
After:
[scrnli_1_3_2024_3-12-11 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/b4c7ae7b-eb3a-4c5e-92f1-ff3472e67b84)
> Added getAssetProfileNames and getDeviceProfileNames APIs

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/TbApplicationEventListener.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
TB Cores rebalancing failed due to an error in one of the partition change event handlers.
Event listeners are called synchronously, thus if one of them failed, the next one won't get to process the event.
In our case, `DefaultTbCoreConsumerService` did not subscribe to new partitions because of a failure in `DefaultSubscriptionManagerService`.
```
Failed to recalculate partitions
org.thingsboard.server.common.data.exception.TenantNotFoundException: Tenant with id xxx not found
at org.thingsboard.server.service.queue.DefaultTenantRoutingInfoService.getRoutingInfo(DefaultTenantRoutingInfoService.java:60)
at org.thingsboard.server.queue.discovery.HashPartitionService.lambda$isIsolated$22(HashPartitionService.java:501)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Concur …
```
> Error handling for PartitionChangeEvent listeners

- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/nosql/TimeseriesServiceNoSqlSetNullEnabledTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/nosql/TimeseriesServiceNoSqlTest.java
Previously, Cassandra saved value only for 1 type. If we had to save null values for the other types, we used param setNullValuesEnabled and did 5 inserts to the DB. Now, we do one insert to DB when setNullValuesEnabled=true.
> Updated CassandraBaseTimeseriesDao to do one db insert instead of 5 when setNullValuesEnabled=true

- ui-ngx/src/app/core/services/item-buffer.service.ts
When copying rule-node there was a bug that didn't allowed to copy the info about singletonMode if it presents. As a solution  singletonMode field placed to a buffer rule-node info.
> Fixed singletonMode info on copy of rule-node

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget.component.ts
- ui-ngx/src/app/shared/models/widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added new widget action handle type - open URL.
> Added new widget action type: Open URL

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
https://thingsboard-portal.atlassian.net/browse/PROD-2892
before:
```
2024-02-13 14:57:26,988 [test-lwm2m-scheduled-53-thread-1] INFO  o.e.l.c.e.DefaultRegistrationEngine - Registered with location '/rd/yUrp8EIjLS'.
2024-02-13 14:57:26,988 [test-lwm2m-scheduled-53-thread-1] INFO  o.e.l.c.e.DefaultRegistrationEngine - Next registration update to coap://localhost:5685 in 5s...
2024-02-13 14:57:26,991 [CoapServer(main)#5] ERROR o.e.l.core.response.SendableResponse - Exception while calling the reponse sent callback
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.doGetAndCache(LwM2mClientContex …
```
> fix_bug_lwm2m/coap_client_queue_Mode

- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java
- application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
- application/src/main/java/org/thingsboard/server/service/ws/WebSocketService.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/sub/AbstractNotificationSubscription.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsSubscription.java
This PR fixes quite a rare bug in our WebSocket API. All new widgets use the new WebSocket commands based on entity data queries and use separate atomic sequence numbers to generate internal subscription commands. Our old widgets used slightly different APIs that used cmdId from the incoming web socket message to generate internal subscription commands. In a rare case, when the dashboard has many widgets of both types, the race condition occurs, and both messages generate the same internal subscription commands. eventually, one of them was ignored.
> Mapping of command id to unique sequence number per subscription id

- application/src/main/resources/thingsboard.yml
- common/transport/lwm2m/pom.xml
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MIdentitySerDes.java
- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapServiceTest.java
- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfigTest.java
- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportServiceTest.java
- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStoreTest.java
- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MIdentitySerDesTest.java
- pom.xml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
This pullrequest configures the LwM2M Transport and LwM2M Transport Bootstrap Service to support the DTLS Connection ID and fixes #10061.
It adds the `transport.lwm2m.dtls.connection_id_length` configuration option, which allows DTLS CID to be turned off or on with a specific connection id length. 
As DTLS CID is not used for the connection if the client does not request it, I have chosen to turn it on by default as it gives the best user experience. The default  is a 6 byte connection id as is the Leshan demo server default and it should fit almost all use cases.
The configuration option is used to configure the scandium DtlsConnector, so it will create the ConnectionIdGenerator; the requirement for CID support.
As now, an existing dtls connection can be made from a different address or …
> Support DTLS Connection ID with configuration

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/OtaLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/NoSecLwM2MIntegrationTest.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
Tetsts
before:
```
2024-02-13 14:57:26,988 [test-lwm2m-scheduled-53-thread-1] INFO  o.e.l.c.e.DefaultRegistrationEngine - Registered with location '/rd/yUrp8EIjLS'.
2024-02-13 14:57:26,988 [test-lwm2m-scheduled-53-thread-1] INFO  o.e.l.c.e.DefaultRegistrationEngine - Next registration update to coap://localhost:5685 in 5s...
2024-02-13 14:57:26,991 [CoapServer(main)#5] ERROR o.e.l.core.response.SendableResponse - Exception while calling the reponse sent callback
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.doGetAndCache(LwM2mClientContextImpl.java:373)
at …
```
> RegistrationOnAwakeCclientQueueMode

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
> Fixed dashboard state autocomplete in widget action component

- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
- ui-ngx/src/app/shared/models/alarm.models.ts
> Fixed typeList URL query and alarm filter config translation

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
Fixed "LwM2M uplink executor is completely locked"
https://thingsboard-portal.atlassian.net/browse/PROD-3183
`"LwM2M uplink-9-1" - Thread t@88
java.lang.Thread.State: WAITING
at java.base@11.0.20/jdk.internal.misc.Unsafe.park(Native Method)
- parking to wait for <18449ac> (a java.util.concurrent.CountDownLatch$Sync)
at java.base@11.0.20/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
at java.base@11.0.20/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
at java.base@11.0.20/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
at java.base@11.0.20/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSyn …
> fixed lwm2m uplink executor lock

- application/pom.xml
- application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
- application/src/main/java/org/thingsboard/server/config/WebConfig.java
- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/controller/AlarmCommentController.java
- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- application/src/main/java/org/thingsboard/server/controller/AssetController.java
- application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
- application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
- application/src/main/java/org/thingsboard/server/controller/CustomerController.java
- application/src/main/java/org/thingsboard/server/controller/DashboardController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
- application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
- application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
- application/src/main/java/org/thingsboard/server/controller/EventController.java
- application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
- application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
- application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/resources/thingsboard.yml
- common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmComment.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/EntityId.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/UserId.java
- common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
- dao/src/test/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDaoTest.java
- pom.xml
Switch to SpringDoc OpenAPI 3.1.0
> Switch to SpringDoc OpenAPI 3.1.0

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbCheckAlarmStatusNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbCheckAlarmStatusNodeTest.java
- rule-engine/rule-engine-components/src/test/resources/logback-test.xml
The ERROR severity will fire only on unexpected exception types. This will prevent flooding the error logger.
The test added:
The rule-node behavior with no change.
> Check alarm status node: log severity reduced for "Failed to parse alarm" for known runtime exceptions

- common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
- common/transport/http/src/test/java/org/thingsboard/server/transport/http/DeviceApiControllerTest.java
- common/transport/http/src/test/resources/logback-test.xml
> [3.7] Http Transport log optimization

- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/service/script/NashornJsInvokeServiceTest.java
- application/src/test/resources/logback-test.xml
- common/script/script-api/src/main/java/org/thingsboard/script/api/AbstractScriptInvokeService.java
- common/script/script-api/src/main/java/org/thingsboard/script/api/js/NashornJsInvokeService.java
- pom.xml
The rare issue I noticed on the build machine is a failed NashornJsInvokeServiceTest.givenSimpleScript**TestPerformance**
It runs 1000 js executions, but sometimes it takes more than **4 minutes**
It becomes **well reproducible** when it does 2000 executions
The profiling shows that JS executions do nothing but waits
Eventually, under the high load, the `delight.nashornsandbox.internal.ThreadMonitor` waits `maxCPUTime` when `maxMemory` is 0.
We set as default maxCPUTime 8000 ms. And the sandbox sometimes waits all 8000ms. 
The Nashorn's source code with this condition is below.
The easiest way to address the issue is to set the CPU limit to 0 or the memory limit to MAX_LONG.
The limit suggested is 100MiB, which is effectively infinite.
Execution time reduced by x1000 for x2 more …
> Nashorn js executor sandbox memory limit

- application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
Attribute scope was treated like a String, while it is an enum now.
> Attribute scope was missed for rule engine message metadata

- rule-engine/rule-engine-api/pom.xml
- rule-engine/rule-engine-api/src/test/java/org/thingsboard/rule/engine/api/util/TbNodeUtilsTest.java
- rule-engine/rule-engine-api/src/test/resources/junit-platform.properties
- rule-engine/rule-engine-api/src/test/resources/logback-test.xml
JUnit5 migration in rule-engine-api
> JUnit5 migration in rule-engine-api

- ui-ngx/src/app/modules/home/components/filter/key-filter-dialog.component.ts
1. In alarm rules if add key filter of type 'Constant' and value type 'Boolean' without touching checkbox - null is saved.
**Result before fix**:
**Result after fix**:
2. Additionally added clear of value field on value type change.
**Before:**
[scrnli_3_11_2024_3-12-43 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/0730bbf8-7acb-4386-9771-10cffae4233d)
**After:**
[scrnli_3_11_2024_3-13-40 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/0eb4a529-ac88-484f-8ed7-cf7d46814b64)
> Fixed key filter dialog when constant key type and boolean value type selected saving null if not touched, added clear of value on value type changed

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/OtaPackageTransportResource.java
if (for whatever reason) californium goes out of transparent block mode it is required to supply the correct block number to not get a internal server error.
This change always adds the matching block number to the response, preventing the error in californium.
No unit test was added, the code was tested with a fleet of 20 devices OTAing over Thread.
Fixes: #10690
> Always send back block num

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNodeTest.java
**Issue:** #7923 
Added ability to transfer msg to originator default rule chain. Also set default value for the maxRuleNodeExecutionsPerMessage property from tenant profile.
Requires rule node UI changes:
Please add toggle for "Forward message to the originator's default rule chain".
Also add tool tip: "If enabled, message will be forwarded to the originator's default rule chain, or rule chain from configuration, if originator has no default rule chain defined in the entity profile."
> Rule Chain node: added ability to transfer msg to originator's default rule chain

- dao/src/main/java/org/thingsboard/server/dao/sql/attributes/AttributeKvRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/attributes/JpaAttributeDao.java
- dao/src/test/java/org/thingsboard/server/dao/service/attributes/BaseAttributesServiceTest.java
This fixes the following error that occurs when trying to find attribute keys by entity id and scope:
```
2024-05-07 18:49:40,556 [DbCallbackExecutorService-0-63] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42883
2024-05-07 18:49:40,556 [DbCallbackExecutorService-0-63] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: operator does not exist: integer = character varying
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
Position: 92
2024-05-07 18:49:40,556 [DbCallbackExecutorService-0-63] ERROR o.t.s.s.q.DefaultEntityQueryService - Failed to fetch attributes keys!
org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [SELECT DISTINCT attribute_key FROM attribute_kv WHERE …
```
> Fix finding of attribute keys by entity id and scope

- application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
- application/src/test/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateServiceTest.java
- application/src/test/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructorTest.java
- application/src/test/java/org/thingsboard/server/service/limits/RateLimitServiceTest.java
- application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
- application/src/test/java/org/thingsboard/server/service/sms/smpp/SmppSmsSenderTest.java
Junit 4 to 5 migration in application.
> Junit 4 to 5 migration in application (Mockito extension)

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- monitoring/src/main/java/org/thingsboard/monitoring/service/transport/TransportHealthChecker.java
LwM2MClientSerDesTest:
```
String s = "7b226e6f64654964223a2274622d6c776d326d2d7472616e73706f72742d30222c22656e64706f696e74223a2253675a4467564b5a617274704a4a717a64647052222c227265736f7572636573223a7b222f335f312e302f302f30223a7b226c774d326d5265736f75726365223a7b226964223a302c2274797065223a22535452494e47222c226d756c7469496e7374616e636573223a66616c73652c2276616c7565223a2230366433633734372d633533342d346661362d383165352d613432623039666339353966227d2c227265736f757263654d6f64656c223a7b226964223a302c226e616d65223a22546573742064617461222c226f7065726174696f6e73223a2252222c226d756c7469706c65223a66616c73652c226d616e6461746f7279223a66616c73652c2274797065223a22535452494e47222c2272616e6765456e756d65726174696f6e223a22222c22756e697473223a22222c226465736372697074696f6e223a22546573742064617461227d7d7d2c22736 …
```
> fix_bug: if setSupportedClientObjectsis is not supported LwM2m.Version

- application/src/main/java/org/thingsboard/server/controller/AuthController.java
- application/src/test/java/org/thingsboard/server/controller/AuditLogControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/TwoFactorAuthTest.java
The Audit Log does not capture the first login from the activation link/activation mail
https://thingsboard-portal.atlassian.net/browse/PROD-3434
> Added login audit log when user is activated

- application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
- application/src/main/java/org/thingsboard/server/controller/CustomerController.java
- application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
- application/src/main/java/org/thingsboard/server/controller/NotificationController.java
- application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
- common/data/src/main/java/org/thingsboard/server/common/data/audit/AuditLog.java
- common/data/src/main/java/org/thingsboard/server/common/data/event/DebugEventFilter.java
- common/data/src/main/java/org/thingsboard/server/common/data/event/LifeCycleEventFilter.java
- common/data/src/main/java/org/thingsboard/server/common/data/event/RuleNodeDebugEventFilter.java
- common/data/src/main/java/org/thingsboard/server/common/data/plugin/ComponentDescriptor.java
- common/data/src/main/java/org/thingsboard/server/common/data/security/DeviceCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/sms/config/SmppSmsProviderConfiguration.java
> fixed swagger allowable values

- ui-ngx/src/app/shared/import-export/export-widgets-bundle-dialog.component.ts
'Include bundle widgets' checkbox now enabled by default
> Include bundle widget checkbox enabled by default

- application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/subscription/ModifySubscriptionResult.java
- application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
- application/src/main/java/org/thingsboard/server/service/ws/WebSocketMsgEndpoint.java
- application/src/main/java/org/thingsboard/server/service/ws/WebSocketService.java
Added scheduled session cleanup  for cases when session was closed before last session command processed
> Added scheduled session cleanup 

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.models.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
- ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
- ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
- ui-ngx/src/app/shared/import-export/import-export.service.ts
If used pattern in tittle:
File name on widget export:
**Before:**
**After**:
(Additionally added widget default name to file name)
> Pattern support for widget title on widget export

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteCborTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
Problem:  
When ContentFormat="lwm2m+tlv " is in the request and the client does not support it, then the lechan Client M14/M4 library code throws an error:  
before:
` {"result":"NOT_ACCEPTABLE"}`
After:
application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteCborTest.java
` {"result":"CHANGED"}`
> fix bug  lwm2m Content Format M14

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
https://thingsboard-portal.atlassian.net/browse/PROD-3498
If you change the credentials in MQTT Basic, the command in "Check connectivity" is formed incorrectly.
> [Check connectivity]  Fixed mqtt basic credentials connectivity command

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
During upgrade next situation was observed:
For each rule node type that is a versioned node, we try to get a list of rule node ids with versions less than the current version. For some reason, the query was timed out for one of the versionned node type. This exception is unhandled in the current logic of upgrade and this stops the process of upgrade for other types of rule nodes.
The solution is to move the try-catch block that is currently outside the loop over versioned node types into the loop logic to have the ability to upgrade other types even if some exception was thrown for the previous type. Additionally, add the rule node type to the error log to have the ability to understand for which rule node type the upgrade failed.
> Rule nodes upgrade: moved try-catch into loop over versioned node types

- ui-ngx/src/app/modules/home/components/widget/lib/canvas-digital-gauge.ts
Fixed colors for neon gauge to add the ability to work with alpha channel.
Before fix:
After fix:
> Fixed colors for neon gauge

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
The parameter "Use redis queue for message persistence" has been deprecated since ThingsBoard version 2.5. Enabling this parameter no longer has any effect, so it has been removed.
Issue: #3086
> Rest API call node: removed deprecated 'useRedisQueueForMessagePersistence' parameter 

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
This fixes the following error on partitions recalculation, caused by some subscription of deleted tenant left in the subs map:
```
2024-06-10 13:05:47,850 [Curator-PathChildrenCache-0] WARN  o.t.s.q.discovery.ZkDiscoveryService - Failed to recalculate partitions
org.thingsboard.server.common.data.exception.TenantNotFoundException: Tenant with id xxx not found
at org.thingsboard.server.service.queue.DefaultTenantRoutingInfoService.getRoutingInfo(DefaultTenantRoutingInfoService.java:60)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
at org.thingsboard.server.queue.discovery.HashPartitionService.getRoutingInfo(HashPartitionService.java:552)
at org.thingsboard.server.queue.discovery.HashPartitionService.isIsolated(HashPartitionService.java:535 …
```
> Handle TenantNotFoundException for stale subscriptions

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.ts
Fixed jumping rows when updating data in Gateway Logs table
before:
[Screencast from 17.06.24 17:40:38.webm](https://github.com/thingsboard/thingsboard/assets/93397261/0df7f61b-b342-42cc-9699-c304b6341470)
after:
[Screencast from 17.06.24 17:39:34.webm](https://github.com/thingsboard/thingsboard/assets/93397261/add2fbe2-07ae-44c1-bbd1-a01f044b07f6)
> Fixed jumping rows when updating data in Gateway Logs table

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNodeTest.java
Added tests for Copy to view node. 
> Copy to view node: added tests

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.ts
When the min or max value changes, these remain the previous values for Gradient.
Before fix:
Change max to 100 and open bar color panel.
After fix:
Change max to 100 and open bar color panel.
> Fixed Min/Max value on gradient panel

- application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
Issue: https://github.com/thingsboard/thingsboard/issues/11145
Thingsboard service crashes if try to disable Swagger-UI
Enabled
Disabled
> Fix startup error when Swagger is disabled

- common/cache/src/main/java/org/thingsboard/server/cache/CacheSpecsMap.java
- common/cache/src/main/java/org/thingsboard/server/cache/RedisTbTransactionalCache.java
- common/cache/src/main/java/org/thingsboard/server/cache/TbTransactionalCache.java
- common/cache/src/test/java/org/thingsboard/server/cache/CacheSpecsMapTest.java
- dao/src/test/java/org/thingsboard/server/dao/cache/RedisTbTransactionalCacheTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/AlarmServiceTest.java
Redis: add ability to disable caching, in case, maxSize specs config is set to 0
> Redis - disable caching in case maxSize is 0

- ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.ts
After fix: action prevented on preview and edit mode.
> Prevent action on preview/edit mode for notification widget

- ui-ngx/src/app/modules/home/components/widget/lib/home-page/recent-dashboards-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/home-page/recent-dashboards-widget.component.ts
In case the customer user has ‘always fullscreen’ mode, the ‘home dashboards’ widget works incorrectly.
It may not navigate at all in case it is used from default dashboard or redirected to the default dashboard if the widget is used from other places. Also, dashboard autocomplete wasn't working at the customer level.
This PR fixes autocomplete and navigation for this widget at the customer level
> Fix 'Home dasboards' widget

- ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
The documentation link doesn't open on a new page
This PR fixes that
> Fix documentation link

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
-  parseBinaryArrayToInt
```
((byte) 0x9F;
TbUtils.parseBinaryArrayToInt([1, 0, 0, 1, 1, 1, 1, 1], 1, 7); return 31;
TbUtils.parseBinaryArrayToInt([1, 0, 0, 1, 1, 1, 1, 1]); return -97;
[(byte) 0xCE, (byte) 0xB2] == 52914
TbUtils.parseBinaryArrayToInt([1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0]); return 52914;
```
- hexToBase64
- parseLongToBinaryArray
`Writes the bit value to the appropriate location in the bins array, starting at the end of the array, to ensure proper alignment (highest bit to low end).`
- parseByteToBinaryArray add Endian
```
byteVal = (byte) 0x39;
int expectedLowCurrent1Alarm = 1;  //  0x39 = 00 11 10 01 (Bin0): 0 == 1
int expectedHighCurrent1Alarm = 0; //  0x39 = 00 11 10 01 (Bin1): 0 == 0
int expectedLowCurrent2Alarm = 0;  //  0x39 = 00 11 10 01 (Bin2): 0 == 0 …
```
> TBEL: added parseBinaryArrayToInt

- dao/src/main/java/org/thingsboard/server/dao/sqlts/dictionary/JpaKeyDictionaryDao.java
If `KeyDictionaryDao.getOrSaveKeyId` was executed in transaction, after calling `keyDictionaryRepository.save` Hibernate wouldn't return newly generated keyId (only after **flush**), thus it returned 0 by default.
The solution is to execute this code outside transaction. This is also helpful when there is a key conflict DB error - won't rollback parent transaction.
> Fix zero attribute key 

- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
- common/queue/src/test/java/org/thingsboard/server/queue/kafka/TbKafkaSettingsTest.java
This fixes the following warn logs on start up:
The cause is that `session.timeout.ms` is consumer-only property, but was mistakenly supplied for producer and admin client configs.
> Fix unrecognized Kafka config 'session.timeout.ms'

- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mTemperatureSensor.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
- When "Collected Value" with TimestampedLwM2mNodes is sent from the client - only the last node was stored  
- When "Collected Value" with TimestampedLwM2mNodes is sent from the client - all node was stored
> lwm2m: fix bug  send From Client CollectedValue

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmsSubscription.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbAttributeSubscription.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbEntityLocalSubsInfo.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionsInfo.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbTimeSeriesSubscription.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/sub/AbstractNotificationSubscription.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsCountSubscription.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsSubscription.java
based on thread dump:
```
"DefaultWebSocketService-0-25" - Thread t@5330
java.lang.Thread.State: WAITING
at java.base@17.0.11/jdk.internal.misc.Unsafe.park(Native Method)
- waiting to lock <7385cf25> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) owned by "DefaultWebSocketService-0-45" t@104496
at java.base@17.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
at java.base@17.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
at java.base@17.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
at java.base@17.0.11/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
at java.base@17.0.11/java.util.concurrent.locks.ReentrantLock.lock(Reen …
```
> DefaultTbLocalSubscriptionService WS single lock refactored by tenantId; TbEntityLocalSubsInfo performance optimizations for remove subscription

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNodeTest.java
- added tests for the generator node
- added validation for supported entity types
- set default value for entity type
- provided upgrade for existing nodes
Here is PE [PR](https://github.com/thingsboard/thingsboard-pe/pull/2699) . 
Must be merged with UI part.
> Generator node: improvements

- ui-ngx/src/app/modules/home/components/widget/lib/home-page/recent-dashboards-widget.component.html
- ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
The widget will display the translated dashboard title in case a translation variable is used for naming.
Before:
After:
> Recent dashboards widget - apply custom translation for dashboard titles

- ui-ngx/src/app/core/http/image.service.ts
- ui-ngx/src/app/shared/components/image/image-gallery.component.ts
- ui-ngx/src/app/shared/components/image/images-datasource.ts
Default image sub-type value added, and the order of parameters in requests changed to keep the backward compatibility with older version
> Image service: default image sub-type value added to requests

- common/queue/src/main/java/org/thingsboard/server/queue/scheduler/DefaultSchedulerComponent.java
- common/queue/src/test/java/org/thingsboard/server/queue/scheduler/DefaultSchedulerComponentTest.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/AbstractActivityManager.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstAndLastEventActivityStrategy.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstEventActivityStrategy.java
When `onReportingPeriodEnd()` throws an exception it causes periodic task to stop all all further executions. Result of this was that activities were not reported at all.
[PE PR](https://github.com/thingsboard/thingsboard-pe/pull/2801)
> Fix last activity not being reported when activity reporting period ends

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNodeTest.java
Added validation for Aws lambda node on init.   
> Aws lambda node: added validation on init

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
The problem that caused by the current logic:
When creating devices and sending telemetry, some can be created with "active" status, some with "inactive" status. Randomly. Moreover, telemetry "arrives" on all devices every second, but the status of the device does not change.
What was changed:
- added tests for DefaultDeviceStateService.onQueueMsg
- changed the logic for saving activity status to the database. Previously, we set hardcoded 'false' as activity status value to the DB, but did not change value to false in the cache. It causes error when activity event happens before added. So it was decided to save value from the cache(relevant activity status) to the DB.
> Fixed incorrect display of device state

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
Added validation for client id, since error occurs during initialization, when client id length is longer than 23. 
It happens because we use Mqtt version 3.1. According to the MQTT 3.1 specification, the client ID should be between 1 and 23 characters.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2799
> Mqtt node: added validation for client id

- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
I introduced java REST Client into my project. When I called getAlarmTypes, I got an error. Then I debugged the rest client code and found that there were some problems. The parameters were not concatenated to the URL. Then I fixed this problem.
> Fixed the problem of getAlarmTypes method query failure in rest-client

- msa/js-executor/config/default.yml
changes the default for kafka.compression to "none", to align with the default setting of the main applications thingsboard.yml 
Fixes #9613
> [FIX] inconsistent default kafka setting (compression)

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqConsumerTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqSettings.java
- common/queue/src/test/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqConsumerTemplateTest.java
Configurable RabbitMQ polling in order that more messages can be obtained from the queue during a poll.
Fixes #8445
A new RabbitMQ specific configuration property has been added that allows users to specify how many messages per queue should be retrieved during a single poll.
This could help to increase throughput when there are many messages on a queue and the polling happens to slow, causing delays in further message processing. (Prerequisite is that the system is properly seized to cope with the higher number of messages).
**Documentation should mention `TB_QUEUE_RABBIT_MQ_MAX_POLL_MESSAGES` and `queue.rabbitmq.max_poll_messages`**
> fix: Slow RabbitMQ message polling

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
Fix debug log message in `MqttTransportHandler:exceptionCaught()`
Currently logs the following:
```
2024-01-02 03:04:05,67890 [...] DEBUG o.t.s.t.mqtt.MqttTransportHandler - [<X>][<Y][<Z>] IOException: {}
java.io.IOException: Connection reset by peer
at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[...]
```
Note the `{}` in the first line.
This patch makes it print the cause message instead of those brackets:
```
2024-01-02 03:04:05,67890 [...] DEBUG o.t.s.t.mqtt.MqttTransportHandler - [<X>][<Y][<Z>] IOException: Connection reset by peer
java.io.IOException: Connection reset by peer
at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[...]
```
> Fix debug log message in MqttTransportHandler:exceptionCaught()

- application/src/main/resources/thingsboard.yml
> added description to the rabbitmq max_poll_messages property

- application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
- application/src/main/java/org/thingsboard/server/service/edge/RelatedEdgesSourcingListener.java
- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
- dao/src/main/java/org/thingsboard/server/dao/edge/BaseRelatedEdgesService.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
This PR introduces fixes for caching for the related edge functionality within the root rule chain. Initially, an empty list is cached, but it was never updated due to the 'Assign to Edge' action events being ignored. Now, all assignment events are pushed, and filters are applied at subsequent levels.
> Fixed issue with Edge Root Rule Chain cache for related edges

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
```
java.lang.NullPointerException: Cannot assign field "timeSeriesUpdateTs" because the return value of "java.util.concurrent.ConcurrentMap.get(Object)" is null
at org.thingsboard.server.service.subscription.DefaultTbLocalSubscriptionService.onTimeSeriesUpdate(DefaultTbLocalSubscriptionService.java:342)
at org.thingsboard.server.service.subscription.DefaultTbLocalSubscriptionService.onTimeSeriesUpdate(DefaultTbLocalSubscriptionService.java:333)
at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.forwardToLocalSubMgrService(DefaultTbCoreConsumerService.java:572)
at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.handleNotification(DefaultTbCoreConsumerService.java:427)
at org.thingsboard.server.service.queue.processing.AbstractConsumerService.lambda$proce …
```
> fixed NPE in subscription service after restart

- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionsInfo.java
- application/src/test/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionServiceTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-4465
```
[e0a17c00-8e1c-11eb-8b41-4fe141e00a57][04a84750-1114-11ef-bef7-5131a0fcf1e6] Failed to push subscription event TbEntitySubEvent(tenantId=e0a17c00-8e1c-11eb-8b41-4fe141e00a57, entityId=04a84750-1114-11ef-bef7-5131a0fcf1e6, type=CREATED, info=TbSubscriptionsInfo(notifications=false, alarms=false, tsAllKeys=false, tsKeys=[kw_in, latitude, longitude], attrAllKeys=false, attrKeys=[unit_id], seqNumber=2387), seqNumber=2387) due to java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
at com.google.protobuf.AbstractMessageLite$Builder.addAllCheckingNulls(AbstractMessageLite.java:352)
at …
```
> fixed concurrent modification in TbSubscriptionsInfo

- pom.xml
https://github.com/FasterXML/jackson-databind/issues/4500
```
mvn dependency:tree | grep fasterxml | grep jackson > dep_jackson.txt
```
```
[[1;34mINFO[m] +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.2:compile
[[1;34mINFO[m] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.2:compile
[[1;34mINFO[m] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.17.2:compile
[[1;34mINFO[m] +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.2:compile
[[1;34mINFO[m] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.2:compile
[[1;34mINFO[m] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.17.2:compile
[[1;34mINFO[m] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.17.2:compile
[[1;34mINFO[m] +- …
```
> jackson.version 2.17.2

- ui-ngx/src/app/shared/components/entity/entity-list.component.ts
- Go to the Notification page
- Open Sent category at the top
- Click the “Notify again” button
- Click the Next button at the dialog bottom right side
Actual result: Nothing happened when a user click Next button inside the Notify again dialog
> Fixed next button for notify again dialog

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mBinaryAppDataContainer.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota5LwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota9LwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2MIntegrationObserveCompositeTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationCreateTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDeleteTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDiscoverTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDiscoverWriteAttributesTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationExecuteTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadCollectedValueTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteCborTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/AbstractLwM2MIntegrationDiffPortTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/util/JsonUtils.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/AbstractLwm2mClientTest.java
before:
Write byte[] to path "19/0/0" only from: 
- String Hexdecimal
- String  Base64
after add Write byte[] to path "19/0/0" from: 
- Integer
- Long
- Float
- Double
> Lwm2m_write_obj_19

- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Before: 
```
2024-10-17 14:03:09,170 [main] INFO  o.e.californium.core.CoapServer - Starting server
2024-10-17 14:03:09,171 [main] INFO  o.e.c.core.network.CoapEndpoint - [LWM2M Client-coap://0.0.0.0:0] Started endpoint at coap://[0:0:0:0:0:0:0:0]:54693
2024-10-17 14:03:09,171 [main] INFO  o.e.l.c.e.DefaultEndpointsManager - New CoAP over UDP endpoint based on Californium library with very experimental support of OSCORE created, 
for server coap://localhost:5685 at coap://[0:0:0:0:0:0:0:0]:54693.
2024-10-17 14:03:09,172 [main] INFO  o.eclipse.leshan.client.LeshanClient - Leshan client[endpoint:LwNoSec00000000_4] started.
2024-10-17 14:03:09,172 [main] INFO  o.t.s.t.l.s.c.LwM2mClientContextImpl - [LwNoSec00000000_4] initialized new client.
2024-10-17 14:03:09,172 …
```
> activity_Failed to send message to core

- ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
The essence of the bug, is that, when you paste `tb-dashboard-state` with actions in it, in the custom action, which has a form, after clicking on state's action button, the form will be submitted. It is not supposed to be happened, so I wrote a type="button" to the action buttons.
Here is reproducing of this bug:
1. Create an action for widget, which will be pasted as a state into the custom action
2. Here is a map widget, with our action:
3. I've added code into the custom action, which will log the event of submitting the form, after clicking on the testAction we can see the next in console:
After adding type="button" to the action buttons, form of the custom action is not submitting.
> Fix of the action bug

- ui-ngx/src/app/shared/components/country-autocomplete.component.html
- ui-ngx/src/app/shared/components/country-autocomplete.component.ts
> Adding outline appearance to the country autocomplete

- application/src/main/java/org/thingsboard/server/service/mail/TbMailSender.java
Fixes #9878
Update `TbMailSender` to correctly handle the `mailFrom` field in the email configuration.
* Checks the `mailFrom` field in the JSON configuration and set it as the sender address if present.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/thingsboard/thingsboard/issues/9878?shareId=dee656a3-8747-41a5-89e8-e6ef63196e62).
> Fix email sender address issue

- application/src/main/java/org/thingsboard/server/service/mail/TbMailSender.java
The `mailFrom` is used for construction of the `MimeMessage`. See
```
private void sendMail(JavaMailSenderImpl mailSender,
String mailFrom, String email,
String subject, String message,
long timeout) throws ThingsboardException {
try {
MimeMessage mimeMsg = mailSender.createMimeMessage();
MimeMessageHelper helper = new MimeMessageHelper(mimeMsg, UTF_8);
helper.setFrom(mailFrom);
helper.setTo(email);
helper.setSubject(subject);
helper.setText(message, true);
sendMailWithTimeout(mailSender, helper.getMimeMessage(), timeout);
} catch (Exception e) {
throw handleException(e);
}
}
```
and
```
private void sendMail(TenantId tenantId, String email,
String subject, String message) throws ThingsboardException {
JsonNode jsonConfig = getConfig(tenantId, "mail");
TbMailSender mailSender = new …
```
> Revert "Fix email sender address issue"

- ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
- ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.ts
- ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Before:
The default grouping interval is applied only if it fits the min/max bounds for the time interval selected before. 
After:
The default grouping interval is applied after time interval selection.
> Timewindow: fix applying default grouping interval

- application/src/main/resources/thingsboard.yml
Changed default values:
- EDGES_SCHEDULER_POOL_SIZE
- EDGES_SEND_SCHEDULER_POOL_SIZE
- EDGES_GRPC_CALLBACK_POOL_SIZE
> Increase default edge-related thread pool sizes

- ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
- ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Before:
Grouping interval from the tab other than selected is applied 
After:
Correct grouping interval is applied correctly
Second issue:
Hiding the grouping interval and max values is a single configuration parameter.
Before:
After value change the parameter value is not synchronized on aggregation type change.
> Timewindow: fixed applying grouping interval on closing configuration dialog

- ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/scada/scada-symbol-object-settings.component.ts
Fixed incorrect logic in the get alarm status functionality. Previously, instead of using the severity list array provided by the user, a merged array was created, combining default values with the user-selected values.
Before:
After:
> Fixed incorrect merging of default SCADA symbol settings with user-defined settings

- application/src/main/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcService.java
The RPC Rule Node does not produce any Success or Failure message in the output if we try to send RPC using generator node.
https://thingsboard-portal.atlassian.net/browse/PROD-5464
```
var msg = {
"method": "getCurrentTime",
"params": {}
};
var metadata = { oneway: true };
var msgType = "RPC_CALL_FROM_SERVER_TO_DEVICE";
return { msg: msg, metadata: metadata, msgType: msgType };
```
```
java.lang.NullPointerException
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1693)
at org.thingsboard.server.queue.discovery.TopicService.getNotificationsTopic(TopicService.java:65)
at org.thingsboard.server.service.queue.DefaultTbClusterService.pushNotificationToCore(DefaultTbClusterService.java:242)
at …
```
> Fix RPC Rule Node not producing any Success or Failure out message

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/Lwm2mTestHelper.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_0_Test.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_1_Test.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_2_Test.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2MIntegrationObserveCompositeTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_0_Test.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_1_Test.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_2_Test.java
- application/src/test/resources/lwm2m/3-1_0.xml
- application/src/test/resources/lwm2m/3-1_1.xml
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
https://thingsboard-portal.atlassian.net/browse/PROD-5618
`{"observe": [ "3_1.1/0/9" ]}`
- The observe operation should work correctly for Object ID = 3 (DEVICE) with version 1.1.
- Telemetry and attributes should be updated and visible in ThingsBoard.
- No telemetry or attributes appear.
- The observe operation is not performed.
- The observe operation should work correctly for Object ID = 3 (DEVICE) with version 1.1.
- Telemetry and attributes should be updated and visible in ThingsBoard.
New Behavior in Leshan 15:
**Leshan 15** now provides version information via the registration.**supportedObject** field (_which was not available previously_).
If no version is specified, it should now follow Lwm2mVersion logic:
-  If the LwM2M client runs on Lwm2mVersion = 1.0, then ver = 1.0.
-  If …
> LwM2M: fix observe

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
- application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java
> Fixed flaky alarm count test

- ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
The current realization triggers stop propagation on the onDashboardMouseDown event in the dashboard and widget components. As a result, it's impossible to close pop-ups by clicking the left mouse button in the dashboard zone. 
Good example of a problem is the AG-GRID table. It contains a pop-up column filters which is currently just impossible to close:
This PR fixes this bug by adding an additional check on enabling 'edit mode'.
> Fix pop-up closing issue on dashboards

- application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/server/actors/service/ComponentActor.java
- application/src/main/java/org/thingsboard/server/actors/shared/AbstractContextAwareMsgProcessor.java
- application/src/main/java/org/thingsboard/server/actors/shared/ComponentMsgProcessor.java
StatsPersistTick scheduled future cancel on actor destroy
Scheduled futures keeps a destroyed actors in memory
StatsTick future exists, but the MailBox is not ready(0) and in destroy progress (1)
> StatsPersistTick scheduled future cancel on actor destroy

- ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
The default color for buttons and FAB is white. The default color for icon is 'text color' from widget settings.
> Fixed default action header button color

- dao/src/main/java/org/thingsboard/server/dao/sql/NamedParameterJdbcTemplateConfiguration.java
- dao/src/test/java/org/thingsboard/server/dao/sql/JdbcTemplateTest.java
`2025-03-27 07:24:31,253 [http-nio-0.0.0.0-8080-exec-2101] WARN  o.t.s.d.s.q.DefaultQueryLogComponent - SLOW QUERY took 3962981 ms: select * from (select entities.*, `
```
jakarta.persistence.query.timeout: "${JAVAX_PERSISTENCE_QUERY_TIMEOUT:30000}" # General timeout for JDBC queries
```
https://thingsboard-portal.atlassian.net/browse/PROD-5905
> Query timeout is not working for EntityDataQuery

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-color-settings-panel.component.ts
Add invalid text to color function.
Switch to the constant tab and make a change.
Before: 
After:
The same behavior for data layer color settings panel:
> Color settings panel tab validation

- application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/ttl/KafkaEdgeTopicsCleanUpService.java
- common/cluster-api/src/main/java/org/thingsboard/server/queue/TbEdgeQueueAdmin.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaAdmin.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
Modify the edge notification system to assign unique consumer groups for each edge. This change addresses the issue of a single consumer group causing rebalances and processing slowdowns for stable edges. By implementing distinct consumer groups, we can enhance stability and ensure efficient processing even as some edges experience frequent reconnections.
> Implement Unique Consumer Groups for Edge Notifications to Improve Stability

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/ProfileState.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/ProfileStateTest.java
Skip null keys at ProfileState to tolerate the issue:
DeviceProfileNode is 'Failed to process' when alarm rules /createRules/INDETERMINATE/schedule/ dynamicValue / sourceAttribute is null 
```
.getSourceAttribute() != null
```
Debug events with failures for DeviceProfile rule node
The failure event stack trace
```
org.thingsboard.server.dao.exception.IncorrectParameterException: Incorrect attribute key null
at org.thingsboard.server.dao.service.Validator.validateString(Validator.java:107)
at org.thingsboard.server.dao.attributes.CachedAttributesService.lambda$find$3(CachedAttributesService.java:159)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.thingsboard.server.dao.attributes.CachedAttributesService.find(CachedAttributesService.java:159)
at …
```
> DeviceProfile alarm - Profile state alarm schedule dynamic attributeSource null

- ui-ngx/src/app/shared/components/popover.component.ts
Fixes a crash when using `tb-help-popup` inside `matSuffix`.
The issue occurred due to Angular CDK attempting to access the overlay pane's style before it was fully rendered, leading to the following error:
```
ERROR TypeError: Cannot read properties of undefined (reading 'style')
at FlexibleConnectedPositionStrategy._resetOverlayElementStyles
```
---
https://github.com/user-attachments/assets/cc13de6d-5594-44b2-b566-741e67fcbfb8
---
https://github.com/user-attachments/assets/9aabf126-946c-462d-a71c-9630167e7c65
---
When `tb-help-popup` is used inside `matSuffix`, the projected element may not be fully rendered at the time overlay positioning is calculated.  
This causes the CDK positioning strategy to fail when it attempts to access or update style properties on an overlay element that …
> Fixed early updatePosition call to prevent CDK overlay crash in matSuffix context

- application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
- application/src/main/java/org/thingsboard/server/service/lwm2m/LwM2MServiceImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportBootstrapConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
[Put your PR description here instead of this sentence.   ](https://thingsboard-portal.atlassian.net/browse/PROD-5956)
> Fixed 404 error when accessing LwM2M Profile Transport Configuration with LwM2M disabled

- application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/AbstractOtaLwM2MIntegrationTest.java
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
`fix bug in the front: useObject19ForOta to useObject19ForOtaInfo`
> lwm2m_fix_bug_object19_For_Ota

- application/src/main/java/org/thingsboard/server/service/entitiy/ota/DefaultTbOtaPackageService.java
- application/src/test/java/org/thingsboard/server/controller/OtaPackageControllerTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-6108
```
org.springframework.dao.DataIntegrityViolationException: could not execute statement [ERROR: value too long for type character varying(1000000)] [insert into audit_log (action_data,action_failure_details,action_status,action_type,created_time,customer_id,entity_id,entity_name,entity_type,tenant_id,user_id,user_name,id) values (?,?,?,?,?,?,?,?,?,?,?,?,?)]; SQL [insert into audit_log (action_data,action_failure_details,action_status,action_type,created_time,customer_id,entity_id,entity_name,entity_type,tenant_id,user_id,user_name,id) values (?,?,?,?,?,?,?,?,?,?,?,?,?)]
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:293)
at …
```
> fixed 'value too long' after saving ota

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/SubscriptionManagerService.java
Cleanup deprecated code that supported `notifyDevice` argument since device notifications are now handled in other component
> Cleanup deprecated API in SubscriptionManagerService

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/ReconnectStrategy.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/ReconnectStrategyExponential.java
- netty-mqtt/src/test/java/org/thingsboard/mqtt/ReconnectStrategyExponentialTest.java
Addressing the issue with frequent reconnect for broken integrations (mqtt client)
Parametrized tests output 
```
2025-03-20 10:57:01,753 [ForkJoinPool-1-worker-1] INFO  o.t.m.ReconnectStrategyExponentialTest - === Reconnect delay test for ReconnectStrategyExponential(1) : calculated min [1] max [60] ===
2025-03-20 10:57:01,757 [ForkJoinPool-1-worker-1] INFO  o.t.m.ReconnectStrategyExponentialTest - == Phase 0 ==
2025-03-20 10:57:01,759 [ForkJoinPool-1-worker-1] INFO  o.t.m.ReconnectStrategyExponentialTest - Retry [0] Delay [1] : min [1] exp [null] jitter [null]
2025-03-20 10:57:01,787 [ForkJoinPool-1-worker-1] INFO  o.t.m.ReconnectStrategyExponentialTest - Retry [1] Delay [3] : min [1] exp [1] jitter [1]
2025-03-20 10:57:01,788 [ForkJoinPool-1-worker-1] INFO …
```
> MQTT client exponential reconnect strategy

- ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
The range previously selected by the user is not applied if the range option is not selected in the time window initially (another last/relative option selected)
History | Last option is selected
Before:
After switching to the Range option, the dates range selected earlier in time will be applied
After: 
After selecting the Range option, the last day interval will be applied
> Make last day selection default in Range (Time window History)

- pom.xml
downgrade logback as the least compatible version with Spring Boot 3.2.12 is logback 1.5.6
> downgrade logback as the least compatible version with Spring Boot 3.2.12 is logback 1.5.6

- common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
- common/proto/src/main/proto/queue.proto
In cluster mode, the internal RPC notification message sent between core nodes was missing two required fields: 'additionalInfo' and 'retries'.
The 'additionalInfo' field is necessary for post-processing logic during the handling of RPC status messages (e.g., RPC_QUEUED, RPC_SENT, RPC_SUCCESSFUL, RPC_EXPIRED), and its absence resulted in null values in those messages, breaking functionality in use cases that depend on this data.
The 'retries' field is used for internal retry logic. Its omission led to a default value of 0 being applied during inter-node communication, which contradicted user expectations regarding the configured number of retry attempts for the RPC.
This fix ensures that both 'additionalInfo' and 'retries' are correctly populated when routing RPC requests between core …
> Added missing fields for RPC message in cluster mode

- packaging/java/build.gradle
RPM packaging: requires .or("java-17-openjdk").or("java-17-openjdk-headless") based on yum list available for AlmaLinux 8; Rocky Linux 8; Oracle Linux 8; RHEL Universal Base Image 8; Fedora 41
The problem to address:
```bash
rpm -Uvh /tmp/thingsboard.rpm
```
Why headless does not work? The headless distro has different aliases with full jdk
```bash
docker run -it --rm --name rpmtest almalinux:8 bash
dnf install java-17-openjdk-headless -y
rpm -q --provides java-17-openjdk-headless-1:17.0.16.0.8-2.el8.aarch64
config(java-17-openjdk-headless) = 1:17.0.16.0.8-2.el8
java-17-headless = 1:17.0.16.0.8-2.el8
java-17-openjdk-headless = 1:17.0.16.0.8-2.el8
java-17-openjdk-headless(aarch-64) = 1:17.0.16.0.8-2.el8
jre-17-headless = 1:17.0.16.0.8-2.el8
jre-17-openjdk-headless = 1:17.0.16.0.8-2.el8 …
```
> RPM packaging support for java-17-openjdk-headless

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
- common/proto/src/main/proto/queue.proto
- common/proto/src/test/java/org/thingsboard/server/common/util/ProtoUtilsTest.java
```
java.lang.NullPointerException
at org.thingsboard.server.gen.transport.TransportProtos$ToDeviceRpcRequestMsg$Builder.setAdditionalInfo(TransportProtos.java)
at org.thingsboard.server.common.util.ProtoUtils.toProto(ProtoUtils.java:570)
at org.thingsboard.server.common.util.ProtoUtils.toProto(ProtoUtils.java:679)
at org.thingsboard.server.service.queue.DefaultTbClusterService.pushMsgToCore(DefaultTbClusterService.java:201)
at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.sendRpcRequestToDevice(DefaultTbRuleEngineRpcService.java:193)
at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.forwardRpcRequestToDeviceActor(DefaultTbRuleEngineRpcService.java:177)
at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.sendRpcRequestToDevice(DefaultTbR …
```
> Fixed handling of RPC with missing additional info in cluster mode

- application/src/main/data/json/system/scada_symbols/cross-connector-hp.svg
> Fixed line width for Cross connector HP SCADA symbol

- ui-ngx/src/app/modules/home/pages/widget/widget-type-autocomplete.component.scss
Before:
Maximum height for widget preview is not set.
If the height is greater than the width, the widget preview scales to fit the maximum width and extends the height of the autocomplete option.
After:
Widget preview scales proportionally to fit the maximum width and height
> Fixed widget preview height in widget type autocomplete

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/stats/EdgeStatsService.java
- application/src/main/java/org/thingsboard/server/service/edqs/KafkaEdqsSyncService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/queue/DefaultTbQueueService.java
- application/src/main/java/org/thingsboard/server/service/ttl/KafkaEdgeTopicsCleanUpService.java
- application/src/test/java/org/thingsboard/server/service/edge/EdgeStatsTest.java
- application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
- common/cluster-api/src/main/java/org/thingsboard/server/queue/TbQueueAdmin.java
- common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java
- common/queue/src/main/java/org/thingsboard/server/queue/RuleEngineTbQueueAdminFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/KafkaAdmin.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaAdmin.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerStatisticConfig.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerStatsService.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaTopicConfigs.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryTbTransportQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/util/TbKafkaComponent.java
- common/queue/src/test/java/org/thingsboard/server/queue/kafka/TbKafkaSettingsTest.java
- common/util/src/main/java/org/thingsboard/common/util/CachedValue.java
After deleting a topic that has active producers, those producers get stuck waiting on metadata:
```
"integration-api-tb-core-consumer-67-thread-7" #182 prio=5 os_prio=0 cpu=4201.10ms elapsed=1030.78s tid=0x0000ffff4403b380 nid=0xc5 in Object.wait()  [0x0000ffff19ffd000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(java.base@17.0.15/Native Method)
- waiting on <no object reference available>
at org.apache.kafka.common.utils.SystemTime.waitObject(SystemTime.java:60)
- locked <0x0000000708338c38> (a org.apache.kafka.clients.producer.internals.ProducerMetadata)
at org.apache.kafka.clients.producer.internals.ProducerMetadata.awaitUpdate(ProducerMetadata.java:123)
- locked <0x0000000708338c38> (a org.apache.kafka.clients.producer.internals.ProducerMetadata) …
```
> Fix topics creation for isolated tenants

- application/src/test/java/org/thingsboard/server/controller/EdqsEntityQueryControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
> Fixed flaky edqs tests

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNodeConfiguration.java
Changes:
- Removed unnecessary executor service that was just doing `rs -> null`
> Save to custom table node: remove redundant executor per node

- pom.xml
PE build was failing due to the MQTT integrations module trying to fetch dependencies from the deprecated Sonatype repo, which responded with 501 Not Implemented. Maven Central is the default repository for Maven and no explicit repository configuration is needed.
Changes:
- Removed deprecated Sonatype repo configuration so Maven Central is used by default
> Remove deprecated Sonatype repo
