thingsboard/thingsboard

- application/src/main/scripts/windows/install.bat
- application/src/main/scripts/windows/uninstall.bat
- application/src/test/java/org/thingsboard/server/controller/AbstractControllerTest.java
- application/src/test/java/org/thingsboard/server/mqtt/AbstractFeatureIntegrationTest.java
- application/src/test/resources/thingsboard-test.properties
> TB-43: Disable check updates in test mode.

- ui/src/app/api/datasource.service.js
- ui/src/app/api/user.service.js
- ui/src/app/api/widget.service.js
- ui/src/app/components/widget.controller.js
MS Internet Explorer compatibility
> exception check (for IE)

- transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
Fix the message type of UnSubAck message
> fix the message type of UnSubAck message

- docker/cassandra/Dockerfile
- docker/cassandra/Makefile
- docker/cassandra/cassandra.yaml
- docker/cassandra/ready-probe.sh
- docker/tb-cassandra-schema/Makefile
- docker/zookeeper/Makefile
Added latest version into Makefile script
> Fixed cassandra image for kubernetes cluster

- application/src/main/scripts/install/install_dev_db.sh
- application/src/main/scripts/windows/install_dev_db.bat
these scripts are mentioned in an updated How To Contribute guide
> Development DB installation scripts added

- pom.xml
lombok.version ==> 1.16.18 updated to support jdk9 compiler
> support compile by java 9

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
Changed the RPC delete set from UUID to Integer to match what is stored as a key in the RPCPending Map
> Fix for Defect #394

- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/handlers/TelemetryRestMsgHandler.java
Prevents infinite (probably) loop if bogus interval is specified.
> Protect against bogus interval

- ui/src/app/locale/locale.constant.js
- ui/src/app/widget/lib/timeseries-table-widget.tpl.html
Moved 'pagination' down according to Andrew's remark.
> Additional improvements for widget "Timeseries - table"

- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/SubscriptionManager.java
- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/handlers/TelemetryRpcMsgHandler.java
- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/handlers/TelemetryWebsocketMsgHandler.java
- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/sub/Subscription.java
- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/telemetry/sub/SubscriptionState.java
- extensions-core/src/main/proto/telemetry.proto
For client-scope-attributes also shared-scope-attributes have been returning when saving extension.
> Bug: Device attributes

- ui/src/app/widget/lib/flot-widget.js
https://github.com/thingsboard/thingsboard/issues/488
> Fix for issue 488

- extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/mail/MailPlugin.java
Allows to add multiple e-mail recipients in TO, CC, BCC seperated by "," 
see https://groups.google.com/forum/#!searchin/thingsboard/attribute%7Csort:date/thingsboard/03V4Out1bgc/XVm9IswTEAAJ
> Update MailPlugin.java - allow multiple recipients

- application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
- ui/src/app/api/alias-controller.js
- ui/src/app/api/entity.service.js
- ui/src/app/device/device-card.tpl.html
Added Description on the device card and
Fixed ugly null pointer exception when there is no or incomplete root rule chain.
Make it go to an log entry instead.
> Description on the Device Card

- transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
Signed-off-by: Chun-Yeow Yeoh <yeohchunyeow@gmail.com>
> add missing API limits on CoAP POST method

- transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
> Add SUB ACK on topic v1/gateway/rpc

- ui/src/app/api/datasource.service.js
- ui/src/app/components/datakey-config.tpl.html
- ui/src/app/locale/locale.constant-en_US.json
Please, review changes very attentively. I have a fear that I could miss a testing of some rare cases.
> Added two additional parameters to post-processing function

- dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsServiceImpl.java
Hello @ashvayka,
Instead of saveOrUpdate, it is written saveOrUpdare. I made this minor fix.
Best,
Yusuf
> Typo fixed on saveOrUpdate method.

- application/src/main/resources/thingsboard.yml
Small fix to be able to setup intervals through environment variables
> Add ability to setup interval through env vars

- tools/src/main/java/org/thingsboard/client/tools/MqttSslClient.java
Reverts thingsboard/thingsboard#1123
> Revert "[WIP]Help refactor code solid patterns"

- ui/src/app/extension/extensions-forms/extension-form-modbus.directive.js
- ui/src/app/extension/extensions-forms/extension-form-modbus.tpl.html
- ui/src/app/locale/locale.constant-en_US.json
[Docs PR](https://github.com/thingsboard/thingsboard.github.io/pull/159) and [gateway implementation](https://github.com/thingsboard/thingsboard-gateway/pull/152).
>  'Reconnect' and 'RTU over TCP' options inTCP Modbus extension nfiguration

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttChannelHandler.java
- ui/src/app/extension/extensions-forms/extension-form-mqtt.tpl.html
This is a blocking issue fix for tb-gateway
> Fix NPE in Netty-mqtt client

- ui/src/app/widget/lib/map-widget2.js
As part of **CP-392** request from the Customer Portal
> improved polygon coordinates parser

- application/src/main/resources/thingsboard.yml
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportService.java
Reverts thingsboard/thingsboard#1642
> Revert "Added MQTT keep-alive parameter"

- pom.xml
updated version in order to let registration from more email domains proceed
> updated Apache validator

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/AbstractTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/SessionMetaData.java
Reverts thingsboard/thingsboard#1692
> Revert "#1686 no response to client side rpc via coap"

- ui/src/app/components/dashboard.directive.js
- ui/src/app/components/widget/widget-config.directive.js
- ui/src/app/components/widget/widget-config.tpl.html
- ui/src/app/components/widget/widget.controller.js
- ui/src/app/locale/locale.constant-de_DE.json
- ui/src/app/locale/locale.constant-en_US.json
- ui/src/app/locale/locale.constant-es_ES.json
- ui/src/app/locale/locale.constant-fr_FR.json
- ui/src/app/locale/locale.constant-it_IT.json
This allows hiding of widget timewindow settings to create customized views based on fixed interval and aggregation of timeseries data
> Allow widget timewindow hiding

- ui/src/app/components/json-form.directive.js
- ui/src/app/components/react/json-form-react.jsx
- ui/src/app/components/react/json-form-schema-form.jsx
- ui/src/app/components/react/json-form.scss
- ui/src/app/components/widget/widget-config.directive.js
- ui/src/app/components/widget/widget-config.tpl.html
- ui/src/app/widget/lib/map-widget2.js
Add the concept of groups to widget's Advanced Configurations which named "SchemaGroup" so that you don't get overwhelmed with configuration items.
> Add SchemaGroup so that it can be grouped when there are many configuration item

- ui/src/app/components/widget/action/custom-action-pretty-editor.directive.js
- ui/src/app/components/widget/action/custom-action-pretty-editor.scss
Fix fullscreen mode for HTML/CSS editors, highlight dividing comments for parts of the sample
> Fix fullscreen mode for HTML/CSS editors

- ui/src/app/components/dashboard.directive.js
- ui/src/app/components/dashboard.tpl.html
- ui/src/app/components/widget/widget-config.directive.js
- ui/src/app/components/widget/widget-config.tpl.html
- ui/src/app/locale/locale.constant-en_US.json
- ui/src/app/locale/locale.constant-es_ES.json
- ui/src/app/locale/locale.constant-fr_FR.json
- ui/src/app/locale/locale.constant-it_IT.json
An icon, with specified color and size selectable in widget configuration panel, can be added as a widget title prefix.
> Add optional icon before widget title

- ui/src/app/widget/lib/google-map.js
Change CDN URL (close RawGit CDN)
> Fix Google map widgets

- ui/src/app/api/attribute.service.js
Add params to delete all data from timeseries
> Fix method service delete timeseries data

- ui/src/app/locale/locale.constant-ru_RU.json
it will fix https://github.com/thingsboard/thingsboard/issues/2265
> fixed interpolation error

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/main/resources/thingsboard.yml
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
Added copy to view node logic for activity event integration, server scope for activity event message metadata
> Activity event support for Copy to view node added

- ui/package-lock.json
- ui/src/app/widget/lib/canvas-digital-gauge.js
On this case: when using animation on any digital gauge value arrived over 1 renewal;
> fixed: bug related to PROD-112, PROD-132

- ui/src/app/widget/lib/multiple-input-widget.js
Update field alignment on init, not only on resize; prevent displaying in a row, when fields should be displayed in a column
> Multiple Attributes: prevent displaying in a row, when fields should be displayed in a column

- ui/src/app/widget/lib/map-widget2.js
preserves previous data on map if no data for current date range received
> UI:fix. Map widget2

- tools/src/main/shell/client.keygen.sh
- tools/src/main/shell/server.keygen.sh
> tools/src/main/shell/*.sh: Fix "yes" patterns

- pom.xml
Reverts thingsboard/thingsboard#2719
> Revert "vulnerabilities"

- ui/src/app/widget/lib/canvas-digital-gauge.js
> [2.5.1]Digital gauge: fix data displaying in mobile browser

- application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
send ENTITY_CREATED event after creating new device from gateway request
> [2.5.1] DefaultTransportApiService improvements

- netty-mqtt/src/main/java/org/thingsboard/mqtt/RetransmissionHandler.java
Follow mqtt 3.1.1 protocol number 3.3.1-2 : The DUP flag MUST be set to 0 for all QoS 0 messages. If the qos of the publish message is not 0, then set dup to true
> Follow mqtt 3.1.1 protocol number 3.3.1-2

- ui/src/app/widget/widget-editor.scss
- ui/src/app/widget/widget-editor.tpl.html
> [2.5] Fixed problem widget-editor in Safari

- ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
Added missing messages and fixed few typo errors.
> Update Czech UI Translation

- common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueRequestTemplate.java
when responses is empty tickTs did not update
> fix DefaultTbQueueRequestTemplate

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/credentials/CertPemClientCredentials.java
close the stream after generateCertificate
> close the stream after generateCertificate

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbCheckAlarmStatusNode.java
Check the status of the alarm, fetched from the database, not the incoming message
> Fix Check alarm status

- ui-ngx/src/assets/locale/locale.constant-es_ES.json
> [3.0] Fixed not correct plural for the Spanish language

- application/src/main/resources/thingsboard.yml
- common/dao-api/src/main/java/org/thingsboard/server/dao/cassandra/AbstractCassandraCluster.java
- dao/src/test/resources/cassandra-test.properties
There's an [issue](https://github.com/thingsboard/thingsboard/issues/2941) connected to this change.
> Moved hardcoded local datacenter name to config

- ui-ngx/src/app/modules/home/components/widget/lib/rpc/led-indicator.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/rpc/round-switch.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/rpc/switch.component.ts
> [3.0] Fixed not correct call custom parseValueFunction in RPC widget

- ui-ngx/src/app/core/services/time.service.ts
New intervals:
30s - 5s
1m - 10s
2hours - 15m
7days - 1 day
> changed aggregation interval to 1/7

- ui-ngx/src/app/shared/components/json-object-edit.component.ts
fix bug beautifyJSON(), minifyJSON()
> fix buf Json edit

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
> [3.0] Alarm widget fix: shows the incorrect value from alarm details

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsAdmin.java
- common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsSettings.java
> enable default credential provider chain for aws sqs

- ui-ngx/src/app/core/http/entity.service.ts
> [3.0] Correction bulk provision without telemetry

- ui/src/app/common/utils.service.js
- ui/src/app/event/event-row.directive.js
- ui/src/app/rulechain/script/node-script-test.service.js
Display sorted metadata keys in rule node debug messages and test transformer function dialogs
> Display sorted metadata keys in rule nodes

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbOriginatorTypeFilterNodeConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbOriginatorTypeSwitchNode.java
Hello,
The user wasn't able to distinguish Alarm message in rule engine. Alarm option is added to switch nodes in rule engine which is described in #3317.
Best.
> [Feature] Alarm option for originator type in rule engine

- ui-ngx/src/app/modules/home/components/widget/dynamic-widget.component.ts
- ui-ngx/src/app/modules/home/models/services.map.ts
- ui-ngx/src/app/modules/home/models/widget-component.models.ts
- ui-ngx/src/app/shared/models/ace/service-completion.models.ts
> Added widget context import Router module

- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultAlarmQueryRepository.java
If the originator name is null we return 'Deleted'
> DefaultAlarmQueryRepository improvements

- ui-ngx/src/app/modules/home/pages/dashboard/dashboard-form.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
dashboard-form name validation fixed (used parent method, like in other entities), rule-chain-details name validation pattern and trim added
> empty string validation fix

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
removed unused ngZone.run and detectChanges, changed functions trackByRowIndex - now is used index, not id, minor improvements for functions, used after data updating.
> improved performance of table widgets

- ui-ngx/src/app/shared/components/entity/entity-select.component.ts
Fixed null id in entity-select component for aliasType CURRENT_TENANT, CURRENT_USER, CURRENT_USER_OWNER
> UI: Fixed null id in entity-select component 

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
Reverts thingsboard/thingsboard#3674
> Revert "alarm state improvements (added details to alarm from device profile …"

- ui-ngx/src/app/core/api/widget-subscription.ts
- ui-ngx/src/app/modules/home/components/widget/legend-config-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/legend-config-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/legend.component.ts
- ui-ngx/src/app/shared/models/widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> UI: Added new options for legend config (sort datakeys in legend)

- ui-ngx/src/app/modules/home/models/services.map.ts
BroadcastService is added to the map
> Additions: servicesMap

- docker/docker-compose.hybrid.yml
- docker/docker-compose.postgres.yml
for "postgres" and "hybrid" types of database setup
> Change docker-compose YAML files to use PostgreSQL version 12 image 

- application/src/main/java/org/thingsboard/server/service/script/RuleNodeJsScriptEngine.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/ScriptEngine.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/MultipleTbMsgsCallbackWrapper.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbAbstractTransformNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbMsgCallbackWrapper.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbTransformMsgNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbTransformMsgNodeTest.java
If array returns in transformation script node, it will send every element as separated message.
> Added ability to return arrays in transformation script node

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesFieldsAsyncLoader.java
> added EntityView type support

- ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
> [3.2.1] Fix map polygon

- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
Install with Вemo fix (revert of previous commit)
>  CassandraBaseTimeseriesDao init method fix (revert)

- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/map-models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget2.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/schemes.ts
- ui-ngx/src/app/modules/home/components/widget/trip-animation/trip-animation.component.ts
Trip Animation at the moment only displays a static color for the data points. This change is to provide the option to dynamically display color based on different parameters for each data point. Show Color Point function.
> Dynamic color for data points

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2MTransportServiceImpl.java
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-config-server.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-add-instances-list.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-add-instances.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-resource.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/profile-config.models.ts
> [WIP][3.3] Lwm2m cert

- ui-ngx/src/app/modules/home/components/entity/entity-details-panel.component.ts
> Fixed merge additional info at updated entity

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/credentials/CertPemCredentials.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/AzureIotHubSasCredentials.java
(cherry picked from commit 36ff1a8f9e853da7b5f1d0bf3e564b37ea0d92bc)
> fixed sas credentials in iot hub node

- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
> Fix of incorrect url for getTenantProfiles in REST Client

- dao/src/main/java/org/thingsboard/server/dao/sqlts/psql/JpaPsqlTimeseriesDao.java
reject old partitions save due to DataIntegrityViolationException
> [3.2.2] added fix for partitions save

- ui-ngx/src/app/core/utils.ts
> UI: Added the ability to get the value of a key that contains dots in the name to a table widgets

- dao/src/main/java/org/thingsboard/server/dao/sqlts/psql/JpaPsqlTimeseriesDao.java
reject old partitions save due to DataIntegrityViolationException
> [2.5.6] added fix for partitions save

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServerInitializer.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServiceImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientProfile.java
- pom.xml
LwM2M: Update Shared attribute
> Lwm2m:  back fix bug: shared attr & change observe in profile

- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
> Lwm2m bug key name

- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/AlarmConditionFilterKey.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/DurationAlarmConditionSpec.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/ProfileState.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNodeTest.java
- ui-ngx/src/app/modules/home/components/profile/alarm/alarm-rule-condition-dialog.component.html
- ui-ngx/src/app/modules/home/components/profile/alarm/alarm-rule-condition-dialog.component.ts
Implemented only duration condition
> PROD-577 Add dynamic duration support in Device profile alarm condition 

- application/src/main/java/org/thingsboard/server/controller/ResourceController.java
- application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ResourceService.java
- common/data/pom.xml
- common/data/src/main/java/org/thingsboard/server/common/data/Resource.java
- common/data/src/main/java/org/thingsboard/server/common/data/lwm2m/LwM2mObject.java
- dao/pom.xml
- dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/ResourceEntity.java
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
- dao/src/main/java/org/thingsboard/server/dao/resource/ResourceDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/resource/ResourceDaoImpl.java
- dao/src/main/java/org/thingsboard/server/dao/sql/resource/ResourceRepository.java
- dao/src/main/resources/sql/schema-entities-hsql.sql
- dao/src/main/resources/sql/schema-entities.sql
- ui-ngx/src/app/core/http/device-profile.service.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-add-instances-list.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-add-instances.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-add-instances.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/profile-config.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> lwm2m: add objectKeyId to back and front profile

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServiceImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
> lwm2m: back transport newKey fix bug object id=19

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServiceImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportResourceCache.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportResourceCache.java
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseTbResourceService.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseTbResourceServiceTest.java
> lwm2m: test model2

- common/data/src/main/java/org/thingsboard/server/common/data/lwm2m/LwM2mInstance.java
- common/data/src/main/java/org/thingsboard/server/common/data/lwm2m/LwM2mResourceObserve.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mSessionMsgListener.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServiceImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientProfile.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/ResourceValue.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/SessionMsgListener.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/lwm2m/LwM2MTransportConfigServer.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseTbResourceService.java
> lwm2m: notification in transport, add, update, del models

- application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseTbResourceControllerTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/lwm2m/LwM2MTransportConfigServer.java
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
back: /api//resource", method = RequestMethod.POST
> Lwm2m add resourses

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServiceImpl.java
back fix bug double "" in name
> lwm2m: back fix bug format name

- application/src/main/java/org/thingsboard/server/controller/RpcController.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/ProtoMqttAdaptor.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/adaptor/JsonConverter.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/adaptor/ProtoConverter.java
rollback previous fix for backward compatibility.
> Fixed RPC string params in protobuf payload type. Reverted changes from the previous fix

- ui-ngx/src/app/modules/home/components/widget/lib/rpc/switch.component.ts
> UI: Fixed switch control widget, didn't update state after get value in call RPC

- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
when make rule chain root in chinese，title display expression like '{{RuleChainName}}'
> Fixed title ex when make rule chain root in chinese

- application/src/main/java/org/thingsboard/server/config/WebConfig.java
> Fixed local environment variable resolve assets page 404

- ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
> UI: Fixed multiple datasource processing data in map widgets

- ui-ngx/src/app/modules/home/pages/edge/edge-routing.module.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
Changes:
1) edge-routing-module: added routes for rule chains from 'edge' scope
2) rulechain-component: refactored scopes
2) rulechains-table-config.resolver: refactored configureCellActions, openRuleChains
> UI: Edge rulechains: open from 'edge' scope

- application/src/main/resources/thingsboard.yml
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/CoapServerContext.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/DefaultCoapServerService.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapServerComponent.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportService.java
- common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
changes needed to be applied in CE for merging implementation of PE CoAP integration.
> refactored CoAP Server component

- application/src/main/java/org/thingsboard/server/actors/service/DefaultActorService.java
- application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/script/AbstractNashornJsInvokeService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetryWebSocketService.java
- application/src/main/java/org/thingsboard/server/service/transport/TbCoreTransportApiService.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueRequestTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueResponseTemplate.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportContext.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- common/util/src/main/java/org/thingsboard/common/util/AbstractListeningExecutor.java
- common/util/src/main/java/org/thingsboard/common/util/ThingsBoardExecutors.java
- common/util/src/main/java/org/thingsboard/common/util/ThingsBoardForkJoinWorkerThreadFactory.java
- dao/src/main/java/org/thingsboard/server/dao/util/AbstractBufferedRateExecutor.java
- rest-client/pom.xml
- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
The aim is to improve the thread analysis experience with JMX and thread dump under heavy load.
> Thread pool naming CE

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2MTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
> Lwm2m: add Write_Update example #1

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2MTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportHandlerUtil.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
> Lwm2m: add Write_Update many

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2MTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/Lwm2mClientRpcRequest.java
> Lwm2m: RPC finish

- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
> Lwm2m: fix bug add new instance

- application/src/main/resources/thingsboard.yml
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MBootstrapSecurityStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2MTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServerHelper.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportUtil.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/adaptors/LwM2MJsonAdaptor.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mFwSwUpdate.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mSecurityStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceProfileEntity.java
> Lwm2m: Fw/Sw updare with test successful/error

- common/queue/pom.xml
- pom.xml
an examples:
assertThat(inst.pollInterval, equalTo(pollInterval));
assertThat(inst.executor, is(executorMock));
assertThat(inst.stopped, is(false));
...
assertThat(i, greaterThanOrEqualTo(j);
The benefits are human-readable asserts like a natural language expression and awesome detailed output when the assertion fails. Especially for collections
> added hamcrest dependency to the test scope. The purpose is assertThat and various Matchers with advanced output

- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
> Lwm2m: fix bug claster

- ui-ngx/src/app/shared/components/snack-bar-component.html
- ui-ngx/src/app/shared/components/toast.directive.ts
> Fixed error message in Led Indicator

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2MTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mNetworkConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportUtil.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mFwSwUpdate.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStore.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
> LWM2M: del log warn

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2MTransportMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServerHelper.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportUtil.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mFwSwUpdate.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/Lwm2mClientRpcRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
Add logs and fix bug NullPoint
> LWM2M: add logs

- msa/js-executor/queue/kafkaTemplate.js
> Fix wrong configuration key for Compression Type

- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
- application/src/test/java/org/thingsboard/server/controller/BaseOtaPackageControllerTest.java
- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
saveOtaPackageData should return OtaPackageInfo
> OtaPackage improvements

- ui-ngx/src/app/core/services/menu.service.ts
- ui-ngx/src/app/modules/home/pages/customer/customer-routing.module.ts
- ui-ngx/src/app/modules/home/pages/customer/customers-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/dashboard/dashboards-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/edge/edge-routing.module.ts
- ui-ngx/src/app/modules/home/pages/edge/edges-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulenode.component.ts
Changes:
1) Edge instances separated from Edge management
2) Path 'edges' changed to 'edgeInstances' / 'edgeManagement'
> Edge: path and menu updates

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2mVersion.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mOperationType.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportUtil.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/HasContentFormat.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/HasVersionedIds.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/LwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MReadCompositeCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MReadCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MReadRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MTargetedCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MUplinkTargetedCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MWriteCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MWriteResponseCompositeCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/composite/AbstractTbLwM2MTargetedDownlinkCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/composite/TbLwM2MReadCompositeCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/composite/TbLwM2MReadCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/composite/TbLwM2MWriteCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/composite/TbLwM2MWriteResponseCompositeCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/IdOrKeyRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/RpcDownlinkRequestCallbackProxy.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/RpcReadResponseCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/composite/RpcLwM2MDownlinkCompositeCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/composite/RpcReadCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/composite/RpcReadResponseCompositeCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/composite/RpcWriteCompositeRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2MUplinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
Operation composite read/write
> Lwm2m: composite read/write

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/LwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
> Lwm2m write composite

- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-header.component.ts
- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- Added missing types;
- Updated translation;
- Added error handler;
- Refactored;
> Edge Downlinks updates

- ui-ngx/src/app/shared/components/time/timewindow-panel.component.html
- ui-ngx/src/app/shared/components/time/timewindow.component.ts
> UI: fix incorrect timewindow displaying

- pom.xml
this will fix the issue with os-maven-plugin version number (using parameter) and upgrade to the latest version
> os-maven-plugin.version fix and update

- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/AbstractOAuth2ClientMapper.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/dashboard/DashboardService.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardInfoDao.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/DashboardInfoRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/JpaDashboardInfoDao.java
find correct dashboard in case multiple dashboard start with the same name.
> Implement of method to find dashboard by name and tenantId

- pom.xml
- tools/src/main/java/org/thingsboard/client/tools/migrator/DictionaryParser.java
- tools/src/main/java/org/thingsboard/client/tools/migrator/RelatedEntitiesParser.java
CVE-2021-22118, CVE-2021-21409, CVE-2020-13956, CVE-2021-29425, CVE-2021-30640, CVE-2021-33037
> [3.3.1]fixed vulnerabilities

- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
when active settings: zoom on click and max clustering zoom
> [3.3.0] UI: Fixed not correct work clustering market showed spidery effect

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.ts
when activate settings update all values not save hidden keys
> [3.3.0] UI: Fixed bug multiple input widget

- ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
- fix typo in "home-settings" string translation
> Fixed Czech UI translation

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/LwM2MClientOtaInfo.java
fixed cases:
The device is updated but hasn`t sent update result "UPDATE_SUCCESSFULLY" ;
If we sent the wrong file.
> fw update improvements

- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/Oauth2AuthenticationSuccessHandler.java
Added logging of error msg to easily identify root cause of failed logins
> [3.3.0] Added logging of error msg to easily identify root cause of failed logins

- application/pom.xml
- pom.xml
I would like to introduce the easy and proper way to test async APIs. 
http://www.awaitility.org/
The Motivation is to make async API tests reliable and remove any Thread.sleep() in future.
Here the good awaitility guide https://www.baeldung.com/awaitlity-testing
```
@Test
public void updatesCustomerStatus() {
// Publish an asynchronous message to a broker (e.g. RabbitMQ):
messageBroker.publishMessage(updateCustomerStatusMessage);
// Awaitility lets you wait until the asynchronous operation completes:
await().atMost(5, SECONDS).until(customerStatusIsUpdated());
...
}
```
> [3.3.0] org.awaitility to test asynchronous API (test scope)

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
fixed race condition when the device sends "unRegister" command and server updates fetched lwm2m clients after the restart.
> fixed race condition during unreq

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MBootstrapConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MInMemoryBootstrapConfigurationAdapter.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MServerBootstrap.java
Bootstrap
- bug: client Client received  "Bad Request" after coonect with bootstrap server
> [WIP] Lwm2m: fix bug Bootstrap + Tests NoSec - ok

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/HasContentFormat.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MObserveRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MReadRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/composite/TbLwM2MReadCompositeRequest.java
> [WIP]Lwm2m content format

- ui-ngx/src/app/modules/home/components/widget/widget.component.ts
Fixed need duplicate id for correct work action - elementClick
> [3.3.0] UI: Fixed widget action element click - not correct processing propagation event

- ui-ngx/src/app/modules/home/components/entity/contact-based.component.ts
- ui-ngx/src/app/modules/home/components/entity/entity.component.ts
- ui-ngx/src/app/modules/home/components/profile/device-profile.component.ts
- ui-ngx/src/app/modules/home/components/profile/tenant-profile.component.ts
- ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
- ui-ngx/src/app/modules/home/pages/asset/asset.component.ts
- ui-ngx/src/app/modules/home/pages/customer/customer.component.ts
- ui-ngx/src/app/modules/home/pages/dashboard/dashboard-form.component.ts
- ui-ngx/src/app/modules/home/pages/device/device.component.ts
- ui-ngx/src/app/modules/home/pages/edge/edge.component.ts
- ui-ngx/src/app/modules/home/pages/entity-view/entity-view.component.ts
- ui-ngx/src/app/modules/home/pages/ota-update/ota-update.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain.component.ts
- ui-ngx/src/app/modules/home/pages/tenant/tenant.component.ts
- ui-ngx/src/app/modules/home/pages/user/user.component.ts
- ui-ngx/src/app/modules/home/pages/widget/widgets-bundle.component.ts
Fixed incorrect work of the asset menu when the user is active / inactive edit mod.
> [3.3.0] Fixed asset disappears menu

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MBootstrapSecurityStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MInMemoryBootstrapConfigStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MServerBootstrap.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2mDefaultBootstrapSessionManager.java
Leshan, leshan-core M4, bootstrap
> Lwm2m fix bug sec bootstrap (ver 1.1)

- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
- application/src/main/java/org/thingsboard/server/service/lwm2m/LwM2MServerSecurityInfoRepository.java
- common/data/src/main/java/org/thingsboard/server/common/data/security/DeviceCredentials.java
Valiidate security Key: RPK and X509
> Lwm2m: Device validate securityKey

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mOperationType.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/LwM2mDownlinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MCreateRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MCreateResponseCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/RpcCreateRequest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/RpcCreateResponseCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2MUplinkMsgHandler.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
> Lwm2m: operation Create

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/attributes/DefaultLwM2MAttributesService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/attributes/LwM2MAttributesService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MTargetedCallback.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2MUplinkMsgHandler.java
old msg Error:
- "error: Failed update resource versionedId - /19_1.0/1/0 value - 11aa. Value is not changed or bad"
new msg:
- if newValue==oldValue - "info" && if update Attributes or new registration
- if bad (newValue==null) - "error"
> [3.3.1]Lwm2m: fix bug log after update resource

- ui-ngx/src/app/modules/home/components/device/device-credentials-mqtt-basic.component.ts
> [3.3.1] UI: Added support for UTF-8 characters in MQTT credential Client ID

- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/service/edge/DefaultEdgeLicenseService.java
- application/src/main/java/org/thingsboard/server/service/edge/EdgeLicenseService.java
- common/dao-api/pom.xml
- common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeService.java
- dao/src/main/java/org/thingsboard/server/dao/edge/EdgeServiceImpl.java
Refactoring: 
- Introduced Edge License service. 
- Remove spring-web dependency from dao
> [3.3.1] Refactoring: Introduced Edge License service & remove spring-web dependency 

- dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
> [3.3.1]Fixed has not been used property SECURITY_USER_LOGIN_CASE_SENSITIVE on password recover

- application/pom.xml
- common/actor/pom.xml
- common/cache/pom.xml
- common/dao-api/pom.xml
- common/data/pom.xml
- common/message/pom.xml
- common/queue/pom.xml
- common/stats/pom.xml
- common/transport/coap/pom.xml
- common/transport/http/pom.xml
- common/transport/lwm2m/pom.xml
- common/transport/mqtt/pom.xml
- common/transport/transport-api/pom.xml
- common/util/pom.xml
- dao/pom.xml
- msa/black-box-tests/pom.xml
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
- pom.xml
- rule-engine/rule-engine-api/pom.xml
- rule-engine/rule-engine-components/pom.xml
- transport/coap/pom.xml
- transport/http/pom.xml
- transport/lwm2m/pom.xml
- transport/mqtt/pom.xml
[3.3.1] Dependency upgrade - testcontainers
The branch was checked out from  https://github.com/thingsboard/thingsboard/pull/5045
`~/thingsboard/msa/black-box-tests$ mvn clean install -DblackBoxTests.skip=false`
> [3.3.1] Testcontainers - dependency upgrade

- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
- ui-ngx/src/app/shared/models/alias.models.ts
'Entity group list' and 'Entity group name' alias are hidden due to recent changes.
Moved check of edgesEnabled to correct place
> [Bug] Fixed alias issue due to edgesEnabled changes

- ui-ngx/src/app/modules/home/components/widget/lib/markdown-widget.component.ts
> [3.2.2] Fix custom translation for markdown card

- ui-ngx/src/app/modules/home/components/filter/key-filter-list.component.html
> [3.2.2] Alarm rules fix translation key type after updating key filter

- ui-ngx/src/app/modules/home/pages/profile/profile.component.html
- ui-ngx/src/app/modules/home/pages/profile/profile.component.scss
- ui-ngx/src/app/modules/home/pages/profile/profile.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-ru_RU.json
- ui-ngx/src/assets/locale/locale.constant-uk_UA.json
> [3.3.2] Add button Copy JWT token to profile

- rest-client/src/main/java/org/thingsboard/rest/client/utils/RestJsonConverter.java
A commit to fix an issue in the Rest Client to be able to parse JSON array values for attributes and time-series.
Currently, it throws a RuntimeException(Can't parse value...)
> [3.3.2] Fixed rest json converter to parse json array

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportCoapResource.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
fix bug info if first update Fw/Sw - failed
> [3.3.2]lwm2m - fix bug info if first update Fw/Sw - failed

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2mDefaultBootstrapSessionManager.java
> lwm2m - authorization in Bootstrap session

- application/src/main/java/org/thingsboard/server/service/lwm2m/LwM2MServiceImpl.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/data/lwm2m/BootstrapConfiguration.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/AbstractServerCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/NoSecServerCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/PSKServerCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/RPKServerCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/ServerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/ServerCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/X509ServerCredentials.java
- common/data/src/main/java/org/thingsboard/server/common/data/lwm2m/ServerSecurityConfig.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
- validate credentials lwm2m profile base64
> [3.3.3] Lwm2m profile bootstrap base64

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/geo/GeoUtil.java
According to the documentation any polygon must be defined as json array with the next format:
[[1CoordinateLatitude,1CoordinateLongitude],[2CoordinateLatitude,2CoordinateLongitude]...[nCoordinateLatitude,nCoordinateLongitude]] where n - number of coordinates which polygon is described by.
After moving points of polygon we receive updated representation of polygon [[[...], [...], [...]]].
As a result - exception on trying to pull out double coordinates as they contain in the array one level deeper.
`java.lang.IllegalStateExceptionat com.google.gson.JsonArray.getAsDouble(JsonArray.java:231)at 
org.thingsboard.rule.engine.geo.GeoUtil.contains(GeoUtil.java:69)at org.thingsboard.rule.engine.geo.AbstractGeofencingNode.checkMatches(AbstractGeofencingNode.java:89)at …
> [3.3.2] Fix exception after moving polygon point on widget

- dao/src/main/java/org/thingsboard/server/dao/sql/relation/JpaRelationDao.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseRelationServiceTest.java
Fixing the issue on the screenshot. Added test.
> [3.3.2] fixed concurrency exception when deleting relation

- application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
- application/src/main/java/org/thingsboard/server/service/install/update/CacheCleanupService.java
- application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
version upgrade: cleanup caches that can not deserialize anymore due to schema upgrade or data update using SQL scripts.
> version upgrade: cache cleanup service added to clear caches that can not deserialize anymore due to schema upgrade

- application/src/main/java/org/thingsboard/server/controller/AssetController.java
> [3.3.3] Lwm2m fix bug api

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
If are connecting new LwM2M clients and at the same time is invoking method getClientBySessionInfo (are sending RPC) the session id  in new LwM2MClient is null
> [3.3.3] fixed NPE

- application/src/main/data/upgrade/3.3.2/schema_update_lwm2m_bootstrap.sql
- application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
- application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
- Updating  device profile profile_data transport_type==LWM2M...
- - mode PSK & NO_SEC - old
- - mode RPK & X509 - server`s public key from HexDec to Base64
- - bootstrap section device profile profile - refactoring to list lwm2m & bootstrap servsers
- Updating  device credentials transport_type==LWM2M...
- - mode PSK & NO_SEC - old
- - mode RPK & X509 -client`s public key and secret key from HexDec to Base64
> [3.3.3] Lwm2m script

- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/secure/TbLwM2MDtlsCertificateVerifier.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/AbstractSslCredentials.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/SslCredentials.java
- add connect client with trust certificate
> [3.3.3] lwm2m - trust Certificate

- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.scss
> [3.3.3] UI: Fix setting layout for Firefox

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/OtaLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapSecurityStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MConfigurationChecker.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MInMemoryBootstrapConfigStore.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
> [3.3.3] lwm2m - includes bootstrap update

- application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
- application/src/main/java/org/thingsboard/server/service/lwm2m/LwM2MServiceImpl.java
- application/src/main/resources/thingsboard.yml
- application/src/test/resources/application-test.properties
- common/queue/src/main/java/org/thingsboard/server/queue/util/TbLwM2mBootstrapTransportComponent.java
- common/queue/src/main/java/org/thingsboard/server/queue/util/TbLwM2mTransportComponent.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapSecurityStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MInMemoryBootstrapConfigStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportBootstrapConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/adaptors/LwM2MJsonAdaptor.java
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- fix bug credentials if bootstrap.enabled = false or lwm2m.enabled = false in *.yml
> [3.3.3] lwm2m - fix bug credentials

- ui-ngx/src/app/shared/components/json-form/json-form.component.html
- ui-ngx/src/app/shared/components/json-form/json-form.component.ts
- ui-ngx/src/app/shared/components/json-form/react/json-form-ace-editor.tsx
- ui-ngx/src/app/shared/components/json-form/react/json-form-schema-form.tsx
- ui-ngx/src/app/shared/components/json-form/react/json-form.models.ts
> [3.3.3] UI: Fixed incorrect work buttons in fullscreen mode at json-form

- application/src/main/resources/thingsboard.yml
Cache specs environments for CE added to enable setup through environment variables.
Default values were left intact.
> Cache specs environments for CE

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapConfigStoreTaskProvider.java
- if error BootstrapRead - update without find Server ID
> lwm2m: BootstrapRead_fix_bug

- application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
edge test refactor to assign an alias for each assert
> [3.3.3] edge test refactor to assign alias for many asserts

- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/SubscriptionManagerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
- application/src/main/java/org/thingsboard/server/service/telemetry/AbstractSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
- common/cluster-api/src/main/proto/queue.proto
- common/dao-api/src/main/java/org/thingsboard/server/dao/timeseries/TimeseriesService.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/BaseDeleteTsKvQuery.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/TsKvLatestRemovingResult.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesLatestDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/TimeseriesLatestDao.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineTelemetryService.java
- ui-ngx/src/app/modules/home/models/datasource/attribute-datasource.ts
added WS notifications if the latest ts has been deleted or rewritten after removing ts
> [3.3.3] ts latest notifications

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfigService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfigServiceImpl.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbDummyLwM2MModelConfigStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2MModelConfigStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mStoreFactory.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbRedisLwM2MModelConfigStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2MUplinkMsgHandler.java
- common/util/src/main/java/org/thingsboard/common/util/CollectionsUtil.java
- common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
sending read and observe requests after sleeping
> [3.3.3] added ability to send lwm2m model updates after sleeping

- pom.xml
netty version upgrade from 4.1.71.Final to the latest 4.1.72.Final
> [3.3.3] netty version upgrade from 4.1.71.Final to the latest 4.1.72.Final

- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
In Api Usage module,when use chinese ,there are some display problem
because of the lose of the translate items
> fix(chinese translate): fix some display problem

- ui-ngx/src/app/modules/home/components/widget/legend.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
> [3.3.3] UI: Show legend fieldset only in timeseries and latest widget

- application/src/main/data/upgrade/3.3.2/schema_update_lwm2m_bootstrap.sql
- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
- application/src/main/java/org/thingsboard/server/service/lwm2m/LwM2MServiceImpl.java
- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/LwM2MServerSecurityConfig.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-config-server.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
- add loadSql for schema_update_lwm2m_bootstrap.sql
- if securityMode==null in profile? securityMode="NO_SEC"
> [3.3.3] lwm2m fix bug update release

- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/map-models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/google-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/here-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/openstreet-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/tencent-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/schemes.ts
> [3.3.3] UI: Add map new settings - "Disable zoom control" and fix disable edit buttons

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2MBootstrapConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/LwM2mDefaultBootstrapSessionManager.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/TbLwM2MDtlsBootstrapCertificateVerifier.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/store/LwM2MBootstrapSecurityStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/secure/LwM2mCredentialsSecurityInfoValidator.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mSecurityStore.java
-  add verify trust certificate to bootstrap mode
> [3.3.3] lwm2m: add verify trust certificate to bootstrap

- application/src/main/java/org/thingsboard/server/service/stats/DefaultRuleEngineStatisticsService.java
- common/message/src/main/java/org/thingsboard/server/common/msg/queue/RuleEngineException.java
> Fix for Bug #5931

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/NumericParseException.java
If we set for the device the profile with rules which use duration or repeating (dynamic value) and the attribute in the source is not int, we will get NPE.
> [3.3.3] fixed NPE in AlarmRuleState

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/AbstractSyncSessionCallback.java
- common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewayDeviceSessionCtx.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/SessionMsgListener.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttGatewayClientTest.java
This PR contains changes to close existing session between device and ThingsBoard if device was removed on UI.
> [3.3.3]Fix for PROD-1337 (Device session doesn't close on device removal)

- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
added to hint create entity tooltip - entity name
> [3.3.3] UI: Add map widget - disable edit or remove control button

- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- application/src/test/java/org/thingsboard/server/rules/flow/AbstractRuleEngineFlowIntegrationTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChainMetaData.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
> Automatic conversion of rule chain metadata for compatibility with 3.3.2-

- application/src/main/java/org/thingsboard/server/service/security/permission/CustomerUserPermissions.java
- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/sql/AlarmControllerSqlTest.java
Issue: [#5836](https://github.com/thingsboard/thingsboard/issues/5836)
Previously, `tenantEntityPermissionChecker` was used to check permissions for alerts, which simply checked for equality of tenant IDs.
The problem is that user and entity must either be in the same `customer` hierarchy (has same _customerId_)
Added new `customerAlarmPermissionChecker` with those checking steps:
1. check that customer and entity is in the one hierarchy (has same _tenantId_)
2. check that entity has the _customerId_
3. check that user and entity is in the same `customer` hierarchy (simply - the equality of _customerId_'s)
Was made a simple refactor of other _customerPermissionChecker_'s
> [3.3.4] Customer alarm permission checker fix

- application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/AbstractCoapAttributesUpdatesIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/AbstractCoapAttributesUpdatesProtoIntegrationTest.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/6241
- Befor test UpdateAttributes:
```
- int expectedObserveCnt = callback.getObserve().intValue() + 1;
- validateUpdateAttributesResponse(callback, expectedObserveCnt);
```
- Befor test DeleteAttributes:
```
- int expectedObserveBeforeDeleteCnt = callback.getObserve().intValue() + 1;
- validateDeleteAttributesResponse(callback, expectedObserveBeforeDeleteCnt);
```
- After test add method **awaitClientAfterCancelObserve**
> [3.4] Сoap fix bug test3

- application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEdgeEventControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- application/src/test/java/org/thingsboard/server/system/BaseHttpDeviceApiTest.java
- application/src/test/java/org/thingsboard/server/transport/coap/AbstractCoapIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/AbstractMqttIntegrationTest.java
- application/src/test/resources/application-test.properties
Test speed up disabling transport and edge for most of the tests.
Issue: https://github.com/thingsboard/thingsboard/issues/6416
PE: https://github.com/thingsboard/thingsboard-pe/pull/821
> [3.4] Test speed up: transport, edge

- application/src/test/java/org/thingsboard/server/controller/AbstractInMemoryStorageTest.java
- application/src/test/java/org/thingsboard/server/controller/ControllerSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/edge/EdgeSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/rules/RuleEngineSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/rules/lifecycle/AbstractRuleEngineLifecycleIntegrationTest.java
- application/src/test/java/org/thingsboard/server/service/ServiceSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/system/SystemSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/transport/TransportNoSqlTestSuite.java
- application/src/test/java/org/thingsboard/server/transport/TransportSqlTestSuite.java
- common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryStorage.java
- common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryTbQueueConsumer.java
- common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryTbQueueProducer.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryTbTransportQueueFactory.java
- common/queue/src/test/java/org/thingsboard/server/queue/memory/InMemoryStorageTest.java
InMemoryStorage refactored from the static singleton to the Spring Bean.
The motivation is to isolate tests. Because the in-memory queue storage was implemented as a static singleton the tests have to clean up the map all the time and potentially may affect other tests making it fluky.
Issue: https://github.com/thingsboard/thingsboard/issues/6413
PE: https://github.com/thingsboard/thingsboard-pe/pull/820
> [3.4] InMemoryStorage refactored from the static singleton to the Spring Bean

- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultQueryLogComponent.java
- dao/src/test/java/org/thingsboard/server/dao/sql/query/DefaultQueryLogComponentTest.java
Issue: #6358
Developing a method that returns a SQL query string with parameters
> [3.4]  Query log: add SQL string with parameters in logs

- application/src/main/data/json/tenant/edge_management/rule_chains/edge_root_rule_chain.json
Updated default edge root rule chain to handle Attributes Deleted, Timeseries Deleted, Timeseries Updated messages by default.
Related to https://github.com/thingsboard/thingsboard/issues/6443
Updated default edge root rule chain to handle additional message types.
> [3.4] Updated default edge root rule chain

- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
This fixes the issue https://thingsboard-portal.atlassian.net/browse/PROD-1470
`consumes = MediaType.MULTIPART_FORM_DATA_VALUE`
`@RequestPart MultipartFile file`
> [3.4] fix bug: OtaPackege_Upload binary file_swagger

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/service/edge/DefaultEdgeNotificationService.java
- application/src/main/java/org/thingsboard/server/service/edge/EdgeNotificationService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/AlarmEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/CustomerEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/DeviceEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/EdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/EntityEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RelationEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/edge/BaseEdgeTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeEventService.java
- dao/src/main/java/org/thingsboard/server/dao/edge/BaseEdgeEventService.java
- dao/src/main/java/org/thingsboard/server/dao/edge/EdgeEventDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeEventInsertRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseEdgeEventServiceTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNode.java
Performance improvements - save edge event method make async.
No updates to the documentation are required.
https://github.com/thingsboard/thingsboard/issues/6454
> [3.4] Make save edge event method async

- common/queue/src/main/java/org/thingsboard/server/queue/memory/DefaultInMemoryStorage.java
- common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryStorage.java
- common/queue/src/test/java/org/thingsboard/server/queue/memory/DefaultInMemoryStorageTest.java
InMemoryStorage interface extracted.
Method `storage.get()` optimized. 
A bunch of tests was added since it is an essential piece of code.
Issue: https://github.com/thingsboard/thingsboard/issues/6413
PE: https://github.com/thingsboard/thingsboard-pe/pull/824
> [3.4] In memory storage improvements

- application/src/main/java/org/thingsboard/server/controller/CustomerController.java
- application/src/main/java/org/thingsboard/server/service/entitiy/DefaultTbNotificationEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/TbNotificationEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/customer/DefaultTbCustomerService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/customer/TbCustomerService.java
> [3.4] refactoring_02: - Customer controller

- ui-ngx/src/app/core/api/alias-controller.ts
- ui-ngx/src/app/core/api/widget-api.models.ts
- ui-ngx/src/app/core/api/widget-subscription.ts
- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget2.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/markdown-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget.component.ts
- ui-ngx/src/app/shared/models/widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Add new **Maximum entities per datasource**  parameter in the **Data settings** of widget configuration.
This allows to configure page size of widget subscription instead of using previously hardcoded value (1024).
See issue #6403.
> [3.4] Add 'Maximum entities per datasource' parameter to widget configuration

- application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/EntitiesExportImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/LocalGitVersionControlService.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitVersionControlService.java
> Refactor loadEntitiesVersion

- application/src/main/java/org/thingsboard/server/controller/EntitiesVersionControlController.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/LocalGitVersionControlService.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityImportResult.java
> Fixes for vc api

- application/src/main/java/org/thingsboard/server/controller/CustomerController.java
- application/src/main/java/org/thingsboard/server/controller/DashboardController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
- application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
- application/src/main/java/org/thingsboard/server/service/entitiy/AbstractTbEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/DefaultTbNotificationEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/SimpleTbEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/TbNotificationEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/customer/DefaultTbCustomerService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DefaultTbDashboardService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/deviceProfile/DefaultTbDeviceProfileService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/deviceProfile/TbDeviceProfileService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/entityRelation/DefaultTbEntityRelationService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/entityRelation/TbEntityRelationService.java
> [3.4] Refactoring: 05 device profile controller, 06 entity relation controller

- ui-ngx/src/app/modules/common/modules-map.ts
- ui-ngx/src/app/shared/models/settings.models.ts
Merge with: [#869](https://github.com/thingsboard/thingsboard-pe/pull/869)
Fix for build.
> [3.4] UI: Fixed build project

- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttChannelHandler.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
fix: typo fix in the variable name and method name v3.4 . renamed **subscribtion** to **subscription**
> [3.4] fix: typo fix in variable name and method name

- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/CustomerImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
> Fix import of public customer

- application/src/main/resources/thingsboard.yml
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/CoapServerContext.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/CoapServerService.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/DefaultCoapServerService.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
- transport/coap/src/main/resources/tb-coap-transport.yml
- Use coap piggybacked responses if possible
- Introduces a new `piggyback_timeout` config parameter
- Implements #1450
Please let me know if you see any issues with the way this is implemented.
> [3.4] Piggybacked CoAP responses

- application/src/test/java/org/thingsboard/server/service/cluster/routing/HashPartitionServiceTest.java
- common/message/src/test/java/org/thingsboard/server/common/msg/tools/RateLimitsTest.java
> [3.4] fixed tests

- application/src/main/java/org/thingsboard/server/service/sync/vc/TbAbstractVersionControlSettingsService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/settings/AdminSettingsService.java
- dao/src/main/java/org/thingsboard/server/dao/settings/AdminSettingsServiceImpl.java
> Fix AdminSettings api

- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
Issue: https://github.com/thingsboard/thingsboard/issues/6321
> [3.4] UI: Bug in zooming of the Image Map 

- ui-ngx/src/app/shared/components/directives/tb-json-to-string.directive.ts
- ui-ngx/src/app/shared/components/json-object-edit.component.ts
- ui-ngx/src/app/shared/models/constants.ts
Issue  https://github.com/thingsboard/thingsboard/issues/6423
JSON editor 
Before:
After: 
JSON input + add icon  
Before:
After:
> [3.4] UI: Fix validation logic for JSON

- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
Issue: [#6550](https://github.com/thingsboard/thingsboard/issues/6550)
Fix for Exit Guard.
> [3.4] UI: Add seter isDirty for rulechain page

- ui-ngx/src/app/core/services/menu.service.ts
- ui-ngx/src/app/modules/home/components/profile/tenant-profile-data.component.ts
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.scss
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.ts
- ui-ngx/src/app/modules/home/pages/admin/queue/queues-table-config.resolver.ts
- ui-ngx/src/app/shared/models/queue.models.ts
Fix:
1. Add height for the side nav menu.
2. Add translation for queues table cell settings.
3. Add a fixed header for the expansion panel.
4. Fixed description for default created queues.
> [3.4] UI: Improvement for queues

- application/src/main/data/upgrade/3.3.4/schema_update.sql
- application/src/main/java/org/thingsboard/server/controller/EntitiesVersionControlController.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/DefaultExportableEntitiesService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/ExportableEntitiesService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/WidgetsBundleExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/WidgetsBundleImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/JsonTbEntity.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/WidgetsBundleExportData.java
- common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetsBundle.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetsBundleEntity.java
- dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetsBundleDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetsBundleRepository.java
- dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleDao.java
- dao/src/main/resources/sql/schema-entities.sql
> Widgets Bundles VC

- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
> [3.4] fixing slow queries logging

- application/src/main/data/upgrade/3.3.4/schema_update.sql
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/TbAbstractVersionControlSettingsService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/data/PendingGitRequest.java
- application/src/main/resources/thingsboard.yml
- common/dao-api/src/main/java/org/thingsboard/server/dao/settings/AdminSettingsService.java
- dao/src/main/java/org/thingsboard/server/dao/settings/AdminSettingsDao.java
- dao/src/main/java/org/thingsboard/server/dao/settings/AdminSettingsServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/sql/settings/AdminSettingsRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/settings/JpaAdminSettingsDao.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
- dao/src/main/resources/sql/schema-entities-idx.sql
- VC requests timeout
- indexes for externalId
> VC improvements

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNodeTest.java
> [3.4] fixed device profile node

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
Issue: [#6691](https://github.com/thingsboard/thingsboard/issues/6691)
Bugs: 
1. "alarm filter" applies only to the selected page, not the entire widget.
Fix: After updating alarm filter set pageIndex to zero for switch pagination to the first page.
2. alarm widget table breaks when alarm sources entity with the same key name as alarm key filed.
Fix: check if alarm status contains value.
> [3.4] UI: Bug fix of alarm widget table

- application/src/main/data/upgrade/3.3.4/schema_update.sql
- application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/EntityViewImportService.java
- common/data/src/main/java/org/thingsboard/server/common/data/EntityView.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/JsonTbEntity.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewDao.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/AbstractEntityViewEntity.java
- dao/src/main/java/org/thingsboard/server/dao/sql/entityview/EntityViewRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/entityview/JpaEntityViewDao.java
- dao/src/main/resources/sql/schema-entities.sql
- ui-ngx/src/app/shared/models/entity-view.models.ts
- ui-ngx/src/app/shared/models/vc.models.ts
> Entity views VC

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
Tests for checking availability of alarms, which have been created by customer user, for the parent customer/tenant
> [3.4] Tests for Alarms availability with users hierarchy

- application/src/main/resources/thingsboard.yml
- common/dao-api/src/main/java/org/thingsboard/server/dao/util/PsqlDao.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/util/PsqlTsLatestAnyDao.java
- dao/src/test/resources/nosql-test.properties
- dao/src/test/resources/sql-test.properties
- docker/tb-node.hybrid.env
- docker/tb-node.postgres.env
- msa/tb/docker-cassandra/Dockerfile
- msa/tb/docker-postgres/Dockerfile
> switch to PostgreSQL10Dialect

- msa/tb-node/docker/Dockerfile
- msa/transport/coap/docker/Dockerfile
- msa/transport/http/docker/Dockerfile
- msa/transport/lwm2m/docker/Dockerfile
- msa/transport/mqtt/docker/Dockerfile
- msa/transport/snmp/docker/Dockerfile
Update Dockerfiles to run commands in a single RUN sentence.
By performing actions in a single RUN, we lower the amount of image layers to use, and Docker image size is lower.
This fixes #6189 .
> [3.4] Optimize Dockerfiles

- msa/js-executor/package.json
- msa/web-ui/package.json
Update the node version in pkg script to be similarly for run time version
> [3.4] UI: Updated version node in pkg script

- application/src/main/java/org/thingsboard/server/service/security/auth/mfa/provider/impl/SmsTwoFaProvider.java
- application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
> VC tests refactoring

- ui-ngx/src/app/modules/home/models/widget-component.models.ts
Drawback: vendor bundler size increase.
```
Initial Chunk Files               | Names         |      Size
vendor.529bc55e40ba67c42b69.js    | vendor        |   2.76 MB
main.a8f72f0ed45b1ba29af3.js      | main          |   2.04 MB
styles.097e0ff43da1e5b59598.css   | styles        | 331.69 kB
scripts.aa32bdcef15ae395bc85.js   | scripts       | 111.25 kB
polyfills.f5a6e99e120e997de594.js | polyfills     |  68.19 kB
runtime.c540d987c0c6366ee0e0.js   | runtime       |   4.86 kB
| Initial Total |   5.31 MB
Initial Chunk Files               | Names         |      Size
vendor.8dde6cf4666e84dc8dc0.js    | vendor        |   2.80 MB
main.33494b9003a09b2add6d.js      | main          |   2.04 MB
styles.097e0ff43da1e5b59598.css   | styles        | 331.69 kB
scripts.aa32bdcef15ae395bc85.js   | scripts …
```
> [3.4] UI: Export all RxJS API into custom widget context

- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
- ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-header.component.ts
Incorrect pagination for edge downlink table:
https://github.com/thingsboard/thingsboard/issues/6514
> [3.4] [UI] Bug/edge fixed downlink table

- msa/js-executor/api/jsInvokeMessageProcessor.js
Fixed #6767.
Logs were extended at compile time.
Changed the logic of deleting script from the cache: before used FIFO method, after delete with the lowest call frequency
> [3.4] JS-executor: Improvement logs and clear cache

- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed incorrect label in tenant profile
> [3.4] UI: Fixed incorrect label in tenant profile

- ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-table.component.ts
> [3.4] UI: Fixed permission check in show alarm details

- application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
> [3.4] Swagger dashboard api typo fix

- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Compression type added for transports yaml
https://github.com/thingsboard/thingsboard/issues/6667
https://github.com/thingsboard/thingsboard-pe/pull/888
> [3.4] Compression type added for transports yaml

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
Issue: https://github.com/thingsboard/thingsboard/issues/6421
> [3.4] Fix NPE in 'copy to view' node

- msa/js-executor/queue/kafkaTemplate.js
…
This prevents the warning message on startup.
as mentioned in [migration notes for the major kafka.js 2.0](https://kafka.js.org/docs/migration-guide-v2.0.0)
Details and performance tests: https://github.com/thingsboard/thingsboard/issues/6750#issuecomment-1159402570
PE: https://github.com/thingsboard/thingsboard-pe/pull/934
> [3.4] js-executor: kafkaClient.producer({ createPartitioner: Partitioners.DefaultPartitioner }) 

- msa/tb/docker-cassandra/Dockerfile
- msa/tb/docker-postgres/Dockerfile
; rm -rf /var/lib/apt/lists/* ; apt-get purge -y --auto-remove
This PR reduces the size of Docker images. The idea appears around the [official Dockerfile for Postgresql](https://github.com/docker-library/postgres/blob/master/Dockerfile-debian.template)
PE: those files are not present in PE
> [3.4] Dockerfile optimization: --no-install-recommends 

- ui-ngx/src/app/core/api/widget-subscription.ts
- ui-ngx/src/app/modules/home/components/widget/legend-config.component.html
- ui-ngx/src/app/modules/home/components/widget/legend-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/legend.component.html
- ui-ngx/src/app/modules/home/components/widget/legend.component.ts
- ui-ngx/src/app/shared/models/widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added option to widget's legend configuration to show latest value.
> [3.4] UI: Add option to show latest value in widget's legend.

- application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
- application/src/main/java/org/thingsboard/server/controller/EntitiesVersionControlController.java
> Version control Swagger docs

- docker/docker-compose.aws-sqs.yml
> [3.4] docker-compose: fixed tb-vc-executor for queue-aws-sqs

- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
- application/src/main/resources/thingsboard.yml
- common/cluster-api/src/main/proto/queue.proto
- common/data/src/main/java/org/thingsboard/server/common/data/StringUtils.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/EntityDataDiff.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/VersionedEntityInfo.java
- common/util/src/main/java/org/thingsboard/common/util/CollectionsUtil.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/PendingCommit.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- ui-ngx/src/app/shared/models/vc.models.ts
> [3.4] VC queue message chunking

- ui-ngx/src/app/core/http/entities-version-control.service.ts
- ui-ngx/src/app/modules/home/components/vc/auto-commit-settings.component.html
- ui-ngx/src/app/modules/home/components/vc/auto-commit-settings.component.scss
- ui-ngx/src/app/modules/home/components/vc/complex-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/complex-version-create.component.ts
- ui-ngx/src/app/modules/home/components/vc/complex-version-load.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.scss
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.scss
- ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.ts
- ui-ngx/src/app/modules/home/components/vc/entity-version-diff.component.scss
- ui-ngx/src/app/modules/home/components/vc/entity-version-diff.component.ts
- ui-ngx/src/app/modules/home/components/vc/entity-version-restore.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.ts
- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.scss
- ui-ngx/src/app/shared/models/vc.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
fixed catch error message and add validation space in commit message
> [3.4] UI: Improvement VC in mobile mode

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
When we running a **version upgrade** and need to **clear all caches**, the Redis cluster clears a single arbitrary master, but not all.
This implementation uses high-level commands that work properly and is implemented at respective connection classes.
```
for i in {0..5}; do docker exec -it docker_redis-node-${i}_1 redis-cli keys "*" ; done
```
running upgrade:
```
smatvienko@linux:~/thingsboard/docker$ ./docker-upgrade-tb.sh --fromVersion=3.3.4
```
Redis is OK for cluster
```
docker exec -it docker_redis_1 redis-cli
```
running upgrade:
```
smatvienko@linux:~/thingsboard/docker$ ./docker-upgrade-tb.sh --fromVersion=3.3.4
```
Redis is OK for standalone
For the local cache, we just iterate through the caches and clear them one by one.
```
CACHE_TYPE=caffeine
```
running upgrade:
``` …
```
> [3.4] Flush all cache - Redis cluster support

- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
PR is WIP because testing is in progress, plz don't merge yet.
- fixed import result calculation (on entity reimport, it was counted as entity was updated, but in fact it was created during the first import attempt)
> [WIP] [3.4] VC fixes

- common/data/src/main/java/org/thingsboard/server/common/data/queue/Queue.java
- dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/QueueValidator.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/TenantProfileDataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseQueueServiceTest.java
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Queue name and topic should contain only ASCII alphanumerics, '.', '_' and '-' characters!
> [3.4] queue validation

- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- old  
`Alarm alarm = checkAlarmId(alarmId, Operation.WRITE); `
- new
`Alarm alarm = checkAlarmId(alarmId, Operation.DELETE);`
> [3.4]fix bug check Alarm delete

- application/src/test/java/org/thingsboard/server/controller/AbstractNotifyEntityTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAssetControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDashboardControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
> [3.4] refactoring: tests Edge

- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/EntityLoadError.java
> [3.4] VC fixes

- application/src/test/java/org/thingsboard/server/controller/AbstractNotifyEntityTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityRelationControllerTest.java
> [3.4] refactoring: tests EntityRelation

- application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
Improvements for the function which resolve the partition indexes for the RE.
Before:
After:
> [3.4] resolving partition idx by hash function

- application/src/main/java/org/thingsboard/server/service/security/permission/CustomerUserPermissions.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
> [3.4] added device-profile read permissions for the customer

- common/queue/src/main/java/org/thingsboard/server/queue/common/AbstractTbQueueTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueRequestTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueResponseTemplate.java
- msa/js-executor/api/jsInvokeMessageProcessor.js
- msa/js-executor/queue/kafkaTemplate.js
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbAbstractTransformNode.java
Here is the resulting screenshot. 
- Before: The first third is mostly timeouts because the `js eval requests` queue has a huge lag.
- After this improvement, x1 js-executor: The second third is processing as faster as js-executor can but without major timeouts. The lag builds in the rule engine's Main queue.
- After, x10 js-executors: The second third is processing at maximum speed CPU available and fall back to stable and smooth run. No lag.
> [3.4] Js executor expired ts

- application/src/test/java/org/thingsboard/server/controller/AbstractNotifyEntityTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseTenantControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseTenantProfileControllerTest.java
> [3.4] Refactoring test 19

- msa/js-executor/queue/rabbitmqTemplate.ts
> [3.4] Fix incorrect shutdown JavaScript Executor RabbitMQ queue

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
This test detects tb-js-executor startup issues like
This will clarify the root cause of black box startup failure in case of js-executor
Current build is fine
> blackbox tests: wait for js-executor kafka message

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/AbstractHasOtaPackageValidator.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/DeviceDataValidator.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidator.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
Added validation for assigned: rule-chain, dashboard, queue, firmware, software in device-profile.
Added validation for assigned: device-profile, firmware, software in device.
> [3.4] fixed device & device-profile validation

- application/src/main/java/org/thingsboard/server/service/entitiy/user/DefaultUserService.java
Old:
`- notificationEntityService.logEntityAction(tenantId, emptyId(EntityType.USER), user, actionType, user, e);`
New:
`- notificationEntityService.logEntityAction(tenantId, emptyId(EntityType.USER), tbUser, actionType, user, e);`
> [3.4] Fix big saved user error

- msa/js-executor/api/utils.ts
- msa/js-executor/queue/awsSqsTemplate.ts
> [3.4] Fix incorrect start JavaScript Executor AWS SQS queue

- application/src/test/java/org/thingsboard/server/controller/AbstractNotifyEntityTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseWidgetsBundleControllerTest.java
- UserControllTest
- WidgetsBundleControllTest
> [3.4] Refactoring tests 20

- application/src/main/resources/thingsboard.yml
- dao/src/test/resources/application-test.properties
> [3.4] Removed unused audit log config settings

- application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
- application/src/main/java/org/thingsboard/server/service/mail/PasswordResetExecutorService.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/BaseAdminControllerTest.java
- common/util/src/main/java/org/thingsboard/common/util/AbstractListeningExecutor.java
- common/util/src/main/java/org/thingsboard/common/util/ListeningExecutor.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/MailService.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mail/TbSendEmailNode.java
> [3.4] Mail server timeout impl

- ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
> [3.4] UI: Fixed not handle tooltip actions with contains space in name for map widgets

- transport/mqtt/src/main/java/org/thingsboard/server/mqtt/ThingsboardMqttTransportApplication.java
Added @EnableScheduling annotation that was accidentally deleted.
> [3.4] fixed transport stats

- ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.ts
> [3.4] UI: Delete unused function in the-queue-autocomplete

- ui-ngx/src/assets/locale/locale.constant-en_US.json
Rename page from "Password and authentication" to "Security"
> [3.4] UI: Rename page from "Password and authentication" to "Security"

- ui-ngx/src/app/modules/home/components/vc/complex-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/complex-version-load.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-version-diff.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-version-diff.component.scss
- ui-ngx/src/app/modules/home/components/vc/entity-version-restore.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.ts
- ui-ngx/src/app/shared/components/entity/entity-type-select.component.scss
Fix height of popover: 
Before:
After:
Added adaptive for vc popovers:
Diff popover on fullscreen:
> [3.4] UI: Improvement for Version Control

- application/src/main/data/upgrade/3.3.4/schema_update.sql
- dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
- dao/src/main/java/org/thingsboard/server/dao/customer/CustomerServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/entity/AbstractEntityService.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/ota/BaseOtaPackageService.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
- dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleServiceImpl.java
- dao/src/main/resources/sql/schema-entities.sql
> [3.4] Unique constraint for external id

- ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.scss
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.ts
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.scss
- ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.ts
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.ts
> [3.4] UI: Fixed responsive create/restore complex version

- application/src/main/java/org/thingsboard/server/service/security/auth/mfa/provider/impl/OtpBasedTwoFaProvider.java
- common/data/src/main/java/org/thingsboard/server/common/data/security/model/mfa/account/TwoFaAccountConfig.java
> [3.4.1] fixed serialization in 2FA (Redis)

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
After the upgrade didn't work predefined thresholds in Flot widgets.
Fixed #7054
> [3.4.1] UI: Fixed didn't work predefined thresholds in Flot widgets

- ui-ngx/src/app/core/auth/auth.service.ts
Fixed https://github.com/thingsboard/thingsboard/issues/6988
> [3.4.1] UI: Not redirect to the previous link after login with 2FA

- application/src/main/resources/thingsboard.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
According to the latest [mqtt-over-ssl document](https://thingsboard.io/docs/user-guide/mqtt-over-ssl/#ssl-configuration-using-java-keystore-deprecated),
```bash
export MQTT_SSL_CREDENTIALS_TYPE=KEYSTORE
export MQTT_SSL_KEY_STORE_TYPE=PKCS12
```
and [configuration document](https://thingsboard.io/docs/user-guide/install/config/#mqtt-server-parameters)
Parameter | Environment Variable | Default Value | Description
-- | -- | -- | --
transport.mqtt.ssl.credentials.keystore.type | MQTT_SSL_KEY_STORE_TYPE  | Type of the key store | Path to the key store that holds the SSL certificate
I'd like to add example in default configuration file make people easier to understand all the format they can use, maybe I should add another PR to document repository later? Thanks
> Update the MQTT SSL key store type example configuration file

- ui-ngx/src/app/shared/components/phone-input.component.ts
Issue: [#7085](https://github.com/thingsboard/thingsboard/issues/7085)
Before fix:
After fix:
> [3.4.1] UI: Fixed bug with double calling code

- ui-ngx/src/app/modules/home/pages/admin/two-factor-auth-settings.component.html
- ui-ngx/src/app/modules/login/pages/login/two-factor-auth-login.component.ts
1. Corrected display of Resend code button after returning from select provider in login form
2. Improved interaction with the 2FA admin configuration form
> [3.4.1] UI: Minor fix in 2FA 

- ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
Issue: [#7104](https://github.com/thingsboard/thingsboard/issues/7104)
When you try to move a circle in image maps, the circle moves to the wrong position.
After fix:
[bcc74356-ea07-437d-9461-3fd25c4e291d.webm](https://user-images.githubusercontent.com/83352633/185107280-706f25ae-e527-422a-a815-06b1f5f9f82f.webm)
> [3.4.1] UI: Fixed bug circle positioning

- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
After updating leaflet-geoman library, the tooltips on the edit buttons in the map stopped being displayed correctly.
Before:
After:
> [3.4.2] UI: Fixed show tooltip in map edit button

- ui-ngx/src/app/modules/home/components/widget/lib/maps/maps-utils.ts
Fixed: #7183 
Fixed after clicking the close tooltip button redirect to home page
> [3.4.2] UI: Fixed in map widgets close tooltip button

- application/src/main/resources/thingsboard.yml
Fixed thingsboard.yml typo in events.debug_partition_size env variable
> fix thingsboard.yml events.debug_partition_size env variable

- ui-ngx/src/app/modules/home/components/widget/lib/entities-hierarchy-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-hierarchy-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-hierarchy-widget-settings.component.html
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/node_disabled_fn.md
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/node_has_children_fn.md
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/node_icon_fn.md
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/node_opened_fn.md
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/node_relation_query_fn.md
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/node_text_fn.md
- ui-ngx/src/assets/help/en_US/widget/lib/entities_hierarchy/nodes_sort_fn.md
Re-created PR [#7004](https://github.com/thingsboard/thingsboard/pull/7004)
> [3.4.2] UI: Pass widget context to callback of entities hierarchy widget.

- ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
> [3.4.2] UI: Fixed hide search input when we delete all symbols

- ui-ngx/src/app/modules/home/components/widget/lib/maps/circle.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/polygon.ts
> [3.4.2] UI: Fixed label polyline/circle follow the mouse

- ui-ngx/src/app/shared/components/file-input.component.ts
Issue: [#7210](https://github.com/thingsboard/thingsboard/issues/7210)
Fixed file input for loading large files of more than 1gb.
> [3.4.2] UI: Fixed file input loader

- dao/src/test/java/org/thingsboard/server/dao/TimescaleDaoServiceTestSuite.java
- dao/src/test/java/org/thingsboard/server/dao/TimescaleSqlInitializer.java
- dao/src/test/java/org/thingsboard/server/dao/service/DaoTimescaleTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/timeseries/nosql/TimeseriesServiceTimescaleTest.java
- dao/src/test/resources/timescale-test.properties
- pom.xml
Please, find out the quick POC of the TimescaleDB on Testcontainers framework for the dao layer.
Testcontainers version has been upgraded to get a TimescaleDB container support.
I made it from master, so feel free to use it in your favorite branch
> dao timescale test suite

- ui-ngx/src/app/shared/models/rule-node.models.ts
Added new message types translate
> [3.4.2] UI:Update message type list

- common/data/src/main/java/org/thingsboard/server/common/data/EntityFieldsData.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetOriginatorFieldsConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetOriginatorFieldsNode.java
issue: https://github.com/thingsboard/thingsboard/issues/7186
UI generator PR: https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/93
> [3.4.2] Bugfix: originator fields node: check value for "null"

- pull_request_template.md
Having crosslinks between PRs is much easier to navigate between editions for reviewers and developers investigating the old PRs.
> PR template: Crosslinks between PRs added

- dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/DataValidatorTest.java
Invalid email address format ```jane.o`brayn@qwqwq.wqwq```!
Solution: add special characters to the validation (they are supported on the front side)
`_!#$%&'*+/=?`{|}~^.-
> [3.4.2] email pattern improvements

- application/src/main/resources/thingsboard.yml
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
https://github.com/eclipse/leshan/issues/1002
> [3.4.2] DTLS retransmission timeout

- common/data/src/main/java/org/thingsboard/server/common/data/audit/AuditLog.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/NoXssValidatorTest.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/7338
> [3.4.2] Additional validation for AuditLog entities

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
issue: https://github.com/thingsboard/thingsboard/issues/7499
> [3.4.2] Fix: change originator node - entity source bug.

- ui-ngx/src/app/modules/home/pages/admin/two-factor-auth-settings.component.ts
> [3.4.2] UI: Fixed not allow whitespace in issuer name at TOTP 2FA provider

- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Issue: https://github.com/thingsboard/thingsboard/issues/7118
Before:
After:
Before:
After:
> [3.4.2] UI:Updated datasource errors style

- common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetsBundle.java
- ui-ngx/src/app/core/http/entity.service.ts
> [3.4.2] UI: Let user to selective export widget bundles to version control.

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetEntityDetailsNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntityDetails.java
Discussion: #7366 
Rule Engine PR: [#95](https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/95)
> [3.4.2] Rule Engine: Details rule node returns entity's ID as well.

- application/src/main/data/upgrade/3.4.1/schema_update.sql
In case the order of columns in the old table is different from the new table, `INSERT INTO new_table SELECT * FROM old_table` would fail.
> [3.4.2] Fix audit logs migration script

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/widget/lib/markdown-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/qrcode-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/markdown-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/qrcode-widget-settings.component.html
- ui-ngx/src/app/shared/components/markdown-editor.component.html
- ui-ngx/src/app/shared/components/markdown-editor.component.scss
- ui-ngx/src/app/shared/components/markdown-editor.component.ts
- ui-ngx/src/assets/help/en_US/widget/editor/widget_js_markdown_pattern.md
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Updated markdown widget logic. Now markdown template gets keys only from the first entity in the entity alias.
Add UI helper to Markdown/HTML pattern in Markdown widget:
Add mat-hint to 'QR code text patter' in QR code widget:
Updated buttons panel for Markdown HTML.
Before:
After:
> [3.4.2] UI: Fix markdown widget

- dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
- dao/src/test/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDaoTest.java
Issue: https://github.com/thingsboard/thingsboard/issues/7417
PE: https://github.com/thingsboard/thingsboard-pe/pull/1234
> [3.4.2] Alarm service optimization - remove async().get() calls from synchronous methods

- ui-ngx/src/app/shared/components/phone-input.component.ts
With this PR users could pass phone numbers with spaces, hyphens and parenthesis. Now it is only E.164 format, i.e. +12015550123
> [3.4.2] UI: Let phone component to accept numbers with spaces, hyphens and parenthesis

- dao/src/main/java/org/thingsboard/server/dao/relation/BaseRelationService.java
The issue is related to Alarm Service performance: https://github.com/thingsboard/thingsboard/issues/7417
PE: https://github.com/thingsboard/thingsboard-pe/pull/1235
Some TODO was resolved. Removed blocking `.get()` operations from the async functions 
Hint: to have a clear view try opening findRelationsRecursively in your IDE
> [3.4.2] findRelationsRecursively refactoring - removed blocking operations

- application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
- application/src/main/java/org/thingsboard/server/service/apiusage/TbApiUsageStateService.java
- application/src/main/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcService.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultAlarmSubscriptionService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineRpcService.java
> Fix compilation error in alarm service for issue #7393

- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
Just refactoring for getting prepared statement query.
PE pull request -  https://github.com/thingsboard/thingsboard-pe/pull/1248
> [3.4.2] CassandraBaseTimeseriesDao refactoring

- application/src/main/java/org/thingsboard/server/service/entitiy/AbstractTbEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
- application/src/test/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmServiceTest.java
Issue: https://github.com/thingsboard/thingsboard/issues/7553
> [3.4.2] Fix alarm subscriptions on rest api

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/util/TenantIdLoaderTest.java
> [3.4.2] Fix code formatting issue in TenantIdLoaderTest

- application/src/main/data/upgrade/3.4.1/schema_update_before.sql
- application/src/main/java/org/thingsboard/server/controller/AssetController.java
- application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
- application/src/main/java/org/thingsboard/server/service/install/DbUpgradeExecutorService.java
- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
- common/data/src/main/java/org/thingsboard/server/common/data/util/TbPair.java
- dao/src/main/java/org/thingsboard/server/dao/asset/AssetDao.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/TbPair.java
- dao/src/main/java/org/thingsboard/server/dao/sql/asset/AssetRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/tenant/TenantRepository.java
> [3.4.2] upgrade asset-profiles using ExecutorService

- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.scss
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
Fixed https://github.com/thingsboard/thingsboard/pull/6374
> [3.4.2] UI: Fixed function setFixedLayout in dashboard layout 

- docker/tb-js-executor.env
- msa/js-executor/api/jsInvokeMessageProcessor.ts
- msa/js-executor/config/custom-environment-variables.yml
- msa/js-executor/config/default.yml
- msa/js-executor/docker/start-js-executor.sh
added memory usage logs:
For control memory usage added next params:
--max-heap-size=200 
--no-compilation-cache
> [3.4.2] js-executor improvements

- msa/js-executor/docker/start-js-executor.sh
> [3.4.2] fix start js

- ui-ngx/src/app/core/http/attribute.service.ts
If the attribute or telemetry name includes special characters like `/ ? : @ & = + $ #`. It could not be removed through the attribute service.
> [3.4.2] UI: Fixes delete attribute or telemetry whose name has special characters

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesByNameAndTypeLoader.java
issue: https://github.com/thingsboard/thingsboard/issues/7599
UI generator PR: https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/100
> [3.4.2] Fix: delete cases from EntitiesByNameAndTypeLoader

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
1. For headers with many values, an array will be returned. Previously only the first entry was returned.
This is especially helpful for `Set-Cookie`, which can hold many entries related to authentication.
2. The processFailureResponse will return headers similar to the OK response. Before that, the headers were ignored.
Issue: https://github.com/thingsboard/thingsboard/issues/7619
PE: https://github.com/thingsboard/thingsboard-pe/pull/1279
> [3.4.2] HTTP client returns headers as an array if there is more than one

- ui-ngx/src/app/core/auth/auth.service.ts
- ui-ngx/src/app/core/interceptors/global-http-interceptor.ts
- ui-ngx/src/app/core/ws/telemetry-websocket.service.ts
Fixes incorrect process error handling when updating JWT
> [3.4.2] UI: Fixes incorrect process error handling when updating JWT

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbFetchDeviceCredentialsNode.java
issue: https://github.com/thingsboard/thingsboard/issues/7645
> [3.4.2] Fix: fetch device credentials node

- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/Oauth2AuthenticationSuccessHandler.java
- application/src/test/java/org/thingsboard/server/service/security/auth/oauth2/Oauth2AuthenticationSuccessHandlerTest.java
With this PR dashboard state that is stored in state param of url will not be ignored by the UI.
PR is related to the issue: [#7640](https://github.com/thingsboard/thingsboard/issues/7640)
> [3.4.2] Feature: support dashboard state after oauth2 redirect to the targeted url

- ui-ngx/package.json
added max_old_space_size for build:prod like PE version
> [3.4.2]added max_old_space_size to the build:prod ui

- ui-ngx/src/app/core/services/dashboard-utils.service.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/add-widget-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
- ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
- ui-ngx/src/app/shared/models/dashboard.models.ts
- ui-ngx/src/app/shared/models/widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Widget could be hidden in mobile mode. It is the same but for desktop.
> [3.4.2] UI: Make possible to hide widget in desktop mode.

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/AttributesUpdateNodeCallback.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributes.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesTest.java
> Attribute nodes add options send notification

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributes.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesTest.java
issue: https://github.com/thingsboard/thingsboard/issues/7667
UI generator PR: https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/102
> [3.4.2] Feature: add options send notifications for 'save attribute' & 'delete attribute'

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
> Backport ability to specify scope in the metadata

- dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileServiceImpl.java
We can't import 2 new assets with the same type without assetProfileId (from 3.4.1 v).
This problem related to the cache. After saving first asset we throw evict cache event.
But this event will be handled when transactional is closed. So method `findAssetProfileByName` during transaction always returns null.
For solving this issue we disable ability to save null to cache in `findAssetProfileByName`.
> [3.4.2] fixed import assets with the same type without assetProfileId

- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/TelemetryEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/ota/DefaultOtaPackageStateService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/SubscriptionManagerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/telemetry/InternalTelemetryService.java
- common/cluster-api/src/main/proto/queue.proto
- common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineTelemetryService.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/msg/DeviceAttributesEventNotificationMsg.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesNodeTest.java
Issue: #7683   
UI PR: https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/103/files
> [3.4.2] Missed logic for sending attributes deleted notification to device in the Delete Attributes node

- application/src/main/java/org/thingsboard/server/service/ota/DefaultOtaPackageStateService.java
This PR contains cherry-picked commits from PR #7672
> Bug 6008: OTA image assigned to device profile does not populate device shared properties

- msa/black-box-tests/pom.xml
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractContainerTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestCoapClient.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestCoapClientCallback.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/CoapClientTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/HttpClientTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
Added black box tests for device provisioning with different strategies in Device Profile.
https://github.com/thingsboard/thingsboard-pe/pull/1294
> [3.4.2] Provisioning black box tests

- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/MqttDeviceProfileTransportConfiguration.java
- add to TransportConfiguration sparkPlug
If "sparkPlug" == true, then "topic filter" must be:
`namespace/group_id/message_type/edge_node_id/[device_id]`
> add_sparkPlug_ to _TransportConfiguration

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/JsonTbEntity.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/RepositorySettings.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.html
- ui-ngx/src/app/modules/home/components/vc/repository-settings.component.ts
- ui-ngx/src/app/shared/models/settings.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- Ignore createdTime and tenantId when comparing entity versions to avoid this:
(Issue: https://github.com/thingsboard/thingsboard/issues/7779)
- Added 'Show merge commits' option in repository settings to be able to see merge commits in versions list:
> [3.4.3] VC: 'Show merge commits' option, improved entity versions comparing

- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityQueryControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
- common/util/src/main/java/org/thingsboard/common/util/RegexUtils.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
- dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
Additional pageLink validation for controllers and query repository.
> [3.4.3] Additional pageLink validation

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
Hotfix for https://github.com/thingsboard/thingsboard/pull/7761
> [3.4.3] Fix for ts subscription handling

- application/src/main/java/org/thingsboard/server/service/entitiy/device/DefaultTbDeviceService.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
https://github.com/thingsboard/thingsboard/issues/7787
> [3.4.3] fixed saveDeviceWithCredentials notifications

- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
Fixed infinite await in bulk import tests
> [3.4.3]fixed bulk import test infinite await

- application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
Added DeviceProfileService and AssetProfileService to TBContext
> [3.4.3] Added DeviceProfileService and AssetProfileService to TBContext

- application/src/test/java/org/thingsboard/server/controller/AbstractNotifyEntityTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseRuleChainControllerTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/alarm/Alarm.java
- common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChainMetaData.java
- common/data/src/main/java/org/thingsboard/server/common/data/util/ReflectionUtils.java
- common/data/src/main/java/org/thingsboard/server/common/data/validation/Length.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/service/ConstraintValidator.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/RuleChainDataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseOtaPackageServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/NoXssValidatorTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbAbstractAlarmNodeConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNodeConfiguration.java
Added validation of custom and javax constraints for `NodeConfiguration` implementations.
Example of rule node validation error:
> [3.4.3] Validation for rule node configuration

- ui-ngx/src/app/core/api/widget-subscription.ts
> Fixed incorrect updated timewindow in Alarm table

- application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
Improved Swagger description for TelemetryController's saveDeviceAttributes and saveEntityAttributes requests.
Issue: #7855
> [WIP][3.5] Improve swagger description for SaveAttributes

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CreateCustomerTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CustomerEditMenuTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/EntityPrototypes.java
Add tests on delete phone number in create customer view and edit menu
> Add tests on delete phone number

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewayDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewayDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
- common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandlerTest.java
- create GatewaySessionHandler extends  AbstractGatewaySessionHandler
- create GatewayDeviceSessionContext extends AbstractGatewayDeviceSessionContext
> [3.5] sparkplug: abstractHandler for Gateway and Sparkplug

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CreateCustomerTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CustomerEditMenuTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/EntityPrototypes.java
Reverts thingsboard/thingsboard#7859
> Revert "[WIP][3.5] Add tests on delete phone number"

- application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/RuleChainsEdgeEventFetcher.java
- application/src/main/java/org/thingsboard/server/service/entitiy/edge/DefaultTbEdgeService.java
- application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
This PR related to issue:
https://github.com/thingsboard/thingsboard/issues/7866
* correctly set isRoot during sync process of the edge rule chain msg
> [3.4.4][Bug][Edge] Correctly set root rule chain on initial sync

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
> Fixed incorrect calculate width when used right layout dashboard

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugSessionCtx.java
- common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandlerTest.java
- refactoring SparkplugNodeSessionHandler extends AbstractGatewaySessionHandler
- refactoring SparkplugSessionCtx extends AbstractGatewayDeviceSessionContext
> [3.4.5] sparkplug: add Sparkplug as extends abstract

- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
Fixed: [#7870](https://github.com/thingsboard/thingsboard/issues/7870)
Fixed to save dialog after switching fixed layout side.
> Detected changes of switching fixed layout side

- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/AlarmEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/DeviceEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RelationEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
Put your PR description here instead of this sentence.   
https://github.com/thingsboard/thingsboard/issues/7869
> [3.5] Push latest timeseries key-value pair to edge on assignment entity to edge

- ui-ngx/src/app/core/http/entity.service.ts
- ui-ngx/src/app/modules/home/pages/profile/profile.component.html
- ui-ngx/src/app/modules/home/pages/profile/profile.component.ts
- ui-ngx/src/app/modules/home/pages/user/user.component.html
- ui-ngx/src/app/modules/home/pages/user/user.component.ts
- ui-ngx/src/app/shared/components/phone-input.component.scss
- ui-ngx/src/app/shared/models/user.model.ts
> Added phone number to user profile

- ui-ngx/src/app/shared/components/phone-input.component.ts
Fixed: [#7874](https://github.com/thingsboard/thingsboard/issues/7874)
Fixed save phone number after a change.
> Fix phone input update on save changes

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNodeTest.java
> [3.4.4] rollback "tellFailure" logic change in TbAbstractGetAttributesNode

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/widget/data-key-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
> Fixed auto-indexing for keys with aggregation

- application/src/main/java/org/thingsboard/server/service/alarm/rule/DefaultTbAlarmRuleStateService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/rule/AlarmRuleEntityStateService.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/rule/AlarmRuleEntityStateDao.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/rule/BaseAlarmRuleEntityStateService.java
- dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/AlarmRuleEntityStateEntity.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/rule/AlarmRuleEntityStateRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/rule/JpaAlarmRuleEntityStateDao.java
- dao/src/main/resources/sql/schema-entities.sql
- dao/src/test/java/org/thingsboard/server/dao/service/AbstractServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseAlarmRuleEntityStateServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/sql/AlarmRuleServiceEntityStateSqlTest.java
- dao/src/test/resources/sql/psql/drop-all-tables.sql
> [WIP] Added dao layer for AlarmRuleEntityState

- application/src/test/java/org/thingsboard/server/controller/AbstractControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/AbstractMqttIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/MqttTestConfigProperties.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv5/MqttV5TestClient.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/AbstractMqttV5ClientSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/AbstractMqttV5ClientSparkplugConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/MqttV5ClientSparkplugBConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/AbstractMqttV5ClientSparkplugTelemetryTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/MqttV5ClientSparkplugBTelemetryTest.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/MetricDataType.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugMetricUtil.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugTopicUtil.java
- common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
- added DeviceTelemetryProto with Sparkplug (node, device)
- added SparkplugMetricUtil
> sparkplug: Telemetry

- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/AbstractMqttV5ClientSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/AbstractMqttV5ClientSparkplugConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/MqttV5ClientSparkplugBConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/AbstractMqttV5ClientSparkplugTelemetryTest.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewayDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/MqttDeviceAwareSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugSessionCtx.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugMetricUtil.java
> [WIP][3.4.5] metrics birth

- ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
- ui-ngx/src/app/shared/components/notification/notification.component.html
- ui-ngx/src/app/shared/components/notification/notification.component.scss
- ui-ngx/src/app/shared/components/notification/notification.component.ts
- ui-ngx/src/app/shared/models/notification.models.ts
> Notification temaplate

- ui-ngx/src/app/modules/home/components/widget/lib/settings/navigation/navigation-cards-widget-settings.component.ts
> Hotfix device profile url for navigation cards settings

- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/AbstractMqttV5ClientSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/attributes/AbstractMqttV5ClientSparkplugAttributesTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/attributes/MqttV5ClientSparkplugBAttributesTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/AbstractMqttV5ClientSparkplugConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/MqttV5ClientSparkplugBConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/AbstractMqttV5ClientSparkplugTelemetryTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/MqttV5ClientSparkplugBTelemetryTest.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewayDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/MqttDeviceAwareSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugSessionCtx.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/MetricDataType.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugMetricUtil.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugTopic.java
> [3.4.5] Sparkplug subscribe

- common/data/src/main/java/org/thingsboard/server/common/data/device/profile/MqttDeviceProfileTransportConfiguration.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugMessageTypeSate.java
Add attributes by Metric`s name, 
- STATE ONLINE
- STATE OFFLINE
> [3.4.5] sparkplug: add attributes by Metric`s name

- application/src/main/java/org/thingsboard/server/controller/UserController.java
- application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/user/UserSettingsService.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsServiceImpl.java
Added rest methods for saving/updating/deleting user settings in UserController
> [WIP] Added controller methods for saving/updating/deleting user settings in UserController

- application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseAssetControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseCustomerControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseRuleChainControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
Transactional tests fail from time to time. Ignored until fixed.
> Ignored unstable integration tests

- application/src/test/java/org/thingsboard/server/transport/mqtt/AbstractMqttIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/MqttTestConfigProperties.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/AbstractMqttV5ClientSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/attributes/AbstractMqttV5ClientSparkplugAttributesTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/attributes/MqttV5ClientSparkplugBAttributesInProfileTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/attributes/MqttV5ClientSparkplugBAttributesTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/AbstractMqttV5ClientSparkplugConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/MqttV5ClientSparkplugBConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/rpc/AbstractMqttV5RpcSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/rpc/MqttV5RpcSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/AbstractMqttV5ClientSparkplugTelemetryTest.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugDeviceSessionContext.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugConnectionState.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugMessageType.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugMetricUtil.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugRpcRequestHeader.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugRpcResponseBody.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/session/DeviceAwareSessionContext.java
- shared attributes test
- rpc
> [3.4.5] sparkplug: rpc/attribute

- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmAssignee.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/AlarmInfoEntity.java
Small fix for getting AlarmInfoEntity - in case when we have no assigned user and trying to get it from the DB we receive a null as an assignee uuid. But later we are trying to create UserId using this identifier. But it throws null pointer exception, because of it cannot be created.
Also unassign method name refactored in AlarmController.
> Small fix for alarm assignment

- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
HashPartitionService: set my partitions atomically 
This will improve partition management in a cluster deployment.
PE: https://github.com/thingsboard/thingsboard-pe/pull/1485
> [3.5] Hash partition service improvement

- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/attributes/AbstractMqttAttributesIntegrationTest.java
> [WIP][3.5] fixed processJsonTestGatewayRequestAttributesValuesFromTheServer

- dao/src/main/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDao.java
issue: #8107 
Changes for remove latest method(Sync with remove method):
logic in the remove method:
> [3.5] bugfix for remove latest telemetry

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
- msa/black-box-tests/src/test/resources/docker-compose.hybrid-test-extras.yml
- msa/black-box-tests/src/test/resources/docker-compose.postgres-test-extras.yml
- msa/black-box-tests/src/test/resources/docker-compose.rabbitmq-server.yml
Before this, Cassandra's container in tests gets 8G on a 32G machine. 
PE: https://github.com/thingsboard/thingsboard-pe/pull/1489
> [3.5] msa black box tests: Cassandra limited to MAX_HEAP_SIZE: 1024M

- common/script/remote-js-client/src/main/java/org/thingsboard/server/service/script/RemoteJsInvokeService.java
- common/script/script-api/src/main/java/org/thingsboard/script/api/js/NashornJsInvokeService.java
- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
Shutdown callback executor for RemoteJsInvokeService.
Call shutdown timeoutExecutorService from AbstractScriptInvokeService
This affected tests that accumulated executor services in memory during many tests run.
PE: https://github.com/thingsboard/thingsboard-pe/pull/1493
> [3.5] ScriptInvokeService - shutdown executors on application exit

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseWidgetsBundleControllerTest.java
- application/src/test/java/org/thingsboard/server/service/script/NashornJsInvokeServiceTest.java
- application/src/test/java/org/thingsboard/server/transport/AbstractTransportIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/coap/AbstractCoapIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/AbstractMqttIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/attributes/AbstractMqttAttributesIntegrationTest.java
- application/src/test/resources/application-test.properties
- application/src/test/resources/logback-test.xml
- common/script/script-api/src/main/java/org/thingsboard/script/api/js/NashornJsInvokeService.java
- dao/src/test/resources/nosql-test.properties
- dao/src/test/resources/sql-test.properties
- msa/pom.xml
- pom.xml
Speedup tests and minimize memory footprint for tests. See the commit log for details:
- handle timeouts on transport tests to provide clear explanation what is the problem. timeout increased for run test stable on slow (busy) environments
- test dependency upgrade: surefire.version 3.0.0-M9
- Shutdown jsExecutor after Nashorn destroy
- tests: surefire plugin: -Xss384k -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=20 
- test memory optimization (disable integration rpc, coap, hikari.maximumPoolSize=16, etc)
- disabled service.integrations and js.evaluator for the most of cases
- spring.test.context.cache.maxSize=1 
- msa modules reordered to tolerate parallel build with 3 parallel threads
> [3.5] Test improvements - memory

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/resources/application-test.properties
- pom.xml
-  fixed test performance degradation (100% C2 Compiler) by removing `-Xss384k` and `Mockito.clearAllCaches()` 
-  removed `spring.test.context.cache.maxSize=1` as it always eq one during application tests (no performance effect)
> [3.5] Test performace fix

- common/cache/src/main/java/org/thingsboard/server/cache/RedisTbTransactionalCache.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
- dao/src/test/java/org/thingsboard/server/dao/AbstractRedisContainer.java
- dao/src/test/java/org/thingsboard/server/dao/RedisSqlTestSuite.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseDeviceCredentialsCacheTest.java
- dao/src/test/resources/application-test.properties
Tests: Redis test suite implemented on testcontainers with valid parameters initialization by System.setProperty
Before this Spring does run initializer and tests effectively runs on caffeine.
Using the latest Redis 7.0.
As result we have 2 failed tests on Redis:
Fixed :
- **skip evicting for an empty key list from Redis**
- fixed test by removing static from variable
PE: https://github.com/thingsboard/thingsboard-pe/pull/1498
> [3.5] Redis test suite on testcontainers

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/OtherPageElements.java
Fixed field tests wich related with edit menu pencil button
> [3.5] Fixed xpath for UI failed tests

- ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.scss
- ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.scss
- ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.scss
Fixes due to angular 15 version upgrade
> [3.5] UI: Fixes due to angular 15 version upgrade

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/AbstractMqttV5ClientSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/attributes/AbstractMqttV5ClientSparkplugAttributesTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/AbstractMqttV5ClientSparkplugConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/connection/MqttV5ClientSparkplugBConnectionTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/rpc/AbstractMqttV5RpcSparkplugTest.java
- application/src/test/java/org/thingsboard/server/transport/mqtt/sparkplug/timeseries/AbstractMqttV5ClientSparkplugTelemetryTest.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/MetricDataType.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugTopic.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/SparkplugTopicUtil.java
For the Sparkplug™ B version of the specification, the UTF-8 string constant for the namespace element will be: "spBv1.0"
> [3.4.5] sparkplug validate namespace

- msa/black-box-tests/README.md
Update instructions for running tests in README.md
> [3.5] Update black box README

- application/src/main/data/upgrade/3.4.4/schema_update.sql
> Fix for upgrade script

- application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsValidator.java
- pom.xml
- rest-client/pom.xml
- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
> REST client concurrency mode fix on token refresh

- ui-ngx/src/app/core/services/menu.service.ts
- ui-ngx/src/app/modules/home/pages/features/features-routing.module.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-routing.module.ts
- ui-ngx/src/app/shared/models/entity-type.models.ts
> Move rule chains menu link in top level

- ui-ngx/src/app/shared/models/time/time.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Discussions: #7716 and #7957
https://user-images.githubusercontent.com/86909129/215708549-bc4e771b-7516-4697-80ec-879e1b089367.mp4
> Add quarter and half year intervals to time window.

- ui-ngx/src/app/core/services/utils.service.ts
These functions are useful for manual dashboard state management in some specific cases.
> Add Base64 functions to Utils service.

- ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
Fix for widget Digital Gauge -> Horizontal Bar for cases when the value is decimal numeric that ends with zeros (e.g. 42.0) - the value was not displayed correctly.
Bug description and screenshots: https://github.com/thingsboard/thingsboard/issues/8112
> 'Horizontal bar' widget displays incorrectly decimal values that ends with zeros

- ui-ngx/src/app/core/services/utils.service.ts
Added "delete" icon(rubbish bin) to the default icon list.
> Added "delete" icon to the default icon list

- ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.html
- ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Option to not only delete or edit existing dashboard filters but also to duplicate them.
https://user-images.githubusercontent.com/86909129/201986432-50d21561-b1ce-4f6d-a795-faba14add03c.mp4
> Add dashboard filter duplication option

- ui-ngx/src/app/shared/components/dashboard-select.component.ts
Rewritten `openDashboardSelectPanel()` to dashboard-select component. Deleted outdated code.
> Refactoring dashborad-select component

- ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.ts
> [3.5]minor ui fixes

- application/src/main/java/org/thingsboard/server/service/system/DefaultSystemInfoService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/DefaultTbServiceInfoProvider.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/TbServiceInfoProvider.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/ZkDiscoveryService.java
> [3.5]fixed system info updates

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
- application/src/test/java/org/thingsboard/server/controller/BaseHomePageApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
> [3.5]minor tests fixes

- ui-ngx/src/app/core/api/widget-api.models.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/states/default-state-controller.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/states/entity-state-controller.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/states/state-controller.component.ts
Fixed https://github.com/thingsboard/thingsboard/pull/8072
> Fixer RP: Optionally update dashboard state when using navigate back API

- application/src/main/data/upgrade/3.4.4/schema_update.sql
- dao/src/main/resources/sql/schema-entities.sql
Added check for empty string in title/label
> [3.5] Fix - Added check for empty string in title/label

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CustomerPageHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/SideBarMenuViewElements.java
Fixed xpath to button that opens the dropdown with profiles
> [3.5] Fixed UI tests after menu update

- application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
- application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
`ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: duplicate key value violates unique constraint "uq_notification_target_name"`
`ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: duplicate key value violates unique constraint "resource_unq_key"`
> [3.5]fixed upgrade script

- pull_request_template.md
> Update PR template delete add version in templates

- pom.xml
**Bug:**
https://github.com/thingsboard/thingsboard/issues/7978
https://github.com/thingsboard/thingsboard/issues/8104
Before:
rename:
```
public interface ExecutionObject
-> int getId(); to int getExecutionObjectId();
```
After:
> [Fix bug][3.5] tbel json decode id

- pom.xml
Reverts thingsboard/thingsboard#8273
> Revert "[Fix bug][3.5] tbel json decode id"

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- application/src/main/java/org/thingsboard/server/controller/AssetController.java
- application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
- application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
- application/src/main/java/org/thingsboard/server/controller/AuthController.java
- application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
- application/src/main/java/org/thingsboard/server/controller/CustomerController.java
- application/src/main/java/org/thingsboard/server/controller/DashboardController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
- application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
- application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
- application/src/main/java/org/thingsboard/server/controller/EventController.java
- application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
- application/src/main/java/org/thingsboard/server/controller/OAuth2ConfigTemplateController.java
- application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
- application/src/main/java/org/thingsboard/server/controller/RpcV2Controller.java
- application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
- application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/java/org/thingsboard/server/controller/TenantController.java
- application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
- application/src/main/java/org/thingsboard/server/controller/UserController.java
- application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
- application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
- application/src/main/java/org/thingsboard/server/service/sms/DefaultSmsService.java
Reverts thingsboard/thingsboard#7527
> Revert "[3.5] removed redundant handleException usages"

- dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityDataAdapter.java
- dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityDataAdapterTest.java
In order to solve the problem of incorrect string representation of integer value for very long ints after convertation from string to double(bc float is not enough sometimes) and back, changed Long.parseLong to BigInteger constructor, added test 4 this case
[jira](https://thingsboard-portal.atlassian.net/browse/PROD-1284)
> [3.5] fix for incorrect long integers, sent on ws to FE 

- ui-ngx/src/app/shared/models/websocket/notification-ws.models.ts
> Fixed updated notification when open notifications popover

- application/src/test/java/org/thingsboard/server/controller/BaseEntityQueryControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/BaseHomePageApiTest.java
Updated tests so that tests rely on initial state before execution.
> Flaky test fixes

- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttSslHandlerProvider.java
Jira ticket:
https://thingsboard-portal.atlassian.net/browse/PROD-1973
Added logging for failed mqtt ssl certificates
> Added logging for invalid mqtt ssl certificates 

- ui-ngx/src/assets/help/en_US/widget/action/custom_additional_params.md
The link for AlarmDataInfo is updated to provide more actual information about the list of alarm parameters included, particularly the originator label.
> Update links for alarm info in widget custom action help

- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
- dao/src/main/java/org/thingsboard/server/dao/ota/BaseOtaPackageService.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/OtaPackageDataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseDeviceProfileServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/BaseOtaPackageServiceTest.java
Put your PR description here instead of this sentence.   
Fixed test errors in BaseDeviceProfileServiceTest and BaseOtaPackageServiceSqlTest
> Firmware-footprint test fixed 

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- application/src/main/java/org/thingsboard/server/controller/AssetController.java
- application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
- application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
- application/src/main/java/org/thingsboard/server/controller/AuthController.java
- application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
- application/src/main/java/org/thingsboard/server/controller/CustomerController.java
- application/src/main/java/org/thingsboard/server/controller/DashboardController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
- application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
- application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
- application/src/main/java/org/thingsboard/server/controller/EventController.java
- application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
- application/src/main/java/org/thingsboard/server/controller/OAuth2ConfigTemplateController.java
- application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
- application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
- application/src/main/java/org/thingsboard/server/controller/RpcV2Controller.java
- application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
- application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/java/org/thingsboard/server/controller/TenantController.java
- application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
- application/src/main/java/org/thingsboard/server/controller/UserController.java
- application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
- application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
> removed redundant handle exception

- dao/src/test/java/org/thingsboard/server/dao/service/BaseAssetServiceTest.java
Optimized a large number of created assets in cycles and values per page in BaseAssetServiceTest.
> Optimization dao tests with cycles

- msa/js-executor/config/custom-environment-variables.yml
- msa/js-executor/config/default.yml
- msa/js-executor/queue/kafkaTemplate.ts
Related issue: https://github.com/thingsboard/thingsboard/issues/7986#issuecomment-1403382688
This PR allows to configure kafkajs `connectionTimeout` property that defaults to 1000ms (link https://github.com/tulios/kafkajs/blob/dcee6971c4a739ebb02d9279f68155e3945c50f7/src/index.js#L56)  via `TB_KAFKA_CONNECTION_TIMEOUT_MS` env var.
Note: To create this PR I tried to mimic the logic that already exists for the `requestTimeout` property.
PS: I'm not sure if I have to add the new var in here (and other `yaml` files):
https://github.com/thingsboard/thingsboard/blob/c7babf20850007b611256dbfee9ab47863a2033c/transport/http/src/main/resources/tb-http-transport.yml#L154-L158
Required changes in docs: 
Add a new entry in the config docs (link …
> Allow to configure kafkajs `connectionTimeout` property

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNodeTest.java
Currently, edge connect/disconnect events are not being pushed to the edge, which prevents them from being used in customer business logic. This causes issues for customers who rely on showing this information on dashboards.
To address this problem, we will modify the push to edge rule node to handle connect/disconnect events as updated attributes or timeseries updates. This will allow us to push the events to the appropriate rule chain and make them available for use in customer business logic.
* Push connect/disconnect events to the rule chain when the edge is connected or disconnected
* Modify the push to edge rule node to handle these events as updated attributes
* Apply these changes to the relevant rule chain
Customers will be able to use edge connect/disconnect …
> [3.5] Push edge connect/disconnect events to rule chain

- ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
- ui-ngx/src/app/shared/components/notification/notification.component.scss
> Fixed show email notification preview in big content

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Original PR for this is done by @FawenYo (https://github.com/FawenYo)
https://github.com/thingsboard/thingsboard/pull/8249#issuecomment-1501677972
This one is cherry picked to be used in 3.5 release.
> [3.5] Add SSL option for Kafka queue connection

- ui-ngx/src/app/modules/home/components/widget/lib/maps/dialogs/select-entity-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/maps/dialogs/select-entity-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/maps-utils.ts
Select entity dialog for circles, polygons, and markers using  Label/Label function for naming in case 'Show label' is active.
Fixed: https://github.com/thingsboard/thingsboard/pull/8067
Markers:
Polygons:
Circles:
> Added label parsing in select entity dialog

- ui-ngx/src/app/shared/components/time/timeinterval.component.ts
- ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
> Fix disable time interval in timewindow panel

- application/src/main/java/org/thingsboard/server/service/ttl/EdgeEventsCleanUpService.java
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
> Typo - fixed startup of edge event clean up service

- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/java/org/thingsboard/server/service/security/AccessValidator.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/BaseTelemetryControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/sql/TelemetryControllerSqlTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/BasicKvEntry.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/BasicTsKvEntry.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/JsonDataEntry.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/StringDataEntry.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeUtils.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
- dao/src/test/java/org/thingsboard/server/dao/service/ConstraintValidatorTest.java
> Fixed xss vulnerabilities in attributes and telemetry

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/RuleChainEditMenuTest.java
Replaced check attribute aria-checked with attribute class
> Fixed ui test on debug mode

- application/src/test/java/org/thingsboard/server/system/RestTemplateConvertersTest.java
> Added test for detection RestTemplate xml content type issue

- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/BaseTelemetryControllerTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/JsonDataEntry.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/StringDataEntry.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeUtils.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
- dao/src/test/java/org/thingsboard/server/dao/service/ConstraintValidatorTest.java
> revert tskv value noxss validation

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSessionState.java
This PR improves logging of edge services - in case interrupt of the sending downlink messages is planned **NO** _WARN_ or _ERROR_ messages in the logs should be available - batch is cancelled, but no _WARN_ or _ERROR_ messages. _ERROR_ and _WARN_ messages are going to be shown only in case real exception happened.
> Edge - improved logic of interruption of sending downlink tasks

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusQueueConfigs.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaTopicConfigs.java
- common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubSubscriptionSettings.java
- common/queue/src/main/java/org/thingsboard/server/queue/util/PropertyUtils.java
- common/queue/src/test/java/org/thingsboard/server/queue/kafka/TbKafkaSettingsTest.java
- common/queue/src/test/java/org/thingsboard/server/queue/util/PropertyUtilsTest.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
This PR allows applying other Kafka parameters as a single line parameter
```
export TB_QUEUE_KAFKA_OTHER_PROPERTIES="metrics.recording.level:INFO;metrics.sample.window.ms:30000"
```
- kafka settings: added default values for values for TbKafkaSettings class
- kafka settings: test added, refactored to use configureSSL exact once
- kafka settings: kafka yaml parameters added for microservices same as thingsboard.yml . PropertyUtils added, duplicated code refactored to getProps. TB_QUEUE_KAFKA_REQUEST_TIMEOUT_MS and TB_QUEUE_KAFKA_SESSION_TIMEOUT_MS moved from other to main properties. Other yaml props is deprecated. other-inline added TB_QUEUE_KAFKA_OTHER_PROPERTIES. Tests added.
> [3.5] Kafka other properties inline

- ui-ngx/src/app/shared/components/color-picker/color-picker.component.scss
Fixed color picker width for the large dialog window.
> Fix color picker input width

- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
- application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
Update parameter of bulk import request was not considered while device bulk import. Fixed.
Jira ticket: https://thingsboard-portal.atlassian.net/browse/PROD-1997
> Fixed telemetry/attribute update while device bulk import

- application/src/main/java/org/thingsboard/server/service/system/DefaultSystemInfoService.java
- application/src/test/java/org/thingsboard/server/controller/BaseHomePageApiTest.java
fixed slack, mail, 2fa features info
> features info improvements

- ui-ngx/src/app/shared/models/device.models.ts
Fixed UI bug after merge https://github.com/thingsboard/thingsboard/pull/6986
> Added init value for MQTT transport configuration in device profile

- application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
https://thingsboard-portal.atlassian.net/browse/PROD-1687
> added log to TenantActor for investigation

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
> fix deduplication node description

- application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
- application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
- application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
- application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/EntitiesLimitTriggerProcessor.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultAlarmSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/update/DefaultUpdateService.java
- application/src/test/java/org/thingsboard/server/service/notification/MockNotificationSettingsService.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/AlarmAssignmentNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/AlarmCommentNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/AlarmNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/ApiUsageLimitNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/DeviceActivityNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/EntitiesLimitNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/EntityActionNotificationRuleTriggerConfig.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/RuleEngineComponentLifecycleEventNotificationRuleTriggerConfig.java
- common/message/src/main/java/org/thingsboard/server/common/msg/notification/trigger/EntitiesLimitTrigger.java
- common/queue/src/main/java/org/thingsboard/server/queue/notification/NotificationRuleProcessor.java
- common/queue/src/main/java/org/thingsboard/server/queue/notification/RemoteNotificationRuleProcessor.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/usagerecord/DefaultApiLimitService.java
- refactoring for default notifications
- fix entities count limit notification rule to be processed after the entity is created
> Notification system improvements

- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-table.component.scss
> Fixed assignee cell height not matching row height in alarm entity table

- ui-ngx/src/app/core/services/script/node-script-test.service.ts
Fixed the problem that there is a possibility that the message can be truncated and, therefore, an invalid JSON is received there
> Fixed error when call test function in rule node

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbLogNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbLogNodeTest.java
> fexed NPE in log node

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
PE PR - https://github.com/thingsboard/thingsboard-pe/pull/1662
Documentation PR - https://github.com/thingsboard/thingsboard.github.io/pull/1036
Added method to TBEL helper, to get ability to convert multilevel json to one level map.
> Feature TBEL function toFlatMap

- ui-ngx/angular.json
- ui-ngx/src/app/shared/components/dialog/node-script-test-dialog.component.html
- ui-ngx/src/app/shared/components/js-func.component.ts
- ui-ngx/src/app/shared/models/ace/ace.models.ts
- ui-ngx/src/app/shared/models/ace/tbel/mode-tbel.js
- ui-ngx/src/app/shared/models/ace/tbel/worker-tbel.js
Put your PR description here instead of this sentence.   
Validation of the syntax of the "foreach" function for TBEL only
fuction: '**foreach'** only for TBEL
Java Script:
TBEL:
Befor:
After:
> Fixed validation of the TBEL "foreach" loop in the "Script fuction" UI component

- ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.html
1. Open any dashboard
2. Edit mode
3. Edit Filter
4. add any filter and save
5. check the conformity of the column and meaning
Before fix: 
After fix:
Made editable column width smaller for better view in mobile mode
> Fixed filters dialog button column width

- ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
- ui-ngx/src/app/shared/models/constants.ts
Added help button for notification dialog:
- sent notification dialog;
- template notification dialog;
- recipient notification dialog;
- rule notification dialog;
Merge with documentation pr: [#1033](https://github.com/thingsboard/thingsboard.github.io/pull/1033)
> Help button for notifications dialog

- ui-ngx/src/app/core/http/notification.service.ts
- ui-ngx/src/app/modules/home/components/notification/notification-bell.component.ts
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.scss
- ui-ngx/src/app/shared/components/notification/notification.component.ts
- ui-ngx/src/app/shared/models/notification.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Navigation to particular delivery method settings from the "New notification" window

- ui-ngx/src/app/shared/models/constants.ts
- ui-ngx/src/app/shared/models/entity-type.models.ts
> Fix help link for resources

- application/src/main/java/org/thingsboard/server/service/ttl/AlarmsCleanUpService.java
- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
- application/src/test/java/org/thingsboard/server/service/ttl/AlarmsCleanUpServiceTest.java
This PR fixes the issue https://github.com/thingsboard/thingsboard/issues/8436
> Fix invalid removed outdated alarms count in logs 

- ui-ngx/src/app/modules/home/pages/edge/edge-routing.module.ts
- ui-ngx/src/app/modules/home/pages/edge/edge.component.html
- ui-ngx/src/app/modules/home/pages/edge/edges-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed incorrect translation keys for edges
before:
after:
> Improve Edge translation

- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.scss
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Copy button becomes visible on the hover effect.
> Copy button for attribute table

- ui-ngx/src/app/core/services/menu.service.ts
- ui-ngx/src/app/modules/home/pages/alarm/alarm-routing.module.ts
Change alarm menu icon.
Before:
After:
> Change alarm menu icon

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
> fixed using default timeout and improvements

- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
- dao/src/main/java/org/thingsboard/server/dao/service/NoXssValidator.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
> kv validator improvements

- application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
- application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
- application/src/test/java/org/thingsboard/server/service/stats/DevicesStatisticsTest.java
Now, devices activity stats are reported by default each 3 minutes.
Also, usage stats timeseries are saved only when a monthly value or an hourly value is changed, or when a new month or a new hour has started.
> Improvements for usage stats

- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
- ui-ngx/src/app/modules/home/pages/notification/template/template-configuration.ts
> Fixed error when we review in send notification

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
- application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
- application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/NewPlatformVersionTriggerProcessor.java
- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationTargetService.java
- common/data/src/main/java/org/thingsboard/server/common/data/CacheConstants.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/NotificationRuleTriggerType.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/VcUtils.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTargetService.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
- dao/src/main/java/org/thingsboard/server/dao/notification/NotificationTargetDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationTargetDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationTargetRepository.java
> Notifications deduplication; upgrade improvements

- ui-ngx/src/app/modules/home/pages/admin/settings-card.scss
> Fixed padding for repository settings fieldset

- ui-ngx/patches/@mat-datetimepicker+core+11.0.3.patch
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
Add support correct property timeInterval after updated library for new version
> Patch for library @mat-datetimepicker/core

- ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.html
- ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.ts
> Fixed queue autocomplete style

- common/util/pom.xml
- common/util/src/main/java/org/thingsboard/common/util/SystemUtil.java
- pom.xml
> fixed start for windows

- ui-ngx/src/app/modules/home/components/alias/aliases-entity-select.component.html
- ui-ngx/src/app/modules/home/components/alias/aliases-entity-select.component.scss
- ui-ngx/src/app/modules/home/components/alias/aliases-entity-select.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.scss
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/components/filter/filters-edit.component.scss
- ui-ngx/src/app/modules/home/components/filter/filters-edit.component.ts
- ui-ngx/src/app/shared/components/time/timewindow.component.html
- ui-ngx/src/app/shared/components/time/timewindow.component.scss
- ui-ngx/src/app/shared/components/time/timewindow.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/theme-overwrites.scss
Improve dashboard edit panel.
**Before:**
**After:**
> Improve dashboard edit panel

- ui-ngx/src/app/shared/models/ace/tbel/worker-tbel.js
https://github.com/thingsboard/tbel/issues/10
for test:
```
// Create new map
var map = {
"temperature": 42,
"smth": 22,
"nonExistingKey": {
"smth": 22
}
};
map.?nonExistingKey.smth = 15;
// Null-Safe expressions using ?
if (map.?nonExistingKey.smth > 10) {
map.smth_check = true;
} else {
map.smth_check = false;
}
// Iterate through the map
foreach(element: map.entrySet()) {
// str = " " +str+ " "+ element.key+" "+element.value
// Get the key
element.key
// // Get the value
element.value;
}
// get map size
map.size();
return {msg: map};
```
before:
after:
> [3.5.1][Fix bug]tbel: Incorrect validation syntax with null field property

- security.md
Added security.md file explaining how to report security vulnerabilities properly.
> Added security.md

- application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/DeviceActivityTriggerProcessor.java
> Check msg originator in DeviceActivityTriggerProcessor

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDriverBaseTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CustomerPageHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/AbstractDeviceTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/CreateDeviceTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeleteDeviceTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeleteSeveralDevicesTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/EditDeviceTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/rulechainssmoke/RuleChainEditMenuTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/Const.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/DataProviderCredential.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/EntityPrototypes.java
- msa/black-box-tests/src/test/resources/all.xml
- msa/black-box-tests/src/test/resources/smokeDevices.xml
- msa/black-box-tests/src/test/resources/uiTests.xml
Added device smoke tests on create device, delete one/several devices, edit device
> [3.5.1] Added UI smoke tests on devices

- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/AlarmRepository.java
removed non existed parameter `a_propagate_to_owner_hierarchy`
```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.QueryException: Named parameter not bound : 
a_propagate_to_owner_hierarchy; 
nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: Named parameter not bound : 
a_propagate_to_owner_hierarchy
```
PE: https://github.com/thingsboard/thingsboard-pe/pull/1739
> [hotfix] alarm repository: fixed tests

- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/CookieUtils.java
- application/src/test/java/org/thingsboard/server/service/security/auth/oauth2/HttpCookieOAuth2AuthorizationRequestRepositoryTest.java
Fixed security (exploit) vulnerability in CookieUtil deserialization.
> fixed cookie deserialization vulnerability

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/service/apiusage/TenantApiUsageState.java
- application/src/main/java/org/thingsboard/server/service/security/auth/mfa/provider/impl/SmsTwoFaProvider.java
- application/src/main/java/org/thingsboard/server/service/sms/DefaultSmsService.java
- application/src/test/java/org/thingsboard/server/service/sms/DefaultSmsServiceTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/UsageInfo.java
- common/data/src/main/java/org/thingsboard/server/common/data/audit/ActionType.java
- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/TenantProfileConfiguration.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/usage/BasicUsageInfoService.java
- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.scss
- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
- ui-ngx/src/app/shared/models/audit-log.models.ts
- ui-ngx/src/app/shared/models/tenant.model.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
1. Added boolean flag to tenant profile configuration to enable/disable sms messaging.
2. Added audit logging for 2-factor authentication and test sms messaging. Added trace logging for all other sms messaging.
> Added feature to disable sms messaging

- application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
- application/src/main/resources/thingsboard.yml
> added ability to disable swagger

- application/src/main/java/org/thingsboard/server/service/resource/DefaultTbResourceService.java
- application/src/main/java/org/thingsboard/server/utils/LwM2mObjectModelUtils.java
- application/src/test/java/org/thingsboard/server/service/resource/sql/BaseTbResourceServiceTest.java
- common/data/pom.xml
- common/data/src/main/java/org/thingsboard/server/common/data/util/TbDDFFileParser.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServerHelper.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
Fixed potential XXE vulnerability in thingsboard while uploading xml files in "Resources library" section by disallowing doctype in xml file.
> Fixed xxe vulnerability

- ui-ngx/src/app/modules/home/components/profile/queue/tenant-profile-queues.component.ts
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.ts
Issue: [#8528](https://github.com/thingsboard/thingsboard/issues/8528)
In this PR fixed 3 bugs with queues:
1. Fixed creating queues (Field 'Queue name' is permanently disabled).
Before:
After:
2. Fixed batch size value (After creating queue and set size different than 1000(1000 - default value) and when you open with queue in UI - batch size for all queues with BATCH strategy is always shown as 1000).
Before:
Batch size is 999.
After:
4. Removed the gap from the radio buttons.
Before:
After:
> Fixed queue bugs

- ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
- ui-ngx/src/app/shared/components/notification/notification.component.html
- ui-ngx/src/app/shared/components/notification/notification.component.ts
Fixed: [#8577](https://github.com/thingsboard/thingsboard/issues/8577)
After fix:
> Custom translate for alarm type

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDriverBaseTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CustomerPageElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/AssignDeviceTabElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/AssignDeviceTabHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/CreateDeviceTabElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/CreateDeviceTabHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/AbstractDeviceTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/AssignToCustomerTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/CreateDeviceTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeleteSeveralDevicesTest.java
Added UI smoke tests on assign devices
> [3.5.2] UI smoke tests on assign devices

- application/src/main/java/org/thingsboard/server/controller/QueueController.java
- application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
changed ServiceType.valueOf to ServiceType.of    
[Jira](https://thingsboard-portal.atlassian.net/browse/PROD-2108)
[Jira](https://thingsboard-portal.atlassian.net/browse/PROD-2110)
>  Fix swagger queue servicetype

- application/src/main/java/org/thingsboard/server/controller/UserController.java
This PR fixes a mixed API usage description.
This aims to fix / close #8594
> [3.5.1] Fix api documentation

- ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-widget-settings.component.html
Fixed: [#8646](https://github.com/thingsboard/thingsboard/issues/8646)
Before fix:
After fix:
> Fixed Chart widget legend settings expansion panel

- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
Fixed: [#8669](https://github.com/thingsboard/thingsboard/issues/8669)
Fixed alarm table first loading.
Before fix:
After fix:
> Fixed infinite loading alarm table

- packaging/java/scripts/windows/install.bat
> jdk 17 for windows

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractBasePage.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDriverBaseTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/AlarmDetailsEntityTabElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CustomerPageHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DashboardPageElements.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DashboardPageHelper.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/alarmassignee/AbstractAssignTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/alarmassignee/AssignDetailsTabAssignTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/alarmassignee/AssignDetailsTabFromCustomerAssignTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/alarmassignee/AssignFromAlarmWidgetTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CreateCustomerTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CustomerEditMenuTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeviceFilterTest.java
- msa/black-box-tests/src/test/resources/alarmAssignee.xml
- msa/black-box-tests/src/test/resources/all.xml
- msa/black-box-tests/src/test/resources/uiTests.xml
Fixed UI tests, added assignee alarm tests to all.xml and uiTests.xml suites
> [3.5.2] Fix for UI tests

- common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationId.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationRequestId.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationRuleId.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationTargetId.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationTemplateId.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/QueueId.java
Some of models are not correctly configured in swagger and it affects swagger UI examples and Python REST client generation.
PE PR - https://github.com/thingsboard/thingsboard-pe/pull/1791
> Fixes for models in Swagger

- pom.xml
Updated version of azure-servicebus java sdk that produced issues with CBS Token Timeouts.
[ce_mvn_tree_after.txt](https://github.com/thingsboard/thingsboard/files/11634318/ce_mvn_tree_after.txt)
[ce_mvn_tree_before.txt](https://github.com/thingsboard/thingsboard/files/11627465/ce_mvn_tree_before.txt)
> Updated version of azure-servicebus java sdk

- ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
- ui-ngx/src/app/shared/components/notification/template-autocomplete.component.html
- ui-ngx/src/app/shared/components/notification/template-autocomplete.component.ts
> Added the option to edit notification templates in the template selector

- common/util/src/main/java/org/thingsboard/common/util/AzureIotHubUtil.java
> fixed azure root ca load

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
> [Hotfix] Check edge session before removal to avoid removing live session

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
- ui-ngx/src/app/shared/models/ace/tbel/worker-tbel.js
befor:
- If you open the edit script
-  If you press test
- logs:
```
2023-06-09 14:51:34,385 [tbel-executor-57-1] WARN  o.t.s.a.AbstractScriptInvokeService - Script has exception counter 1 on disabledFunctions for id ff2e02c5-7986-4029-b88e-64166a0ad8d0, exception [Error: Unterminated statement!]
[Near : {...  ....}]
^
[Line: 6, Column: 2]
```
after:
- If you open the edit script
-  If you press test
- logs:
```
2023-06-09 15:10:04,531 [tbel-executor-57-1] WARN  o.t.s.a.AbstractScriptInvokeService - Script has exception counter 1 on disabledFunctions for id 730a5fb5-1525-462d-a5af-c1aaf82345c4, exception [Error: TBEL does not support the 'switch'.]
[Near : {...  ....}]
^
[Line: 6, Column: 2]
```
> [FIX_BUG][3.5.1] switch: add validation to tbel

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
```
var value = hexToBytes("41EA62CC");
var intVal = parseBytesToInt(value, 0, 4);
var valueRev = hexToBytes("CC62EA41");
var floatValBigEndianDef = parseBytesToFloat(value, 0);
var floatValBigEndian = parseBytesToFloat(value, 0, true);
var floatValLitleEndian = parseBytesToFloat(value, 0, false);
var floatValLitleEndianRevToFixed_3 = toFixed(parseBytesToFloat(valueRev, 0, false), 3);
var list = [65, -22, 98, -52];
var floatListBigEndianDef = parseBytesToFloat(list, 0);
var floatListBigEndian = parseBytesToFloat(list, 0, true);
var floatListLitleEndian = parseBytesToFloat(list, 0,  false);
return {
msg: {
bytes: {
bytes: value,
intVal: intVal,
floatValBigEndianDef: floatValBigEndianDef,
floatValBigEndian: floatValBigEndian,
floatValLitleEndian: floatValLitleEndian, …
```
> tbel: add parseBytesToFloat

- ui-ngx/src/app/core/auth/auth.service.ts
- ui-ngx/src/app/core/http/notification.service.ts
- ui-ngx/src/app/core/services/menu.service.ts
- ui-ngx/src/app/modules/home/menu/side-menu.component.html
- ui-ngx/src/app/modules/home/menu/side-menu.component.ts
- ui-ngx/src/app/modules/home/pages/account/account-routing.module.ts
- ui-ngx/src/app/modules/home/pages/account/account.module.ts
- ui-ngx/src/app/modules/home/pages/home-pages.module.ts
- ui-ngx/src/app/modules/home/pages/notification/notification.module.ts
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.html
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.scss
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.ts
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings-routing.modules.ts
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.html
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.scss
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
- ui-ngx/src/app/modules/home/pages/profile/profile-routing.module.ts
- ui-ngx/src/app/modules/home/pages/security/security-routing.module.ts
- ui-ngx/src/app/shared/components/user-menu.component.html
- ui-ngx/src/app/shared/components/user-menu.component.ts
- ui-ngx/src/app/shared/models/notification.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed: [#8818](https://github.com/thingsboard/thingsboard/issues/8818)
Change log:
1. Change “Profile” to “Account”;
2. Remove “Security” from the list and transfer to Account;
3. Add user notification settings.
> User notification settings

- ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.html
- ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.ts
Fixed: [#8737](https://github.com/thingsboard/thingsboard/issues/8737)
Before fix:
After fix:
> Fixed OAuth2 deletion domains/mobile applications/providers settings

- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.scss
Fixed: [#8820](https://github.com/thingsboard/thingsboard/issues/8820)
Before fix:
After fix:
> Added z-index for selected rule node

- ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts
Fix for Analogue gauge widgets for cases when the value is decimal numeric that ends with zeros (e.g. 42.0) - the value was not displayed correctly.
PROD-2207 issue description: https://thingsboard-portal.atlassian.net/browse/PROD-2207
PE pr: https://github.com/thingsboard/thingsboard-pe/pull/1828
> [3.5.2] Fix prod-2207: display correctly analogue gauge values

- ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarm.component.scss
Fixed: [#8827](https://github.com/thingsboard/thingsboard/issues/8827)
If the condition of Clear alarm rule is too long, the View and Edit buttons aren't displayed.
Before fix:
After fix:
> Fixed width Clear alarm rule section

- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
> Fixed Timeseries table widget display columns without sources

- application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/AlarmTriggerProcessor.java
- common/data/src/main/java/org/thingsboard/server/common/data/alarm/Alarm.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/info/AlarmNotificationInfo.java
- ui-ngx/src/app/shared/components/notification/notification.component.html
- ui-ngx/src/app/shared/components/notification/notification.component.ts
- ui-ngx/src/app/shared/models/notification.models.ts
Remove notification color selection for cleared alarms notification
Before:
After:
> Remove specify alarm notification style for cleared alarm notification

- ui-ngx/src/app/shared/models/time/time.models.ts
Fixed #8833 
Before:
When selecting 'previous quarter' and 'previous half year'  intervals in timewindow, the widget remains in the loading state, and appropriate data is not fetched.
After:
Widget data is loaded appropriately to a selected interval, and no errors appear.
> Fixed loading widget data for 'previous quarter' and 'previous half year' timewindow intervals

- application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
Put your PR description here instead of this sentence.   (https://thingsboard-portal.atlassian.net/browse/PROD-1395)
After:
- CREDENTIALS ACCESS_TOKEN with deviceProfile ID
```
{
"device": {
"name":"Name_DeviceWithCredantial_AccessToken",
"label":"Label_DeviceWithCredantial_AccessToken",
"deviceProfileId":{
"id":"9d9588c0-06c9-11ee-b618-19be30fdeb60",
"entityType":"DEVICE_PROFILE"
}
},
"credentials": {
"credentialsType": "ACCESS_TOKEN",
"credentialsId": "6hmxew8pmmzng4e3une2"
}
}
```
```
curl -X 'POST' \
'http://localhost:8080/api/device-with-credentials' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwidXNlcklkIjoiOWQxODY5ODAtMDZjOS0xMWVlLWI2MTgtMTliZTMwZmRlYjYwIiwic2NvcGVzI …
```
> [fix_bug][3.5.2] swagger_device_controller: regactoring example request "create device with credential"

- application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
- common/message/src/main/java/org/thingsboard/server/common/msg/MsgType.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNode.java
Under certain conditions init of rule chains happens before APP_INIT message arrived into actor system.
As a result - incorrect state of rule nodes during init phase because of HashPartitionService is not ready yet.
> HotFix - fixed init of rule chains - init only on APP_INIT msg

- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.html
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.ts
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
- ui-ngx/src/app/shared/models/notification.models.ts
> User notification settings by notification type

- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/SaveDeviceWithCredentialsRequest.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
Fixed validations and saving device with the same name.
> fixed saveDeviceWithCredentials api

- ui-ngx/src/app/core/http/attribute.service.ts
- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
- ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.html
- ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.scss
- ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.ts
- ui-ngx/src/app/modules/home/components/home-components.module.ts
- ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
- ui-ngx/src/assets/locale/locale.constant-ca_ES.json
- ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
- ui-ngx/src/assets/locale/locale.constant-da_DK.json
- ui-ngx/src/assets/locale/locale.constant-de_DE.json
- ui-ngx/src/assets/locale/locale.constant-el_GR.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-es_ES.json
- ui-ngx/src/assets/locale/locale.constant-fa_IR.json
- ui-ngx/src/assets/locale/locale.constant-fr_FR.json
- ui-ngx/src/assets/locale/locale.constant-it_IT.json
- ui-ngx/src/assets/locale/locale.constant-ja_JP.json
- ui-ngx/src/assets/locale/locale.constant-ka_GE.json
- ui-ngx/src/assets/locale/locale.constant-ko_KR.json
- ui-ngx/src/assets/locale/locale.constant-lv_LV.json
- ui-ngx/src/assets/locale/locale.constant-pt_BR.json
- ui-ngx/src/assets/locale/locale.constant-ro_RO.json
- ui-ngx/src/assets/locale/locale.constant-sl_SI.json
- ui-ngx/src/assets/locale/locale.constant-tr_TR.json
- ui-ngx/src/assets/locale/locale.constant-uk_UA.json
- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
- ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Delete entity timeseries by 4 strategies:
- Delete all data including key
- Delete old data except latest value
- Delete latest value
- Delete data for time period
> [3.5.2] [UI] Delete entity timeseries data

- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
> Improvement for entity autocomplete

- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
- dao/src/test/java/org/thingsboard/server/dao/service/EntityServiceTest.java
Fixed user phone display in entities table
Jira: https://thingsboard-portal.atlassian.net/browse/PROD-2238
> Fixed user phone display in entities table

- ui-ngx/src/app/core/ws/public-api.ts
Added public-api for websocket services. Exported notification-websocket and websocket services
> Added public-api for websocket services. 

- ui-ngx/src/app/shared/components/js-func.component.html
Added the opportunity to create custom buttons for js-function.
> Added ng-content to js-func conponent

- ui-ngx/src/app/modules/home/components/widget/lib/legend.component.scss
Show cursor pointer on hover in LegendComponent.
PE pr: https://github.com/thingsboard/thingsboard-pe/pull/1872
Before
After:
> LegendComponent show cursor pointer on hover

- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
PE pr: https://github.com/thingsboard/thingsboard-pe/pull/1871
> Widget Entities Table: show pointer if row has click action

- ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.html
- ui-ngx/src/assets/locale/locale.constant-ca_ES.json
- ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
- ui-ngx/src/assets/locale/locale.constant-da_DK.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-es_ES.json
- ui-ngx/src/assets/locale/locale.constant-fr_FR.json
- ui-ngx/src/assets/locale/locale.constant-ko_KR.json
- ui-ngx/src/assets/locale/locale.constant-sl_SI.json
- ui-ngx/src/assets/locale/locale.constant-tr_TR.json
- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
- ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Change label 'Customer to assign the device' to 'Assign to customer'.
> Change field label assign customer

- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.scss
Fixed: [#8986](https://github.com/thingsboard/thingsboard/issues/8986)
Before fix:
Fixed list:
- Fixed hide alarm type item behind three dots if label is too long.
- Added scroll to panel if it expands beyond the screen.
- Added adaptive for small screen.
> Fixed alarm filter panel

- ui-ngx/src/assets/locale/locale.constant-ca_ES.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-es_ES.json
- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
- ui-ngx/src/assets/locale/locale.constant-zh_TW.json
> Add double quotes to highlight 'remove other entities' confirm phrase in version control dialog

- application/src/main/resources/thingsboard.yml
- dao/src/main/java/org/thingsboard/server/dao/nosql/CassandraAbstractAsyncDao.java
- dao/src/main/java/org/thingsboard/server/dao/util/AbstractBufferedRateExecutor.java
* Cassandra: unlimited cached thread pool replaced with limited pool to prevent stack memory peaks. New env CASSANDRA_QUERY_RESULT_PROCESSING_THREADS introduced.
* Cassandra: AbstractBufferedRateExecutor improved logging to clarify whether the Read or Write operations logged 
This intended to fix memory consumption and overall stability under the high load (see the picture below)
PE: https://github.com/thingsboard/thingsboard-pe/pull/1891
> Feature/ Cassandra unlimited cached thread pool replaced with limited pool to prevent stack memory peaks

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/ZkDiscoveryService.java
- common/queue/src/test/java/org/thingsboard/server/queue/discovery/ZkDiscoveryServiceTest.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
If node removed then better to wait some time instead of immediately partitions recalculation. Its helpful for rollout restart.
> added recalculatePartitions delay for node restarting

- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Added "Debug sign" for messages with errors in rule nodes. It will be useful to test messages with errors with current script in rule node.
> Enabled test with this message for OUT messages with errors

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttGatewayClientTest.java
- netty-mqtt/pom.xml
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttChannelHandler.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClient.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientConfig.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttHandler.java
- netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttSubscription.java
- netty-mqtt/src/test/java/org/thingsboard/mqtt/integration/MqttIntegrationTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
Please, review this on downstream the https://github.com/thingsboard/thingsboard-pe/pull/1886
* mqtt-client: messages processing moved from netty event loop pool and to the handlerExecutor to make netty handlers non-blocking
* MqttHandler - processAsync (for AbstractMqttIntegration)
> MQTT client channel handler invoke handlers for incoming publish (master branch base)

- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaProducerTemplate.java
- common/queue/src/test/java/org/thingsboard/server/queue/kafka/TbKafkaProducerTemplateTest.java
- common/queue/src/test/resources/logback-test.xml
TbKafkaProducerTemplate will add headers for each message when the log level: 
* DEBUG - producer Id and thread name; 
* TRACE - stack trace first 10-2=**8 lines**
Kafka compression is highly recommended before you enable this feature.
To enable, adjust `logback.xml`
```
<logger name="org.thingsboard.server.queue.kafka.TbKafkaProducerTemplate" level="DEBUG"/>
```
or for a very short time:
```
<logger name="org.thingsboard.server.queue.kafka.TbKafkaProducerTemplate" level="TRACE"/>
```
The content of additional headers will look like in the picture below:
Lines 0 and 1 will be always skipped because those are internal methods
PE: https://github.com/thingsboard/thingsboard-pe/pull/1888
> TbKafkaProducerTemplate will add analytics headers for each message on debug or trace log level

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
- pom.xml
- ui-ngx/src/app/shared/models/ace/tbel/worker-tbel.js
- Tbel rollback validation switch
- Add switch to tbel:
` <tbel.version>1.0.7</tbel.version>`
> [3.5.2]Tbel_rollback_validation_switch

- ui-ngx/src/app/shared/components/entity/entity-select.component.ts
Fixed: [#8964](https://github.com/thingsboard/thingsboard/issues/8964)
Add to several devices relation contains tenant.
Before fix:
Change as example device type (remove default).
After fix:
Change as example device type (remove default).
> Fixed entity select component for alias dialog component

- ui-ngx/src/app/core/services/utils.service.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.html
- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.scss
- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
> Fixed resize alarm filter config component

- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/TelemetryControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeUtils.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
Added optional noxss validation for attribute/telemetry value
> Added optional noxss validation for attribute/telemetry value

- ui-ngx/src/app/shared/components/phone-input.component.scss
> Aligned phone input flags container by input field

- ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarm.component.scss
> Fixed layout for clear alarm rule

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/ZkDiscoveryService.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Updated default value and added short description for recalculate_delay property.
> updated recalculate_delay

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNodeConfiguration.java
Updated default math node config to show an example of real case scenario instead of simple 2+2(Addition).
New config will handle transforming Fahrenheit to Celsius temperatureCelsius= (temperature - 32) / 1.8 using CUSTOM operation and expression: (x - 32) / 1.8).
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/1922
> Updated default config for math node

- ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
- ui-ngx/src/app/modules/home/components/relation/relation-filters.component.scss
- ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-key-row.component.html
- ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-keys-panel.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/add-rule-node-dialog.component.scss
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.scss
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
- ui-ngx/src/app/shared/components/entity/entity-type-list.component.html
- ui-ngx/src/app/shared/components/entity/entity-type-list.component.ts
- ui-ngx/src/app/shared/components/help-popup.component.html
- ui-ngx/src/app/shared/components/help-popup.component.scss
- ui-ngx/src/app/shared/components/help-popup.component.ts
- ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.html
- ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.ts
- ui-ngx/src/app/shared/components/string-items-list.component.html
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/form.scss
- ui-ngx/src/styles.scss
Added style options according to rule node design. Changed Relation filters style, added hintMode to the helper button, added help tooltips to chip fields(optional).
Before:
After:
Help button in hintMode (smaller padding and icons, now can be put in one line with hint text): 
Added the opportunity to create additional buttons for chip components:
> Updated components that using in enrichment/filter rule nodes 

- common/data/src/main/java/org/thingsboard/server/common/data/msg/TbMsgType.java
- common/data/src/test/java/org/thingsboard/server/common/data/msg/TbMsgTypeTest.java
- common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbMsgTypeSwitchNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbMsgTypeSwitchNodeTest.java
Added internalType field to TbMsg to have the ability to use switch-cases instead of if-return blocks.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/1920
> Added internalType field to TbMsg to have the ability to use switch-cases instead of if-return blocks.

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
The first two commits are made to prove the blocking issue by the same originator.
With dispatcher pool size 2 = 2 parallel msgs by the same slow originator - processing blocked
With dispatcher pool size 3 > 2 parallel msgs by the same slow originator - processing happens (but with reduced parallelism)
A fix required
UPD: After the fix was implemented test passed.
> Math node sequential non blocking

- pom.xml
- ui-ngx/src/app/shared/models/ace/tbel/worker-tbel.js
Examples:
```
var input = [-1, -7, -3, -4];
var output = 9;
var outputY = 19;
for (var i = 0; i < input.size; i++) {
output = i * 10;
if (i === 3) {
output = input[i];
break;
output = i * 100;
} else if (i === 0) {
outputY = 19;
for (var y = 0; y < input.size; y++) {
outputY = y * 10 * 2;
if (y === 1) {
outputY = input[y];
break;
outputY = y * 100 * 2;
}
outputY = y * 1000 * 2;
}
}
output = i * 1000;
}
return {msg: [output, outputY],  metadata: metadata, msgType: msgType};
```
```
var input = [-1, -7, -3, -4];
var output = 9;
var outputY = 19;
var i = 0;
var y = 0;
foreach(a: input) {
output = i * 10;
if (i === 3) {
output = input[i];
break;
output = i * 100;
} else if (i === 0) {
outputY = 19;
y = 0;
foreach(b: input) {
outputY = y * 10 * 2;
if (y === 1) {
outputY = input[y];
break; …
```
> [fix_bug][3.5.2]tbel:  add break to for, foreach

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNode.java
During the merge to the cloud, I found that some obsolete code left since the last PR. Code cleaned
> TbMathNode code cleanup

- application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/BaseEntityExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DashboardExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/RuleChainExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DashboardImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/RuleChainImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
- common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
This PR fixes the following issues:
- error when importing Asset Profiles and Rule Chains at the same time (https://github.com/thingsboard/thingsboard/issues/8806)
- UUIDs in rule node configuration replaced with tenant id on version load
Also, default timeouts related to VC were increased.
> Fixes for Version Control

- ui-ngx/yarn.lock
Update flot lib after merge: [#4](https://github.com/thingsboard/flot/pull/4)
> Update flot lib

- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Change:
- Update install for HTTP (Curl already installed since the 10.2 version of MacOS 2002 year)
Before:
After:
- Update install command for MQTT.
Before:
After:
> Update device connectivity HTTP/MQTT install for MacOS

- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
- ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
- ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
- ui-ngx/src/app/modules/home/components/relation/relation-table.component.html
- ui-ngx/src/app/modules/home/components/relation/relation-table.component.ts
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.html
- ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-hierarchy-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-hierarchy-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
- ui-ngx/src/app/modules/home/home.component.html
- ui-ngx/src/app/modules/home/home.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
- ui-ngx/src/app/shared/models/page/page-link.ts
> Improvement search in the platform added ignore space symbols in the start and end search text

- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
> Rename selector matSuffix in entity-subtype-list.component

- application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
- application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
Edge Attribute Request processing - added support of JSON attributes properly: use JSON type instead of String
> Edge Attribute Request processing - added support of JSON attributes

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.scss
Fixed padding for multiple input widget with enabled group settings.
Before fix:
After fix:
> Fixed padding for multiple input widget

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
Math node tests refactored
Implemented ParametrizedTests instead reset mocks
1000 times Parametrized tests run looks ok:
> [3.5.2] Math node tests refactoring

- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Fixed Columns to display panel get title based on label, not name. Also, this title supported custom translation.
Before fix:
After fix:
> Timeseries table widget columns display fixed columns name

- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
Remove Microsoft teams delivery type from Notification settings.
> Remove Microsoft teams from Notification settings

- ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
>  Remove close search fields in entities table when empty

- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
> Fix event table rule node event table columns overlap

- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Added missing translation for tenant profile details

- ui-ngx/src/app/modules/home/pages/profile/profile.component.html
- ui-ngx/src/app/modules/home/pages/user/user.component.html
- ui-ngx/src/app/shared/components/contact.component.html
Added type email for email input fields.
> Added type email for input

- ui-ngx/src/app/core/api/entity-data-subscription.ts
- ui-ngx/src/app/core/api/widget-subscription.ts
- ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
Fixed: [#9067](https://github.com/thingsboard/thingsboard/issues/9067).
Before fix:
-add latest widgets with aggregation and change real-time timewidow.
After fix:
-after changing timewindow widgets work fine.
> Fixed infinite loading for latest widgets with aggregation on change timewindow
