- ui-ngx/src/app/modules/home/pages/rulechain/add-rule-node-dialog.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.scss
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
- ui-ngx/src/app/shared/models/rule-node.models.ts
Pull Request description
Angular 15 migration caused UI bug for disabled rule node configuration controls. Issue details described https://github.com/angular/angular/issues/48350#issuecomment-1405900515
Screenshot of the rule node configuration for tenant user without readOnly permissions:
Before:
After:
> Fix for showing disabled form controls in rule nodes

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
- ui-ngx/src/styles.scss
> Fixed show/hide action and style timeseries table widgets

- pom.xml
- in Function **result**: "unable to resolve variable 'a'"
```
var output = 0;
output = testBreak(output);
for (var a = 0; a < 10; a++) {
}
for (var y = 0; y < 2; y++) {
output++;
}
for (var r = 0; r < 10; r++) {
}
return {
msg: [output], metadata: metadata, msgType: msgType
};
function testBreak(val) {
for (var a = 0; a < 5; a++) {
output++;
}
val = output;
for (var r = 0; r < 9; r++) {
val++;
}
return val;
}
```
- in Function **result**: "Infinite Loops For" -> Should throw ScriptExecutionStoppedException
```
var output = 0;
for (var a = 0; a < 100; a++) {
output = testBug(output);
}
output = testBug(output);
return {
msg: [output], metadata: metadata, msgType: msgType
};
function testBug(val) {
for (var a = 0; a< 9; a++) {
val++;
}
return val;
}
```
> [fix_bug][3.5.2]tbel_unable resolve function with for

- application/src/main/java/org/thingsboard/server/config/CryptoConfig.java
- application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
- application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
- application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsService.java
- application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
- application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/security/auth/JwtTokenFactoryTest.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
> Notification to sysadmin when default JWT signing key is used

- common/script/script-api/src/main/java/org/thingsboard/script/api/AbstractScriptInvokeService.java
…
before with NO tenant
after:
> AbstractScriptInvokeService: tenantId added to the log on script invocation blocked

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNodeConfiguration.java
> fix math node default config argument name issue because UI have strict order of arguments

- ui-ngx/src/app/core/services/utils.service.ts
- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
- ui-ngx/src/app/shared/components/popover.component.ts
- ui-ngx/src/app/shared/components/popover.models.ts
- ui-ngx/src/app/shared/components/time/quick-time-interval.component.scss
- ui-ngx/src/app/shared/components/time/timewindow.component.ts
- ui-ngx/src/app/shared/models/overlay.models.ts
- ui-ngx/src/app/shared/models/public-api.ts
> Improved timewindow position

- ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
- ui-ngx/src/app/shared/models/rule-node.models.ts
> Fixed set disabled state for rule node configuration

- ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.component.scss
Fixed blur icon when enabled overlay
Before:
After:
> Fixed blur icon in value card widget in vertical layout

- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-widget-settings.component.html
> Fix for entities table config 'Display entity label column' input disabled

- ui-ngx/src/app/modules/common/modules-map.ts
> Fixed pipes in modules map

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Bug: if pie flot has datasource with multiple entities, on slice click action that navigates to another dashboard state with setting entity from widget only the first entity is taken.
**BEFORE**
**AFTER**
> Fix for pie flot widget slice click action

- ui-ngx/src/app/shared/components/entity/entity-type-list.component.html
- ui-ngx/src/assets/locale/locale.constant-ca_ES.json
- ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
- ui-ngx/src/assets/locale/locale.constant-da_DK.json
- ui-ngx/src/assets/locale/locale.constant-de_DE.json
- ui-ngx/src/assets/locale/locale.constant-el_GR.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-es_ES.json
- ui-ngx/src/assets/locale/locale.constant-fa_IR.json
- ui-ngx/src/assets/locale/locale.constant-fr_FR.json
- ui-ngx/src/assets/locale/locale.constant-it_IT.json
- ui-ngx/src/assets/locale/locale.constant-ja_JP.json
- ui-ngx/src/assets/locale/locale.constant-ka_GE.json
- ui-ngx/src/assets/locale/locale.constant-ko_KR.json
- ui-ngx/src/assets/locale/locale.constant-lv_LV.json
- ui-ngx/src/assets/locale/locale.constant-pt_BR.json
- ui-ngx/src/assets/locale/locale.constant-ro_RO.json
- ui-ngx/src/assets/locale/locale.constant-ru_RU.json
- ui-ngx/src/assets/locale/locale.constant-sl_SI.json
- ui-ngx/src/assets/locale/locale.constant-tr_TR.json
- ui-ngx/src/assets/locale/locale.constant-uk_UA.json
- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
- ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Updated required error text for the tb-entity-type-list component according to the new design.
> Update required error text for the entity type select

- ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
> Fixed show hint in custom property for queue settings

- common/data/src/main/java/org/thingsboard/server/common/data/queue/ProcessingStrategy.java
- common/data/src/main/java/org/thingsboard/server/common/data/queue/SubmitStrategy.java
- dao/src/test/java/org/thingsboard/server/dao/service/TenantProfileServiceTest.java
This fixes the following error:
```
[edge-event-check-scheduler-61-thread-1] ERROR o.t.s.s.edge.rpc.EdgeGrpcSession - [bc7138f0-382b-11ee-b6c5-dd8cce90d040][217f73b2-867b-4a07-b301-60c02676b546] Exception during converting edge event to downlink msg
java.lang.RuntimeException: Class org.thingsboard.server.common.data.queue.ProcessingStrategy does not implement Serializable or externalizable
at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)
at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext …
```
> Fix tenant profile update msg construction for Edge

- ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
Before saving the dashboard:
**Before fix** _After saving the dashboard_**:**
**After fix** _After saving the dashboard_**:**
> Fixed widget import in the dashboard when the duplicate IDs

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityConfiguration.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
Download cert improvements for unknown protocols.
> download cert improvements

- application/src/test/java/org/thingsboard/server/controller/AlarmCommentControllerTest.java
> Alarmcomment test fix

- ui-ngx/src/app/modules/home/components/filter/filter-predicate-list.component.html
- ui-ngx/src/app/modules/home/components/filter/key-filter-list.component.html
> Fixed min height with hint for alarm rule key filters row

- ui-ngx/src/app/core/auth/auth.service.ts
> Fixed auth service function updatedAuthUserFromToken when authUser and tokenData in null

- application/src/main/data/json/edge/rule_chains/edge_root_rule_chain.json
- application/src/main/data/json/tenant/device_profile/rule_chain_template.json
- application/src/main/data/json/tenant/rule_chains/root_rule_chain.json
- application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
- application/src/test/java/org/thingsboard/server/service/install/InstallScriptsTest.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/RuleChainDataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/validator/RuleChainDataValidatorTest.java
Tests added to validate DefaultRuleChains and EdgeDefaultRuleChains JSON templates
Tests fail when "version" is located in the `configuration` tree.
The correct node version has to be above the `configuration` tree with the name `configurationVersion`
See `org.thingsboard.server.common.data.rule.RuleNode` class for field names.
test added for device profile default rule chain as well:
> Set Attribute node version in rule chain templates

- build_proto.sh
`./build_proto.sh` was added to improve developer performance.
Usage: `./build_proto.sh`
> Building ThingsBoard protobuf-containing packages script

- ui-ngx/src/app/modules/home/components/attribute/add-attribute-dialog.component.html
- ui-ngx/src/app/modules/home/components/attribute/add-attribute-dialog.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Fixed add telemetry dialog validation hints

- application/src/test/java/org/thingsboard/server/controller/TelemetryControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
Added validation on space key for telemetry and attributes
> Added validation on space key for telemetry and attributes

- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/AbstractRuleChainMetadataConstructor.java
- application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
- common/edge-api/src/main/proto/edge.proto
Edge RuleNodeProto - added singletonMode and configurationVersion fields.
> Add singletonMode and configurationVersion Fields to Edge RuleNodeProto

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
> Isolated queues: fix partitions recalculation

- ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
> fixed home page device activity widget

- ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
Reverts thingsboard/thingsboard#9250
> Revert "fixed home page device activity widget"

- ui-ngx/src/styles.scss
The highlighting of entity row is divided in all thingsboard tables when hovering or focusing etc.
BEFORE : 
AFTER :
To fix this issue mat-mdc-cell background: inherit was changed to -> background-color: transparent to avoid color overlapping between row and cell.
> Bug fix/table cell global style

- ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
- ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.ts
- ui-ngx/src/app/shared/models/websocket/notification-ws.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Added notification popover loadings state

- ui-ngx/src/app/shared/components/string-items-list.component.html
- ui-ngx/src/app/shared/components/string-items-list.component.ts
- ui-ngx/src/theme-overwrites.scss
> Added default color for mat-hint; Added onTouch event for string items list component

- ui-ngx/src/app/core/services/dashboard-utils.service.ts
Fixed initial datasource name for the new widget.
Before fix:
After fix:
Already saved widget:
Widget library config:
> Remove initial name from datasource

- application/src/main/java/org/thingsboard/server/actors/service/DefaultActorService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
- application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
- common/message/src/main/java/org/thingsboard/server/common/msg/queue/PartitionChangeMsg.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/event/PartitionChangeEvent.java
Changes:
- fixed partitions recalculation when **turning off** tenant profile isolation
- single partition change event after `recalculatePartitions` call
- fixed startup of isolated rule engines when there is no generic rule engines yet
> PartitionService improvements

- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/AssetEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/CustomerEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/EdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/EntityViewEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/TelemetryEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/UserEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
- application/src/test/resources/application-test.properties
- dao/src/test/resources/sql/system-test-psql.sql
Edge tests stability improvements:
- seq_id column remove maxvalue
- increased timeoutt for waiting on edge imitator responses
> Edge tests stability improvements

- ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.scss
Edge instructions updates:
- set tabs position sticky
- code wrapper change background, border
- copy button change color
Before:
After:
> Edge install instructions minor updates

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Minor gateway fixes

- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.scss
> Fixed toggle node library button for safari

- ui-ngx/src/app/shared/components/help-popup.component.html
Fixed button type to help popup
> Add type "button" for help popup

- ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.scss
> Fix missed style for delete timeseries panel

- ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
> Add support import widgets bundles in old format

- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
- dao/src/main/resources/sql/schema-entities.sql
Updated db schema version from 3.5.2 to 3.6.0
> Updated db schema version from 3.5.2 to 3.6.0

- dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
- dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
- dao/src/test/java/org/thingsboard/server/dao/service/WidgetTypeServiceTest.java
We had an error after removing all widget types from a bundle!
> fixed delete all types from widgets bundle

- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/WidgetTypeExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/WidgetTypeImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/WidgetsBundleImportService.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
- common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/WidgetTypeExportData.java
- ui-ngx/src/app/shared/models/vc.models.ts
> fixed widget-bundle import and added widget type VC support

- application/src/main/data/upgrade/3.6.0/schema_update.sql
- application/src/main/java/org/thingsboard/server/service/ttl/AlarmsCleanUpService.java
- application/src/main/java/org/thingsboard/server/service/ttl/NotificationsCleanUpService.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationRequestService.java
- dao/src/main/java/org/thingsboard/server/dao/notification/NotificationDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/insert/sql/SqlPartitioningRepository.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
- dao/src/main/resources/sql/schema-entities-idx.sql
- dao/src/main/resources/sql/schema-entities.sql
> Performance improvements for notification center 

- application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
> Fix failing tests

- .github/workflows/check-configuration-files.yml
> Update and rename main.yml to check-configuration-files.yml

- common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/entityview/EntityViewService.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardDao.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsDao.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/entity/AbstractEntityService.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewDao.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/service/PaginatedRemover.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/EntityAlarmRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/DashboardRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/JpaDashboardDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/device/DeviceCredentialsRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceCredentialsDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/entityview/EntityViewRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/entityview/JpaEntityViewDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/user/JpaUserCredentialsDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/user/UserCredentialsRepository.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserCredentialsDao.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
Deletion of tenant with 500 devices on QA cluster is now faster by 30% (35 seconds avg instead of 50).
> Improvements for tenant deletion

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
**BEFORE**
[Screencast from 12.10.23 18:18:02.webm](https://github.com/thingsboard/thingsboard/assets/87172504/2a1b2c59-1086-44d3-ab00-23d699c3645d)
**AFTER**
[Screencast from 12.10.23 18:19:18.webm](https://github.com/thingsboard/thingsboard/assets/87172504/536c1242-bd63-4eab-84ad-67758beed9fe)
> Fix chart widgets color transparency not working in hex and hsla formats

- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
- ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.ts
> Enabled all delete strategies for multiple delete timeseries UI

- ui-ngx/src/app/modules/home/components/profile/tenant-profile-dialog.component.html
- ui-ngx/src/app/modules/home/components/profile/tenant-profile-dialog.component.scss
- ui-ngx/src/app/modules/home/components/profile/tenant-profile-dialog.component.ts
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
Remove unnecessary padding for tenant profile dialog;
Fixed layout for queue form.
Before fix:
After fix:
> Fixed tenant profile dialog

- ui-ngx/src/app/modules/home/components/profile/tenant-profile-autocomplete.component.html
Fixed: [#8978](https://github.com/thingsboard/thingsboard/issues/8978)
Before fix:
After fix:
> Fixed tenant profile autocomplete hide edit button and add create new button

- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.html
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.ts
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.html
- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
> Improvement for notification settings

- ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarms-table-basic-config.component.html
Fixed: [#9371](https://github.com/thingsboard/thingsboard/issues/9371)
Before fix:
After fix:
> Alarm table settings replace alarm source

- ui-ngx/src/app/core/auth/auth.service.ts
Fixed: [#9330](https://github.com/thingsboard/thingsboard/issues/9330)
After fix:
German profile:
Log in as Tenant user with English profile (without reload page):
> Fixed translation on change lang

- ui-ngx/src/app/modules/home/components/filter/key-filter-dialog.component.ts
- ui-ngx/src/app/shared/models/query/query.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added Client/Server/Shared attribute as key types for filter list.
> Added client/server/shared attribute to key filter

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
Connector RPC params hotfix
Passing params into request from params fix
> Connector RPC parаms hotfix

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
Connector RPC params hotfix
Default value of params now is '{}' instead of {} for correct displaying in the input filed
> PRC params json hotfix

- application/src/main/java/org/thingsboard/server/service/queue/TbCoreConsumerStats.java
- application/src/test/resources/application-test.properties
PE: https://github.com/thingsboard/thingsboard-pe/commits/hotfix/3.6
> TbCoreConsumerStats: core notifications stats by message type

- application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
> DefaultNotificationRuleProcessor - submit to executor sooner

- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaProducerTemplate.java
TbKafkaProducerTemplate: addAnalyticHeaders - stacktrace level increased from 10 to 20 for TRACE enabled
In practice, ten lines is not enough for some cases
It will look like that, but more lines:
> TbKafkaProducerTemplate: addAnalyticHeaders - stacktrace level increased from 10 to 20 for TRACE enabled

- application/src/main/java/org/thingsboard/server/controller/DeviceConnectivityController.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerWithDefaultPortTest.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Renamed mqtts ca file for device connectivity
> Renamed mqtts ca file for device connectivity

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/rule/RuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/rule/RuleNodeDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/rule/JpaRuleNodeDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/rule/RuleNodeRepository.java
- dao/src/test/java/org/thingsboard/server/dao/sql/rule/JpaRuleNodeDaoTest.java
- Fix rule node upgrade script logic to have ability upgrade more then 1024 rule nodes of the same type.
- Simplify logic by adding new DAO API. 
- Added tests for new DAO API 
PE PR:
> fixed rule nodes upgrade script 

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/TbRuleEngineConsumerStats.java
- application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/QueueEvent.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbQueueConsumerManagerTask.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbQueueConsumerTask.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineConsumerContext.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManager.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
- application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
- common/cluster-api/src/main/java/org/thingsboard/server/queue/TbQueueConsumer.java
- common/queue/src/main/java/org/thingsboard/server/queue/common/AbstractTbQueueConsumerTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryTbQueueConsumer.java
> Rule Engine consumer service refactoring

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/ProtoUtils.java
- application/src/main/java/org/thingsboard/server/service/queue/TbCoreConsumerStats.java
- application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
- application/src/test/java/org/thingsboard/server/service/queue/ProtoUtilsTest.java
- common/cluster-api/src/main/proto/queue.proto
- common/data/src/main/java/org/thingsboard/server/common/data/EntityType.java
- common/data/src/main/java/org/thingsboard/server/common/data/id/EntityIdFactory.java
- common/data/src/main/java/org/thingsboard/server/common/data/plugin/ComponentLifecycleEvent.java
- common/message/src/main/java/org/thingsboard/server/common/msg/plugin/ComponentLifecycleMsg.java
- common/message/src/main/java/org/thingsboard/server/common/msg/plugin/RuleNodeUpdatedMsg.java
1 Make ComponentLifecycle protos **human-readable** with such a tool like Redpanda (UI for Kafka, ex. Kowl) 
2. Reduce CPU encoding/decoding overhead with a POJO mapper
3. Reduce disk size in queue
4. Reduce network traffic, compression overhead, and latency
Before this, the core or rule-engine component lifecycle notification looked like that
Even if you decode the message with `base64 -d` you will end up with an unreadable payload like that
> ComponentLifecycleMsgProto implemented as replacement of raw byte encoding

- ui-ngx/src/app/modules/home/pages/widget/widget-library-routing.module.ts
- ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-widgets.component.ts
> Added breadcrumbs when navigate to editing widgets from the widget bundle

- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
> Improvement default widget bundle in attributes/timeseries tables

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/date-format-settings-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/date-format-settings-panel.component.scss
> Fixed position of help icon in custom date config of card widgets

- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/metadata/units.json
> Added decibel-milliwatts unit to dictionary

- ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Fixed: [#9458](https://github.com/thingsboard/thingsboard/issues/9458) 
Before fix:
After fix:
> Fixed advanced widget setting boarder radius property

- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-es_ES.json
- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
> Changed 'Java Script' to 'JavaScript'

- application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
- application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
- application/src/test/java/org/thingsboard/server/controller/EdgeEventControllerTest.java
- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/AlarmEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/UserEdgeTest.java
- dao/src/main/java/org/thingsboard/server/dao/eventsourcing/SaveEntityEvent.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
- ui-ngx/src/app/core/http/entity.service.ts
Improvements to reduce server load and prevent unnecessary event storage in the edge queue:
* User **LOGIN** actions are ignored and not pushed to the Edge.
* **ALARM** updates are disregarded unless the 'Push to Edge' node is explicitly added to push these updates.
* Edge events are not queued if the edge is not activated.
* Certain edge events are not added to the queue if the edge is inactive. These entities will be synced during the connection phase.
* Added possibility to load Alarm entity details for Edge downlinks screen. At the moment behavior is next:
> Optimizations for Edge Queue Event Storage and Server Load Reduction

- application/src/test/java/org/thingsboard/server/edge/TenantProfileEdgeTest.java
> Fixed testIsolatedTenantProfile - correct expected number of downlink msgs

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTestEntity.java
class Date  is depricated
class TbDate  implements InstantSource
> [3.7]tbDate_Instant

- pom.xml
Problem: When converting the time stamp in seconds to milliseconds, the received number is out of the variable range.
https://github.com/thingsboard/thingsboard/issues/9312
Before:
After:
> [fix_bug][3.6]tbel: Integer from Json to Long

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTestEntity.java
> [master] tbData_ java11_date_to_Instant

- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/AssetProfileExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DeviceProfileExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/AssetProfileImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceProfileImportService.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/9495
> Version control: fix edgeRuleChainId substitution for asset and device profiles

- application/src/main/java/org/thingsboard/server/controller/NotificationController.java
- application/src/main/java/org/thingsboard/server/controller/NotificationRuleController.java
- application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
- application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
- application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
This fixes the issue https://github.com/thingsboard/thingsboard/issues/9463
> Fix 'Device created' notification when creating alarm using REST API

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
> [master][tbDate_to_instant]tbDate_add_toZonedDateTimeString

- application/src/main/resources/thingsboard.yml
In situations with low connection throughput, the ThingsBoard (TB) server may send duplicate messages to the Edge, mistakenly marking these messages as failed. However, in reality, these 'failed' messages get delivered to the Edge, but with a timeout longer than the default setting.
This Pull Request (PR) aims to increase the default timeout to prevent the unnecessary sending of duplicate messages from the cloud to the Edge, especially under low network conditions like 2G/3G. 
While this adjustment optimizes for slower connections, there is a downside for more stable connections. If there are genuine message delivery failures, the entire batch might be flagged as problematic after a more extended delay compared to the default 10 seconds.
> Increased default value of EDGES_SLEEP_BETWEEN_BATCHES to handle 2G/3G connections

- application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
> Distribute partitions between Rule Engines based only on tenant id

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
> [3.7]tbDate_add_toZoneDateTimeString

- application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
- application/src/test/java/org/thingsboard/server/controller/WidgetsBundleControllerTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleService.java
- dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetsBundleDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetsBundleRepository.java
- dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleDao.java
- dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleServiceImpl.java
Added api request parameter to retrieve all tenant bundles without system
> Added api request parameter to retrieve tenant only bundles

- msa/js-executor/config/custom-environment-variables.yml
- msa/js-executor/config/default.yml
- msa/js-executor/queue/awsSqsTemplate.ts
- msa/js-executor/queue/kafkaTemplate.ts
- msa/js-executor/queue/pubSubTemplate.ts
- msa/js-executor/queue/rabbitmqTemplate.ts
- msa/js-executor/queue/serviceBusTemplate.ts
Added global queue prefix support for js-executor
> Added global queue prefix support for js-executor

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
> Color range setting

- ui-ngx/src/app/shared/components/rule-chain/rule-chain-select.component.scss
> Fixed rule chain selector padding

- ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
- ui-ngx/src/assets/locale/locale.constant-da_DK.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
UI: Added hint for reletion-type-autocomplite.component and changed somme tranlations
> Improved translations in component

- docker/docker-compose.yml
- msa/js-executor/docker/Dockerfile
- msa/js-executor/pom.xml
- msa/monitoring/docker/Dockerfile
- msa/tb-node/docker/Dockerfile
- msa/tb/docker-cassandra/Dockerfile
- msa/tb/docker-postgres/Dockerfile
- msa/transport/coap/docker/Dockerfile
- msa/transport/http/docker/Dockerfile
- msa/transport/lwm2m/docker/Dockerfile
- msa/transport/mqtt/docker/Dockerfile
- msa/transport/snmp/docker/Dockerfile
- msa/vc-executor-docker/docker/Dockerfile
- msa/web-ui/docker/Dockerfile
- msa/web-ui/pom.xml
- ui-ngx/pom.xml
*  thingsboard/openjdk17:bookworm-slim
*  thingsboard/node:16.20.2-bookworm-slim
*  thingsboard/haproxy-certbot:2.2.31-alpine3.18
> Feature/docker images update 3.7

- docker/docker-compose.yml
- msa/js-executor/docker/Dockerfile
- msa/js-executor/pom.xml
- msa/tb-node/docker/Dockerfile
- msa/web-ui/docker/Dockerfile
- msa/web-ui/pom.xml
- ui-ngx/pom.xml
* thingsboard/node:16.20.2-bookworm-slim
* thingsboard/haproxy-certbot:2.2.31-alpine3.18
> Feature/docker images update 3.6.1

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
> connectivity upgrade fix

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
> [master]tbDate_delete_zoneDateTimeString_11

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
> [fix bug][master]_tbDate_now()

- application/src/test/java/org/thingsboard/server/service/notification/NotificationTargetApiTest.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationTargetRepository.java
Fixed ilike function for native query
> Fixed ilike syntax for native query

- application/src/test/java/org/thingsboard/server/controller/WidgetsBundleControllerTest.java
> syncEdgeTest fix. testFindTenantWidgetsBundlesByPageLink - cleanup system widgets

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Updated mosquitto_pub connectivity command with double quotes for user credentials
> Updated mosquitto_pub connectivity command to support white spaces in user creds

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeConfiguration.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
_Issue:_ Currently, the implementation is not allowed to send a correct **plain/text** payload. The RestApiCallNode features a configuration field labeled "trimDoubleQuotes.", however, this approach has proven problematic. It does not adequately handle situations where specific symbols like newline characters \n, tabs \t, curly braces {}, square brackets [], and others are present in the serialized message.
_Fix:_ To address this issue, we should implement a more robust solution. Specifically, we should perform deserialization after the message has been serialized within the unbindMsg() method of the RuleNodeScriptEngine (JacksonUtil.toString()). 
This deserialization process should make use of JacksonUtil.fromString(). To ensure the correctness of this approach, comprehensive tests have …
> Fix trim double quotes for RestApiCallNode

- ui-ngx/src/assets/dashboard/customer_user_home_page.json
- ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
https://github.com/thingsboard/thingsboard/pull/9268
> fixed device active/inactive widgets in home-page

- application/src/main/java/org/thingsboard/server/controller/UserController.java
- application/src/test/java/org/thingsboard/server/controller/UserControllerTest.java
Fixed incorrect usage of 'Optional'.
> fixed getUsersForAssign if originator was removed

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
> Fix of error not displaying in dashboard force fullscreen mode

- ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.scss
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
Fixed alarm type list:
- Fixed empty option.
Before fix:
After fix:
- Fixed width of chip with long name.
Before fix:
After fix:
- Added entity type on blur;
- Added custom translation for alarm type chips.
> Fixed alarm type list width and empty option

- ui-ngx/src/app/modules/home/components/profile/add-device-profile-dialog.component.scss
Fixed max with of alarm rule step page with long condition.
Before fix:
After fix:
> Fixed width of alarm rule for device profile dialog

- ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/display-columns-panel.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
- ui-ngx/src/styles.scss
Issue: [#9521](https://github.com/thingsboard/thingsboard/issues/9521)
Before fix:
After fix:
> Fixed display column panel in table widgets for scrolling long list columns

- ui-ngx/src/app/modules/home/components/event/event-filter-panel.component.html
- ui-ngx/src/app/modules/home/components/event/event-filter-panel.component.scss
- ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Merge after: [#9522](https://github.com/thingsboard/thingsboard/pull/9522)
Before fix:
After fix:
> Refactoring event filter panel

- ui-ngx/src/app/shared/components/markdown-editor.component.ts
> Fixed updated value in markdown input component and refactoring this component

- ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/analog-gauge-basic-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-compass-widget-settings.component.html
Fixed range list output configuration.
Add type number for compass settings.
> Fixed range list basic settings analog gauge 

- ui-ngx/src/app/modules/home/pages/user/user.component.html
- ui-ngx/src/app/modules/home/pages/user/user.component.ts
> Hide display buttons activation link and resend activation when user activated

- application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
https://thingsboard-portal.atlassian.net/browse/PROD-2552
> fixed query timeout exception

- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
> Added logging in case edge test failed on initial check

- application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/sql/resource/TbResourceRepository.java
> fixed get lwm2m resources

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Fixed: [#9458](https://github.com/thingsboard/thingsboard/issues/9458)
Convert widget style system and custom to one style formatting - camelCase.
> Convert widget style to camel case

- ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
> Fixed updated show value and toltip in liquid level widget

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
fixed removing blackbox volumes
> blackbox improvements

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.ts
Added log printing to coap commands and deleted MacOs option for CoAp protocol.
> Added log printing to coap commands

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/TenantProfileMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/WidgetTypeMsgConstructor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/relation/RelationEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantProfileEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/widget/WidgetTypeEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/utils/EdgeVersionUtils.java
- application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
Minor refactoring for backward compatibility with older edges (before 3.6.1) and 3.6.1 CE
> Fix widget type and tenant profile data backward compatibility

- ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
**BEFORE**
https://github.com/thingsboard/thingsboard/assets/54553744/eb0cfbcb-2dce-4903-8145-a718846ff75b
**AFTER**
https://github.com/thingsboard/thingsboard/assets/54553744/2397da24-ea9e-465d-afc5-fdf349e79fdc
> Fixed liquid level widget additional checkup for datasources

- ui-ngx/src/app/modules/home/components/widget/widget.component.scss
> Added additional z-index to widget no data container

- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessor.java
- application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessorTest.java
Avoid errors on the cloud in case huge attribute pushed to the edge:
```
tb-docker-tb-core1-1         | com.google.gson.JsonSyntaxException: String value length [5307] for key [demo_app_air_quality_sensors_instructions] is greater than maximum allowed [1024]
tb-docker-tb-core1-1         | 	at org.thingsboard.server.common.transport.adaptor.JsonConverter.parseProtoValues(JsonConverter.java:198)
tb-docker-tb-core1-1         | 	at org.thingsboard.server.common.transport.adaptor.JsonConverter.convertToAttributesProto(JsonConverter.java:149)
```
> Telemetry edge processor: added check for attr/timeseries value size

- dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeRepository.java
> EdgeRepository - fixed typo searchText <> textSearch

- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
> save timeseries without latest: removed callback for entity view

- application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
Improved test cleanup method to ensure tenant deletion.
> Improved afterTest method

- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/RuleChainDataValidator.java
> Save rule chain metadata: validate node configuration only after upgrade

- application/src/test/java/org/thingsboard/server/transport/coap/CoapTestClient.java
- application/src/test/java/org/thingsboard/server/transport/coap/client/CoapClientIntegrationTest.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/AbstractSyncSessionCallback.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/CoapOkCallback.java
Added support for NON CoAP messages. These kind of messages should not be acknowledged by server and response will have the same type.
> Add processing for NON messages in CoAP

- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
Hotfix alarm type list uncontrolled focus.
1. Login as a tenant user;
2. Open the alarm menu or any dashboard with an alarm widget;
3. Open (click) the Alarm filter;
4. Set existing alarm types ;
5. Add a manual alarm type - and try to add a second;
As a result, You can’t add new alarm types and focus on this field stay active event if click out of the field.
After fix all works correctly.
> Fixed uncontrolled focus alarm type list

- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
> Improve flaky test

- application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
- application/src/main/resources/thingsboard.yml
- common/cluster-api/src/main/proto/queue.proto
- common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/DefaultEntityLimitsCache.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/EntityLimitKey.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/EntityLimitsCache.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- dao/src/main/java/org/thingsboard/server/dao/exception/EntitiesLimitException.java
- dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
> Implement cache for the entity creation request

- common/cache/src/main/java/org/thingsboard/server/cache/TbTransactionalCache.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/asset/AssetProfileService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceProfileService.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/entityview/EntityViewService.java
- dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
- dao/src/test/java/org/thingsboard/server/dao/service/AssetServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/service/DeviceServiceTest.java
Fixed TB service save methods to avoid putting into cache anything that can be rolled back
> Transactional cache issue

- application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
> Edge sync test edge stability improvements

- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
- msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
Fixed flaky test deviceDeletedClosingSession.
Added cassandra volume deletion after tests.
> blackbox tests improvements

- application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
- application/src/test/java/org/thingsboard/server/controller/WidgetTypeControllerTest.java
Extended widgetTypes access to customer user authority
> Extended widgetTypes access to customer user authority

- common/cache/src/main/java/org/thingsboard/server/cache/RedisTbTransactionalCache.java
- common/data/src/main/java/org/thingsboard/server/common/data/FstStatsService.java
- common/queue/src/main/java/org/thingsboard/server/queue/util/ProtoWithFSTService.java
- common/stats/src/main/java/org/thingsboard/server/common/stats/FstStatsServiceImpl.java
> added encode/decode time stats and refactoring

- application/src/main/java/org/thingsboard/server/config/CustomOAuth2AuthorizationRequestResolver.java
- application/src/main/java/org/thingsboard/server/config/TbRuleEngineSecurityConfiguration.java
- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
https://github.com/thingsboard/thingsboard/pull/9718
> fixed rule-engine stats

- application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
> fixed flaky test

- application/src/main/data/json/edge/install_instructions/docker/instructions.md
- docker/docker-compose.hybrid.yml
- docker/docker-compose.postgres.yml
- msa/tb/docker-cassandra/Dockerfile
Updated postgres image from 12 to 15 version
> Updated postgres image version from 12 to 15

- application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
Added loading of the default dashboard to load demo script.
> Added default gateway dashboard to loadDemo script

- pom.xml
https://github.com/thingsboard/tbel/pull/24 
Array.indexOf((searchElement)) -> super
Array.join() +
Array.pop() +
Array.push() +
Array.slice(int start, int end) +
Array.unshift() +
Array.shift() +
Array.sort() +
Array.toSorted() +
Array.reverse() +
Array.toReversed() +
Array.slice() +
Array.slice(int start) +
Array.indexOf(searchElement, fromIndex)
Array.join()
Array.concat() +
Array.splice() +
Array.toSpliced() +
Array..with(index, value) +
Array.fill() +
Map.sortByKey
Map.sortByValue
> [3.7]tbel Release 1.1.5_

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
The existing solution for the "localhost" case (--network=host) works only for Linux platforms. Fixed "localhost" case to work on all platforms (replaced "--network=host" with "--add-host=host.docker.internal:host-gateway").
Also updated gateway commands: added port exposing, changed container name to contain device name.
> Fixed mqtt/coap docker connectivity commands (localhost case)

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
- common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
> [3.6.2]Fix_bug_Tbdate_default_tz

- application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
API is very big and it's hard to find something on a page without manually expanding all tags.
Fixes #9721
Expand all tags in Swagger UI.   
Before:
After:
> Expand all tags in Swagger UI

- ui-ngx/src/assets/locale/locale.constant-zh_CN.json
The Chinese translations of 'inactive' and 'active' are reversed
> The Chinese translations of 'inactive' and 'active' are reversed

- ui-ngx/src/app/core/api/alarm-data.service.ts
Fixed: [#9618](https://github.com/thingsboard/thingsboard/issues/9618)
Before fix:
After fix:
> Fixed infinity alarm loading on unresolved data sources

- ui-ngx/src/app/modules/home/components/vc/version-control.scss
> Fixed version control message text display behaviour 

- ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/app/shared/models/public-api.ts
- ui-ngx/src/app/shared/models/query/query.models.ts
Shared query.models.ts to use in custom widget development. This change affected effected enum Direction so it was refactored.
> Add query.models to public-api

- ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.html
- ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.ts
- ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.html
- ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.ts
- ui-ngx/src/app/modules/home/components/rule-chain/rule-chain-autocomplete.component.html
- ui-ngx/src/app/modules/home/components/rule-chain/rule-chain-autocomplete.component.ts
- ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
- ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html
- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
- ui-ngx/src/app/shared/components/ota-package/ota-package-autocomplete.component.html
- ui-ngx/src/app/shared/components/ota-package/ota-package-autocomplete.component.ts
Fixed: [#9648](https://github.com/thingsboard/thingsboard/issues/9648)
Improve for autocomplete:
- asset profile autocomplete;
- device profile autocomplete;
- rule chain autocomplete;
- dashboard autocomplete;
- entity autocomplete;
- ota package autocomplete.
After fix:
> Improve added links to entities from setting of entities

- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
- ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
- ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
- ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
[Screencast from 16.11.23 13:19:48.webm](https://github.com/thingsboard/thingsboard/assets/87172504/74a6442d-c1c7-4041-a6dc-d38c8709cd88)
> Added entity links to alarm table originator column

- ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/analog-gauge-basic-config.component.ts
Fixed output configuration for border-radius from basic settings.
Before fix:
After fix:
> Fixed border radius for basic settings analog gauge widgets

- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
> Fixed translation key for error of rule engine TTL exceptions days field

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.scss
> Fixed padding for multiple input widget with group setings

- ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.component.ts
Fixed https://github.com/thingsboard/thingsboard/issues/9673 
Before:
After:
> Fixed card widget display only numeric value

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.ts
**BEFORE**  
https://github.com/thingsboard/thingsboard/assets/54553744/f9d9d601-c396-420c-b5d9-b8a759a7c552
**AFTER**
https://github.com/thingsboard/thingsboard/assets/54553744/328f1bc6-4b32-4f3f-acc9-8de63f58d6ab
> Fixed JSON type attribute in multiple input widget

- ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
- ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
- ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html
- ui-ngx/src/app/modules/home/components/profile/alarm/alarm-duration-predicate-value.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
- ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
- ui-ngx/src/app/modules/home/pages/admin/mail-server.component.html
- ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.html
- ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-table-config.resolver.ts
- ui-ngx/src/app/modules/home/pages/security/security.component.html
- ui-ngx/src/app/modules/home/pages/user/users-table-config.resolver.ts
- ui-ngx/src/app/shared/components/button/copy-button.component.html
- ui-ngx/src/app/shared/components/button/copy-button.component.ts
Changes are related to tb-icon component that were made to render not only material but mdi icons and etc. Some of the logic wasn't changed that led to conflicts and icons are not appearing in many places.
**BEFORE**
**AFTER**
> Fixed mdi and other icons appearing

- ui-ngx/src/app/core/http/widget.service.ts
> Fixed export widget bundle url

- application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
> Fix image API tests

- dao/src/main/java/org/thingsboard/server/dao/sql/TbSqlBlockingQueue.java
The motivation was an issue when 2 of 3 `sql-queue-latest` stopped working because of an SQL error. 
Restarting the system helps for a short period until the same SQL reproduced.
The TbSqlBlockingQueue loop should work with no interruption during the whole lifecycle of the ThingsBoard instance.
The evidence of the problem is on the screenshot
According to the Hikari pool, the SQL queue does nothing but has messages in the queue.
The fix provided resolves the stability issue (see screenshot below). All `sql-queue-*` loops are working without interruption despite SQL errors.
In collaboration with @volodymyr-babak
> [3.6.2] TbSqlBlockingQueue failover improvement

- application/src/main/resources/thingsboard.yml
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Updated config parameter description
> Updated config parameter description

- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/metadata/units.json
Addition to [PR for widgets](https://github.com/thingsboard/thingsboard/pull/9806)
> Added milligram per cubic meter unit

- application/src/main/java/org/thingsboard/server/exception/ThingsboardCredentialsViolationResponse.java
- application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponseHandler.java
- application/src/main/java/org/thingsboard/server/service/security/exception/UserPasswordNotValidException.java
- application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
- application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/exception/ThingsboardErrorCode.java
- common/data/src/main/java/org/thingsboard/server/common/data/security/model/UserPasswordPolicy.java
Added max length password policy. 
Also added a boolean value to force users to update their not valid password.
> Added max length password policy

- ui-ngx/src/app/modules/home/pages/admin/security-settings.component.html
- ui-ngx/src/app/modules/home/pages/admin/security-settings.component.scss
- ui-ngx/src/app/modules/home/pages/admin/security-settings.component.ts
- ui-ngx/src/app/modules/home/pages/security/security.component.html
- ui-ngx/src/app/modules/home/pages/security/security.component.ts
- ui-ngx/src/app/modules/login/pages/login/login.component.html
- ui-ngx/src/app/modules/login/pages/login/login.component.ts
- ui-ngx/src/app/shared/models/constants.ts
- ui-ngx/src/app/shared/models/settings.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Merge with: [#9775](https://github.com/thingsboard/thingsboard/pull/9775)
Add input 'Maximum password length';
Add checkbox 'Force to reset password if not valid';
> Improvement for security settings

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/test/java/org/thingsboard/server/dao/util/DeviceConnectivityUtilTest.java
The motivation is to improve mergeability with forks.
Another minor test improvement was applied.
> [3.6.2] Device connectivity controller test improvements

- dao/src/main/java/org/thingsboard/server/dao/sql/TbSqlBlockingQueue.java
TbSqlBlockingQueue does not log an error on InterruptedException because of normal lifecycle
> [3.6.2] TbSqlBlockingQueue does not log an error on InterruptedException because of normal lifecycle

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
Updated upgrade script for 3.6.1 to clean up securitySettings cache.
> Updated upgrade script for 3.6.1 to clean up securitySettings cache

- application/src/test/java/org/thingsboard/server/transport/coap/CoapTestCallback.java
- pom.xml
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
Coap RPC tests with 50 repeatings.
> fixed flaky tests

- application/src/main/data/upgrade/3.6.1/schema_update.sql
- dao/src/main/resources/sql/schema-entities-idx.sql
> Added edge_event idx by tenant id and edge id

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/controller/AuthController.java
- application/src/main/java/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.java
- application/src/main/java/org/thingsboard/server/service/security/exception/UserPasswordNotValidException.java
- application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
- application/src/main/java/org/thingsboard/server/service/security/system/SystemSecurityService.java
Made some performance enhancement: moved password policy check before user info rest calls
> Moved password policy check before user info rest calls

- application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_preparing.md
> Fixed edge upgrade script - added volumes section

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java
Kafka producer can be configured to use PEM certificates:
But at the moment this producer can't be initialized, because new line symbol is tracked as two separate symbols - \ and n.
BEFORE:
This fix will be applied to SSL certificate properties and replace \ and n symbols with a single new line symbol \n.
AFTER:
> TbKafkaNode - replace \ and n symbols with new line symbol \n

- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Changed placeholder for the Enter asset profile field

- ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.models.ts
> Liquid level widget remove percent from label for n/a value 

- ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
> Fixed backward compatibility for notification settings

- ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-gauge-widget-settings.component.ts
Fixed:
- Fixed minor ticks count config name;
Before fix:
Reload page
After fix:
Reload page
- Fixed infinite loop;
Before fix:
Set max ticks - 4 and Major ticks count - 9
After fix:
Set max ticks - 4 and Major ticks count - 9
> Fixed analog gauge infinite loop for major ticks

- ui-ngx/src/app/core/http/device.service.ts
- ui-ngx/src/app/core/http/image.service.ts
- ui-ngx/src/app/core/http/ota-package.service.ts
- ui-ngx/src/app/core/http/resource.service.ts
- ui-ngx/src/app/core/services/resources.service.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.ts
- ui-ngx/src/app/shared/models/device.models.ts
>  Fixed download gateway launch file and refactoring downloads file

- pom.xml
> [3.6.2]Tbel 1 1 5

- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
> Fixed incorrect link to install necessary tool for MQTT in Windows

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Rename default state controller to static

- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeUpgradeInstructionsService.java
- application/src/main/java/org/thingsboard/server/service/edge/instructions/EdgeUpgradeInstructionsService.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/update/DefaultUpdateService.java
- application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
- ui-ngx/src/app/core/http/edge.service.ts
- ui-ngx/src/app/modules/home/pages/edge/edge.component.ts
> Edge - fix instructions upgrade

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
This minor test optimization will help to pass the test for customized CA_ROOT_CERT_PEM value
> [3.6.2] test optimization CA_ROOT_CERT_PEM from constant

- ui-ngx/src/assets/locale/locale.constant-uk_UA.json
* Translation of sidebar titles
* Сorrection of typos
* Translation of the "access", "account", and "action" sections
> Update Ukrainian translation

- ui-ngx/src/app/modules/home/pages/admin/general-settings.component.ts
Before:
[Screencast from 21.12.23 13:14:16.webm](https://github.com/thingsboard/thingsboard/assets/87172504/bf240856-d5c1-489a-b1aa-03bf731d4a32)
After:
[Screencast from 21.12.23 13:15:06.webm](https://github.com/thingsboard/thingsboard/assets/87172504/538414ee-a20c-49be-8a6c-e56faa9b798c)
> Fixed device connectivity sysadmin settings disabled inputs values disappearing on save

- application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Added forgotten check for HTTPS port.
Added additional test.
Removed unused variables
> Fix for device check connectivity host and port check

- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/ResourceExportService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/ResourceImportService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
> Fixes for images version control

- application/src/main/resources/thingsboard.yml
Added env variables for "max-file-size" and "max-request-size" yml parameters
> Added env variables for "max-file-size" and "max-request-size" yml parameters

- transport/http/src/main/resources/tb-http-transport.yml
Added spring multipart parameters to http transport
> Added spring multipart parameters to http transport

- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/main/java/org/thingsboard/server/controller/EntitiesVersionControlController.java
- application/src/main/java/org/thingsboard/server/service/executors/VersionControlExecutor.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
- application/src/main/resources/thingsboard.yml
- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
> Version control performance improvements

- application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/ImageExportData.java
`"public": true` in import data json was deserialized into `isPublic = false`
> Fix image's isPublic on import

- application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
Moved creation of edge before device/asset creation to have time to process set edge root rule chain before activation
> Fixed EdgeControllerTest.testSyncEdge

- application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/AbstractOAuth2ClientMapper.java
> Fix isolated queues creation

- application/src/main/resources/thingsboard.yml
- common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsAdmin.java
- common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsProducerTemplate.java
- common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsSettings.java
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Fixed native thread allocation error fix by providing one producer executor with a limited thread pool size.
> TbAwsSqsProducerTemplate fix 

- application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/EntitiesLimitTriggerProcessor.java
Fixed invalid notification about entities usage:
> Usage: 0/1 (0%)
> Fix invalid entities limit notification

- ui-ngx/src/app/modules/home/components/widget/config/widget-settings.component.ts
Fixed #9929
Fixed incorrect validation JSON form in widgets
**Before:**
**After:**
> Fixed validation JSON form in custom widgets

- application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityConfiguration.java
https://thingsboard-portal.atlassian.net/browse/PROD-2853
Add the ability to change the default (hardcoded) connectivity configuration for install.
Useful for cluster deployment if we use load balancers.
> set default device conncectivity params from yml during install

- application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
- application/src/test/resources/logback-test.xml
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
> Fix public resource key regeneration on image update

- dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
- dao/src/test/java/org/thingsboard/server/dao/service/AssetServiceTest.java
> Fix asset relations deletion

- application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
- Added missing WidgetTypeController APIs to RestClient(with overloaded methods for page-based APIs)
- Added missing WidgetsBundleController APIs to RestClient(with overloaded methods for page-based APIs)
- Set Deprecated annotation for the deprecated APIs to display them with struck-out text and with a grey background
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2285
> Added missing WidgetTypeController & WidgetsBundleController APIs to RestClient

- application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
This api was created for UI needs only and requires specific prefixed added to fqn. Users that use this endpoint are confused with errors that fqn is not valid.
> Hidden "/widgetType?fqn" from swagger doc 

- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/TransportActivityManager.java
> Move activity-related logic to abstract class

- application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
- application/src/test/java/org/thingsboard/server/actors/tenant/TenantActorTest.java
> fixed unnecessary device actor init on rule-engine

- monitoring/src/main/java/org/thingsboard/monitoring/config/MonitoringTarget.java
- monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportInfo.java
- monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportMonitoringTarget.java
- monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportType.java
- monitoring/src/main/java/org/thingsboard/monitoring/data/notification/HighLatencyNotification.java
- monitoring/src/main/java/org/thingsboard/monitoring/data/notification/ServiceFailureNotification.java
- monitoring/src/main/java/org/thingsboard/monitoring/data/notification/ServiceRecoveryNotification.java
- monitoring/src/main/java/org/thingsboard/monitoring/notification/NotificationService.java
- monitoring/src/main/java/org/thingsboard/monitoring/notification/channels/NotificationChannel.java
- monitoring/src/main/java/org/thingsboard/monitoring/notification/channels/impl/SlackNotificationChannel.java
- monitoring/src/main/java/org/thingsboard/monitoring/service/transport/TransportHealthChecker.java
- monitoring/src/main/resources/tb-monitoring.yml
> Improvements for monitoring service

- application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
In our business case we need to generate audit logs and maybe events for assets (buildings) from Rule Engin based on incoming timeseries from our control devices.
> Add Event and Audit Logs services to TbContext.

- rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
> Add image API to RestClient

- application/src/main/resources/thingsboard.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
Updated transport.sessions.inactivity_timeout default value to be in sync with state.defaultInactivityTimeoutInSec, updated description for these params.
> Synchronized DEFAULT_INACTIVITY_TIMEOUT  and TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT default env values

- ui-ngx/src/app/shared/components/image/image-dialog.component.ts
When the image dialog is not updated, preview when uploading a new image. Reproduced only public image.
**Init state:**
**Before:**
**After:**
> Fixed not updated image preview when updated image

- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Tenant profile dialog refactoring translate

- application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
Extended error handling for "sendResetPasswordEmailAsync" from ThingsboardException to Exception to log all types of errors.
> Extended error handling from ThingsboardException to Exception

- ui-ngx/src/app/modules/home/pages/admin/general-settings.component.html
> Fixed sysadmin general settings for Firefox

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.scss
- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.scss
Fixed not properly displaying of copy-code button after device creation on Firefox.
Before
After
> Fixed not properly displaying of copy-code button

- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
Fixed links in originator column in alarm table for entities that can no have alarms
> Disabled originartor column details page links in alarms table for entities that can not have alarm

- ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Step to reproduce:
- Add timeseries table with two datasources.
- For the second datasorce for any data key change the default column visibility to 'Hidden'.
As a result: the second tab in the table for this data key is still visible but in column to display panel this column is disabled.
Before fix:
After fix:
> Fixed default column visibility for timeseries table widget

- ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-keys-panel.component.ts
> Fixed console error on deleting data key

- application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
- application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
https://thingsboard-portal.atlassian.net/browse/PROD-3019
> fixed stack overflow error

- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/audit/AuditLogService.java
- dao/src/main/java/org/thingsboard/server/dao/Dao.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmCommentDao.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmCommentService.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogDao.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/audit/DummyAuditLogServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/audit/sink/ElasticsearchAuditLogSink.java
- dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/JpaPartitionedAbstractDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/audit/JpaAuditLogDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/ota/JpaOtaPackageInfoDao.java
- dao/src/test/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDaoTest.java
When using `JpaRepository.save`, it executes additional select by id in case the entity has preset id (thus for all our entities that use JpaAbstractDao).
Used `EntityManager` directly in the `JpaAbstractDao`.
Default JpaRepository implementation:
```
if (entityInformation.isNew(entity)) {
em.persist(entity);
return entity;
} else {
return em.merge(entity);
}
```
Before:
After:
Also, normalized SQL-related error messages.
Before:
After:
> Performance improvements for entities saving

- .github/workflows/license-header-format.yml
> GitHub workflow license-header-format.yml

- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
> Make saveRuleChainMetaData @Transactional

- dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Added extra mapping for the gateway launch command docker compose file, because the gateway cannot connect to the external server that runs in docker on the same machine if the gateway connects to the non localhost.
> Added extra mapping for the gateway launch command docker compose file

- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/test/java/org/thingsboard/server/dao/service/DeviceServiceTest.java
Fixed saveDeviceWithAccessToken method to delete device if credentials saving failed
> Added Transactional for saveDeviceWithAccessToken

- dao/src/main/java/org/thingsboard/server/dao/edge/BaseEdgeEventService.java
> Fix compile error 

- ui-ngx/src/app/core/http/image.service.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
- ui-ngx/src/app/modules/home/components/widget/lib/maps/markers.ts
This pull request is created to resolve the critical issue with images load on map.
**BEFORE:**
**AFTER:**
> Map optimisation improvements for requests of icon images and async rendering

- ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.html
- ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/form.scss
> Added dynamic volume inputs and other minor improvements for liquid level widget.

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
Changed validators for gateway -> general configs -> storage tab ->  path fields.
Before
After
Before
After
> Fixed in Thingsboard Iot Gateway dashboard validator gateway configuration

- ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-communication-config.component.html
- ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-communication-config.component.scss
- ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-mapping.component.html
- ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-mapping.component.scss
**BEFORE:**
https://github.com/thingsboard/thingsboard/assets/54553744/a9fc9a59-3007-4a49-998d-446c95a2c606
**AFTER:**
https://github.com/thingsboard/thingsboard/assets/54553744/1a69944a-01e4-4013-9aa3-20caf203db29
> Added html responsive improvement for SNMP transport config

- ui-ngx/src/app/shared/components/time/timewindow.component.scss
- ui-ngx/src/styles.scss
Minor improvements for global styles and timewindow.
> Improvements for styles and timewindow scss

- ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Currently Thingsboard dashboards inherit Rows limit from "angular-gridster2". That prevents users having larger dashboards. This PR increases limit from "100" rows to "3000".  
Notes:
- Users may need to refresh web browser cache for old dashboards
- This change is backwards compatible. If a dashboard created after this change is used on an instance with a default limits, the widgets will be rearranged to fit the limit
- I'm not aware of any regressions
Closes https://github.com/thingsboard/thingsboard/issues/7493
Upstream issue: https://github.com/tiberiuzuld/angular-gridster2/issues/455
Video demonstration:
[angular-gridster2__maxRows.webm](https://github.com/thingsboard/thingsboard/assets/44649402/67652982-ba30-4294-8286-916f7bae80aa)
- [*] You have reviewed the guidelines …
> For Angular Gridster, increase "maxRows" limit from "100" to "3000"

- application/src/main/data/json/tenant/dashboards/gateways.json
- ui-ngx/src/app/core/api/widget-api.models.ts
- ui-ngx/src/app/modules/home/models/widget-component.models.ts
Added the getEntityDetailsPageURL method to the IWidgetUtils interface for generating entity details page URLs based on ID and entity type depends of the platform. This enables dynamic URL construction within custom functions in gateways.json.
> Fixed dynamic links creation for dashboard gateways devices instances details

- ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
UI: Removed extra > character from dashboard-autocomplete component.
> Removed extra > character

- ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
- ui-ngx/src/assets/help/en_US/rulenode/common_node_script_args.md
- ui-ngx/src/assets/help/en_US/rulenode/switch_node_script_fn.md
- ui-ngx/src/assets/help/en_US/rulenode/tbel/common_node_script_args.md
- ui-ngx/src/assets/help/en_US/rulenode/tbel/switch_node_script_fn.md
Replaced hard-coded document link paths with site-base-url.
> Replaced hard-coded document link paths with site-base-url

- ui-ngx/src/app/modules/home/components/filter/filters-edit.component.ts
Before:
[scrnli_2_2_2024_6-34-24 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/251ba560-75b9-491a-89ec-985386ff1861)
After:
[scrnli_2_2_2024_6-32-55 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/42352824-313e-448e-9918-4906315b409b)
> Fixed dashboard entity filter remembers user input on close and cancel

- ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
When moving between dashboards gridster options weren't updated in a right way.
**BEFORE:**
**AFTER:**
> Fixed gridster options update for mobile mode

- ui-ngx/src/app/core/notification/notification.models.ts
- ui-ngx/src/app/modules/home/models/widget-component.models.ts
- ui-ngx/src/app/shared/components/snack-bar-component.html
- ui-ngx/src/app/shared/components/snack-bar-component.scss
- ui-ngx/src/app/shared/components/toast.directive.ts
Update toast notification for new design:
- warn
- error
- success
- info
> Update toast notification

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineInternalQueueConsumerManager.java
- application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManager.java
- common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
- common/data/src/main/java/org/thingsboard/server/common/data/queue/Queue.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/QueueKey.java
> Internal Rule Engine queues

- application/src/main/java/org/thingsboard/server/service/mail/RefreshTokenExpCheckService.java
In yml, the `mail.oauth2.refreshTokenCheckingInterval` is set in seconds, while the `@Scheduled` was thinking it is in milliseconds and did the check every two minutes instead of once a day.
Also, numerous related errors every 2 minutes on PaaS but without any error description:
Added error stacktrace in PE PR.
> Fix mail refresh token check

- application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_0/NoSecLwM2MIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_0/PskLwm2mIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_3/NoSecLwM2MIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_3/PskLwm2mIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_null/NoSecLwM2MIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_null/PskLwm2mIntegrationDtlsCidLengthTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/AbstractLwM2MIntegrationDiffPortTest.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/LwM2MIntegrationDiffPortTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbInMemoryRegistrationStore.java
https://github.com/thingsboard/thingsboard/pull/10063/files
There are no problems in the Thingsboard code.
> test_lwm2m__change port_update registration

- application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/AlarmEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/BaseAlarmProcessor.java
- application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
- application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
- application/src/test/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmServiceTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEventActionType.java
- dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
When we delete an alarm, `processAlarmDeleteNotification` should be invoked.
When we delete an alarm, `removeDeviceState` should not be invoked.
> fixed delete alarm events (device profile node)

- dao/src/main/java/org/thingsboard/server/dao/edge/EdgeServiceImpl.java
> Add @Lazy annotation to prevent circular dependency

- application/src/main/java/org/thingsboard/server/controller/ImageController.java
- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/X509_NoTrustLwM2MIntegrationTest.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/util/SslUtil.java
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
- dao/src/main/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidator.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/geo/TbGpsGeofencingActionNodeTest.java
1. delete deprecated  Base64Utils
2. 
before:
```
verify(ctx.getAttributesService(), never()).find(any(), any(), any(), anyString());
```
after:
```
verify(ctx.getAttributesService(), never()).find(any(), any(), any(AttributeScope.class), anyString());
```
> fix_bug: any Tetsts

- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
- common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java
- msa/js-executor/queue/kafkaTemplate.ts
Global Queue Prefix is now correctly respected by js-executor, rule-node and tb-rule-engine-notifications-node- consumer groups
> Added global queue prefix to js-executor, rule-node and tb-rule-engine-notifications-node- consumer group id

- pom.xml
this pull requests increases to logback version to 1.4.14, to make the JSONEncoder feature available.
solves: #10193
> update logback to 1.4.14 to allow for json logging

- application/src/main/resources/thingsboard.yml
Changed default value for CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED from false to true.
> CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED=true by default

- application/src/main/resources/thingsboard.yml
Updated env parameter description for SQL_TTL_TS_TS_KEY_VALUE_TTL
> Updated env parameter description for SQL_TTL_TS_TS_KEY_VALUE_TTL

- common/data/src/main/java/org/thingsboard/server/common/data/StringUtils.java
- dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
- dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityKeyMappingTest.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/AlarmRuleStateTest.java
- ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html
- ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.ts
- ui-ngx/src/app/modules/home/components/filter/string-filter-predicate.component.html
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Added alarm state handling for IN, NOT_IN types of operation
> Added alarm state handling for IN, NOT_IN types of operation

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
The MVEL engine, under specific circumstances, is not able to identify the proper constructor when varargs are used:
This fix replaces the constructor with vararg variables with two separate constructors - one with and one without the variable.
> TbDate - use strict constructors instead of constructors with var args

- msa/js-executor/api/jsInvokeMessageProcessor.ts
js executor log memory usage as a single line
This will improve the log experience because a multiline log is hard to read
Currently looks like:
```
2024-02-26 19:41:09,647 [JsInvokeMessageProcessor] INFO: Current memory usage: {"rss":89866240,"heapTotal":43966464,"heapUsed":38125176,"external":1391450,"arrayBuffers":276819}
```
> js executor log memory usage as a single line

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/profile/BaseAssetProfileProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/BaseDeviceProcessor.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/test/java/org/thingsboard/server/dao/service/DeviceServiceTest.java
Issue: https://github.com/thingsboard/thingsboard/issues/10203
> Edge - fix uplink order to correctly process messages 

- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
- ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
> Added workaround for matChipInputAddOnBlur selection bug in tb-entity-subtype-list input

- ui-ngx/src/app/shared/components/image/image-dialog.component.ts
- ui-ngx/src/app/shared/components/image/upload-image-dialog.component.ts
- ui-ngx/src/app/shared/models/resource.models.ts
The feature to make an additional request after uploading an image to the gallery has been removed.
**Before:**
**After:**
> Optimized updated image in Image Gallery

- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
> Typo in send notification component

- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
- ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
- ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.scss
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
Fixed:
align loading 
incorrect sticky header when scrolling
Before:
After:
> Minor fixed in notification dialog

- ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
> Add hint to setting notification rule Edge communication failure

- ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
> Required mark and error text were changed in the recipients' field of the notification rule dialog

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
> Space before the required mark has been removed in widget action

- ui-ngx/src/app/core/http/public-api.ts
- ui-ngx/src/app/modules/home/models/services.map.ts
Services listed in the services map can be used from widget custom actions.
Services listed in http/public-api can be referenced in the thingsboard-widgets-extension.
> New services added to Services Map in Widget Context

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
- application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
- application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsService.java
- application/src/test/java/org/thingsboard/server/service/security/auth/JwtTokenFactoryTest.java
> Fix JWT settings updating for Rule Engines

- application/src/main/java/org/thingsboard/server/service/edge/EdgeContextComponent.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/test/java/org/thingsboard/server/service/limits/RateLimitServiceTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java
- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
- ui-ngx/src/app/shared/models/limited-api.models.ts
- ui-ngx/src/assets/help/en_US/notification/rate_limits.md
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Add rate limits for edge uplink message

- ui-ngx/src/app/shared/components/image/embed-image-dialog.component.scss
> Added fixed width for embed image dialog

- ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Configured for y-axis min/max values are not applied correctly.
Before:
The null value in the data key settings causes the min/max values configured for the chart not to be applied. 
The next two widgets have the same configuration, excepting the y-axis min/max values in the data key settings.
After:
If min/max values in the data key settings are not set (it doesn't matter whether null or undefined), the min/max values set in the chart advanced configuration are applied.
> Fixed applying min/max y-axis parameters in flot chart

- ui-ngx/src/app/shared/components/image/image-dialog.component.ts
If you update an image that is public, browsers can ignore the header that does not need to be cached and needs to be checked for relevance. https://github.com/whatwg/fetch/issues/1088
> Fixed incorrect cache when open preview public image

- application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
- application/src/main/java/org/thingsboard/server/service/notification/channels/MobileAppNotificationChannel.java
- application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationRequestStats.java
Firebase does not accept null values in the message's data, failing with errors like this: `null value in entry: info.userFirstName=null`
> Fix mobile notification sending failures

- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java
Clone git repo if tmp directory was deleted
> Fix git repository initialization after repo directory deletion

- ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
> Add icon to configure mobile app notification

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
- ui-ngx/src/app/shared/models/widget.models.ts
> Refactoring widgetActionTypes

- dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
- dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
- dao/src/main/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDao.java
- dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNode.java
Refactoring to improve performance. Non-blocking implementation for `SqlTimeseriesLatestDao` and `CachedAttributesService`
> TbAbstractGetAttributesNode: get latest moved to the last step because SqlTimeseriesLatestDao.findLatest() effectively do blocking DB calls, so getting attr async will do the job without awaiting the latest response.
> Latest ts and attribute async improvement

- ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
> Fixed not edit action source

- common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
- msa/js-executor/docker/Dockerfile
- msa/js-executor/pom.xml
- msa/web-ui/docker/Dockerfile
- msa/web-ui/pom.xml
- ui-ngx/pom.xml
When running a parallel build on a brand-new environment. Yarn install are often failed (by file not found). And especially during a parallel multi-arch build with `docker buildx` (connection timeout). Yarn does not support a parallel build. 
```
mvn clean install -T 1C -Ddockerfile.skip=false -DskipTests
```
Clean yarn cache
```
rm -r ~/.cache/yarn
```
* The key is a `--mutex` by network port. It works fine for local and docker multi-arch builds
* Network timeout is 100sec is ms
* Network concurrency decreased down to 4 (default 8) 
* Non-interactive mode
```
yarn install --production --non-interactive --network-concurrency 4 --network-timeout 100000 --mutex network
```
CLI
Docker buildx
> Parallel and multiarch build on clean environment for yarn install

- ui-ngx/src/app/core/services/dialog.service.ts
- ui-ngx/src/app/shared/components/dialog/alert-dialog.component.ts
- ui-ngx/src/app/shared/components/dialog/confirm-dialog.component.ts
- ui-ngx/src/app/shared/components/dialog/error-alert-dialog.component.ts
> Automatically close default dialogs (Alert/Confirm/Error) on route change

- application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
> Add callback executor for device state service

- application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultFirebaseService.java
> Add APNS config for push notification in mobile phone

- ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
> Added sorting to 'Originator' column for alarm table

- ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.html
- ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
> Fixed expand notification delivery template when editing

- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
> Fix page size existingNotificationTypes for Edge

- application/src/main/java/org/thingsboard/server/service/ttl/rpc/RpcCleanUpService.java
- dao/src/main/java/org/thingsboard/server/dao/rpc/RpcDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/rpc/JpaRpcDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/rpc/RpcRepository.java
- dao/src/test/java/org/thingsboard/server/dao/sql/rpc/JpaRpcDaoTest.java
- dao/src/test/resources/logback.xml
> Refactoring / delete rpc native query

- dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
- dao/src/main/java/org/thingsboard/server/dao/entity/DefaultEntityServiceRegistry.java
https://thingsboard-portal.atlassian.net/browse/PROD-3303
```
java.lang.NullPointerException: null
at org.thingsboard.server.dao.entity.BaseEntityCountService.lambda$countByTenantIdAndEntityType$0(BaseEntityCountService.java:35)
at org.thingsboard.server.cache.TbTransactionalCache.getAndPutInTransaction(TbTransactionalCache.java:69)
at org.thingsboard.server.dao.entity.BaseEntityCountService.countByTenantIdAndEntityType(BaseEntityCountService.java:34)
at org.thingsboard.server.dao.usage.BasicUsageInfoService.getUsageInfo(BasicUsageInfoService.java:56)
at org.thingsboard.server.controller.UsageInfoController.getTenantUsageInfo(UsageInfoController.java:43)
at org.thingsboard.server.controller.UsageInfoController$$FastClassBySpringCGLIB$$1dbad98d.invoke(<generated>)
at …
```
> fixed NPE related to the entity service registry initialization

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
When deleting queue, partition change event with empty partitions list arrives.
Ignoring such event if queue not found.
> Ignore partition change event for deleted queues

- application/src/main/java/org/thingsboard/server/service/mail/RefreshTokenExpCheckService.java
Added condition for RefreshTokenExpCheckService for case when refresh token was dropped
> Oauth2 mail refresh token check is being executed only for active not expired token

- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/tenant/TenantMsgConstructorV1.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/tenant/TenantMsgConstructorV2.java
> Edge - minor fix

- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
- application/src/test/java/org/thingsboard/server/utils/TbSubscriptionUtilsTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/EntityType.java
> Fix TbSubscriptionUtils order for matching KeyValueType and DataType

- ui-ngx/.eslintrc.json
- ui-ngx/src/app/shared/components/time/timeinterval.component.ts
- ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
> Fixed some time new time windows intervals not apply in timewindows panel

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.scss
- ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.scss
- ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.scss
- ui-ngx/src/form.scss
> Fixed mask for older version chrome

- ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.models.ts
> Fixed Power button widget on Firefox

- application/src/main/java/org/thingsboard/server/service/queue/TbRuleEngineConsumerStats.java
- common/stats/src/main/java/org/thingsboard/server/common/stats/DefaultStatsFactory.java
- common/stats/src/main/java/org/thingsboard/server/common/stats/StatsFactory.java
> Add tenantId tag to Rule Engine stats

- ui-ngx/src/app/shared/components/image/multiple-gallery-image-input.component.html
- ui-ngx/src/app/shared/components/image/multiple-gallery-image-input.component.ts
> Fixed not opened image gallery when used multiple-gallery-image-input.component.ts

- application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
- application/src/main/java/org/thingsboard/server/controller/TwoFactorAuthConfigController.java
Fixed placeholder resolving for springdoc.
```
o.s.core.utils.PropertyResolverUtils - Could not resolve placeholder 'recipientTitle' in value "Creates or updates notification template.
```   
After changes, the description in Swagger is the same.
> fixed resolving placeholder in Operation notes

- ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.ts
Before [Safary]:
After [Safary]:
> Fixed battery level widget for safari and firefox

- application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessor.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantEdgeProcessor.java
- application/src/main/resources/thingsboard.yml
- application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessorTest.java
- application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessorTest.java
- common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
[Issue](https://github.com/thingsboard/thingsboard/issues/10470)
Also, a Notification message is sent if the limit is violated.
> Yaml config for max size of telemetry message sent to Edge

- application/src/main/java/org/thingsboard/server/service/entitiy/AbstractTbEntityService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
- application/src/main/java/org/thingsboard/server/service/entitiy/device/DefaultTbDeviceService.java
- application/src/test/java/org/thingsboard/server/controller/AssetControllerTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/AlarmRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
Fixed asset/device deletion method to avoid deletion of propagated alarms.
> Do not delete propagated alarms while asset deletion

- application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
- common/data/src/main/java/org/thingsboard/server/common/data/EntityType.java
- common/data/src/main/java/org/thingsboard/server/common/data/kv/DataType.java
- common/proto/src/main/java/org/thingsboard/server/common/util/KvProtoUtil.java
- common/proto/src/test/java/org/thingsboard/server/common/util/KvProtoUtilTest.java
> Fix KvProtoUtils order for matching KeyValueType and DataType

- msa/js-executor/package.json
- msa/js-executor/yarn.lock
- pom.xml
- org.postgresql:postgresql [42.7.3](https://mvnrepository.com/artifact/org.postgresql/postgresql/42.7.3)
- org.apache.zookeeper:zookeeper [3.9.2](https://mvnrepository.com/artifact/org.apache.zookeeper/zookeeper/3.9.2)
- "@google-cloud/pubsub": ["^4.3.3"](https://yarnpkg.com/package?q=%40google-cloud%2Fpubsub&name=%40google-cloud%2Fpubsub&version=4.3.3) --> protobufjs "^7.2.4"
https://github.com/thingsboard/thingsboard/security/dependabot?q=is%3Aopen+severity%3Acritical
> Critical dependency vulnerabilities fix

- docker/haproxy/config/blocklist.txt
- docker/haproxy/config/haproxy.cfg
- docker/haproxy/config/trustlist.txt
> HAproxy rate and connection limits (images api included)

- application/src/main/java/org/thingsboard/server/controller/EntityQueryController.java
- application/src/test/java/org/thingsboard/server/controller/UserControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
> Improve entity data query

- application/src/main/data/upgrade/3.6.3/schema_update.sql
- application/src/main/java/org/thingsboard/server/controller/NotificationController.java
- application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
- application/src/main/java/org/thingsboard/server/service/notification/channels/MobileAppNotificationChannel.java
- application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultFirebaseService.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
- application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationService.java
- common/data/src/main/java/org/thingsboard/server/common/data/notification/Notification.java
- common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
- dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
- dao/src/main/java/org/thingsboard/server/dao/model/sql/NotificationEntity.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationService.java
- dao/src/main/java/org/thingsboard/server/dao/notification/NotificationDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRepository.java
- dao/src/main/resources/sql/schema-entities-idx.sql
- dao/src/main/resources/sql/schema-entities.sql
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
- rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/notification/FirebaseService.java
> Improvements for mobile notifications

- application/src/main/java/org/thingsboard/server/service/entitiy/EntityStateSourcingListener.java
- application/src/main/java/org/thingsboard/server/service/entitiy/tenant/DefaultTbTenantService.java
- application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
- application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/tenant/TenantService.java
- dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
```
2024-03-26 17:46:21,502 [http-nio-0.0.0.0-8080-exec-3] WARN o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 23505 
2024-03-26 17:46:21,502 [http-nio-0.0.0.0-8080-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: duplicate key value 
violates unique constraint "api_usage_state_unq_key" Detail: Key (tenant_id, entity_id)=(fe3c96c0-eb87-11ee-969a-b93273cfdc4d, 
fe3c96c0-eb87-11ee-969a-b93273cfdc4d) already exists. 
2024-03-26 17:46:21,511 [http-nio-0.0.0.0-8080-exec-3] WARN o.t.s.controller.TenantController - Database error: 
DataIntegrityViolationException - PSQLException: ERROR: duplicate key value violates unique constraint "api_usage_state_unq_key" 
Detail: Key (tenant_id, entity_id)=(fe3c96c0-eb87-11ee-969a-b93273cfdc4d, fe3c96c0-eb87-11ee-969a-b93273cfdc4d) …
```
> Fix tenant creation

- common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
- dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
- dao/src/test/java/org/thingsboard/server/dao/service/EntityServiceTest.java
[Improve query after review](https://github.com/thingsboard/thingsboard/pull/10386)
> Entity Data Query: improvement

- application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/AbstractLwM2MIntegrationDiffPortTest.java
- application/src/test/resources/logback-test.xml
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbInMemoryRegistrationStore.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStore.java
```
2024-04-10 16:44:48,708 [CoapServer(main)#7] ERROR o.t.s.t.l.s.d.AbstractLwM2MIntegrationDiffPortTest - RegistrationUpdate arguments [RegistrationUpdate [registrationId=3OhZexS2EL, clientTransportData=IpPeer [peerAddress=/127.0.0.1:58668, identity=Identity [psk=SOME_PSK_ID_5]], lifeTimeInSec=null, smsNumber=null, bindingMode=null, objectLinks=null, alternatePath=null, supportedContentFormats=null, supportedObjects=null, availableInstances=null, additionalAttributes={}, applicationData={}]]
```
> fix_bug_lwm2m tests dif Port

- ui-ngx/src/assets/locale/locale.constant-en_US.json
> [IoT Gateway] Deleting an extra in in the Docker Commands/Launch Command pop-overs

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-3409
```
The encodeURI() function escapes characters by UTF-8 code units, with each octet encoded in the format %XX, left-padded with 0 if necessary. Because lone surrogates in UTF-16 do not encode any valid Unicode character, they cause encodeURI() to throw a [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError).
```
> tbel_encodeDecodeUri_java_as_mdn

- application/src/main/resources/thingsboard.yml
EDGES_RPC_CLIENT_MAX_KEEP_ALIVE_TIME_SEC, EDGES_RPC_KEEP_ALIVE_TIME_SEC, EDGES_RPC_KEEP_ALIVE_TIMEOUT_SEC
> Added details description of edge params

- ui-ngx/src/app/core/http/device-profile.service.ts
[Put your PR description here instead of this sentence.   ](https://thingsboard-portal.atlassian.net/browse/PROD-3447)
error: lwm2m**/**?
```
http://localhost:8080/api/resource/lwm2m/?sortProperty=id&sortOrder=ASC&objectIds=3_1.2
```
ok
```
http://localhost:8080/api/resource/lwm2m?sortProperty=id&sortOrder=ASC&objectIds=3_1.2'
```
> fix_bug_lwm2m_API_getLwm2mObjects

- monitoring/src/main/java/org/thingsboard/monitoring/client/Lwm2mClient.java
> Monitoring: increase lwm2m client registration lifetime

- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/test/java/org/thingsboard/server/service/sql/SequentialTimeseriesPersistenceTest.java
- common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
- common/proto/src/main/java/org/thingsboard/server/common/adaptor/ProtoConverter.java
- common/proto/src/test/java/org/thingsboard/server/common/adaptor/JsonConverterTest.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/adaptors/JsonCoapAdaptor.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/adaptors/ProtoCoapAdaptor.java
- common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportServerHelper.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/JsonMqttAdaptor.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/ProtoMqttAdaptor.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/util/JsonUtils.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/geo/TbGpsGeofencingActionNode.java
Replaced the use of the deprecated parse() methods from the JsonParser class with the use of a static methods.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2529
> Replaced deprecated JsonParser methods

- ui-ngx/package.json
- ui-ngx/src/app/app.component.ts
- ui-ngx/src/app/core/auth/auth.service.ts
- ui-ngx/src/app/core/core.module.ts
- ui-ngx/src/app/core/services/resources.service.ts
- ui-ngx/src/app/core/settings/settings.effects.ts
- ui-ngx/src/app/core/settings/settings.utils.ts
- ui-ngx/src/app/core/translate/translate-default-loader.ts
- ui-ngx/src/app/core/utils.ts
- ui-ngx/src/app/modules/login/pages/login/login.component.html
- ui-ngx/src/app/shared/components/json-content.component.html
- ui-ngx/src/app/shared/components/json-content.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/yarn.lock
> Improved detect and set translation platform language

- common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
- common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
- common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandlerTest.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
PE PR - https://github.com/thingsboard/thingsboard-pe/pull/2483
Device activity for devices, connected through the gateway, doesn't update in activity manager, so in cannot be processed correctly and can easily be disconnected by reaching session timeout between core and transport. to avoid this we need to use PINGREQ for gateway as a devices activity events, in case of overwriteDeviceActivity parameter enabled for the gateway.
In this PR I have added the next logic - when ping requests for gateway device will be also activity events for devices, connected through the gateway
> Devices activity, connected through the gateway fix

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisSecurityStore.java
fix bug: lwm2m redis - add logs to decode securityInfo by endpoint
> fix bug_lwm2m_redis_add_ logs

- ui-ngx/src/app/app.component.ts
- ui-ngx/src/app/core/auth/auth.selectors.ts
- ui-ngx/src/app/core/auth/auth.service.ts
- ui-ngx/src/app/shared/components/json-content.component.ts
> Improved detect auth user in load

- common/data/src/main/java/org/thingsboard/server/common/data/Tenant.java
Deleted "required" from tenant email swagger schema
> Deleted "required" from tenant email swagger schema

- dao/src/test/java/org/thingsboard/server/dao/AbstractRedisContainer.java
- docker/docker-compose.hybrid.yml
- docker/docker-compose.kafka.yml
- docker/docker-compose.redis-cluster.yml
- docker/docker-compose.redis-sentinel.yml
- docker/docker-compose.redis.yml
- docker/docker-compose.yml
- msa/black-box-tests/src/test/resources/docker-compose.redis-ssl.yml
for docker-compose, msa and testcontainers
**blocked by**: https://github.com/thingsboard/docker/pull/14
> docker images upgraded

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
> added clear cache for upgrade from 3.6.4 to 3.7.0

- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'transport.coap.dtls.connection_id_length' in value "${transport.coap.dtls.connection_id_length}"
```
> coap.dtls.connection_id_length added default null value to tolerate yaml inconsistency case

- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'transport.coap.dtls.connection_id_length' in value "${transport.coap.dtls.connection_id_length}"
```
> fix_bug_coap_connection_id_length

- application/src/test/java/org/thingsboard/server/service/state/DefaultRuleEngineDeviceStateManagerTest.java
[PE PR](https://github.com/thingsboard/thingsboard-pe/pull/2550)
> Replace static mocks with consumers in `DefaultRuleEngineDeviceStateManagerTest`

- application/src/main/java/org/thingsboard/server/service/entitiy/EntityStateSourcingListener.java
> Improvement for EntityStateSourcingListener

- dao/src/test/java/org/thingsboard/server/dao/service/EntityServiceTest.java
Added tests for EntityService to increase code coverage
> Added tests for EntityService

- dao/src/test/java/org/thingsboard/server/dao/service/event/BaseEventServiceTest.java
- dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningDaysAlwaysExistsTest.java
- dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningHoursAlwaysExistsTest.java
- dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningIndefiniteAlwaysExistsTest.java
- dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningMinutesAlwaysExistsTest.java
- dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningMonthsAlwaysExistsTest.java
- dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningYearsAlwaysExistsTest.java
> deprecated ISO_DATETIME_TIME_ZONE_FORMAT replaced with ISO_8601_EXTENDED_DATETIME_TIME_ZONE_FORMAT

- application/src/main/resources/thingsboard.yml
This will fix the issue with failed health check even if elasticsearch sink does not enabled
I have experienced this during install:
```
2024-04-29 18:45:52,417 [main] INFO  o.t.s.s.i.SqlEntityDatabaseSchemaService - Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
2024-04-29 18:45:52,428 [main] INFO  o.t.s.s.i.SqlEntityDatabaseSchemaService - Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
2024-04-29 18:45:52,461 [main] INFO  o.t.s.s.i.SqlAbstractDatabaseSchemaService - Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
2024-04-29 18:45:52,493 [RMI TCP Connection(1)-127.0.0.1] WARN  o.s.b.a.e.ElasticsearchRestClientHealthIndicator - Elasticsearch health check failed …
```
> manage ElasticsearchRestClientHealthIndicator HealthCheck (default is disabled)

- common/coap-server/pom.xml
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
- common/coap-server/src/test/java/org/thingsboard/server/coapserver/TbCoapDtlsSettingsTest.java
> TbCoapDtlsSettingsTest

- application/src/main/java/org/thingsboard/server/service/notification/channels/MobileAppNotificationChannel.java
> Improve mobile notifications stability

- application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
> Fix flaky test testBulkImportDeviceWithUpdateFalse

- application/src/test/java/org/thingsboard/server/controller/AuditLogControllerTest.java
AuditLogControllerTest fix
7days partition clashed with default 1 day
```
partitioningRepository.createPartitionIfNotExists("audit_log", entityTs, TimeUnit.DAYS.toMillis(7));
```
> AuditLogControllerTest fix

- ui-ngx/src/app/core/core.module.ts
- ui-ngx/src/app/core/settings/settings.utils.ts
- ui-ngx/src/app/core/translate/translate-default-loader.ts
> Improvement translate loader and types

- pom.xml
After updating the `json-schema-validator` version, the mail sender does not work!
> fixed mail sender

- transport/coap/pom.xml
- transport/http/pom.xml
- transport/lwm2m/pom.xml
- transport/mqtt/pom.xml
JUnit5 migration in transport.
> JUnit5 migration in transport.

- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/DefaultExportableEntitiesService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/ExportableEntitiesService.java
- application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
- application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/DeviceProfile.java
- common/data/src/main/java/org/thingsboard/server/common/data/HasDefaultOption.java
- common/data/src/main/java/org/thingsboard/server/common/data/asset/AssetProfile.java
- common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChain.java
- dao/src/main/java/org/thingsboard/server/dao/ExportableEntityDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetProfileDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceProfileDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/rule/JpaRuleChainDao.java
> VC: resolve existing default entity when loading version

- application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
- application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
Fixed the issue with redirecting to the login page after page reload.
> fix with security matchers

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
- ui-ngx/src/app/shared/models/dashboard.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
[simplescreenrecorder-2023-11-13_17.44.29.webm](https://github.com/thingsboard/thingsboard/assets/87172504/cab5f2f7-b69f-4cc7-9c03-e22b0bb17490)
> Added ability to display dashboard right layout first in mobile view

- ui-ngx/src/app/modules/home/components/widget/config/data-keys.component.ts
- ui-ngx/src/app/shared/components/color-input.component.ts
- ui-ngx/src/app/shared/components/color-picker/color-picker-panel.component.html
- ui-ngx/src/app/shared/components/color-picker/color-picker-panel.component.scss
- ui-ngx/src/app/shared/components/color-picker/color-picker-panel.component.ts
- ui-ngx/src/app/shared/components/color-picker/color-picker.component.html
- ui-ngx/src/app/shared/components/color-picker/color-picker.component.scss
- ui-ngx/src/app/shared/components/color-picker/color-picker.component.ts
- ui-ngx/src/app/shared/components/color-picker/hex-input.component.html
- ui-ngx/src/app/shared/components/color-picker/hex-input.component.scss
- ui-ngx/src/app/shared/components/color-picker/hex-input.component.ts
- ui-ngx/src/app/shared/components/dialog/color-picker-dialog.component.html
- ui-ngx/src/app/shared/components/popover.component.ts
- ui-ngx/src/app/shared/components/popover.service.ts
- ui-ngx/src/app/shared/shared.module.ts
Redesign for color picker
Popover:
Mobile
Tablet
Desktop
Dialog:
Mobile
Tablet
Desktop
> Color picker design improvement

- ui-ngx/src/app/modules/home/components/widget/lib/legend.component.html
Added parsing Unicode into symbols for chart legend 
Before:
After:
> Parsing unicode in legend

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings-panel.component.scss
> Fixed timeseries chart widget threshold settings styles

- ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
Custom translations wasn't working for the originator on the alarms page, here are the screens before and after fix.
Before:
After:
> [Custom Translation] Add support for custom translations of alarm originator on the alarms page

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
math node flaky test fixed
10000 runs passed in parallel mode
> math node flaky test fixed

- application/src/main/data/upgrade/3.6.4/schema_update.sql
Fixed schema_update.sql for case when attribute_kv is empty
> Fixed schema_update.sql for case when attribute_kv is empty

- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/OtaPackageTransportResource.java
if (for whatever reason) californium goes out of transparent block mode it is required to supply the correct block number to not get a internal server error.
> Always send back block num

- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
> fixed removing relations between rule nodes

- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
When we create a new tenant, we need to follow Event ordering (TenantEntity, then other entities).
`defaultEntitiesCreator.accept(tenantId);` should be invoked before the Tenant save event because during save default rule chains, we publish cache evict event for relations, which should be processed first. (In the future, we plan to add custom events handler with special ordering In one **transtction**) 
EntityStateSourcingListener
> fixed events ordering during tenant creation

- common/queue/src/main/java/org/thingsboard/server/queue/notification/DefaultNotificationDeduplicationService.java
> Fix for notification deduplication service

- application/src/main/java/org/thingsboard/server/service/install/SqlAbstractDatabaseSchemaService.java
- application/src/main/java/org/thingsboard/server/service/install/SqlEntityDatabaseSchemaService.java
before:
after:
No conflicts during merge to PE.
> updated log entry for adding customer_title_unq_key if doesn't exist

- application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
- common/cache/src/main/java/org/thingsboard/server/cache/limits/DefaultRateLimitService.java
- common/cache/src/main/java/org/thingsboard/server/cache/limits/RateLimitService.java
- dao/src/main/java/org/thingsboard/server/dao/util/AbstractBufferedRateExecutor.java
The following error occurs when deleting tenant (from demo.thingsboard.io):
```
2024-05-03 11:59:21,158 [housekeeper-consumer-31-thread-1] WARN  o.t.s.s.h.HousekeeperService - [xxx] Failed to process timeseries history deletion for api usage state xxx for key 'transportApiState' (attempt 0), submitting for reprocessing
org.thingsboard.server.common.data.exception.TenantProfileNotFoundException: Profile for tenant with id xxx not found
at org.thingsboard.server.cache.limits.DefaultRateLimitService.checkRateLimit(DefaultRateLimitService.java:71)
at org.thingsboard.server.cache.limits.DefaultRateLimitService.checkRateLimit(DefaultRateLimitService.java:61)
at org.thingsboard.server.dao.util.AbstractBufferedRateExecutor.submit(AbstractBufferedRateExecutor.java:117)
at …
```
> Fix "Failed to process timeseries history deletion" when deleting tenant

- pom.xml
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
> Commons logging excluded

- application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
- application/src/main/java/org/thingsboard/server/service/mail/MailSenderInternalExecutorService.java
- application/src/main/java/org/thingsboard/server/service/mail/TbMailContextComponent.java
- application/src/main/resources/thingsboard.yml
- common/data/src/main/java/org/thingsboard/server/common/data/exception/RateLimitExceededException.java
- common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java
> Mail rate limits and watchdog

- ui-ngx/src/app/core/services/dynamic-component-factory.service.ts
This PR addresses an issue in the platform's markdown widget where an incorrect HTML tag would not trigger an error message, yet it would cause adjacent widgets with correct code to malfunction on the dashboard. The fix ensures that all widgets operate independently and errors are handled gracefully without affecting the overall dashboard functionality.
Before:
After:
>  Fix for Incorrect HTML tag handling in markdown widgets

- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
> Fix maxRuleNodeExecutionsPerMessage (failed test TenantProfileEdgeTest.testTenantProfiles)

- ui-ngx/src/app/core/api/data-aggregator.ts
- ui-ngx/src/app/shared/models/time/time.models.ts
With given data keys config in entities table widget:
Aggregation result
**before:**
[Screencast from 10.04.24 12:46:15.webm](https://github.com/thingsboard/thingsboard/assets/87172504/2747a1d6-55dc-481b-93ba-189293ae9188)
**after:**
[Screencast from 10.04.24 12:47:29.webm](https://github.com/thingsboard/thingsboard/assets/87172504/6ab0fbcf-7728-4add-9b9d-614543b1a2f9)
> Fix for aggregation in entities table widget

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
> fix_bug_LwM2MClientSerDes_test

- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
Problem:
```
2024-05-08 17:13:56,385 [LwM2M uplink-0-1] ERROR o.t.s.t.l.s.u.DefaultLwM2mUplinkMsgHandler - [deviceEndpointRpc144] endpoint [{}] error Unable registration.
19:13:56   java.lang.NullPointerException: null
```
> fix_bug_setSupportedClientObjects_root

- application/src/main/java/org/thingsboard/server/service/security/model/token/JwtTokenFactory.java
> Jwt token factory refactored due to PE

- application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
- application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
> Added more logs to DefaultTbApiUsageStateService

- msa/js-executor/api/utils.ts
- msa/js-executor/config/custom-environment-variables.yml
- msa/js-executor/config/default.yml
- msa/js-executor/queue/kafkaTemplate.ts
> Add SSL support for Kafka queue connection in JS executor

- application/src/main/java/org/thingsboard/server/service/mobile/secret/MobileSecretRedisCache.java
> Fix MobileSecretRedisCache

- application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/subscription/ModifySubscriptionResult.java
- application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
- application/src/main/java/org/thingsboard/server/service/ws/WebSocketMsgEndpoint.java
- application/src/main/java/org/thingsboard/server/service/ws/WebSocketService.java
Added scheduled session cleanup for cases when session was closed before last session command processed
> Added scheduled session cleanup

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
https://thingsboard-portal.atlassian.net/browse/PROD-3707
Fixed empty default config in gateway connector.
Before
After
> fixed race condition during adding new gateway connector with default config

- application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
> added upgrade for the gateway rate limits

- application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
- application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
> Fix NotificationApiTest

- application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
- application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainActorMessageProcessor.java
- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
- application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
- application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java
- application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/queue/Queue.java
- common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
- common/message/src/main/proto/tbmsg.proto
- common/proto/src/main/proto/queue.proto
- common/queue/src/main/java/org/thingsboard/server/queue/common/TbRuleEngineProducerService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/PartitionService.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/QueueRoutingInfo.java
- common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerStatsService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
- ui-ngx/src/app/modules/home/components/profile/queue/tenant-profile-queues.component.ts
- ui-ngx/src/app/modules/home/components/profile/tenant-profile.component.ts
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
- ui-ngx/src/app/modules/home/components/queue/queue-form.component.ts
- ui-ngx/src/app/shared/models/queue.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Queue option to duplicate msgs to all partitions

- application/src/main/resources/thingsboard.yml
- common/queue/src/test/java/org/thingsboard/server/queue/util/PropertyUtilsTest.java
- msa/js-executor/config/default.yml
- msa/vc-executor/src/main/resources/tb-vc-executor.yml
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/http/src/main/resources/tb-http-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
- transport/mqtt/src/main/resources/tb-mqtt-transport.yml
- transport/snmp/src/main/resources/tb-snmp-transport.yml
```
2024-05-10 11:11:27,811 [main] INFO  o.a.k.c.s.a.AbstractLogin - Successfully logged in.
2024-05-10 11:11:43,904 [main] INFO  o.a.k.c.t.i.KafkaMetricsCollector - initializing Kafka metrics collector
2024-05-10 11:11:44,451 [main] WARN  o.t.server.queue.kafka.TbKafkaAdmin - [tb_transport.api.responses.localhost] Failed to create topic
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:16 …
```
> Kafka Confluent compatibility out of the box: segment.bytes:52428800

- ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.html
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Added hint for Time series chart for comparison series

- ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Fixed for column index, even action is not cell click, disables save due to incorrect validation
> Fixed widget action dialog column index field blocks save

- application/src/main/resources/thingsboard.yml
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/CoapServerContext.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/CoapServerService.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/DefaultCoapServerService.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
- common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapTransportComponent.java
- common/coap-server/src/test/java/org/thingsboard/server/coapserver/TbCoapDtlsSettingsTest.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportContext.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportService.java
- common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
- transport/coap/src/main/resources/tb-coap-transport.yml
- transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
In all *.yml on CE and PE dtls settings should look like this:
```
coap:
dtls:
...
(without transport)
```
In TbCoapDtlsSettings itself there should not be transport either, as it is a common structure for different services.
> coap_refactoring_ransport_yml_03

- application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaAttributeDao': Unsatisfied dependency expressed through field 'dataSource': Error creating bean with name 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties': Could not bind properties to 'DataSourceProperties' : prefix=spring.datasource, ignoreInvalidFields=false, ignoreUnknownFields=true
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
at …
```
> clear all WS sessionsMap when stopping the application

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
Device Profile Node Alarm start ts can't be greater then alarm end ts!
> fixed alarm rule with future ts

- application/src/main/java/org/thingsboard/server/controller/AuthController.java
- application/src/main/java/org/thingsboard/server/service/security/model/SecurityUser.java
- application/src/main/java/org/thingsboard/server/service/security/model/token/JwtTokenFactory.java
- application/src/test/java/org/thingsboard/server/service/security/auth/JwtTokenFactoryTest.java
- common/data/src/main/java/org/thingsboard/server/common/data/BaseDataWithAdditionalInfo.java
- common/data/src/main/java/org/thingsboard/server/common/data/security/model/JwtPair.java
> Fix token sessionId calculation

- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
Fixed hotkey event for Search nodes field.
> Fixed hotkey event for search field on rule chain page

- ui-ngx/src/app/shared/components/popover.component.scss
Fixed **Navigate to new dashboard state** action with **Dashboard state display option: Open in popover** with disabled **Hide dashboard toolbar in popover** displaying popover with hidden close button under toolbar
before:
after:
> Fixed popover close button hidden under dashboard toolbar

- ui-ngx/src/app/shared/components/color-picker/color-picker.component.scss
> Fixed Color picker centering color copy for dialog

- ui-ngx/src/app/core/api/alarm-data-subscription.ts
Fixed fetch new alarm data in real-time.
Due to next code, we can't set startTs for realtime because we will not see data updates after creating a new one Alarm.
So startTs we should set only for history data. For realtime "startTs"," endTs" should changed dynamically by current time.
> [TimeWindow] - For Realtime alarm data query

- common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
> fixed device profile proto deserialization

- ui-ngx/src/app/shared/components/image/gallery-image-input.component.scss
> Fixed layout with long file name

- application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
> fixed component type dropdown in swagger

- application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
Fixed entity data query permission part for DASHBOARD entity.
This fixes issue https://github.com/thingsboard/thingsboard/issues/10812
> Fixed entity data query for dashboards on customer level

- application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
- application/src/main/java/org/thingsboard/server/controller/QueueStatsController.java
- application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
- common/dao-api/src/main/java/org/thingsboard/server/dao/queue/QueueStatsService.java
- dao/src/main/java/org/thingsboard/server/dao/queue/BaseQueueStatsService.java
- dao/src/main/java/org/thingsboard/server/dao/queue/QueueStatsDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/queue/JpaQueueStatsDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/queue/QueueStatsRepository.java
- dao/src/test/java/org/thingsboard/server/dao/service/QueueStatsServiceTest.java
Added api to retrieve queue stats entities
> Added api to retrieve queue stats entities

- application/src/main/java/org/thingsboard/server/controller/ImageController.java
> fixed multipart file for image upload in swagger

- packaging/java/scripts/windows/install.bat
- packaging/java/scripts/windows/install_dev_db.bat
After changing the package name for the application, installation in Windows does not work.
`Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.PropertiesLauncher
ThingsBoard installation failed!`
> used package name instead of hardcoded for windows packaging

- ui-ngx/src/app/shared/models/widget.models.ts
In this pull request, we have updated the example for creating a new time series widget. The changes were necessary to prevent the use of deprecated widgets in the example. 
Before:
After:
> Updated widget template for new timeseries widget creation

- ui-ngx/src/app/modules/home/components/widget/config/basic/cards/progress-bar-basic-config.component.html
- ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.html
- ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/cards/progress-bar-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/progress-bar-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/battery-level-widget-settings.component.html
- ui-ngx/src/app/shared/models/widget-settings.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Fixed list:
- Added Drag icon for ticks (Digital gauge advanced settings);
B:
A:
- Fixed Min Max Value for gradient tab;
- Fixed gradient Color calculation for digital gauge and other widget.
- Add advanced gradient tab for digital gauge;
- Fixed Drag and Drop;
- Delete setting property 'default color' and use bar constant color.
> Hot fix for color settings and digital gauge

- application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
Implemented entity field "name" for queue stats entity
> Implemented entity field "name" for queue stats entity

- application/src/main/java/org/thingsboard/server/controller/AlarmController.java
- application/src/main/java/org/thingsboard/server/controller/AssetController.java
- application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
- application/src/main/java/org/thingsboard/server/controller/DashboardController.java
- application/src/main/java/org/thingsboard/server/controller/DeviceController.java
- application/src/main/java/org/thingsboard/server/controller/EdgeController.java
- application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
- application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
- application/src/main/java/org/thingsboard/server/controller/QueueStatsController.java
- application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
- application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
Swagger: fixed the way arrays are displayed in request param
> Swagger: fixed the way arrays are displayed in request param

- ui-ngx/src/app/modules/home/components/alias/entity-alias-dialog.component.ts
- ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
- ui-ngx/src/app/modules/home/components/relation/relation-filters.component.ts
1. Fixed error on save relation query alias with empty relation filter
before:
[Screencast from 10.06.24 16:40:32.webm](https://github.com/thingsboard/thingsboard/assets/87172504/4d9caae9-d77f-494e-958e-c669ee542374)
after:
[Screencast from 10.06.24 16:42:56.webm](https://github.com/thingsboard/thingsboard/assets/87172504/dac818d1-73ed-4b6f-9ef8-eed8537c3c39)
2. Not option is disabled until relation type is empty
before:
after:
> Relation filter enhancement

- ui-ngx/src/app/shared/models/limited-api.models.ts
> Fixed typo translate in api-limit

- ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
> Fixed notification again not apply new params

- dao/src/main/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidator.java
- dao/src/test/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidatorTest.java
[Put your PR description here instead of this sentence.   ](https://thingsboard-portal.atlassian.net/browse/PROD-3838)
> Fix_bug lwm2m Bootstrap ShortServerId

- application/src/main/java/org/thingsboard/server/service/notification/rule/cache/DefaultNotificationRulesCache.java
- dao/src/main/java/org/thingsboard/server/dao/eventsourcing/ActionCause.java
- dao/src/main/java/org/thingsboard/server/dao/housekeeper/CleanUpService.java
- dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
> Fix "Tenant not found" errors on tenant deletion

- application/src/main/java/org/thingsboard/server/service/notification/channels/EmailNotificationChannel.java
- application/src/main/java/org/thingsboard/server/service/notification/channels/SmsNotificationChannel.java
> Fix sysadmin notification being sent with tenant mail sender

- dao/src/main/java/org/thingsboard/server/dao/sql/rule/RuleNodeRepository.java
- dao/src/test/java/org/thingsboard/server/dao/sql/rule/JpaRuleNodeDaoTest.java
We don't need a count query during the rule nodes upgrade. The change provided should improve the performance of rule node IDs retrieval for environments(demo.thingsboard.io) where the total number of rule nodes of one type is huge.
> Rule node ids seach query: replaced Page with Slice to exclude count query execution

- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.ts
Fixed label for long min max value;
Fixed position update;
> Hotfix for color settings

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
Fixed templates display on opening SNMP connector
before:
after:
> Fixed templates display on opening SNMP connector

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
> Refactor stale subs cleanup on ClusterTopologyChangeEvent

- ui-ngx/src/app/modules/home/components/widget/lib/rpc/persistent-table.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> "Request Timeout." -> "Request timeout"

- ui-ngx/src/app/shared/models/device.models.ts
> Fix MD5 SNMP authentication protocol

- dao/src/test/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidatorTest.java
add tests by Fix bug lwm2m bootstrap short id
> Add tests for LwM2M device profile validation

- application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
- common/data/src/main/java/org/thingsboard/server/common/data/TenantProfile.java
- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
- common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/TenantProfileConfiguration.java
Updated TenantProfile swagger example
> Updated TenantProfile swagger example

- dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
Fixed cassandra timeseries deletion if partition is INDEFINITE
> Fixed cassandra timeseries deletion if partition is INDEFINITE

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
In the previous PR, a new property was added to the rule node configuration, but the version was not set. Despite this, all previously created nodes continued to function correctly, as did the nodes created after the last change. This was because the new property was initialized with value false during the conversion to the configuration class inside the init method. In this PR, the missing version has now been set. All existing nodes continue to function correctly with this update.
> Mqtt node: set rule node version

- application/src/main/data/json/edge/instructions/install/centos/instructions.md
- application/src/main/data/json/edge/instructions/install/ubuntu/instructions.md
- application/src/main/java/org/thingsboard/server/service/edge/instructions/BaseEdgeInstallUpgradeInstructionsService.java
- application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeInstallInstructionsService.java
- application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeUpgradeInstructionsService.java
Updates to Edge Install/Upgrade instructions:
1. Java 17 install guide
2. Fix tag usage to download files from github
3. Refactoring - move common part of install/upgrade services to base class
> Edge install instructions update. Use Java 17. Fix tag usage

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.html
- ui-ngx/src/app/shared/models/page/sort-order.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/assets/locale/locale.constant-lt_LT.json
- ui-ngx/src/assets/locale/locale.constant-pl_PL.json
Changed status column title to 'level' in logs
Gateway Logs:
before:
after:
Gateway Connector Logs:
before:
after:
>  Changed status column title to 'level' in logs

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
- ui-ngx/src/app/shared/models/page/sort-order.ts
fixed gateway dashboard sorting by status
**before:**
ASC and DESC:
**after:**
ASC: 
DESC:
> Fixed gateway dashboard sorting connectors by status

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.scss
Added adaptive height for datamaping dialog
before:
after:
>  Added adaptive height for datamaping dialog

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/device-info-table.component.html
Added asterisk symbol to fields 'name' and 'profile name' in MQTT Connector Device Configuration
before:
after:
> Added asterisk symbol in Device Configuration

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Changed method field in SNMP Connector
before:
after:
> Changed method field in SNMP Connector

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.scss
Added max width to the display of the template name
before:
after:
> Added max width to the display of the template name

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
Added missing inputs for Custom and GRCP Connectors
**Connector Creation:**
before:
after:
**Connector configuration:**
before:
after:
> Added missing inputs for Custom and GRCP Connectors

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
Removed toggle 'fill configuration with default values' for GRCP and Custom Connectors
before:
after:
> Removed toggle 'fill configuration with default values'

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.scss
Optimized the 'Commands' table in the statistics tab for the 'General configuration' pop-up window
before:
after:
> Optimized the 'Commands' table in the statistics tab

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
Added optimization for the fields in Gateway Configuration
before:
after:
> Added optimization for the fields in Gateway Configuration

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rest-connector-secuirity/rest-connector-security.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rest-connector-secuirity/rest-connector-security.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rest-connector-secuirity/rest-connector-security.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
Changed Security block for REST Connector
before:
after:
> Changed Security block for REST Connector

- ui-ngx/src/app/shared/components/json-content.component.html
Made JSON content toolbar visible
before:
after:
> Made JSON content toolbar visible

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
**1.Disabled autocomplete for connector name form field in add dialog to prevent overwriting existing connector with same name.**
before:
[Screencast from 13.06.24 12:51:25.webm](https://github.com/thingsboard/thingsboard/assets/87172504/2c3094e9-a9d8-4f34-868a-60865a42de62)
after:
[scrnli_6_13_2024_12-14-16 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/263db869-673f-49fe-bd82-ed293fd8baf3)
**2. Added missing duplicate name error icon**
before: 
after:
> Fixed Gateway connectors name form fields

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/sns/TbSnsNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/sns/TbSnsNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/sqs/TbSqsNodeTest.java
Added tests for the Sqs and Sns nodes.
> AWS nodes: added tests

- ui-ngx/src/app/modules/home/pages/widget/widget-type-autocomplete.component.html
- ui-ngx/src/app/modules/home/pages/widget/widget-type-autocomplete.component.ts
- ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
- ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html
- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
- ui-ngx/src/app/shared/components/entity/entity-list.component.html
- ui-ngx/src/app/shared/components/entity/entity-list.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Added no text option for autocomplete

- ui-ngx/src/app/modules/home/components/device/device-info-filter.component.html
- ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.html
- ui-ngx/src/app/modules/home/pages/asset/asset-table-header.component.html
>  Fixed entity table header components disabled create new device/asset profile 

- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.ts
Issue occurs because of mat-chip-row focus-out event transforms it's values(array of objects in this case) to array of strings as described in issue - https://github.com/angular/components/issues/26358 
before:
[scrnli_6_13_2024_6-42-05 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/984a8b9c-2190-4601-ae10-7ba55fc205c8)
after:
[scrnli_6_13_2024_6-45-28 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/5fac969f-6715-4e69-83b1-ccf93504ba37)
> Fixed LWM2M device profile transport configuration "object list" form field value persistence on tab switch

- ui-ngx/src/app/modules/home/components/profile/device/coap-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-transport-configuration.component.ts
before:
[scrnli_6_18_2024_3-15-57 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/83189868-c3f5-4ada-b6b7-6af8716b85d2)
after:
[scrnli_6_18_2024_3-20-23 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/0e36744d-f4d8-4294-9ddf-b28bc29858d0)
> Fixed disappearing of device profile transport config form on tab switch if it is invalid

- ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
- ui-ngx/src/app/modules/home/models/datasource/attribute-datasource.ts
If attribute or telemetry has empty string value it was not displayed in attribute table. This PR disables filtering of empty string attributes.
**before fix:**
**after fix:**
Copy value button is not shown for such values.
> Disabled filtering of attributes with empty string values for attribute table

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
> Fixed UI build

- application/src/main/java/org/thingsboard/server/controller/BaseController.java
- application/src/test/java/org/thingsboard/server/controller/DashboardControllerTest.java
- dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
> Proper error message when deleting dashboard referenced by asset profile

- application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
- common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
> Use Main queue if supplied queueName is empty

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
> send resourse change/delete events only for lwm2m

- application/src/main/data/upgrade/3.7.0/schema_update.sql
- application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
- application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
> Upgrade script from 3.7.0 to 3.7.1

- pom.xml
[Put your PR description here instead of this sentence.   ](https://thingsboard-portal.atlassian.net/browse/PROD-2461)
`Integer.MAX_VALUE + 1
`
```
Expected :{msg={sys=2147483647, sunrise=2147483648}}
Actual   :{msg={sys=2147483647, sunrise=-2147483648}}
```
`Integer.MIN_VALUE - 1`
```
Expected :{msg={sys=-2147483648, sunrise=-2147483649}}
Actual   :{msg={sys=-2147483648, sunrise=2147483647}}
```
```
{
"sys": 2147483647
}
```
```
var time = msg.sys + 10;
msg.sunrise = time;
return {msg: msg};
```
```
{
"sys": -2147483648
}
```
```
var addValue = -10;
var time = msg.sys + addValue;
msg.sunrise = time;
return {msg: msg, metadata: metadata, msgType: msgType};
```
> fix_bug_tbel_Operations_ADD_ SUB

- ui-ngx/src/app/shared/models/constants.ts
- ui-ngx/src/app/shared/models/rule-node.models.ts
Merge with rule config: [#175](https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/175)
Merge with BE: [#10646](https://github.com/thingsboard/thingsboard/pull/10646)
> AWS lambda node

- ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-state.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-tooltip.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.models.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
Added convert Unicode into symbols in legend and tooltip for chart widgets
Before:
After:
> Added support unicode symbols in chart legend/tooltip

- application/src/main/data/json/tenant/dashboards/gateways.json
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.ts
Added connector name in connector logs
before:
after:
> Added connector name in connector logs

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNodeTest.java
Issue: https://github.com/thingsboard/thingsboard-edge/issues/114
> hotfix for calculate delta node: fixed false positive tests & fixed NPE

- application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/OAuth2EdgeEventFetcher.java
- application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/oauth2/OAuth2EdgeProcessor.java
> Fix Edge Oauth2 validation

- application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
- application/src/main/resources/thingsboard.yml
> [SWAGGER-UI] added ability to change swagger group name (definition)

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-3994
After improvements:
> [Rest API Call node] fixed adding body condition and content-type creation

- common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmCreateOrUpdateActiveRequest.java
- common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmUpdateRequest.java
- dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
> JpaAlarmDao debug log added

- application/src/test/java/org/thingsboard/server/edge/NotificationEdgeTest.java
- application/src/test/java/org/thingsboard/server/edge/OAuth2EdgeTest.java
Fixed test after merging hotfix Edge functional: https://github.com/thingsboard/thingsboard/pull/11175
> Fix OAuth2EdgeTest

- application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
- application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
Handle properly DELETE cases for ASSET/DEVICE to push ENTITY_DELETED msg into correct rule chain of the profile.
Issue reproducible in microservices setup or after restarts when cache is empty. 
If entity removed, device or asset profile cache service can't provide proper entity profile id and as a result removed event is not going into device or asset profile rule chain but into root rule chain.
> Handle properly DELETE cases for ASSET/DEVICE to push ENTITY_DELETED event into correct rule chain

- application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleEngineComponentActor.java
- dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
- dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
> Fix entities deletion task reprocessing

- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
Issue: if data key is configured as hidden by default on legend,  pressing it on legend will not render series as expected in case if data updating is not in progress. Fixed https://github.com/thingsboard/thingsboard/issues/10432
**Before:**
[scrnli_7_8_2024_2-50-35 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/d7966b6d-b5fa-4427-af1f-5407e35abede)
**After:**
[scrnli_7_8_2024_2-47-41 PM.webm](https://github.com/thingsboard/thingsboard/assets/87172504/a489859c-2d6b-47a5-9e14-61994b60d591)
> Fixed hidden by default chart series not rendering on unhide

- ui-ngx/src/app/shared/components/entity/entity-list.component.ts
- Login as tenant admin;
- Move to Notification center;
- Click on Send notification button;
- Create any recipient and add it;
- Full another required fields and send the notification;
- Go to the Recipient tab and delete the created recipient;
- Move to Sent tab  and click on the Notify again button and try to send notification
Expected result: the Next button doesn’t work, and empty field is highlighted;
Actual result: the Next work and error message appear on the Review tab;
Before fix:
Click 'Next' button
After fix:
Click 'Next' button
> Fixed notify again validation after deleted recipient

- ui-ngx/src/app/modules/home/components/widget/config/basic/chart/bar-chart-with-labels-basic-config.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/bar-chart-with-labels-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/chart-bar-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/chart-fill-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/chart-fill-settings.component.ts
> Fixed invalid tooltip in chart fill settings

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Add/update:
- parseBytesToInt(List<Byte> data);
- parseBytesToInt(List<Byte> data, int offset);
- parseBytesToInt(byte[]  data);
- parseBytesToInt(byte[] data, int offset);
- parseBytesToLong(List<Byte> data);
- parseBytesToLong(List<Byte> data, int offset);
- parseBytesToLong(byte[]  data);
- parseBytesToLong(byte[]  data, int offset);
-  parseBytesToFloat(List<Byte> data);
- parseBytesToFloat(List<Byte> data, int offset, int length);
- parseBytesToFloat(List<Byte> data, int offset, int length, boolean bigEndian);
-  parseBytesToFloat(byte[] data);
-  parseBytesToFloat(byte[] data, int offset);
-  parseBytesToFloat(byte[] data, int offset, int length);
-  parseBytesToFloat(byte[] data, int offset, int length, boolean bigEndian);      
- parseBytesToDouble(List<Byte> data);        
- …
> TBEL: added parameter length to methods parseBytesToNumber

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
- pom.xml
> TBEL: new version tbel and added  test hexToBytes

- ui-ngx/src/app/core/auth/auth.service.ts
Issue: if set any dashboard as home dashboard with disabled "Hide home dashboard toolbar"
and enable "Always fullscreen" for customer user
duplication of user menu occurs:
After fix:
> Fixed user menu duplication on customer home/default dashboard

- ui-ngx/src/app/modules/home/components/profile/add-device-profile-dialog.component.html
- ui-ngx/src/app/modules/home/components/profile/device-profile.component.html
- ui-ngx/src/app/modules/home/components/profile/device/coap-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/default-device-profile-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/default-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/device-profile-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/device-profile-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.html
- ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-transport-configuration.component.ts
- ui-ngx/src/app/modules/home/pages/device-profile/device-profile-tabs.component.html
Continuation of https://github.com/thingsboard/thingsboard/pull/11035
1. Fixed device profile creation redirected to transport tab:
before:
[scrnli_7_17_2024_5-55-26 PM.webm](https://github.com/user-attachments/assets/ec371589-2c17-49a3-aa77-6b8995d856d5)
after:
[scrnli_7_17_2024_5-58-04 PM.webm](https://github.com/user-attachments/assets/e7b50b9c-5b16-4934-9ffb-b4c598dabe6e)
2. Fixed blocked save while editing device profile if Default transport type was selected after leaving invalid any other type:
before:
[scrnli_7_17_2024_6-04-57 PM.webm](https://github.com/user-attachments/assets/2f03a9b9-cb5e-420e-91dd-e5d5b27be074)
after:
[scrnli_7_17_2024_5-59-14 PM.webm](https://github.com/user-attachments/assets/242760a8-6325-488f-a04f-a0c677f2a974)
> Fixed device profile create/update form validation

- ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.html
- ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Validation min max value for digital gauge settings

- ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.ts
- ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.ts
Fixed:
- Asset profile autocomplete component;
- Device profile autocomplete component.
Before:
After:
> Fixed overlapping dialog window by autocomplete list

- ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.html
- ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
Fixed Editing Resource title for JS module Resource
before:
[Screencast from 26.07.24 12:16:25.webm](https://github.com/user-attachments/assets/5086dcf2-ca0c-4a28-8574-346fbad90de6)
after:
[Screencast from 26.07.24 12:16:51.webm](https://github.com/user-attachments/assets/765fc3e6-84ce-4af0-9bf5-d785e39cf795)
> Fixed Editing Resource title for JS module Resource

- ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-config-server.component.html
Fixed Device Profile LwM2M Server information collapsed state view
before:
after:
> Fixed Device Profile LwM2M Server information collapsed state view

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
> Removed persisted data on creation of new Connector in RPC configuration

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
> Fixed updating credentials in gateway dashboard

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
Removed table Add Connector button from page on no connectors displayed.
before:
after:
> Removed table Add Connector button from page on no connectors displayed

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
Fixed Connector Form state after connector with basic config removal
before:
[Screencast from 25.07.24 19:34:04.webm](https://github.com/user-attachments/assets/e13334fc-d36a-4b54-ae0e-c8ed255039d0)
after:
[Screencast from 25.07.24 19:32:41.webm](https://github.com/user-attachments/assets/ab0a7649-b165-448f-b03d-4bd5642bf555)
> Fixed Connector Form state after connector with basic config removal

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
**OPC-UA Data mapping crushing on creating empty connector fix**
before:
after:
> OPC-UA Data mapping crushing on creating empty connector fix

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
- ui-ngx/src/app/shared/pipe/key-value-not-empty.pipe.ts
Added 'With Response' to MQTT templates and removed Response Time when With Response = false
before:
after:
> Added 'With Response' to MQTT templates and removed Response Time

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/server-config/server-config.component.html
Fixed spacing in OPC-UA server tab
before:
after:
> Fixed spacing in OPC-UA server tab

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
- ui-ngx/src/styles.scss
Added ability to open statistics settings from statistics state on Gateway dashboard 
before: 
after:
> Added ability to open statistics settings from statistics state on Gateway dashboard

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/broker-config-control/broker-config-control.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/security-config/security-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/server-config/server-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/workers-config-control/workers-config-control.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
Added view update for Connectors on switching active connector
before:
[Screencast from 11.07.24 16:14:40.webm](https://github.com/thingsboard/thingsboard/assets/93397261/d6ec68dc-089a-48ee-81f1-48671d9ecc86)
after:
[Screencast from 11.07.24 16:15:45.webm](https://github.com/thingsboard/thingsboard/assets/93397261/098382d9-11a1-4dea-922b-dd56cc9c4851)
> Added view update for Connectors on switching active connector

- application/src/test/java/org/thingsboard/server/service/script/NashornJsInvokeServiceTest.java
- pom.xml
Applied the fix: https://github.com/javadelight/delight-nashorn-sandbox/issues/151#issuecomment-2253844165
> Fix script compile error (ScriptCPUAbuseException) with Nashorn sandbox

- common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
- common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
- padStart - String.prototype.padStart() 
```
padStart("010011", 8, '0') return "00010011";
```
- padEnd - String.prototype.padEnd() 
```
padEnd("203439900FF", 16, '*') return "203439900FF******";
```
- parseByteToBinaryArray, parseBytesToBinaryArray, parseLongToBinaryArray:
```
TbUtils.parseByteToBinaryArray(0x39) return [1, 0, 0, 1, 1, 1, 0, 0]
TbUtils.parseByteToBinaryArray(0x39, 6)  return [1, 0, 0, 1, 1, 1]
TbUtils.parseBytesToBinaryArray([0x39]) return [1, 0, 0, 1, 1, 1, 0, 0]
TbUtils.parseLongToBinaryArray(52914L, 4) return [0, 1, 0, 0] 
```
- old
```
TbUtils.intLongToString(58L, MIN_RADIX) return "111010"
```
- new
```
TbUtils.intLongToString(58L, MIN_RADIX) return "00111010"
```
> TBEL: added padStart, padEnd, parseByteToBinaryArray, parseBytesToBinaryArray, parseLongToBinaryArray

- application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineStrategyTest.java
> added TbRuleEngineStrategyTest

- application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
Issue: https://github.com/thingsboard/thingsboard/issues/6973
> Async transport API requests processing

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java
Changed 'timeseries' to 'time series' in node name and details.
> Timeseries node: change name

- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractDataSubCtx.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractSubCtx.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmDataSubCtx.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbEntityDataSubCtx.java
- application/src/main/java/org/thingsboard/server/service/subscription/TbLocalSubscriptionService.java
- application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
- application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
- application/src/main/resources/thingsboard.yml
- common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java
- common/message/src/main/java/org/thingsboard/server/common/msg/tools/TbRateLimitsException.java
- common/util/src/main/java/org/thingsboard/common/util/DeduplicationUtil.java
> Rate limit for WS subscriptions

- ui-ngx/src/app/core/services/mobile.service.ts
> Fixed issue with opening dashboards in the mobile app on iOS

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
Removed Unexpected Tooltips from toolbar on Edit Connectors Tables
before:
after:
> Removed Unexpected Tooltips from toolbar on Edit Connectors Tables

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.ts
Added Connector tables Row Action buttons descriptions tooltips
before:
after:
> Added Connector tables Row Action buttons descriptions tooltips

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-values/modbus-values.component.scss
Fixed Modbus Slave Config Values visibility
before:
after:
> Fixed Modbus Slave Config Values visibility

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/broker-config-control/broker-config-control.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Fixed saving validation on creating empty OPC connector
before:
[Screencast from 30.07.24 15:50:07.webm](https://github.com/user-attachments/assets/a70fc198-153c-44e8-9202-656a2d1084a9)
after:
[Screencast from 30.07.24 15:48:31.webm](https://github.com/user-attachments/assets/c5f84780-911b-47c3-8b85-02fdacd8ab9a)
> Fixed saving validation on creating empty OPC connector

- monitoring/src/main/java/org/thingsboard/monitoring/data/Latencies.java
- monitoring/src/main/java/org/thingsboard/monitoring/service/BaseMonitoringService.java
> Add WS subscribe latency monitoring

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
Added tests for the GCP PubSub node.   
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2745
> PubSub node: added tests

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/kafka/TbKafkaNodeTest.java
Added tests for the kafka node. 
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2747
> Kafka node: added tests

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetAttributesNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetDeviceAttrNodeTest.java
Added tests for the related device attributes node.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2748
> Related device attributes node: added tests

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNode.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeTest.java
Added tests for the mqtt and azure iot hub nodes.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2744
> Mqtt and Azure iot hub nodes: added tests

- common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentTransportResourceTest.java
Added tests for new measurement types.
> Efento new types: added tests

- application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
- application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
- application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
- common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
Replace text the timeseries/time-series with the time series (into two separate words) in swagger.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2741
> Swagger: replaced text timeseries/time-series to time series

- application/src/main/resources/thingsboard.yml
- docker/docker-compose.redis-cluster.yml
- docker/docker-compose.redis-sentinel.yml
- docker/docker-compose.redis.yml
- msa/black-box-tests/src/test/resources/docker-compose.redis-ssl.yml
Redis version freeze note for docker deployments and thingsboard.yml
> Redis compatibility note

- application/src/main/java/org/thingsboard/server/actors/shared/ComponentMsgProcessor.java
- application/src/main/java/org/thingsboard/server/actors/stats/StatsPersistTick.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbLogNode.java
- StatsPersistsTick - singleton (Effective Java by Joshua Bloch)
- TbLogNode - skip if logger disabled (reduce script calls, and memory pressure from json and string)
> Rule engine memory optimizations

- application/src/main/java/org/thingsboard/server/service/install/update/ImagesUpdater.java
- common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/secure/TbLwM2MDtlsBootstrapCertificateVerifier.java
- dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmCommentService.java
This PR is related to three incremental bug fixes in three different logging statements.
Please see the commits for details
> Fix bugs in three logging statement 

- ui-ngx/src/app/modules/home/components/entity/entity-details-panel.component.ts
> Hide details panel/page tabs if no additional tabs present

- ui-ngx/src/assets/locale/locale.constant-en_US.json
Mark as read -> Mark all as read;
> Notification widget rename header button name

- ui-ngx/src/app/modules/home/components/widget/config/basic/cards/unread-notification-basic-config.component.html
Appearance -> Card appearance;
> Notification widget rename basic settings appearance

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.scss
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
- ui-ngx/src/assets/help/en_US/widget/lib/gateway/modbus-functions-data-types_fn.md
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Gateway Modbus Connector added UI adjustments, helplinks and hints
[Screencast from 08.08.24 17:55:46.webm](https://github.com/user-attachments/assets/51df2f0e-73e5-4f1d-a4b3-2988c986ffbe)
> Gateway Modbus Connector added UI adjustments, helplinks and hints

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
Fixed Duplicate Name validation on Adding new Connector
before:
[Screencast from 08.08.24 19:26:04.webm](https://github.com/user-attachments/assets/88a79efe-b26a-4a5e-9503-762ee6d66c34)
after:
[Screencast from 08.08.24 19:26:49.webm](https://github.com/user-attachments/assets/7784326f-8d00-4f24-9e73-801383750049)
> Fixed Duplicate Name validation on Adding new Connector

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
- ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
Fixed Issue of viewing Out of Sync Connector and gateway-connectors component refactoring
before:
[Screencast from 12.08.24 11:09:50.webm](https://github.com/user-attachments/assets/999acbf2-cbde-41a8-8461-ac27e1208d81)
after:
[Screencast from 12.08.24 11:06:21.webm](https://github.com/user-attachments/assets/0e2738dd-1332-43d3-918c-4314a8b72185)
> Fixed Issue of viewing Out of Sync Connector

- application/src/main/data/json/system/scada_symbols/cylindrical-tank.svg
- application/src/main/data/json/system/scada_symbols/elevated-tank.svg
- application/src/main/data/json/system/scada_symbols/horizontal-tank.svg
- application/src/main/data/json/system/scada_symbols/large-cylindrical-tank.svg
- application/src/main/data/json/system/scada_symbols/large-stand-cylindrical-tank.svg
- application/src/main/data/json/system/scada_symbols/large-stand-vertical-tank.svg
- application/src/main/data/json/system/scada_symbols/large-vertical-tank.svg
- application/src/main/data/json/system/scada_symbols/pool.svg
- application/src/main/data/json/system/scada_symbols/small-spherical-tank.svg
- application/src/main/data/json/system/scada_symbols/spherical-tank.svg
- application/src/main/data/json/system/scada_symbols/stand-cylindrical-tank.svg
- application/src/main/data/json/system/scada_symbols/stand-horizontal-tank.svg
- application/src/main/data/json/system/scada_symbols/stand-vertical-short-tank.svg
- application/src/main/data/json/system/scada_symbols/stand-vertical-tank.svg
- application/src/main/data/json/system/scada_symbols/vertical-short-tank.svg
- ui-ngx/src/app/modules/home/components/widget/lib/settings/common/scada/scada-symbol-object-settings.component.html
> Tank SCADA symbol

- ui-ngx/src/app/core/services/dashboard-utils.service.ts
- ui-ngx/src/app/core/services/item-buffer.service.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.ts
- ui-ngx/src/app/shared/import-export/import-export.service.ts
- ui-ngx/src/app/shared/models/dashboard.models.ts
> Fixed delete widget in layout and improved dashboard layout types

- ui-ngx/src/app/modules/home/components/dashboard-page/layout/add-new-breakpoint-dialog.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.scss
> Fixed adaptive manage layout dialog

- application/src/main/data/json/system/widget_bundles/scada_water_system_symbols.json
Update bundle for tank SCADA symbol
> Update widget bundle for tank SCADA symbol

- application/src/main/resources/thingsboard.yml
- msa/tb-node/docker/Dockerfile
Some customers use a reverse proxy for monolith deployments!
> Fix Swagger issues when reverse proxy is used

- application/src/main/java/org/thingsboard/server/controller/AdminController.java
- common/data/src/main/java/org/thingsboard/server/common/data/objects/AttributesEntityView.java
- common/data/src/main/java/org/thingsboard/server/common/data/objects/TelemetryEntityView.java
- fixed description for POST call **/api/admin/settings** in the Admin Controller 
- Issue: #7421
- fixed wrong JSON example for POST call **api/entityView** in the Entity View Controller 
- Issue: #6634
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2756
> [Swagger Documentation] Fixed description

- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/ChangeOriginatorSource.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/OriginatorSource.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeConfiguration.java
- rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesByNameAndTypeLoader.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
Added tests for the change originator node.
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/2751
> Change originator node: added tests

- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbAckNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbCheckpointNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNodeTest.java
- rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbRuleChainOutputNodeTest.java
Added tests for the following flow type rule nodes:
- acknowledge 
- checkpoint
- output
> Flow type rule nodes: added tests

- common/cache/src/main/java/org/thingsboard/server/cache/TbTransactionalCache.java
> Fix getOrFetchFromDB for versioned transactional cache

- common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
> VC: fix error message when using https url with private key authentication

- common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceService.java
- common/data/src/main/java/org/thingsboard/server/common/data/HasOtaPackage.java
- dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
- dao/src/main/java/org/thingsboard/server/dao/sql/device/DeviceRepository.java
- dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceDao.java
- dao/src/test/java/org/thingsboard/server/dao/service/DeviceServiceTest.java
https://thingsboard-portal.atlassian.net/browse/PROD-4214
> Fixed queries for get/count devices without OTA

- dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceProfileEntity.java
- dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/JpaPartitionedAbstractDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetProfileDao.java
- dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceProfileDao.java
> Fix entity's version incremented twice

- application/src/main/java/org/thingsboard/server/controller/NotificationController.java
- application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
> Ignore unknown notification recipient groups

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Fixed issue with not saving Widget on Widget editing
before:
[Screencast from 22.08.24 16:32:33.webm](https://github.com/user-attachments/assets/5b7a72ec-e55b-4a6b-93f5-85dca6017cd3)
after:
[Screencast from 22.08.24 16:33:17.webm](https://github.com/user-attachments/assets/e35bef9a-809c-4fa6-9913-4b48b8a6fd7b)
> Fixed issue with not saving Widget on Widget editing

- application/src/main/data/json/system/scada_symbols/left-heat-pump.svg
- application/src/main/data/json/system/scada_symbols/right-heat-pump.svg
- application/src/main/data/json/system/widget_bundles/scada_water_system_symbols.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Heat pump SCADA symbols

- application/src/main/data/json/system/scada_symbols/stand-filter.svg
- application/src/main/data/json/system/widget_bundles/scada_water_system_symbols.json
- ui-ngx/src/assets/locale/locale.constant-en_US.json
> Stand filter SCADA symbol

- ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
- ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.html
- ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts
- ui-ngx/src/app/shared/import-export/import-export.service.ts
- ui-ngx/src/app/shared/models/entity.models.ts
- ui-ngx/src/app/shared/models/rule-chain.models.ts
Added UI part of RuleChain Editor Version Conflict
[Screencast from 29.08.24 13:21:31.webm](https://github.com/user-attachments/assets/fa8e22e8-975e-4425-8403-d4cac861ccaf)
> Added UI part of RuleChain Editor Version Conflict

- ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
- ui-ngx/src/app/shared/components/entity/entity-select.component.html
- ui-ngx/src/app/shared/components/entity/entity-select.component.ts
- ui-ngx/src/app/shared/components/entity/entity-type-select.component.ts
- ui-ngx/src/app/shared/models/entity-type.models.ts
- ui-ngx/src/assets/locale/locale.constant-en_US.json
Merge with: [#179](https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/179)
Changes for improving generator node.
> Improvement for generator node

- ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
> Added trace log level

- ui-ngx/src/app/core/services/dashboard-utils.service.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
> Improved move all widget action: fixed overlap widget and add support dashboard layout

- ui-ngx/src/app/core/services/dashboard-utils.service.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/layout.models.ts
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.ts
> Fixed infinite load when select divided layout

- ui-ngx/src/app/modules/home/components/dashboard-page/layout/add-new-breakpoint-dialog.component.html
- ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.html
> Improved style for select dashboard breakpoint

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
> Fixed incorrect min-width for dashboard layout in preview mode at specific breakpoints

- ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.html
Step to reproduced:
1. Changing attribute in the input field changes the attribute in the select field.
2. Changing the attribute in the select fiels changes it in the input field
3. Now changing the attribute in the input field does not change the attribute in the select field but still changes value of the attribute on the device.
> Fixed multiple input widget not updated dynamically selector after change and save value

- ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
> Fixed error tooltip for 'Minimum layout width' in layout configuration

- ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
- ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
- ui-ngx/src/assets/help/en_US/widget/action/show_widget_action_cell_fn.md
Fixed entity table widget for incorrect work example in help:
> Fix entity table widgets to correctly process entity type for "show cell button action" function
